### ISSUE TITLE
3.0 - requestAction usage

### ISSUE THREAD

**Issue by rhelms** [cakephp/docs#1364]
The example code for requestAction usage (http://book.cakephp.org/3.0/en/development/routing.html#Cake\Routing\RequestActionTrait::requestAction) shows a controller action returning the results of a find.

However, the return value of an action must now be a Response, so this example is no longer appropriate.

Could suggest replacing with Cells, but that still requires rendering, and you can't access  the raw data from the calling function. The other alternative is rendering the JSON, then decoding to plain old PHP objects, but that's still not hitting the nail on the head as a suitable replacement.

**Comment by markstory** [comment]
Thanks for the poke @ravage84 :D
