### ISSUE TITLE
CakePHP 3 Installation without intl or Composer

### ISSUE THREAD

**Issue by ghost** [cakephp/docs#1606]
My server (hosted by Rochen) does not allow for the installation of Composer or php5-intl, for some reason or another.

I installed CakePHP3 without Composer, but when I do it that way I get an error due to the missing intl library. Is there a way to not require this file so that I can use CakePHP3 on my website?

**Comment by HumanG33k** [comment]
I just want to say sometimes we not have any ssh/command line acces for security reason.
- cake app dev can only drop files on a "prepare" server
- admin which will not execute something or let people execute composer for ie.
Real case i face to.
