### ISSUE TITLE
RFC 3.0 - Change in Concept for Docs Translations

### ISSUE THREAD

**Issue by ravage84** [cakephp/docs#1713]
In recent times we've had quite a few starts of translations or better said translation attempts.
As I've mentioned before I'm not a big fan of them because of reasons I've also stated before.

Though I **do** see some need and some use to some certain translations.

But as the past has proven, we have yet to see an up to date and 100 % covered translation of the docs in any language.
Since I don't believe we will ever achieve that without trying to greatly mobilize our community for that cause, I would like to propose a (little) change in concept when it comes to docs translations.

So let's answer why should we have translations of the docs in various languages?
I think the most compelling reason is to *attract developers which aren't strong in English to our Community and our Framework, by easing up their first steps*.

Those first steps are in my opinion (translated into the current book chapters and pages)
* Welcome
* Basic Instalation and requirements (does not need to cover the advanced installations, but URL rewriting)
* Getting Started
* Blog Tutorial
* CakePHP Overview
  * Wat is CakePHP, Why use it?
  * Understanding MVC
  * Where to get help?

Those chapters and pages make sure a developer will
* understand the basics of the framework
* and have a working installation.

Beyond that, I believe we can neglect the translations.
This will help to prevent the translations become outdated because the content of the pages mentioned above is not changed as much as the rest of the docs.

Simply said:
Let's consolidate all the pages that a developer needs to **understand the basics of the framework** and **have a working installation**  into a first  "act" of the book and only allow translations of this act.

Since we have to change how the book is structured, this RFC is headed towards 3.0 and not 2.0.

**Comment by andtxr** [comment]
I do agree on intro sections being a base for new languages too. I am focusing on the main sections first. And there will be a long work ahead. Today, here in Brazil, there is a lazy habit about other languages. Even the bigger Facebook CakePHP brazilian community does not accept any non-portuguese content. It is a little hard to penetrate in such politics. I am thinking if it is a good idea to create some group references in the docs for each language to ease recruiting tasks.

**Comment by cake17** [comment]
@andtxr we add the french community website on [this page](http://book.cakephp.org/3.0/en/intro/where-to-get-help.html). If there is a reference website, maybe the portuguese can add it there.
I'm happy to see other languages translated :)

**Comment by cake17** [comment]
I might have a temporary solution for partial translations.

I'm wondering if we could just keep the same tree folders and files up to date with the en version.

Then for untranslated files, we put a message on the page, something like this (I'll take the example of a spanish page):
    The documentation is not currently supported in es language.
    Please feel free to send us a pull request on [github](http://www.github.com/cakephp/docs).
    You can referer to the english version to have information about this page's topic.

We would only put this message and no english version below. This means:
- no need to keep it up to date each time the english version changes
- People who want to translate don't have to create the files as we maintain the structure of folders & files for all languages (not really tiresome as it does not change every week).
- This also encourages people to use "Improve Docs" as all pages are created. (Just need to copy paste english version)
- and best of all, no depreciated version (no old page not up-to-date).

I will do this for es version, let me know what you think of this.

**Comment by cake17** [comment]
After working on es files, just a reminder here to avoid sphinx issues: needs to include all the toc.

Otherwise, I think it can be a solution to the unmaintained translations.

**Comment by markstory** [comment]
@cake17 I think including a note about the missing translations is a good idea. Like you said it might help encourage more contributors and gives us a way to remove outdated content without creating tons of 404s.

**Comment by andtxr** [comment]
@cake17 i have registered cakephp-br.org to keep the same URL standard. Soon I will think about the page structure.

**Comment by andtxr** [comment]
I think, at least, that a link for the current english page should be placed below the advice for better navigation and shortcuts.

**Comment by cake17** [comment]
@andtxr nice. If you want, you can have a look at what we've done for the fr community website. The sources are editable by the fr community on [github](https://github.com/cakephp-fr/cakephp-fr.github.io).

+1 for the english link, now the questions are:
- is there a way to get the pagename variable in .rst files (or do we write the pagename directly, meaning no possible copy paste between pages) ?
- Or do we put it in layout with a condition ? If the page is empty, then we print the default message

**Comment by cake17** [comment]
Maybe just changing the content of the note could be enough:

    .. note::
        The documentation is not currently supported in es language for this page.

        Please feel free to send us a pull request on
        `Github <https://github.com/cakephp/docs>`_ or use the **Improve This Doc**
        button to directly propose your changes.

        You can referer to the english version in the select top menu to have
        information about this page's topic.

**Comment by andtxr** [comment]
What about localize it for each lang? Would work? Or brings more headache than benefits?

**Comment by cake17** [comment]
Yes it would be better.

For now it's just a copy paste for all untranslated pages, so we can copy paste a localized version. My chineese, japanese and spanish aren't good enough to translate something like that :) Otherwise we put the english version if no one gives us a translation ?

**Comment by andtxr** [comment]
I may handle spanish too, at least for minor adjusts, if nobody takes it. For the chinese and japanese we probably should use english version until someone appears. :+1:

**Comment by cake17** [comment]
Ok cool, I can take care of ja and zh if you want, I let you spa and pt ?

We can use the last note I made (if an english native speaker comes here, don't hesitate to correct it ! :) )

**Comment by andtxr** [comment]
Sure. Pushing in a few minutes.

**Comment by cake17** [comment]
I close this one as #2550 has been merged
