### ISSUE TITLE
RFC 3.0 Main Chapter folder structure reorganisation

### ISSUE THREAD

**Issue by ravage84** [cakephp/docs#1903]
Recently we introduced the following "main chapters" within the book:

- Preface
- Getting Started
- General Topics
- Utility Classes
- Other

http://book.cakephp.org/3.0/en/index.html

But the way we are doing them is through CSS trickery, which complicates aspects such as translations.

The idea behind those main chapters is great and the way to go but the current folder structure doesn't reflect this organisation:

https://github.com/cakephp/docs/tree/3.0/en

I tried to setup a PR where I reorganized the folder structure but I tripped over the toctree generation of sphix :rage: 

What I want to propose is moving all (propably with exceptions) content pages of one main chapter into a folder named after the main chapter.

We would end up having a folder structure like this below ``/en/``:

- preface/
  - contributing/
    - backwards-compatibility.rst
    - cakephp-coding-conventions.rst
    - code.rst
    - documentation.rst
    - tickets.rst
  - intro/
     - cakephp-folder-structure.rst
     - conventions.rst
     - where-to-get-help.rst
  - tutorials-ande-xamples/
     - ...
  - getting-started/
     - ...
  - contributing.rst
  - intro.rst
  - quickstart.rst
  - tutorials-ande-xamples.rst
- general-topics/
  - ...
- utility-classes/
  - ...
- other/
  - ...
- content.rst
- index.rst

Certainly the new structure has one more level but at least it realistically reflects the TOC tree.
Like this, we won't need any CSS trickery to display the chapter titles/separators int he TOC tree.

**Comment by markstory** [comment]
Closing as its been a long time with no action. If there is still interest, a pull request would be great.
