### ISSUE TITLE
2.x Chapter 01 too short and don't have real means, chapter 13 too short (only 1 page)

### ISSUE THREAD

**Issue by donhuvy** [cakephp/docs#2060]
Issue: 
In CakePHP cookbook documention (language: English) - Release 2.x (update November 27th, 2014). 
Chapter 01 have only 1 page.
Chapter 13 have only 1 page.
The content of Chapter 01: Getting Started, have 8 lines of content. It is irrational structure.
_____________________________________________________________
Suggested action: 
- Remove chapter 01, add old content (8 lines of text) to chapter 02.
- Add section setup virtual host, mod_rewrite, security .etc to deployment chapter or keep Chapter 13 in section of other chapter.

**Comment by markstory** [comment]
Closing as there were a few PDF improvements done.
