### ISSUE TITLE
Indices and tables in PDF

### ISSUE THREAD

**Issue by ravage84** [cakephp/docs#2068]
I presume it is not intended that the Indices and tables chapter in the PDF shows only this:
````
• genindex
• modindex
````

![indices-and-tables](https://cloud.githubusercontent.com/assets/625761/5245664/f14ba208-795e-11e4-9460-b49bff3580e0.png)

**Comment by ravage84** [comment]
The problem seems to be quite old:
http://osdir.com/ml/general/2013-01/msg29646.html

I removed the modindex reference in #2244 

@markstory to my understanding, removing the genindex reference also removes the index from the PDF. Hope you have a better insight into sphinx :grey_question: 
But I think we should keep it in, as it is useful.

Working around this ugliness, we could try to put a label onto the reference, like
````
:ref:` Index <genindex>`
````

**Comment by markstory** [comment]
The generated index being included doesn't seem like a terrible thing to me.

**Comment by cake17** [comment]
I close this because #3259 has been merged
