### ISSUE TITLE
CakePHP 3.0 phpunit.xml with Fixture configuration not 100% clear

### ISSUE THREAD

**Issue by kevinquinnyo** [cakephp/docs#2253]
It's possible I'm just missing something obvious, but it took me a long time to figure out that I needed to add a `<listeners>` section to my phpunit.xml in order for PHPunit Fixtures to work properly for a plugin I had written tests for.

I added the following because I was comparing my code with the debug_kit's 3.0 branch [phpunit.xml.dist](https://github.com/cakephp/debug_kit/blob/3.0/phpunit.xml.dist) plugin:

phpunit.xml
```xml
        <!-- Setup a listener for fixtures -->
        <listeners>
                <listener
                class="\Cake\TestSuite\Fixture\FixtureInjector"
                file="./vendor/cakephp/cakephp/src/TestSuite/Fixture/FixtureInjector.php">
                        <arguments>
                                <object class="\Cake\TestSuite\Fixture\FixtureManager" />
                        </arguments>
                </listener>
        </listeners>
```

I couldn't find mention of this in the book at http://book.cakephp.org/3.0/en/development/testing.html

Is it mentioned elsewhere?  It seems to me it could be mentioned there perhaps one of the following places, or as it's own heading directly after these sections:

* http://book.cakephp.org/3.0/en/development/testing.html#creating-test-suites
* http://book.cakephp.org/3.0/en/development/testing.html#creating-tests-for-plugins

**Comment by markstory** [comment]
This block is also in the app skeleton and when creating a plugin using bake. How did you end up without one?

**Comment by kevinquinnyo** [comment]
Hm, I guess it's because we didn't use `bake` to generate the plugin skeleton.  I think we just created the directory structure and `phpunit.xml` manually, but I can't remember.

**Comment by markstory** [comment]
I can update the docs to mention including this section in the `phpunit.xml` as part of the fixtures docs then.

**Comment by kevinquinnyo** [comment]
Awesome, thanks.  I wonder if it should also mention that if you're using composer for autoloading namespaces, you should be sure to add the Fixture namespace for your plugin's `composer.json` like:

```javascript
// snip..

	"autoload": {
		"psr-4": {
			"MyPlugin\\": "src",
			"MyPlugin\\Test\\Fixture\\": "tests/Fixture"
		}
	},
	"autoload-dev": {
		"psr-4": {
			"MyPlugin\\Test\\": "tests",
			"MyPlugin\\Test\\Fixture\\": "tests/Fixture"
		}
	}
```
Or is that outside the scope of this documentation?  I know that using composer is the recommended way of installing a cakephp project and handling dependencies so it seems natural to include that as well.

**Comment by markstory** [comment]
We assume that in app plugins will be created with bake. I can add the relevant composer updates to the plugins docs though as not everyone will use bake.

**Comment by kevinquinnyo** [comment]
I think we're going to start using `bake` more from now on based on this conversation.  Thanks for updating the docs though.

**Comment by markstory** [comment]
Pull request up now #2256
