### ISSUE TITLE
3.0 - Incorrect table named

### ISSUE THREAD

**Issue by Xety** [cakephp/docs#2266]
Hello,

In the exemple http://book.cakephp.org/3.0/en/orm/behaviors/translate.html#using-a-separate-translations-table the name of the table `articles_i18n` is incorrect, it should be `ArticlesI18n` else it will result to an error :
![4n9njff](https://cloud.githubusercontent.com/assets/8210023/5721158/541ab112-9b2e-11e4-8741-6c6eb27677ce.png)

I'm sorry i can't do a PR right now, i don't have the time.

**Comment by lorenzo** [comment]
Thanks, we just need to update the documentation after a recent fix we made.

**Comment by lorenzo** [comment]
Oh, derp. This is the docs repo xD
