### ISSUE TITLE
3.0 - Doc for plugin ACL

### ISSUE THREAD

**Issue by Xety** [cakephp/docs#2267]
Hello,

I think it should be nice if we can have a doc for the plugin ACL. I don't know if it's better to have it on the repo or in the official doc, but anyways we should have it.
Because i never used ACL in Cake2 and i'm gonna start using it and i don't know where to start, how it's work etc and i'm a little lost. :smile:

**Comment by lorenzo** [comment]
I would *personally* suggest not using ACL. There are better alternatives built into the core or that can be  derived out of it.

Independent of that, we should have documentation. We just need someone that cares about the library to port the docs from 2.x

**Comment by Xety** [comment]
Oh ok. What alternatives can you suggest me please ? (If you had to do a website with like 10 ranks, and like 15 permissions by rank.)

Else, for the documentation, we can look the documentation of the 2.x for this plugin ?

**Comment by dereuromark** [comment]
@Xety Take a look here: https://github.com/FriendsOfCake/awesome-cakephp/tree/cake3#authentication-and-authorization

**Comment by Xety** [comment]
Can you please create a new-branch `acl` or something like that ? I have started to port the docs from 2.x. But it would be nice if i can push on a different branch so, you will also be able to commit in it.

**Comment by Xety** [comment]
Closed as #3564 is open now.
