### ISSUE TITLE
Add intl special placeholder formatting warning

### ISSUE THREAD

**Issue by dereuromark** [cakephp/docs#2291]
The intl formatting with special placeholders seems to be quite buggy, especially on PHP5.4.
See http://sandbox3.dereuromark.de/sandbox/cake_examples/i18n

We should either try to shim/fix stuff, or better (easier) yet adjust the documentation and add warnings where necessary, e.g. the http://php.net/manual/de/class.messageformatter.php#115841 or `{0,number,decimal}` issue.

**Comment by lorenzo** [comment]
@dereuromark Can you add the limitations to the docs?

**Comment by dereuromark** [comment]
Are we able to test those things in the core using travis for PHP 5.4 5.5 and 5.6?
That would probably make it easier to keep track of what is possible since what version.

**Comment by lorenzo** [comment]
In php 5.5:

```php
echo __('Your balance on the {0,date} is {1,number,currency}. {2,number,percent} more.', [strtotime('2014-01-13 11:12:00'), 1354.376, 0.02]);
```

```
Your balance on the Jan 13, 2014 is $1,354.38. 2% more
```

So it seems to work fine. Maybe it has to do with your version of icu?

**Comment by lorenzo** [comment]
Also using DateTime works: (5.5)

```php
echo __('Your balance on the {0,date} is {1,number,currency}. {2,number,percent} more.', [new DateTime, 1354.376, 0.02]);
```

```
Your balance on the Jan 18, 2015 is $1,354.38. 2% more.
```

**Comment by dereuromark** [comment]
I am using a standard debian 6 running PHP5.4.36. How can I check on the icu?

**Comment by lorenzo** [comment]
```php
echo INTL_ICU_VERSION
```

**Comment by dereuromark** [comment]
It's 4.4.1.

**Comment by lorenzo** [comment]
That's quite old @dereuromark

**Comment by dereuromark** [comment]
Yeah, locally I am running 49.1.2 but have the same problems.

**Comment by markstory** [comment]
Sounds like updating ICU is a solution here.

**Comment by dereuromark** [comment]
Sounds like many will trip over that one in the near future, as there are no doc guidelines regarding what version for what feature.

**Comment by markstory** [comment]
Ok, without more extensive testing, we can't really say much more than 'a recent version of icu'.

**Comment by dereuromark** [comment]
Well, that will be a challenge for most I believe..
I installed a brandnew debian7 with PHP5.5 (all up to date packages). The ICU version: `ICU version: 4.8.1.1`.
So unless we also provide a way to describe how to update ICU to a reasonably working version manually, I am afraid we shouldn't put that stuff in the docs, when it will be broken on 90% of all systems.

**Comment by jadb** [comment]
I agree with @dereuromark about instructions (or at least a link, a quick google search didn't return satisfactory results for me, but that's me;)).

I create VMs using Puphpet and checked the ICU version on over 10 created in the past year or so and all seemed to have a good enough version.

**Comment by dereuromark** [comment]
@jadb Thats good to hear. But I also didn't find any good links on how to manually upgrade it for debian for example.

**Comment by jadb** [comment]
@dereuromark - no, just the version.

**Comment by markstory** [comment]
Pull request up now.
