### ISSUE TITLE
uploadedFile validation needs to be documented

### ISSUE THREAD

**Issue by lorenzo** [cakephp/docs#2326]
One common question in IRC is how to make validation for a file input optional. Docs should explain how to pass this option to the this validation rule.

**Comment by markstory** [comment]
I can add docs for this.

**Comment by bcrowe** [comment]
Isn't this covered quite literally in the first example under [Conditional Validation](http://book.cakephp.org/3.0/en/core-libraries/validation.html#conditional-validation)?

**Comment by markstory** [comment]
I thin @lorenzo meant the specific validation method was missing an example.

**Comment by markstory** [comment]
Pull request up now.
