### ISSUE TITLE
IIS rewriting - is this guide still good?

### ISSUE THREAD

**Issue by toby1kenobi** [cakephp/docs#2336]
I have been unable to get rewriting working in IIS (admittedly 8.5) with the rewrite module, I'm wondering if [this web.config](http://book.cakephp.org/2.0/en/installation/url-rewriting.html#url-rewrites-on-iis7-windows-hosts) is good? 

I have IIS pointing at the root of a fresh cake 2 install and have added DebugKit. IIS is pointing at CakePHP's root and is configured to handle PHP using FastCGI. The only change I've currently made to the config is creating a web.config in the CakePHP root, containing just the rewrite rules from the documentation. 

IIS serves up the homepage ok, telling me everything's working, so app/webroot/index.php is being used (and CSS/img paths still work), but if I modify the url to something like /pages/thing (expecting to be told there's no view for that path) I still see the contents of home.ctp.

**Comment by toby1kenobi** [comment]
It's possible this is an IIS issue (or bug) - I think it's because $_SERVER['REQUEST_URI'] is not available, this seems to be on ongoing problem http://support.microsoft.com/kb/2277918.

**Comment by toby1kenobi** [comment]
if (!isset($_SERVER['REQUEST_URI']) && isset($_SERVER["HTTP_X_ORIGINAL_URL"])) {
	$_SERVER['REQUEST_URI'] = $_SERVER["HTTP_X_ORIGINAL_URL"];
    }

**Comment by ravage84** [comment]
I haven't tested it with IIS 8+ yet, but it should work with 7 and 7.5.

Yes, IIS isn't unproblematic when it comes to URLs and PHP.
May be you experience something like this:
https://github.com/cakephp/cakephp/pull/1359

If you find a solution, feel free to open a PR, please.
