### ISSUE TITLE
3.0: Explain difference of FormHelper::submit() and ::button

### ISSUE THREAD

**Issue by nrother** [cakephp/docs#2344]
I find [the doc](http://book.cakephp.org/3.0/en/views/helpers/form.html#Cake\View\Helper\FormHelper::submit) about `button()` and `submit()` very confusing.

After reading I had the imagination that `submit()` will forward all requests to `button()`, but enables me to specify an image, which button seems not to allow.

After looking in the code I saw that `submit()` does *not* call `button()` but contains a variety of other code.

Some where in the docs I found a warning always to end my Forms with `submit()`, but then I saw that `button()` will also generate a submit button.

IMHO the doc (and maybe the API?) should be much clearer here. What's the difference and when to use which method?

**Comment by markstory** [comment]
The biggest difference is that submit() generates a submit input, while button generates a button tag. I can update the docs so this is clearer.

**Comment by markstory** [comment]
I think #2345 helps clarify the two methods. If it doesn't let me know what is still unclear and I can try to fix any remaining issues.

**Comment by nrother** [comment]
Ok, `<button>` vs. `<input type="submit">` made some things clearer.

But I'm still missing a clear recommendation in the docs which one to use at the end of my form.

Most things I found about this on the web recommend using buttons for modern browsers, not inputs. But looking at the [code of the FormHelper](https://github.com/cakephp/cakephp/blob/3.0/src/View/Helper/FormHelper.php#L1674) it looks like that submit does a lot of form-related stuff that button does not.

At least for me it's a bit unclear why there are two functions which seem to do similar things.

**Comment by dereuromark** [comment]
@nrother That is mostly historical, I believe. In some (we all know which) older or less sophisticated browsers, which also didn't implement the by the widely used HTML standards, the button submit was not always working correctly. As such the input element was crucial here.
In the present we probably don't have that issue anymore.

But you can easily switch the templates to have submit() also use a button if you prefer that.

**Comment by markstory** [comment]
@nrother There isn't a clear recommendation as at the end of the day it doesn't matter which one you use very much.

The additional code in submit() is to handle image submits, which have some additional complexity because of how they work.

**Comment by nrother** [comment]
Ok, confusion cleared now!

Maybe one should think about merging submit() into button() and add something like `['style' => 'legacy']` That would make it clear that it doesn't matter which one you use.

**Comment by dereuromark** [comment]
@nrother In the end submit() outputs a submit element, and button() outputs a button element. So I don't see the need to merge it at this point IMO.

**Comment by markstory** [comment]
Until html merges the two button types I don't think we should either.
