### ISSUE TITLE
Docs should mention how to exactly test plugins

### ISSUE THREAD

**Issue by dereuromark** [cakephp/docs#2358]
Refs https://github.com/cakephp/cakephp/issues/5828

Currently people don't know that you need to composer update/install inside the app's plugins to actually make them testable as autarkic systems.

So maybe sth like
- navigate into the plugin
- run `composer update` (or `composer install` when desired to pull from lock file) as the plugin itself needs to get all dependencies directly, it is an autarkic system in testing
- then run `phpunit`

(especially the 2nd point) should be added here:
http://book.cakephp.org/3.0/en/development/testing.html#running-tests

As more code style:

```
$ cd vendor/your-namespace/your-plugin
$ composer update
$ phpunit
```

**Comment by markstory** [comment]
You should really not be doing this, and instead running the tests _outside_ of the vendor directory. Running tests in vendor/ dirs will only encourage people to do development there which is just begging for composer to destroy changes by accident. Just ask @rchavik :smile:

**Comment by dereuromark** [comment]
hehe, either way we should probably complete the guide and make it clear even for composer beginners on how to run them.
That side note about the danger here might also be a valuable addition.

**Comment by markstory** [comment]
I personally find that if one is going to maintain standalone plugins there is actually a benefit in developing them in isolation, or symlinking into an app while they are being built. Of course composer will trash symlinked repos too :cry:

**Comment by rchavik** [comment]
When symlinking:

- Read composer/composer#3050
- Note: `--prefer-source`

**Comment by markstory** [comment]
Neato, I didn't know about `--prefer-source`.

**Comment by markstory** [comment]
Closing as I never heard back about #2416
