### ISSUE TITLE
[ Blog Tutorial - Part 2 ] does not run ?

### ISSUE THREAD

**Issue by nagoring** [cakephp/docs#2363]
Hello 

[ Blog Tutorial - Part 2 ] does not run.
misstake function index in [Create the Articles Controller] .

NG
$articles = $this->Articles->find('all');
$this->set(compact('articles'));

OK
$articles = $this->Articles->find('all');
$this->set('articles');

http://book.cakephp.org/3.0/en/tutorials-and-examples/blog/part-two.html

**Comment by andtxr** [comment]
``$this->set(compact('articles'));`` works fine.
I did not catch the problem.

**Comment by dereuromark** [comment]
What you describe as OK I would not use to pass variables down. Instead the first example should work just fine. It does for all of us. Double-check that you didnt make a spelling mistake.

**Comment by nagoring** [comment]
Thank you very much for your advice.
It was settled.
