### ISSUE TITLE
Reverse Dispatcher and Routes inside intro.rst?

### ISSUE THREAD

**Issue by warriorkitty** [cakephp/docs#2371]
https://github.com/cakephp/docs/blob/3.0/en/intro.rst#cakephp-request-cycle

Here, the book says:

![1](https://cloud.githubusercontent.com/assets/5781483/6091833/f6ea9eea-aebe-11e4-8b6e-d08eb6e5c34a.png)

But the picture above in docs shows differently?

![123](https://cloud.githubusercontent.com/assets/5781483/6091834/1bc83768-aebf-11e4-86fe-62aca47b0a0b.png)

**Comment by andtxr** [comment]
Thanks @warriorkitty :+1:

**Comment by antograssiot** [comment]
fixed in #2372
