### ISSUE TITLE
branch tag is not clear enough

### ISSUE THREAD

**Issue by warriorkitty** [cakephp/docs#2385]
https://github.com/cakephp/docs/blob/3.0/en/installation.rst#keeping-up-to-date-with-the-latest-cakephp-changes

In this example, it's not clear which part of the composer.json is "branch". Please provide the example with the word branch inside.

Example:
![cake2](https://cloud.githubusercontent.com/assets/5781483/6101275/a33e4abc-b021-11e4-82d3-6b8b8d3bcff4.png)

**Comment by antograssiot** [comment]
@warriorkitty I would rather remove the sentence after the example : 
``Where <branch> is the branch name you want to follow``. 
as the most important here IMO is the composer ``php composer.phar update``.

Would it be ok for you ? Do you wan't to try and submit a PR, if not I can handle it ?

**Comment by warriorkitty** [comment]
@antograssiot I agree. Sure, I can try it.

**Comment by antograssiot** [comment]
a Pr is open
