### ISSUE TITLE
Documentation for cakePHP-3Translation (GERMAN)

### ISSUE THREAD

**Issue by joerg1979** [cakephp/docs#2402]
Hi together,
is it planned to publish a german CookBook-transaltion when the final version of cakePHP3 is released.

Regards
Jörg

**Comment by cake17** [comment]
Hi @joerg1979 
I remember that german guys from core team said it was not necessary to have a german translation as almost all germans speak english.

But if you're willing to translate it or find a german team that wants to participate, we could add a german folder structure.

**Comment by ravage84** [comment]
Hallo Jörg

You find the previous discussion here:
https://github.com/cakephp/docs/pull/1531

Actually I am rather willing to help German speaking CakePHP developers in person through IRC or anything else than to see somebody start the German translation only to let it become abandoned...

@dereuromark already held two CakePHP Meetups in Berlin recently. It's likely there will be more and may be in other places.
Also we are building up a German Community on Facebook:
https://www.facebook.com/groups/146324018754907/

Also I was thinking about opening up an official German CakePHP IRC channel ``#cakephp-de`` on Freenode.

I think there are REALLY better ways to help the German community than to start a German translation of the book....

Grüsse aus der Schweiz

**Comment by markstory** [comment]
Closing as the existing German contributors don't think that a translation is necessary. I think having other support channels for groups in different languages is a great idea.
