### ISSUE TITLE
Improve the Doc link for Chinese need update

### ISSUE THREAD

**Issue by dotku** [cakephp/docs#2463]
The link for improve the doc is https://github.com/cakephp/docs/edit/master/zh_CN/installation.rst; however the currect one is https://github.com/cakephp/docs/edit/master/zh/installation.rst.

**Comment by markstory** [comment]
I think this might have something to do with the directory being zh, but the language name being zh_CN in zh/conf.py. Perhaps @blackpuppy knows more.

**Comment by blackpuppy** [comment]
@dotku, you can take a look at the discussion of the pull request [#1754](https://github.com/cakephp/docs/pull/1745).  Basically, the language is zh_CN and the physical path/URL is zh.  So the "Improve this Doc" button should follow the physical path/URL.  Such inconsistency is the worry that I had at the moment.  At that time, we changed the ``lang_link()`` and ``has_lang()`` functions in file ``config/cake18n.py`` to map the language to folder.

To fix the problem, we need to map the language to the physical path/URL for the "Improve this Doc" button too.  Currently its link is:

    href="https://github.com/cakephp/docs/edit/{{ branch }}/{{ language }}/{{ pagename }}.rst"

Could we add another variable lang_folder (="zh" for language zh_CN) for this?  Apparently, the language and folder are two different things now.

**Comment by blackpuppy** [comment]
fixed in pull request [#2464](https://github.com/cakephp/docs/pull/2464)

**Comment by markstory** [comment]
Closing as this should be corrected now.
