### ISSUE TITLE
3.0 - There should be more example of collection methods in "Retrieving data"

### ISSUE THREAD

**Issue by lorenzo** [cakephp/docs#2468]
The only examples of using collection methods for finders are in the "Query Builder" section, which some users never imagined them to be there. We should move some of the example and add a few more

**Comment by markstory** [comment]
Would having examples of using map(), combine(), and extract() help? I think we have to be careful documenting all the methods as many collection methods have SQL variants that should be used instead.

**Comment by markstory** [comment]
Fixed with #3082
