### ISSUE TITLE
Calling the dirty method for associated entities when these are updated manually.

### ISSUE THREAD

**Issue by rawroland** [cakephp/docs#2473]
It would be a good idea to mention that saving associated entities when the data has been changed would only function if the `dirty` method is called on that property. See [https://gist.github.com/rawroland/de6f0959cf435633083e] for an example of the method call.

**Comment by markstory** [comment]
Where would you expect to see this mentioned?

**Comment by rawroland** [comment]
I think it would make sense in the [saving associations](http://book.cakephp.org/3.0/en/orm/saving-data.html#saving-associations) section.

**Comment by markstory** [comment]
Thanks, I'll get that added unless you want to do the honors :smile:

**Comment by markstory** [comment]
Fixed in #2478
