### ISSUE TITLE
3.0 - Associations stategy

### ISSUE THREAD

**Issue by patrickconroy** [cakephp/docs#2476]
This tripped me up a couple times until I dug into the core. On http://book.cakephp.org/3.0/en/orm/associations.html it says that strategies default to 'SELECT', which:

1. Isn't a valid strategy, it should be lowercase 'select'. 'SELECT' throws an error if you attempt to set that as a strategy.
2. Isn't the default. The default is 'join'.
3. There are 3 valid strategies, not 2. 'join', 'select', 'subquery'.

I started updating my docs fork but I don't know exactly what the language should be.

**Comment by lorenzo** [comment]
the reason is in uppercase is because it defaults to `Association::STRATEGY_SELECT`. What do you mean you don't know what language should be?

**Comment by patrickconroy** [comment]
`STRATEGY_SELECT` has a value of `'select'`. Wrapping quotes around (half of) a const name is confusing. The value of `STRATEGY_SELECT` isn't `'SELECT'`. Users can't specify `'SELECT'`, and you're expecting them to know that when that's construct of the internals.

And by language I mean that it needs to explain 3 different strategies, not the two that it currently does.

**Comment by bcrowe** [comment]
1. I agree that it should reflect the actual key's userland value.
2. The default is only 'join' when containing a hasOne/Many on the subsequent belongsTo Model. Although, I think this could be clarified: `join` if possible - else `select`.
3. Yup.

I can update this.

**Comment by bcrowe** [comment]
Ah, actually... the listed strategies under each hasMany / belongsTo section are correct for their respective association types. So, all three *are* covered.

**Comment by patrickconroy** [comment]
Hm.. I don't see any association type describing the 'join' strategy. And so only `hasOne` and `belongsTo` default to `join`, it seems?

**Comment by bcrowe** [comment]
@patrickconroy Right, because you wouldn't be using `join` with hasMany, etc. `join`'s existence is sort of implicit via `hasOne`'s and `belongsTo`'s `joinType` option and lack of a `strategy` option.

**Comment by patrickconroy** [comment]
Thanks @bcrowe. Right now the strategy for hasOne / belongsTo is mutable.. should that be updated so that if users try changing it it throws an error? Maybe if whatever classes extend `Association` have a `$validStrategies` property instead of a single `$valid` array in `\Cake\ORM\Association`? It might cause less headaches for people.
