### ISSUE TITLE
HABTM Documentation not correct

### ISSUE THREAD

**Issue by ctopjian** [cakephp/docs#2486]
After seeking the help of *"savant"* on #cakephp irc chat, we both agreed the documentation found at [http://book.cakephp.org/2.0/en/models/saving-your-data.html]  for *saveAssociated()* is incorrect.

When attempting to save multiple model data on a _HABTM_ association saveAssociated() does not function as stated. Clarification on the matter in the documentation would be appreciated :-)

**Comment by markstory** [comment]
Closing as I've not heard any other issues related to this.

**Comment by ctopjian** [comment]
Was the saveAssociated() function tested on a HABTM model? Perhaps I should provide an example?

**Comment by markstory** [comment]
Yes, there are tests for saveAssociated() and HABTM. The tests have

```php
		$this->loadFixtures('Article', 'Tag', 'Comment', 'User', 'ArticlesTag');
		$data = array(
			'Article' => array(
				'user_id' => 1,
				'title' => 'Article Has and belongs to Many Tags'
			),
			'Tag' => array(
				'Tag' => array(1, 2)
			),
			'Comment' => array(
				array(
					'comment' => 'Article comment',
					'user_id' => 1
		)));
		$Article = new Article();
		$result = $Article->saveAssociated($data);
		$this->assertFalse(empty($result));

		$result = $Article->read();
		$this->assertEquals(2, count($result['Tag']));
		$this->assertEquals('tag1', $result['Tag'][0]['tag']);
		$this->assertEquals(1, count($result['Comment']));
		$this->assertEquals(1, count($result['Comment'][0]['comment']));
```
