### ISSUE TITLE
Full text search on book.cakephp.org not working when referrer request header isn't sent by the browser (because of missing Access-Control-Allow-Origin header)

### ISSUE THREAD

**Issue by stefan-hausmann** [cakephp/docs#2497]
hope that this is the correct place for the following issue:

when using full text search on book.cakephp.org in Firefox browser, everything works as expected:
![image](https://cloud.githubusercontent.com/assets/5585744/6651316/8b4703be-ca3d-11e4-9799-19bdc90a3487.png)

but when doing the very same search in Chrome, no search results are shown:
![image](https://cloud.githubusercontent.com/assets/5585744/6651320/b296d8f4-ca3d-11e4-873a-31aeb464f77f.png)

Seems there is a problem with a missing Access-Control-Allow-Origin header that prevents cross-site ajax requests from book.cakephp.org to search.cakephp.org?

**Comment by markstory** [comment]
I can get that fixed.

**Comment by markstory** [comment]
I wasn't able to reproduce this on my machine using Chrome 41.0.2272.89. Both the search at the top of the page, and the standalone search page functioned correctly.

If I inspect the headers on the search responses, they do include `Access-Control-Allow-Origin:http://book.cakephp.org` as expected.

**Comment by stefan-hausmann** [comment]
Thanks for investigating.

This is a screenshot of the headers I get on Chrome  41.0.2272.89 m on Windows 8

![image](https://cloud.githubusercontent.com/assets/5585744/6661548/fd02a1a4-cbad-11e4-8bff-84f773547824.png)

that shows that I don't get the Access-Control-Allow header.

Indeed the problem doesn't seem to exist everytime - I remember it working sometimes in Chrome, too. Maybe there is some load balancing in place on search.cakephp.com so different servers send different headers?

**Comment by stefan-hausmann** [comment]
Seems I've figured it out. I run Chrome in "no-referrers" mode (by appending "--no-referrers" when starting chrome.exe). As soon as I re-enable sending the referrer header again, everything works as expected.

Question is: why isn't the Access-Control-Allow-Origin header set if the referer request header is missing?

**Comment by markstory** [comment]
I don't know. Perhaps it is a 'feature' of chrome?

**Comment by stefan-hausmann** [comment]
I can't think of any reason why Chrome should alter/remove response headers based on whether refererer header sending is enabled/disabled...

just an assumption: maybe search.cakephp.org inspects the referrer request header and sets the Access-Control-Allow-Origin accordingly after white-listing it (as there may be other urls that are allowed to access search.cakephp.org, but aren't shown in the headers when used in the context of book.cakephp.org)?

Although being a minor problem and not of relevance for most of the users, I think full text search should not rely on the refererrer header being set, as it even isn't obvious to the normal user that full text search on book.cakephp.org uses an AJAX request to fetch the search results.

**Comment by markstory** [comment]
I attempted to try and set multiple Access-Control headers, however this caused issues with stock versions of firefox and had to be reverted.

**Comment by stefan-hausmann** [comment]
Thanks for re-opening this and trying to fix it!

I did a little research because I wasn't aware of the problems with setting multiple Access-Control headers before, and this is what I found out:

Suggested and commonly accepted solution is to read the value of the `origin` header sent by the client with cross-domain-requests, then compare this to the whitelist of allowed domains and set the Access-Control-Allow-Origin header accordingly.

So instead of relying on the `referrer` header, just use the `origin` header which is designed for these kind of requests.
See http://stackoverflow.com/a/1850482

Hope the problem could be solved for the some more paranoid people ;-)

Thanks,
Stefan

**Comment by markstory** [comment]
I cna give the origin approach a shot.

**Comment by stefan-hausmann** [comment]
great, thanks!

**Comment by markstory** [comment]
Fixed. The search proxy now looks at both the Origin and Referer headers.

**Comment by stefan-hausmann** [comment]
Mark, thank you very much! Great idea to use both headers to ensure no existing functionality is broken.
