### ISSUE TITLE
Next button should follow the order in the left TOC

### ISSUE THREAD

**Issue by lorenzo** [cakephp/docs#2522]
For example going to http://book.cakephp.org/3.0/en/controllers/components/authentication.html and clicking `next` will take you to a chapter that is several items down in the TOC. If you click `next` again, it'll take you to a section that is not under the same sub-section.

One solution to this is entirely removing the prev - next button.

**Comment by josegonzalez** [comment]
+1 remove

**Comment by markstory** [comment]
I'm fine with killing the next/prev buttons too.

**Comment by antograssiot** [comment]
it works correctly for me locally...

**Comment by markstory** [comment]
Perhaps the problem is related to te version of sphinx?

**Comment by antograssiot** [comment]
@markstory totally possible i'm using 1.2.3 and 1.2 seems to be on the server from what I saw [from jenkins](http://ci.cakephp.org/job/CakePHP%203.0%20-%20Book/1561/console).

**Comment by lorenzo** [comment]
No, the problem is related to the way we show the TOC. It is generated via CSS, and not using the sphinx libs. Therefore, the sequence of the book is entirely unaligned with our menu

**Comment by antograssiot** [comment]
removed in #2547
