### ISSUE TITLE
Console command cake showing error

### ISSUE THREAD

**Issue by mahana123** [cakephp/docs#2530]
>>>>  my php version is as > 5.4.16
![image](https://cloud.githubusercontent.com/assets/7337293/6797950/48b926e6-d22e-11e4-81dc-50114d514cd6.png)

>>>>  after i set up cakephp3.0 first stable release the initial screen shown like below 

![image](https://cloud.githubusercontent.com/assets/7337293/6797962/6d324822-d22e-11e4-8d12-f5672be84564.png)

But when i run the command "cale" in console it shows me error like like below

![image](https://cloud.githubusercontent.com/assets/7337293/6797923/fef2c490-d22d-11e4-8220-fa8efd6a2df9.png)

Any solution ?

Note : the bin directory i have added to my Environment variable so cake can run from command from any path.

**Comment by rchavik** [comment]
Are you sure you're using the correct php in the console?

**Comment by lorenzo** [comment]
Show the output of `php -v` when you run it in the console

**Comment by mahana123** [comment]
ohh !!! its my fault i mapped php 5.3.10 from wamp server and i m using xampp 5.6. 
Thanks rchavik and lorenzo for saving my time.
