### ISSUE TITLE
3.0 book, union and limit

### ISSUE THREAD

**Issue by ionas** [cakephp/docs#2538]
The book should explain briefly how to add a limit() after doing a union (on the union result)
Rel: http://book.cakephp.org/3.0/en/orm/query-builder.html#unions

**Comment by markstory** [comment]
This might be tricky as applying limits to unions in a cross vendor way is not simple. The most compatible way to do it is with yet another select statement.

**Comment by ionas** [comment]
Yeah... hm. Some user found a way to add epilogue() or so to the query to have the limit run on the union but that might still be mysql only.

While I am not entirely happy as it is a very rare case (unions, I hope) I am going to close this.
