### ISSUE TITLE
Docs on a plugin AppController lacking and outdated

### ISSUE THREAD

**Issue by watermark** [cakephp/docs#2539]
The section discussing setting up controllers in a plugin doesn't go into much detail on setting up the AppController in the plugin.  It does mention creating a file called "ContactManagerAppController", which seems inappropriate for cake3.

Cake bake makes a file called just "AppController.php" in the plugin's Controller directory.  This file contains:

```php
<?php

namespace PluginName\Controller;

use App\Controller\AppController as BaseController;

class AppController extends BaseController
{

}
```

**Comment by markstory** [comment]
I can update the plugin docs.

**Comment by markstory** [comment]
Closing as a pull request to update the docs is up now.
