### ISSUE TITLE
3.0 - Add a list of all TestCase assertion methods & add missed methods to the IntegrationTestCase list

### ISSUE THREAD

**Issue by Xety** [cakephp/docs#2543]
Hello,

It should be nice to have a list of the `TestCase` assertion methods like the `IntegrationTestCase` list : http://book.cakephp.org/3.0/en/development/testing.html#assertion-methods because tbh i didn't know that there were all this assertion methods.

Methods to add in the list : 
- assertTextNotEquals()
- assertTextEquals()
- assertTextStartsWith()
- assertTextStartsNotWith()
- assertTextEndsWith()
- assertTextEndsNotWith()
- assertTextContains()
- assertTextNotContains()
- assertTags()
- assertHtml()

Also, in the `IntegrationTestCase` list, some methods are missed :
- assertContentType()
- assertResponseNotContains()
- assertCookie()

**Comment by markstory** [comment]
Could we just link to the API? That would reduce maintenance and give people always current docs.

**Comment by Xety** [comment]
Yes good idea.
