### ISSUE TITLE
Version banner

### ISSUE THREAD

**Issue by davidyell** [cakephp/docs#2544]
I was just on the book, and I saw the new banner

`This document is for CakePHP 3.0. You might want to refer to the 2.x stable documentation if you are not using CakePHP 3.0.`

Which is great, but I had a minor pointer, I'd like to suggest changing the wording to remove the word 'stable'. As `2.x` is stable, and to me it makes it sound like `3.x`, the document you're currently looking at, isn't stable.

Why is it `CakePHP 3.0` but `2.x` ? Could we not just say `v2` and `v3` ?

Just a thought

**Comment by markstory** [comment]
Yeah, I'm going to update the links and banners this weekend.

**Comment by davidyell** [comment]
Ace, thanks Mark.

**Comment by antograssiot** [comment]
updated in #2547

**Comment by markstory** [comment]
Reopening so I don't forget to fix nginx and add notes.

**Comment by markstory** [comment]
Closing as #2568 is open now.
