### ISSUE TITLE
2.X - HtmlHelper::link() visual bug

### ISSUE THREAD

**Issue by HavokInspiration** [cakephp/docs#2551]
I noticed an error on the HtmlHelper doc for master ([link](http://book.cakephp.org/2.0/en/core-libraries/helpers/html.html#HtmlHelper::link)).

Apparently, this is wrapped in a blockquote.
I tried to take a look at it, but I don't really know the technology and the formating around the doc and could not manage to find the cause of this.
The only thing striking me would be the line length of the method declaration but I don't know if that can have an impact.

See screenshot below :

![screenshot from 2015-03-26 22 28 11](https://cloud.githubusercontent.com/assets/5243386/6857525/95f3ffd2-d407-11e4-9c20-8301d90fa38e.png)

**Comment by markstory** [comment]
Yep, looks bad.
