### ISSUE TITLE
Add language selection for mobile devices

### ISSUE THREAD

**Issue by ravage84** [cakephp/docs#2556]
On mobile devices there is no way to change the language.
Yesterday I wanted to give somebody the link to a translated page but couldn't without changing the URL manually.
We should add a language selection for mobile devices, too.

![book-30-on-mobile](https://cloud.githubusercontent.com/assets/625761/6867955/5bce8c98-d487-11e4-9e97-bd391c7b3760.png)

**Comment by ravage84** [comment]
Probably this should be fixed in combination with https://github.com/cakephp/docs/issues/2523

**Comment by markstory** [comment]
Where could we put another menu?

**Comment by HavokInspiration** [comment]
Perhaps the "Search" button could be overlapping the search input, "be in it" in a way (I have trouble finding a way to express this correctly in English).
That would make room for another button.

**Comment by ravage84** [comment]
@HavokInspiration you probably mean something like this?

![mockup](https://cloud.githubusercontent.com/assets/625761/6882282/581d36d2-d57f-11e4-9c81-42061514b48c.png)

@markstory I think his idea is the best way right now.
Alternatively at the bottom, which sucks for people who often need to switch, though.
But may be we have to rethink the whole header/navigation organisation...

**Comment by HavokInspiration** [comment]
@ravage84 Yep, exactly. I edited my first comment and posted a screenshot
But I fear that this will require a lot of changes in the header style.
From what I gathered, I think it could be done only with CSS, the architecture seems okay for this.

That will require some extensive tests though.

**Comment by chinpei215** [comment]
What about adding the language selection into the navigation? I think it would be easy to implement.
```javascript
// In app.js
modal.append( '<h2>Other Languages</h2>' );
modal.append( $('.languages ul').clone() );
```
![lang](https://cloud.githubusercontent.com/assets/7399393/14861341/ca27990c-0ce7-11e6-8f5d-6080f0e0a592.png)

**Comment by markstory** [comment]
This has been addressed by the redesign.
