### ISSUE TITLE
clean depreciated branches

### ISSUE THREAD

**Issue by cake17** [cakephp/docs#2559]
To me, the following branches can be removed, but just to be sure

- **3-0-template** : the changes from last commit of this branch are already inside the 3.0 branch.
- **3.0-formatresults** : same here
- **3.0-tutorial-fixes** : last changes on Mar 17, 2014
- **acl-rewrite** : last changes on Mar 14, 2012
- **revert-1784-patch-2** : last changes on Sep 29, 2014
- **update-testing-migration** : last changes on 24 Nov 2014

**Comment by markstory** [comment]
Thanks for pointing this out. I deleted the stale branches.
