### ISSUE TITLE
3.0 - **recipies** in index.html

### ISSUE THREAD

**Issue by ITCherry** [cakephp/docs#2565]
Hi
I would like to help translate "Traditional Chinese" Language.
For index.html, I have a question to ask.
The word is correct?  **recipies**
I do not know what it means.
Sentence:
"To help you along, we have created a cookbook packed with examples and recipies to get the common tasks completed."

**Comment by lorenzo** [comment]
It should be recipes, it is a typo

**Comment by markstory** [comment]
Fixed in 726d5a879c9bd4741186a7aba0c28477b38dd2d0

**Comment by ITCherry** [comment]
Thanks your help.
