### ISSUE TITLE
Make bake plugin dependency clearer

### ISSUE THREAD

**Issue by dereuromark** [cakephp/docs#2589]
In http://book.cakephp.org/3.0/en/bake/usage.html
it still looks like 2.x, that bake it natively included. We should probably add a note that it has to be included via composer in order to be able to bake.

**Comment by ravage84** [comment]
:+1:  A note stating that it is not included anymore and a link to https://github.com/cakephp/bake#installation should suffice.

**Comment by markstory** [comment]
Pull request up now.
