### ISSUE TITLE
About find('list')

### ISSUE THREAD

**Issue by zx4357685** [cakephp/docs#2626]
I think there has someting lost on "retrieving-data-and-resultsets" view 

I think you should introduce the value format of  "keyField" and "valueField"

When I use the find('list') to make the data like 
    
    [
        'Table1s.id'=>'Table2s.name'
    ]

the option 'keyField' and "valueField" should be like 'table1.id' and "table2.name"

May be I didn't see it,if so,please close this

**Comment by jadb** [comment]
Do you mean this: 

http://book.cakephp.org/3.0/en/orm/retrieving-data-and-resultsets.html#finding-key-value-pairs

**Comment by zx4357685** [comment]
Yes!
But I don't want to get array form the same table

**Comment by lorenzo** [comment]
It is missing an example of how to use find('list') with an association

**Comment by markstory** [comment]
Pull request up.
