### ISSUE TITLE
$this->table in Table object not taking in consideration

### ISSUE THREAD

**Issue by anouarcharif** [cakephp/docs#2630]
Hi,

I was building a Plugin in cakephp3 until i found i problem with $this->table("my_table");

SQLSTATE[42S02]: Base table or view not found: 1146 "table" doesn't exist, even if i specify my_table in ModelsTable class ... so i think it's an issue ...

**Comment by dereuromark** [comment]
Why are you posting this in docs and not in cakephp itself?

**Comment by anouarcharif** [comment]
Because it's an issue with cakephp 3 ... im wrong ?

**Comment by dereuromark** [comment]
This is about the documentation. The bugtracker is @ https://github.com/cakephp/cakephp/issues
