### ISSUE TITLE
CakePHP Website not working

### ISSUE THREAD

**Issue by ITCherry** [cakephp/docs#2650]
Hi everyone,

When I open the cakephp website, this webpage is not available.
About cakephp.org and subsites are not working. Help me deal the issue.
I want to keeping studying.

**Comment by ravage84** [comment]
I cannot confirm this.
Just checked with cache disabled.
All links on the front page work properly.

May be try to clear your cache as the cakephp.org website got redesigned recently.

**Comment by lorenzo** [comment]
There was an issue with the servers, we apologise for the problem

**Comment by ITCherry** [comment]
Never mind. When the problem occurred, I had done clear cache.
Be glad to have solved the problem.
