### ISSUE TITLE
logic error in sub-query snippet

### ISSUE THREAD

**Issue by donhuvy** [cakephp/docs#2658]
In this section: 
https://github.com/cakephp/docs/blob/master/en/models/retrieving-your-data.rst#sub-queries

have logic error at this line:

$subQuery = ' "User"."id" NOT IN (' . $subQuery . ') ';

**Comment by markstory** [comment]
What should the code be instead?

**Comment by donhuvy** [comment]
I am sorry. close #2658. but I think we should naming $subQuery in another way.

**Comment by markstory** [comment]
If you have a suggestion for a different name, feel free to open a pull request :smile:
