### ISSUE TITLE
Explain the difference between format() and other methods in Time

### ISSUE THREAD

**Issue by lorenzo** [cakephp/docs#2685]
The format from ICU is only valid for the methods that output locale-aware strings, but some people try to use `format()` as if it were ICU aware.

Refs https://github.com/cakephp/cakephp/issues/6137

**Comment by markstory** [comment]
Should format() also accept ICU constants?

**Comment by lorenzo** [comment]
that would be even more confusing, imo

**Comment by markstory** [comment]
Ok.

**Comment by markstory** [comment]
Closing this as the original issue was for TimeHelper which aliases format() to _be_ the i18nFormat method. This is a bit silly, but TimeHelper has always been a bit silly. I'll update the relevant doc block on TimeHelper instead.
