### ISSUE TITLE
composer create-project not working on ubuntu 14.04

### ISSUE THREAD

**Issue by systemshq** [cakephp/docs#2692]
When I type in:-

php composer.phar create-project --prefer-dist cakephp/app test

into my ubuntu 14.04 system it finishes with the error messages below. Is it me doing something wrong or is this a bug?

psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to work.)
cakephp/debug_kit suggests installing ext-sqlite (DebugKit needs to store panel data in a database. SQLite is simple and easy to use.)
Writing lock file
Generating autoload files
Created `config/app.php` file
Script App\Console\Installer::postInstall handling the post-install-cmd event terminated with an exception

                                                        
  [InvalidArgumentException]                            
  Maximum number of attempts must be a positive value.  
                                                        

create-project [-s|--stability="..."] [--prefer-source] [--prefer-dist] [--repository-url="..."] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progress] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [package] [directory] [version]

**Comment by lorenzo** [comment]
Fixed, it was a change in composer that broke our installation script. Thanks for the report

**Comment by ravage84** [comment]
Crosslinking: https://github.com/cakephp/app/issues/241
