### ISSUE TITLE
bookmarker tutorial

### ISSUE THREAD

**Issue by matusmuransky** [cakephp/docs#2696]
Hi there,
I'm experiencing I guess a routing problem. I've followed the whole tutorial up to the point where you define the router as stated in the tutorial and right after that you define the tags function in the BookmarksController.php file. After that, when i refresh the page it still comes up with an error saying that the Error: TaggedController could not be found. even though I edited the routes file and the BookmarksController just like the tutorial says. 

Thanks for any help in forward!

**Comment by markstory** [comment]
What does your routes file look like?
