### ISSUE TITLE
Table validations sets is difficult to find in the book

### ISSUE THREAD

**Issue by lorenzo** [cakephp/docs#2704]
In general the descriptions for validating data that is meant to be saved in tables is scattered and difficult to find, there should be a chapter dedicated to it.

**Comment by markstory** [comment]
Would having it all in one place in the saving chapter be better, or we could have a separate chapter for validation.

**Comment by ravage84** [comment]
@markstory It might be good to have it mentioned and linked from there but adding more  and more stuff to one chapter doesn't make it more overseeable...
So :+1: to having it in one place, but not preferably not squashed into an existing chapter.

**Comment by markstory** [comment]
I can try splitting out validation into a separate chapter.

**Comment by markstory** [comment]
Closing as #2717 is open now.
