### ISSUE TITLE
A note about using custom authentication objects with plugin notation

### ISSUE THREAD

**Issue by elboletaire** [cakephp/docs#2746]
I'm not sure about adding this issue here. Probably would be better an issue directly to the CakePHP core source code, but I'm not sure if this is a documentation issue or a code issue.

In [Using Custom Authentication Objects](http://book.cakephp.org/3.0/en/controllers/components/authentication.html#using-custom-authentication-objects) it states that you can configure a plugin authentication object using plugin notation:

```php
    $this->Auth->config('authenticate', [
        'Openid', // app authentication object.
        'AuthBag.Combo', // plugin authentication object.
    ]);
```

But this doesn't seem to work, unless I specify the full namespace of the class:

```php
    $this->Auth->config('authenticate', [
        'AuthBag\Auth\Combo', // plugin authentication object.
    ]);
```

BTW, I think that the "Creating Custom Authentication Objects" and "Using Custom Authentication Objects" examples should be the same. Having multiple examples is confusing (the example creates an `OpenidAuthenticate` class and in the other example we configure `AuthBag.Combo`).

**Comment by gtrias** [comment]
+1

**Comment by lorenzo** [comment]
In your case, it will only work with the full namespace as it is missing the 'Authenticate' word at the end. It should has been `class ComboAuthenticate`.

I agree having two sections is silly, do you want to send a pull request for that?

**Comment by elboletaire** [comment]
Ok this is a miss-documented feature. The class has the `Authenticate` word and you must not specify it.

In my case I've created an 'OAuth2Authenticate' object and I was specifying it as:

```php
    $this->Auth->config('authenticate', [
        'OAuth2.OAuth2'
    ]);
```

Doing it this way works. If we had the same example for both probably wouldn't happen this.

Soooo, I'll do a pull request adding this note + changing the examples to be the same :smile:
