### ISSUE TITLE
[3.X] [View] prepend capture mode?

### ISSUE THREAD

**Issue by albertboada** [cakephp/docs#2749]
Is there any particular reason why `View->prepend()` has no capture mode? I've been playing with Cake3 only for a few days but I have the feeling this is very needed on a "extending templates/layouts in multiple levels" use case. Say:

Layout1: Hey
Layout2: there,
View: Albert

```html
<!-- View template --> 
<?php $this->layout = 'Layout2' ?>

<?php $this->prepend('topbar') ?>
    <div>Albert</div>
<?php $this->end() ?>
<!-- -->

<!-- Layout2 -->
<?php $this->extend('Layout1') ?>

<?php $this->prepend('topbar') ?>
    <div>there, </div>
<?php $this->end() ?>
<!-- -->

<!-- Layout1 -->
<?php $this->prepend('topbar') ?>
    <div>Hey </div>
<?php $this->end() ?>

<?= $this->fetch('topbar') ?>
<!-- -->
```

If I understood correctly, the alternatives would be either

```html
<!-- Layout2 -->
<?php $this->start('topbar') ?>
    <div>there, </div>
    <?= $this->fetch('topbar') ?>
<?php $this->end() ?>
```
or 

```html
<!-- Layout2 -->
<?php $this->prepend('topbar', '<div>there, </div>'); ?>
```

which are somehow less convenient in lots of cases.

But most important, why offer this syntax with `append` (which is useful for appending in a same-template scenario) but not with `prepend` (which would be useful for *"appending"* in a template hierarchy scenario)?

**Comment by dereuromark** [comment]
I can see the point of having those two methods behave similarly.
But if you look at the code you will see the difficulties with implementing it the way you suggest:
https://github.com/cakephp/cakephp/blob/master/src/View/View.php#L579-L580

It will start capturing, echo the existing content and then end it afterwards.
Doing this in a similar way might very well mess up the order for mode "prepend", right?

**Comment by markstory** [comment]
You can use start() and fetch to 'prepend'. That is wht there is no prepend with capture mode.

If you feel strongly about this feature you can always provide a pull request to implement it. However, it isn't as trivial as append() with capture is.

**Comment by albertboada** [comment]
Ok, I see. It would be nice to have but it's a complex problem to solve. Roger that.
I will look into it a little bit, altho if u have not been able to solve this I dont think I will...

@markstory Is the alternative you propose the same that I mentioned in the first post or are u talking about a different approach? 

Btw, sorry for opening this in the `docs` project, I'm not sure what happened here (or for opening it at all lol)

**Comment by dereuromark** [comment]
Let's close this and once you have a solution please make a PR to the main repo at https://github.com/cakephp/cakephp . Thank you for giving it a try!
