### ISSUE TITLE
Note about shell aliasing missing

### ISSUE THREAD

**Issue by dereuromark** [cakephp/docs#2754]
We should add a note about how to short-alias shells @ http://book.cakephp.org/3.0/en/console-and-shells.html

Only the docs mention it super-briefly: http://api.cakephp.org/3.0/class-Cake.Console.ShellDispatcher.html#_alias

And maybe also, that shells are now auto-aliased to the short form, e.g. `AssetCompress.AssetCompress` can now be used as `AssetCompress` again just as it used to be possible in 1.x :)

**Comment by markstory** [comment]
Pull request up now.

**Comment by dereuromark** [comment]
The short aliasing is not mentioned @ https://github.com/cakephp/docs/commit/016b052a2719f4855fb9e02e06bb0203c3cc29ba though?
That was the main reason for this ticket as this is not to be found anywhere in the docs yet.

**Comment by markstory** [comment]
@dereuromark Doesn't the example show one? I thought the paragraph explained the aliasing process as well. What did you have in mind?

**Comment by dereuromark** [comment]
`cake b` for `cake bake` or `cake m` for `cake migrations` when you use custom short aliasing in your bootstrap file.

**Comment by markstory** [comment]
So adding your own aliases?

**Comment by dereuromark** [comment]
Yes, one letter short-codes as an example.

**Comment by markstory** [comment]
Ok, that wasn't at all clear from this issue. I will update the pull request when I get to a real computer.
