### ISSUE TITLE
magic findBy doc missing changes

### ISSUE THREAD

**Issue by dereuromark** [cakephp/docs#2811]
in 2.x findBy returned find(first) - limit 1 so to speak
in 3.x it is only mentioned implicitly @ http://book.cakephp.org/3.0/en/orm/retrieving-data-and-resultsets.html#dynamic-finders (that it now behaves like `find('all')`).
I think it should be added more clearly that you now need to append `->first()` to have the same resut as in 2.x (limit 1 instead of all).
Also here: http://book.cakephp.org/3.0/en/appendices/orm-migration.html#finder-method-changes and/or in the 3.0 migration guide.

Otherwise people trip over it when upgrading 2.x apps that use those finders a lot.

**Comment by markstory** [comment]
Fixed with #2816
