### ISSUE TITLE
typo in cakephp3.0 cookbook pdf 

### ISSUE THREAD

**Issue by sumit-sharma** [cakephp/docs#2836]
"Table class names are plural and CamelCased. People, BigPeople, and ReallyBigPeople are all examples of conventional model names." should be "Model class names are plural and CamelCased. People, BigPeople, and ReallyBigPeople are all examples of
conventional model names.
"

**Comment by sumit-sharma** [comment]
"Table class names are plural and CamelCased. People, BigPeople, and ReallyBigPeople are all examples of conventional model names." should be "Model class names are plural and CamelCased. People, BigPeople, and ReallyBigPeople are all examples of
conventional model names.
"

**Comment by antograssiot** [comment]
it make sense to me that it's table here. Entities are singular so it seems good to be that specific.

**Comment by markstory** [comment]
I agree with @antograssiot. Table and entity classes together represent a big part of an application's model. Being specific here about conventions for each half is useful.
