### ISSUE TITLE
Explanations needed on page 16 and 17 in the Cookbook

### ISSUE THREAD

**Issue by ThinkALot** [cakephp/docs#2847]
I would like to suggest some changes to pages 16 and 17 in the online Cookbook, as I am confused by what is presently written there. (I am new to CakePHP)

In the following doc:

http://book.cakephp.org/3.0/_downloads/en/CakePHPCookbook.pdf

on page 16, the second example is:

```php
public function tags()
{
$tags = $this->request->params['pass'];
$bookmarks = $this->Bookmarks->find('tagged', [
'tags' => $tags
]);
$this->set(compact('bookmarks', 'tags'));
}
```

A detailed explanation of these two items would be very helpful:

```
request->params['pass'];
compact('bookmarks', 'tags');
```

Where does the value for bookmarks come from? 

The third example is:

```
public function findTagged(Query $query, array $options)
{
$fields = [
'Bookmarks.id',
'Bookmarks.title',
'Bookmarks.url',
];
return $this->find()
->distinct($fields)
->matching('Tags', function ($q) use ($options) {
return $q->where(['Tags.title IN' => $options['tags']]);
});
}
```

A detailed explanation of each of these items would be very helpful:

Query $query 
array $options
distinct($fields)
function ($q) 
use ($options) 
$q
$options['tags']

On page 17, in the first example, an explanation of this syntax would be helpful:
$this->Html->link

Also, why is there a letter h before the first parenthesis?
<small><?= h($bookmark->url) ?></small>

It is not clear to me how the sentence after the page 17 example is relevant to the example. Here is the sentence:

" CakePHP expects that our templates follow the naming convention where the template has the lower case and underscored version of the controller action name." I understand the meaning, but should I see an example somewhere? Is it referring to something else on the page?

Another sentences states that " In our view we’ve used a few of CakePHP’s built-in helpers". But what exactly is a helper? Please show which item in the code is considered a helper.

Also, I cannot find tags.ctp anywhere in the project folders, which I set up according to the instructions provided. Where can I find tags.ctp ?

Thanks.

**Comment by markstory** [comment]
The findTagged() method is using a few features of newer versions of PHP. Namely:

* [type hints](http://php.net/manual/en/language.oop5.typehinting.php)
* [anonymous functions](http://php.net/manual/en/functions.anonymous.php)

The syntax on page 17 is an object method call, which has some [examples here](http://php.net/manual/en/language.oop5.visibility.php. It also use [short tags](http://php.net/manual/en/language.basic-syntax.phptags.php).

I'll add some more detail about `h()` and what helpers are, and where tags.ctp comes from though.

**Comment by dakota** [comment]
`request->params` is part of the `Request` object, and is described later in the book (http://book.cakephp.org/3.0/en/controllers/request-response.html#request-parameters)

`compact('bookmarks', 'tags');` is a basic PHP language construct (http://php.net/compact). My opinion is that there should be an implicit assumption in the CakePHP Book that the reader should have a working knowledge of PHP before tackling a framework. However, perhaps we need to look at introducing links to the PHP manual within the tutorials?

`bookmarks` is assigned by this line:

```php
$bookmarks = $this->Bookmarks->find('tagged', [
'tags' => $tags
]);
```

`Query $query` and `array $options` are [type hints](http://php.net/manual/en/language.oop5.typehinting.php) (As mentioned by @markstory above), and is again a basic PHP construct.

`distinct($fields)` is part of the CakePHP ORM and is explained in depth later on in the book (http://book.cakephp.org/3.0/en/orm/query-builder.html), it generates `DISTINCT` SQL queries (http://www.techonthenet.com/sql/distinct.php) which is a basic SQL construct (And again should not be explained in the CakePHP book)

`function ($q)  use ($options)` is a [PHP closure/anonymous function](http://php.net/manual/en/functions.anonymous.php), which is a PHP construct that was introduced in PHP 5.3

`$q` is simply a function argument for the anonymous function.

`$options['tags']` is an array and we are accessing the `tags` element within that array (Again, basic PHP)

Your comments are definitely valid, but we must just be careful not to turn the CakePHP book into a glorified clone of the PHP manual.

**Comment by ThinkALot** [comment]
If an explanation seems redundant, links to the php manual and relevant parts of the Cookbook etc would be very helpful.

Generally, I assume the CakePHP community would like to attract new users. The most likely prospects are people who have not yet adopted a framework, such as young people just learning how to program, or amateurs like me who learned procedural programming years ago, and never got around to object-oriented programming or frameworks. Both types of users are facing a steep learning curve -- and a lot of discouragement. Naturally, they will be inclined to choose the path of least resistance. 

In that regard, I've found the Symphony documentation to be very self-explanatory, but the syntax seems verbose. As for Laravel, I've previously been reluctant to adopt it because it seems to change so much from one version to the next. But I'm really impressed with the current Laracast videos. They spoon-feed the viewer, and go one small step at a time, alternately explaining the procedures and the related concepts. I find that approach really helpful. See for yourself: https://laracasts.com/series/laravel-5-fundamentals 

So at this point, I'm inclined to go that route. Nonetheless, I think the CakePHP team could compete, by making instructional videos too. I myself have made some non-technical screencasts, and I can tell you it's not hard. All you need is Camtasia Studio, for example, a half-decent mic, a boom stand, and an audio interface. 

Of course, none of this matters, if the CakePHP team is happy to just keep the existing users. But if you want to retain market share in the long run, you need to make it really easy for less experience users who are just entering the "market". While I don't understand CakePHP very well, I do get the impression that it's a high quality framework that could attract a lot of new users, if you made it easy enough to learn.

**Comment by markstory** [comment]
Closing as the improvements I could reasonably squeeze into the docs have been added. Thanks again for the great feedback @ThinkALot.
