### ISSUE TITLE
Error in the blog tutorial part 3

### ISSUE THREAD

**Issue by ironbone** [cakephp/docs#2851]
When flowing the instruction after
http://book.cakephp.org/3.0/en/tutorials-and-examples/blog/part-three.html#reordering-categories-with-treebehavior
We get an error because of the new version in index().
In the previous version of index() we added pagination which we also use in index.ctp.

After changing the index() the errors are because of using pagination in index.ctp

**Comment by markstory** [comment]
What errors are you getting?

**Comment by ironbone** [comment]
There is the screen-shot in th attachment
I followed the tutorial and I had no problems until this point

The instruction is a little bit not clear. After the  link 
http://book.cakephp.org/3.0/en/tutorials-and-examples/blog/part-three.html#reordering-categories-with-treebehavior
there is the content of index.ctp given. So because there only <tr>,<td> definitions so I thing I should just replace the corresponding part from the previous version of index.ctp by the given part.
Replacing the whole index.ctp has no sens because the given content do not create valid HTML.



Therefore at the end of the new index.ctp I still have the "Pagination" part. But it does not work because in the new version of the action index() in CategoriesController the are no "Pagination" settings
![image](https://cloud.githubusercontent.com/assets/5064512/8118426/17622058-108f-11e5-89bc-406faf504f2e.png)
.

**Comment by markstory** [comment]
Thanks @ironbone I'll update the code snipped to be better.

**Comment by ironbone** [comment]
Thanx - I'm waiting for the update

**Comment by markstory** [comment]
Pull request up now.
