### ISSUE TITLE
3.0 Supported Database Engines/Drivers

### ISSUE THREAD

**Issue by ravage84** [cakephp/docs#2866]
Except for a short list of supported database engines on the installation page
http://book.cakephp.org/3.0/en/installation.html#requirements
and some inline mentions of DB drivers
http://book.cakephp.org/3.0/en/orm/database-basics.html#configuration
there is no prominent list of supported database backends.

For 2.x we had the DataSources page
http://book.cakephp.org/2.0/en/models/datasources.html
, which listed them and was easily reachable through the search, too.
http://book.cakephp.org/2.0/en/search.html?q=sqlserver&check_keywords=yes&area=default

When I search for "sqlserver" now, I get
http://book.cakephp.org/3.0/en/search.html?q=sqlserver&check_keywords=yes&area=default

I think we should have a separate page for the DB engine drivers
http://api.cakephp.org/3.0/namespace-Cake.Database.Driver.html
to make the supported DB engines more visible.

At the same time, we could consolidate some information how  those divers work on that page.

**Comment by markstory** [comment]
There could be a short supported drivers section in the database-basics chapter.

**Comment by markstory** [comment]
New section added. If there is more to be done, pull requests or more comments are appreciated.
