### ISSUE TITLE
Helpers documentation should not mention controllers anymore

### ISSUE THREAD

**Issue by lorenzo** [cakephp/docs#2883]
Since we now have `AppView` we should encourage our users to load helpers there instead of doing it in the controllers: http://book.cakephp.org/3.0/en/views/helpers.html

**Comment by dereuromark** [comment]
What about http://book.cakephp.org/3.0/en/core-libraries/registry-objects.html#loading-objects and the
```php
$this->addHelper('Flash')
```
call?

**Comment by lorenzo** [comment]
what about it @dereuromark ?

**Comment by dereuromark** [comment]
Should those still be promoted/used then?
Because defining them on multiple levels (controller, AppView, view ctp) is sure not the coolest thing.
