### ISSUE TITLE
2 similar paragraphs

### ISSUE THREAD

**Issue by Soelen** [cakephp/docs#2890]
http://book.cakephp.org/3.0/en/bake/usage.html#bake-themes

I got confused because the upper link didn't explained much how to do so, after many tries and confusing I checked other articles and found this

http://book.cakephp.org/3.0/en/bake/development.html#creating-a-bake-theme

it is basicially the same paragraph like from the first link but it is getting more in detail, the first link should be removed or should have at least a link which leads to the second one!

**Comment by markstory** [comment]
Docs updated now.
