### ISSUE TITLE
double line

### ISSUE THREAD

**Issue by developperKesako** [cakephp/docs#2892]
in the page 
http://book.cakephp.org/3.0/en/views/helpers/form.html#generating-entire-forms

they have a double line . The double line is showed in this image 
![doublon](https://cloud.githubusercontent.com/assets/13013352/8301048/f7c1cd34-198a-11e5-9b95-f90be594376d.png)

**Comment by bcrowe** [comment]
Thanks! PR opened https://github.com/cakephp/docs/pull/2893
