### ISSUE TITLE
bug tuto widget

### ISSUE THREAD

**Issue by developperKesako** [cakephp/docs#2894]
Hello, In the tutorial  To the widget wenn we call the function render you have forgott the second arguments . The really function are 
public function render(array $data, ContextInterface $context)

if they don't have ContextInterface $context they have a bug 
![bug_tutorial_widget](https://cloud.githubusercontent.com/assets/13013352/8302638/600d0aa4-1998-11e5-8760-d2e404f87895.png)

**Comment by ravage84** [comment]
Refs: http://api.cakephp.org/3.0/class-Cake.View.Widget.WidgetInterface.html#_render

``public function render(array $data, ContextInterface $context);``

It seems, though, that the ``$context`` parameter isn't used in all implementing classes:
http://api.cakephp.org/3.0/source-class-Cake.View.Widget.BasicWidget.html#47-81
http://api.cakephp.org/3.0/source-class-Cake.View.Widget.FileWidget.html#39-70
http://api.cakephp.org/3.0/source-class-Cake.View.Widget.LabelWidget.html#58-88
http://api.cakephp.org/3.0/source-class-Cake.View.Widget.LabelWidget.html#58-88

**Comment by markstory** [comment]
Pull request open now.
