### ISSUE TITLE
Cannot custom MissingRouteException

### ISSUE THREAD

**Issue by anhtuank7c** [cakephp/docs#2902]
Dear all.
I cannot custom MissingRouteException message.
It always return message: Not Found
I wanna replace by my own language: Trang bạn tìm kiếm không tồn tại.
I have to change the message in Cake Core ExceptionRenderer.php, and it's work but not a good idea.
I did create missing_route.ctp in Error Template folder but in van.
Image here: http://prntscr.com/7kp8h7

**Comment by rchavik** [comment]
Why would you want to do this?  The MissingRouteException is only used when `debug > 0`.  When `debug = 0`, all those exceptions cannot be used.

**Comment by anhtuank7c** [comment]
When user try to access none existing link on my site.
[Production mode]
By default, cakephp v3.0 return message Not Found.
This message look ugly although i did change the error template.
I want the message must friendly and understandable to amateur user.

**Comment by rchavik** [comment]
Then supply your own `APP/View/Errors/error400.ctp`.

**Comment by rchavik** [comment]
For 3.x: `APP/src/Template/Error/error400.ctp`

Thank you @neon1024

**Comment by markstory** [comment]
Closing as there are existing templates that can be updated.

**Comment by anhtuank7c** [comment]
Existing template error400.ctp and error500.ctp can be up to date, but that's layout, when throw MissingRouteException, cannot change the message.
Default and hard fixed message (Not Found) in ExceptionRenderer line 225 and line 227.
I can't change this message.

**Comment by markstory** [comment]
Those messages are not hard coded though. They are run through the i18n functions, but in the `cake` domain, not the default/app domain.

**Comment by davidyell** [comment]
Which raises the question can the existing copy be changed, without having to use the translations?

**Comment by markstory** [comment]
@davidyell Sure - implement your own error handlers.
