### ISSUE TITLE
missing namespace

### ISSUE THREAD

**Issue by Soelen** [cakephp/docs#2903]
http://book.cakephp.org/3.0/en/views/helpers.html#aliasing-helpers

in the
// src/View/Helper/MyHtmlHelper.php
part

namespace App\View\Helper;

is missing, without it cakephp 3 will throw a fatal error out: "cannot redeclare class MyHtmlHelper"

**Comment by dereuromark** [comment]
If you want you can make a PR to fix this.

**Comment by markstory** [comment]
Fixed with 3a2947eefc5f57fd6dadbe88274686905f8f15b5
