### ISSUE TITLE
Bookmarker tutorial is lacking some explanations

### ISSUE THREAD

**Issue by ThinkALot** [cakephp/docs#2925]
On this page:
http://book.cakephp.org/3.0/en/tutorials-and-examples/bookmarks/intro.html

an explanation of the following two examples would be helpful: 
public function tags()
public function findTagged

Thanks.

**Comment by markstory** [comment]
What wasn't clear about these functions? Was it where they should go in the application code? Or what they are doing?

**Comment by ThinkALot** [comment]
I think it would help if you could explain how the example code works. Specifically, 

First example: public function tags

Speaking for myself, I think 
params['pass'];
needs to be explained. I don't know what 'pass' means. I can guess that this is data coming from the router example. But is pass a special word? Or could I write params['xyz']?

Also: find. Is that a built-in function? I think it would help to mention that.

Also: set. An explanation would be helpful. This is the first tutorial. I think the second tutorial explains that "set" is a special word used to pass data to the view. That is suggested in the prior sentence, but a lot is left to the imagination.

When reading this example, there seemed to be so much vagueness that I felt bogged down. I imagine other readers might feel the same way. 

Next: public function findTagged

Again, speaking for myself, I think this needs to be explained: 
"Query $query, array $options"
Where does "$query" come from? 
What does the syntax "Query $query" mean?
Why is Query capitalized?
What is the "options" array?

Also: Find. (again). This seems to by a SQL substitute. Is it? And what does "function ($q) use ($options)" mean? Why is $q in brackets? Is it possible to explain why this particular syntax is appropriate in this particular situation?

I can guess at the answers, but if I do that, I'm never sure whether I'm misunderstanding something.

I hope I answered your question.

Thanks.

**Comment by markstory** [comment]
Thanks for explaining what wasn't clear. I'll add more explanation around the CakePHP features that aren't clear there.

**Comment by ThinkALot** [comment]
Part of what's confusing about the second example is that it seems to mix oop syntax together with procedural programming syntax (i.e. "function ($q)"). I'm not familiar enough with oop to know if this is normal, or if it's a special feature of CakePHP. In any case, I think an explanation would help remove any doubt that readers might have.

Here's some additional feedback: I'm wondering about this sentence, which is on the same web page: "In config/routes.php, add the following at the top of the file:". This sentence precedes the "Router::scope" example. It's been a couple of weeks since I did the tutorial, but I recall struggling to make this work. Eventually I got it to work by inserting the example code not at the top of the file, but after this: "Router::defaultRouteClass('Route');"

By the way, one feature of the php.net web site that seems helpful is the provision for "User Contributed Notes" below each official definition. Those notes typically provide helpful usage examples, as you can see here: 
http://php.net/manual/en/functions.user-defined.php
Perhaps allowing user-contributed notes on the CakePHP website would enable users to benefit from a mutual exchange of ideas, relevant to each particular topic. To avoid spam, I suppose you could allow contributions only from pre-approved individuals. Just a thought.

**Comment by markstory** [comment]
The `function ($q)` syntax isn't necessarily procedural. That specific bit of code creates an [anonymous function](http://php.net/manual/en/functions.anonymous.php) which is also an object.

I can update the routes file example to include the full file contents instead of just the content to append.

We used to have user-contributed notes and it was a disaster. The comments were full of wrong and incorrect information. We removed them because moderating comments and keeping the information correct and free of spam was a considerable amount of work.

**Comment by josegonzalez** [comment]
@ThinkALot a better approach - and one we take now - is allowing users to contribute back to the docs (there is a contribute button on each page). It allows us to better moderate contributions as well as give users the ability to make positive changes :)

**Comment by ThinkALot** [comment]
I understand how spam and misleading user comments can become a huge maintenance headache. And I agree that the CakePHP contribute button is a good idea. However, what I like about php.net is that there are typically so many *examples* below each article -- all crowd-sourced. As an enthusiast, not a pro, I find examples can sometimes help me understand, even when the official docs elude me. I realize the php user community must be relatively large, and so there can be numerous contributors. But I wonder how the website weeds out the inevitable spam and misleading comments. I suppose they must have a system of some kind.

**Comment by markstory** [comment]
I tried to address some of the unclear parts from the original issue description.

**Comment by ThinkALot** [comment]
Thanks. I think that's an improvement. But may I suggest that you clarify further? Specifically:

In the public function tags example, it would be helpful to explain this syntax:
params['pass'];
Is "pass" a special word? Or could I write something like params['xyz']?

In the "public function findTagged" example, it would be helpful to explain the following syntax in detail:
function ($q) use ($options)
If it's an anonymous function -- which is a concept I'm not familiar with -- perhaps you could mention that that is a php feature, not a special CakePHP feature. In any case, it seems a complicated and intimidating bit of code, and no doubt your less-knowledgeable readers -- like me -- would appreciate an explanation.

Thanks.

**Comment by markstory** [comment]
@ThinkALot I can add more information on those.
