### ISSUE TITLE
The blog tutorial has a problem. Also, some suggestions, and a question.

### ISSUE THREAD

**Issue by ThinkALot** [cakephp/docs#2935]
I just finished this tutorial. I liked it better than the bookmarker tutorial, because it was easier to understand. However, I encountered a problem on this page:

http://book.cakephp.org/3.0/en/tutorials-and-examples/blog/part-three.html

in the following sentence:

"Using your web browser, add some new categories using the /yoursite/categories/add controller action."

When I tried that, I found that the Categories drop-down box would not accept any input. I followed the instructions exactly, so I guess something is wrong with the code. What do you think?

Also, I have three suggestions:

1. When you mention this that "the TreeBehavior has been attached to your CategoriesTable in the initialize() method", the first question I have is: "How did the Bake process know that this line of code should be inserted? What was the trigger?" I suggest you comment on this in the tutorial.

2. Windows users would appreciate a reminder to reverse the slash direction in code such as this:
"bin/cake migrations create Initial". I wasted some time yesterday trying to figure out why the bake command was not working for me. (I think the first bake command may be on page 1 of the tutorial.)

3. On page 2 of the tutorial, the following sentence can be found: 
"We use FlashComponent’s magic __call() method to set a message to a session variable, which will be displayed on the page after redirection. " That's puzzling, because the __call() method cannot be seen in any of the code examples. Where is it?

Finally, I have a question: Can a CakePHP 3 website be set up easily on a *shared* server? Creating dynamic websites is something I do occasionally, and while I do the development on Windows 7 and Xampp, the production server is a *shared* Apache Linux server. Will a CakePHP 3 website be difficult to configue on that?

**Comment by markstory** [comment]
> When I tried that, I found that the Categories drop-down box would not accept any input. I followed the instructions exactly, so I guess something is wrong with the code. What do you think?

Did you make some categories? You would need some for the input box to have options.

> Finally, I have a question: Can a CakePHP 3 website be set up easily on a shared server? Creating dynamic websites is something I do occasionally, and while I do the development on Windows 7 and Xampp, the production server is a shared Apache Linux server. Will a CakePHP 3 website be difficult to configue on that? 

Yes. Many people use shared hosting, or services like pagodabox/heroku for hosting small sites.

**Comment by ThinkALot** [comment]
Okay, on the /categories/add page, there's a drop-down box marked "Parent", which seems to serve no purpose. I thought that was where I should enter the new category, but I realize now that the second field is where I should enter it. So the form does work after all. But does the Parent drop-down box actually serve any purpose?

**Comment by ThinkALot** [comment]
After clicking around a bit, I can see that it's possible to create a parent category, and the tree structure becomes visible when creating an article. 

However, the List Categories link displays the same data as the list List *Parent* Categories link. Is that the desired functionality?

**Comment by markstory** [comment]
@ThinkALot yes if you upgrade your bake version, the parent categories link should go away from what I remember.

**Comment by ThinkALot** [comment]
My composer.json file says:         "cakephp/bake": "~1.0" and I ran composer update recently, just before starting the blog tutorial.

Here's another puzzling issue:

For both tutorials (blog and bookmarker), when I run phpunit in the project folder, I get the following error message:

E:\Xampp\htdocs\cakeblog>phpunit
PHPUnit 3.7.21 by Sebastian Bergmann.

Configuration read from E:\Xampp\htdocs\cakeblog\phpunit.xml.dist

Exception: Referenced fixture class "App\Test\Fixture\ArticlesFixture" not found. Fixture "app.articles" was referenced in test case "App\Tests\TestCase\Controller\CategoriesControllerTest". in [E:\Xampp\htdocs\cakeblog\vendor\cakephp\cake
php\src\TestSuite\Fixture\FixtureManager.php, line 180]

I'm getting that error for both tutorials. Any thoughts?

**Comment by markstory** [comment]
Does that fixture exist?

**Comment by ThinkALot** [comment]
I have a tests folder just inside the project folder. But it's plural, not singular. Within the \tests\Fixture folder is only one file: CategoriesFixture.php. That file does not contain the word "articles". The only place I've found an ArticlesFixture.php file is in this folder: Xampp\htdocs\cakeblog\vendor\cakephp\cakephp\tests\Fixture 

I think the error is indicating that a referenced file or class cannot be found. However, I don't understand the significance of this, since I don't know what the articles class would be for. I guess I could delete the reference. Or I could create the file and class -- but I wouldn't know how. 

I wonder why composer created the reference without creating the class. Any ideas about that?

**Comment by HavokInspiration** [comment]
The problem probably comes from the ``CategoriesControllerTest.php`` file in ``{your_app_folder}/tests/TestCase/Controller``.
You might be calling a fixture that does not exist.
Can you provide us the content of the ``CategoriesControllerTest.php`` ?

**Comment by ThinkALot** [comment]
Here are the contents of /tests/TestCase/Controller/CategoriesControllerTest.php

<?php
namespace App\Tests\TestCase\Controller;

use App\Controller\CategoriesController;
use Cake\TestSuite\IntegrationTestCase;

/**
 * App\Controller\CategoriesController Test Case
 */
class CategoriesControllerTest extends IntegrationTestCase
{

    /**
     * Fixtures
     *
     * @var array
     */
    public $fixtures = [
        'app.categories',
        'app.articles'
    ];

    /**
     * Test index method
     *
     * @return void
     */
    public function testIndex()
    {
        $this->markTestIncomplete('Not implemented yet.');
    }

    /**
     * Test view method
     *
     * @return void
     */
    public function testView()
    {
        $this->markTestIncomplete('Not implemented yet.');
    }

    /**
     * Test add method
     *
     * @return void
     */
    public function testAdd()
    {
        $this->markTestIncomplete('Not implemented yet.');
    }

    /**
     * Test edit method
     *
     * @return void
     */
    public function testEdit()
    {
        $this->markTestIncomplete('Not implemented yet.');
    }

    /**
     * Test delete method
     *
     * @return void
     */
    public function testDelete()
    {
        $this->markTestIncomplete('Not implemented yet.');
    }
}

**Comment by antograssiot** [comment]
@ThinkALot so you either need to change ``public $fixtures = [ 'app.categories', 'app.articles' ];`` to ``public $fixtures = [ 'app.categories']`` or to bake/create the articles fixture

**Comment by ThinkALot** [comment]
Thanks for the suggestion. However, running phpunit now produces the following error:

Exception: Unable to insert fixtures for "App\Tests\TestCase\Controller\CategoriesControllerTest" test case. SQLSTATE[HY000] [1045] Access denied for user 'my_app'@'localhost'
(using password: YES) in [E:\Xampp\htdocs\cakeblog\vendor\cakephp\cakephp\src\TestSuite\Fixture\FixtureManager.php, line 254]

Since the error exists in both tutorials, it seems that composer or bake has done something wrong. If so, anyone who tries the tutorials will encounter the same problem, until it's fixed in composer or bake. So I suppose that's where the error should be corrected. Am I on the right track?

Thanks.

**Comment by antograssiot** [comment]
you need to define a test database configuration in src/config/app.php

**Comment by antograssiot** [comment]
oups fat fingers, sorry

**Comment by antograssiot** [comment]
@ThinkALot I sugest that you read http://book.cakephp.org/3.0/en/development/testing.html#test-database-setup

**Comment by ThinkALot** [comment]
Thanks for the suggestion. However, I did set up and configure the database while following the instructions for both tutorials. I'm sure I did that correctly, because both of my tutorial sites are functional.

**Comment by markstory** [comment]
The test database setup is different from the application database connection. CakePHP uses separate connections so that mistakes don't get made. The error message contains `'my_app'@'localhost'` which means you still have the default 'test' datasource definition.

**Comment by ThinkALot** [comment]
Thanks. I didn't realize that. However, after configuring the test database setup, I received the following error message:

←[33;1mI←[0m←[33;1mI←[0m←[33;1mI←[0m←[33;1mI←[0m←[33;1mI←[0mException: Referenced fixture class "App\Test\Fixture\ArticlesFixture" not found. Fixture "app.articles" was referen
ced in test case "App\Test\TestCase\Model\Table\CategoriesTableTest". in [E:\Xampp\htdocs\cakeblog\vendor\cakephp\cakephp\src\TestSuite\Fixture\FixtureManager.php, line 180]

So I removed the Articles reference in the CategoriesTableTest.php, as well as from CategoriesControllerTest.php. Now phpunit returns this message:

←[33;1mI←[0m←[33;1mI←[0m←[33;1mI←[0m←[33;1mI←[0m←[33;1mI←[0m←[33;1mI←[0m←[33;1mI←[0m←[33;1mI←[0m
Time: 0 seconds, Memory: 6.50Mb
←[30;43m←[2KOK, but incomplete or skipped tests!
←[0m←[30;43m←[2KTests: 8, Assertions: 0, Incomplete: 8.
←[0m←[2K

I guess that means there are no problems, right?

Thanks for your help.

**Comment by antograssiot** [comment]
@ThinkALot Exactly, just needs to write tests now :wink: 
Also, on windows, if you turn `colors="true"` to `color="false"` in your ``phpunit.xml.dist`` line 3, it will clean up the output a bit from what I remember..

**Comment by ThinkALot** [comment]
Thanks.

**Comment by markstory** [comment]
I think all the questions and documentation shortcomings have been addressed here. If not let us know.
