### ISSUE TITLE
Default joinType in hasOne associations incorrectly says 'INNER'

### ISSUE THREAD

**Issue by anguswoodman** [cakephp/docs#2964]
In 3.0 docs

See bottom of screenshot: http://cl.ly/image/2h231C0I2C11 
From here: http://book.cakephp.org/3.0/en/orm/associations.html#hasone-associations

PR of code change here: https://github.com/markstory/cakephp/commit/fbed75aa3370751180c04dbe511b324add95d292

**Comment by markstory** [comment]
Fixed in 968ad567195966375cd8f9a67b357f088186d717
