### ISSUE TITLE
Installation error of php version

### ISSUE THREAD

**Issue by delhiinformation** [cakephp/docs#2970]
Hi,

I've php version 5.4.3 installed with apache 2.4.2 with mod_rewrite. All the required dependencies are enabled in php, i.e. mbstring extension and intl string. While I'm trying to install cakePHP version 3 through command line, it completes the installation but with the following error:- 
Your requirements could not be resolved to an installable set of packages
Problem 1
- This package requires php >=5.4.16 but your PHP version <5.4.3> does not satisfy that requirement.

I've attached the screenshot of the command prompt window. This issue is occurring for multiple packages.

![cakephp-error](https://cloud.githubusercontent.com/assets/633496/8765543/e77472ee-2e2d-11e5-90f0-63d4850bec1c.jpg)

Please let me know how I can fix it.

Thanks

VIkas Kukreja

**Comment by antograssiot** [comment]
As stated in the [doc](http://book.cakephp.org/3.0/en/installation.html#requirements) and in the error message which is quite clear, you need a php version  equal or greater than 5.4.16 to run cakephp 3.

**Comment by delhiinformation** [comment]
Hi,

But I have php 5.4.3 installed which is greater than the required version but still I'm not able to install it.

**Comment by delhiinformation** [comment]
Hi,

But I've php version 5.4.3 which is greater than required version and I'm
still not able to install it correctly.

On Sun, Jul 19, 2015 at 4:04 PM, Anto <notifications@github.com> wrote:

> Closed #2970 <https://github.com/cakephp/docs/issues/2970>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cakephp/docs/issues/2970#event-359417904>.
>



-- 
Regards,

Vikas Kukreja

**Comment by HavokInspiration** [comment]
PHP 5.4.3 was released before PHP 5.4.16
5.4.16 does not mean 5.4.1.6 ; it means PHP 5.4._sixteen_ (checked against 5.4._three_)

**Comment by delhiinformation** [comment]
Thanks Yves for clarification, I uninstalled the previous version and
installed the latest wamp. It worked like a charm. Thanks!

On Sun, Jul 19, 2015 at 4:32 PM, Yves P. <notifications@github.com> wrote:

> PHP 5.4.3 was released before PHP 5.4.16
> 5.4.16 does not mean 5.4.1.6 ; it means PHP 5.4.*sixteen* (checked
> against 5.4.*three*)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cakephp/docs/issues/2970#issuecomment-122649558>.
>



-- 
Regards,

Vikas Kukreja
