### ISSUE TITLE
Typo in http://book.cakephp.org/3.0/en/core-libraries/inflector.html

### ISSUE THREAD

**Issue by ritesh-pandey** [cakephp/docs#2983]
![screenshot from 2015-07-23 23 07 45](https://cloud.githubusercontent.com/assets/1433681/8857481/b375e24c-318f-11e5-98b1-813503a821dd.png)

`big\boxes` instead of `big_boxes`

**Comment by HavokInspiration** [comment]
Would you like to submit a pull request to fix this ?

**Comment by antograssiot** [comment]
@ritesh-pandey do you want to submit a pull request ?

**Comment by ritesh-pandey** [comment]
Yup. Submitting in 5 mins.

**Comment by ritesh-pandey** [comment]
Done. I am contributing for the first time so I might have missed some conventions. Please let me know if anything needs to be corrected.
https://github.com/cakephp/docs/pull/2984/

**Comment by markstory** [comment]
Looks good now.
