### ISSUE TITLE
3.x doesn't require primary key fields to be named `id` by convention anymore

### ISSUE THREAD

**Issue by ndm2** [cakephp/docs#3007]
Currently the docs say that by convention a primary key named `id` is expected, but that's not true anymore, the primary key is figured from the possibly set primary key constraints.

https://github.com/cakephp/docs/blob/3.0/en/orm/table-objects.rst#basic-usage

**Comment by HavokInspiration** [comment]
Do you want to submit a pull request to correct this ?

**Comment by ndm2** [comment]
I'm hesitating as I'm note entirely sure whether primary key constraints might be optional, ie whether using only `Table::primaryKey()` to explicitly define the key would be valid and won't cause any side-effects.

**Comment by HavokInspiration** [comment]
My knowledge of the internal of the ORM is too limited to give you a proper answer as to whether it will cause side effects or not.

But your assertion is correct from what I gather in the ORM.
Not specifically defining a PK using the ``Table::primaryKey()`` method will cause the ORM to reflect the PK constraints from the table. The ``id`` column name is not mandatory, _per se_.

**Comment by lorenzo** [comment]
But it is still a convention we like to follow

**Comment by markstory** [comment]
I think the docs are fine as they stand. The convention is to use id. But the framework is far more flexible now.

**Comment by HavokInspiration** [comment]
Ok. I thought adding a note saying that any primary key constraints would be used as PK by the framework would not have hurt. But I'll bow to the majority :smile:
