### ISSUE TITLE
Views documentation incorrect

### ISSUE THREAD

**Issue by lilHermit** [cakephp/docs#3054]
There are numerous references to a method in `View` called `layout` however its a field http://book.cakephp.org/3.0/en/views.html

For example 

```java
$this->getView()->layout('admin');
```
should be
```java
$this->getView()->layout = 'admin';
```

**Comment by HavokInspiration** [comment]
Indeed, the method was introduced in 3.1

**Comment by antograssiot** [comment]
I've proposed a solution in #3056.
We could discuss there
