### ISSUE TITLE
3.0 Migration Guide

### ISSUE THREAD

**Issue by ionas** [cakephp/docs#3069]
http://book.cakephp.org/3.0/en/appendices/3-0-migration-guide.html
1. no mentioning of Security::generateAuthKey() being removed (Security::hash() is being mentioned)
2. no mentioning of Model::saveField() being removed

**Comment by markstory** [comment]
>  no mentioning of Model::saveField() being removed
The entire ORM was replaced. We didn't mention the various other methods being removed either.

**Comment by jhli** [comment]
Is it a good idea to add a note on how to update a single field in 3.x?

**Comment by ravage84** [comment]
If the docs actually lack a proper explanation on how to update a single field, we should add one.

Closing this as I think it's :ok: not to mention each and every small removed method in the already long list of changes.
