### ISSUE TITLE
the 3.x docs about email is not correct

### ISSUE THREAD

**Issue by ADmad** [cakephp/docs#3075]
_From @danielzzz on August 6, 2015 16:38_

the info here is marked as 3.x but it works only for 3.1 
http://book.cakephp.org/3.0/en/core-libraries/email.html

_Copied from original issue: cakephp/cakephp#7191_

**Comment by HavokInspiration** [comment]
Fixed with #3086.
Admonitions were added around the Mailers examples and a warning was added to notify about namespace changes.
