### ISSUE TITLE
hejl;f

### ISSUE THREAD

**Issue by ramashankar26** [cakephp/docs#3112]
gkudsjfgs.cbgsfd

**Comment by antograssiot** [comment]
:scream: :wink:

**Comment by ramashankar26** [comment]
<php?
$echo = "hello";
?>

**Comment by ramashankar26** [comment]
![framework_architecture](https://cloud.githubusercontent.com/assets/12497081/9289221/f074f1ee-4385-11e5-88d9-27848a883f7e.jpg)
