### ISSUE TITLE
Cake 3.x Blog Tutorial - Issue with Categories

### ISSUE THREAD

**Issue by dividedbynothing** [cakephp/docs#3123]
Hello!

I've encountered an issue with the Cake 3.x Blog tutorial in Part 3 in the section "Reordering Categories with TreeBehavior".  

After modifying my files per the tutorial (CategoriesController.php and index.ctp template), I only get one category record listed (the first record in the database).  I suspect the issue lies in the CategoriesController.php.  My index method looks like this (per the tutorial):
```php
    public function index()
    {
        $categories = $this->Categories->find('threaded')
            ->order(['lft' => 'ASC']);
        $this->set(compact('categories'));
    }
```
Also, I noticed in the tutorial code for the index.ctp template, the table head row contains 9 cells, while the table body row(s) only contain 8.  The table body rows are missing the Parent Category Title in the 3rd cell.

Any assistance or advice on either of these would be great!
Thanks,
DBN

**Comment by markstory** [comment]
Closing as it seems that @cake17 has this addressed in their pull request.

**Comment by dividedbynothing** [comment]
Works great!  Thanks!
