### ISSUE TITLE
3.0 Blog Tutorial Part 3 - Wrong input() string

### ISSUE THREAD

**Issue by RaXaR** [cakephp/docs#3130]
Hi I found an issue in the last block of text on the [CakePHP 3.0 Blog Tutorial - Part 3](http://book.cakephp.org/3.0/en/tutorials-and-examples/blog/part-three.html) page.
In the last block the code shows `$this->Form->input('categories');`. 
I think it should be `$this->Form->input('category_id');`. 
Might be confusing to new users :)

**Comment by markstory** [comment]
Pull request open now #3131.
