### ISSUE TITLE
DebugKit throws integrity constraint error with mysql connection

### ISSUE THREAD

**Issue by mneil** [cakephp/docs#3163]
Every now and then I see a fatal error which appears to be caused by debugkit. Integrity constraint violation. Unable to delete records with foreign key constraint... in the requests table. The root of the problem appears to be that I have "quoteIdentifiers" either not set (default false) or set to false explicitly because I just copied the default DB connection. By setting "quoteIdentifiers" to true in the connection settings I am able to stop receiving the errors. 

The debugkit docs http://book.cakephp.org/3.0/en/debug-kit.html should state that, when using a mysql connection defined in the app configuration, "quoteIdentifiers" should to be set to true. My configuration looks like:

```
'debug_kit' => [
            'className' => 'Cake\Database\Connection',
            'driver' => 'Cake\Database\Driver\Mysql',
            'persistent' => false,
            'host' => '127.0.0.1',
            'username' => '',
            'password' => '',
            'database' => '',
            'encoding' => 'utf8',
            'timezone' => 'UTC',
            'cacheMetadata' => true,
            'quoteIdentifiers' => true
        ]
```

**Comment by markstory** [comment]
What is the exact error you are getting from MySQL? I don't understand how identifier quoting and constraint violations could be linked.

**Comment by mneil** [comment]
It will take some time to get the exact error. I only reported it after resolving it so I haven't seen it for a while.

I also do not know how they were related. Cake's error actually linked to the docs and suggested that enabling identifier quoting *could* possibly fix it. I just remember it was an integrity constraint violation and it mentioned the requests table.

**Comment by mneil** [comment]
Here's the actual output from the log. In the UI it also referenced that setting quoteIdentifiers could resolve the issue. I haven't seen the problem since I set quoteIdentifiers to true in my debug_kit connection settings so I'm assuming it fixed it.

2015-08-16 23:13:20 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`database`.`panels`, CONSTRAINT `request_id_fk` FOREIGN KEY (`request_id`) REFERENCES `requests` (`id`))

Stack Trace:
#0 /vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php(36): PDOStatement->execute(NULL)
#1 /vendor/cakephp/cakephp/src/Database/Connection.php(274): Cake\Database\Statement\MysqlStatement->execute()
#2 /vendor/cakephp/cakephp/src/Database/Query.php(175): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#3 /vendor/cakephp/debug_kit/src/Model/Table/RequestsTable.php(85): Cake\Database\Query->exec

**Comment by markstory** [comment]
Ok. Adding identifier quoting is not actually solving the issue. It looks like the table deletes used in `gc()` are in the wrong order. I'll fix that.

**Comment by markstory** [comment]
Pull request up now.
