### ISSUE TITLE
3.0: Blog tutorial typo

### ISSUE THREAD

**Issue by mtkocak** [cakephp/docs#3167]
There is a typo here: http://book.cakephp.org/3.0/en/tutorials-and-examples/blog/part-three.html

    Generate Skeleton Code for Categories
    Create all files by launching bake commands:

    bin/cake bake model Categories
    bin/cake bake controller Categories
    bin/cake bake template Categories
    The bake tool has created all your files in a snap. You can give them a quick read if you want re-familiarize yourself with how CakePHP works.

    Note
    If you are on Windows remember to use instead of /.
    You’ll need to edit the following in src/Template/Categories/index.ctp:

I changed the last line to this:

    You’ll need to edit the following in src/Template/Categories/add.ctp:

Please check:
https://github.com/mtkocak/docs/commit/3168b738710c636807dd0bfa460787c635d0a530

**Comment by markstory** [comment]
@mtkocak Any way you could send that as a pull request?

**Comment by markstory** [comment]
Closing as #3166 has the fix for this.
