### ISSUE TITLE
2.7.3 ZIP Download Is Missing the Flash Element

### ISSUE THREAD

**Issue by Zian** [cakephp/docs#3200]
The documentation (http://book.cakephp.org/2.0/en/core-libraries/helpers/flash.html) says "Flash elements are found under the app/View/Elements/Flash directory" but when I browse to the app\View\Elements folder in cakephp-2.7.3.zip, all I see is a file named "empty".

**Comment by antograssiot** [comment]
@Zian This is the directory where you can put your own flash template.
I suggest that your read [this](http://book.cakephp.org/2.0/en/core-libraries/components/flash.html)

I though it was related to cakephp/cakephp#7282 but this was solved last week and the templates are presents in `lib/Cake/View/Elements/Flash`
