### ISSUE TITLE
3.0: "bake migration CreateUsers" or "bake migration create_users"

### ISSUE THREAD

**Issue by mtkocak** [cakephp/docs#3201]
here at http://book.cakephp.org/3.0/en/migrations.html the command to generate a migration is like:

```
bin/cake bake migration CreateProducts name:string description:text created modified
```
but in the https://github.com/cakephp/migrations the command is like:
```
bin/cake bake migration create_users name:string created modified
```

which one is right? I think this is a little confusing.

**Comment by markstory** [comment]
I think both forms work if I remember correctly.

**Comment by ravage84** [comment]
Yup, both should work. But it wouldn't hurt if we document that _somewhere_.

**Comment by markstory** [comment]
pull request up now.
