### ISSUE TITLE
[3.0] old namespace and class name in errors.rst.

### ISSUE THREAD

**Issue by okinaka** [cakephp/docs#3217]
Several classe and namespace are old in en/development/errors.rst.
For example, RecordNotFoundException was moved from ORM to Datasource.

**Comment by ravage84** [comment]
@okinaka , thanks for bringing this up.
Please, feel free to create a Pull Request with the necessary fixes.

Relevant:
http://api.cakephp.org/3.0/class-Cake.Datasource.Exception.RecordNotFoundException.html
http://book.cakephp.org/3.0/en/development/errors.html
