### ISSUE TITLE
I see a error in documentation, but cannot find it in the docs repository

### ISSUE THREAD

**Issue by motsmanish** [cakephp/docs#3250]
I see a error in documentation, http://book.cakephp.org/3.0/en/core-libraries/validation.html
For using a rule from the table provider, rule used is 'uniqueTitle', but its not in the code and throws error with CakePHP 3.x version. Correct rule is 'validateUnique'.

I forked the 'docs' repository, but do not find the above text to replace with correct rule.

Am I looking at the wrong place?

**Comment by cake17** [comment]
You can edit a page by clicking directly the "Improve this doc" at the top right of the docs page. You'll be able to edit and proposed a PR.

**Comment by motsmanish** [comment]
Thanks.
