### ISSUE TITLE
Cake3: Custom Datasource

### ISSUE THREAD

**Issue by steefaan** [cakephp/docs#3253]
A documentation about own datasources for cake3 would be nice. There is a really good example for an external datasource for cake2. A similar (maybe with the same example) documentation for cake3 would be nice.

**Comment by davidyell** [comment]
:+1:

**Comment by lorenzo** [comment]
I think that what people is actually asking for is a tutorial on how to satisfy different interfaces in the framework. This sounds more like a (lengthy) tutorial than just documentation.

**Comment by davidyell** [comment]
To me the documentation page in the book just needs to cover a few key topics.

* Definition of what a datasource is in Cake 3
 * Just an outline of the responsibilities of the classes in the framework
 * Also help to define the language and terms used
* What do the Connection and Driver classes do
* An example of a datasource for connecting to a remote data source
 * A remote web service seems to be the key use-case for this

**Comment by lorenzo** [comment]
I also think the main problem is people coming from 2.x thinking in terms of datasources, instead of libraries dedicated to talking to the service they need. We need to make clear somehow that there is no concept of an abstract "datasource" in cake 3

**Comment by davidyell** [comment]
So if I've made my library how do I integrate it with the Cake ORM?

**Comment by ravage84** [comment]
Agree with @lorenzo 

May be even add some explanation why there is no such thing (because it was a bad idea to start with, IMHO).

**Comment by lorenzo** [comment]
the ORM is for relational databases, unless you have made a relational database you cannot use the ORM with it.

You can though, create classes to connect to your service and retrieve data, and implement certain interfaces depending on what your goal is. Do you want to make it form friendly? Make a `FromContext` object. Do you want to make it *look like* the ORM? Implement all the methods in `RepositoryInterface`. Do you want to return entity-like objects? Make those objects implement `EntityInterface`

Depending on your scope you may not want to implement all of them. Actually, implementing `RepositoryInterface` makes sense only for a handful of things, in my opinion.

**Comment by davidyell** [comment]
> May be even add some explanation why there is no such thing

So there the page would need to provide alternative routes.

> makes sense only for a handful of things, in my opinion

What kinds of things?

**Comment by markstory** [comment]
> So it sounds like the most often asked for use case (remote web service) would be just a Table class which connects using something (guzzle/curl/CakeSocket) and returns an entity of api data to the application.

Table classes are for relational databases again. This is a scenario where you _might_ want to implement the `RepositoryInterface`. However, that assumes that your remote service has CRUD like operations. If you're using guzzle and working with remote API's you might be better off looking at guzzle's service client generation.

With all that said, I can see how having more detail on what the various aspects of the ORM are at a high level, and some information on how to implement the Datasource interfaces.

Are you folks finding working remote web services challenging/confusing, or is there another class of datasource that is being difficult?

**Comment by davidyell** [comment]
I'm not sure how @steefaan feels, but for me personally, it's knowing how to plumb my connection to the remote web service into the framework as my expectation is in the controller to be able to do something like `$tweets = $this->Twitter->find()`.

**Comment by markstory** [comment]
But Twitter, has numerous resources, much like a relational database. Wouldn't you be doing something like `$this->TwitterMessages->find(..)`?

**Comment by davidyell** [comment]
Yep, but my interest lays in how to do that. Is `$this->TwitterMessages` an instance of a `Table` class, or an instance of my own repository class?

**Comment by markstory** [comment]
Ok, I can start working on an example of how to read/write messages from Twitter using the Datasource interfaces.

**Comment by davidyell** [comment]
Also might be handy, @lorenzo mentioned that @jadb had made a base web service driver class already, https://github.com/UseMuffin/Webservice

**Comment by davidyell** [comment]
I've got mine working okay and blogged it.

http://jedistirfry.co.uk/blog/2015-09/connecting-to-a-web-service/

**Comment by MyiOffice** [comment]
With humble respect for the intelligence of experienced coders here - and from one who is primarily a content developer - I believe the fire up home page should have a link to some live sample consoles that are automatically configured during the install. Documentation and instructions could then be presented in context with the samples - reduces significantly the abstract text and code now presented.

**Comment by davidyell** [comment]
That's valuable feedback @MyiOffice but this ticket is about custom datasources. You'd have better luck creating a new issue.

**Comment by dereuromark** [comment]
@ all
Is someone able to provide a PR with the suggested docs additions?
Otherwise we have to close this for lack of activity.
