### ISSUE TITLE
Translate behavior  need better tutorial

### ISSUE THREAD

**Issue by salines** [cakephp/docs#3288]
I try to implement translate behavior, and I got lost in the code following the documentation.

I have CakePHP 2 application that works in three languages, I try them migrate to CakePHP 3.x, but unlike 2.x documentation that I quickly realize, here in CakePHP 3 documents there are many ambiguities, at least for us who are poorer with knowledge English.

Please give us examples and point out what to put in the controller table, entity, ...

Step by step, I believe that you will thus get more fans.

Thank you.

**Comment by markstory** [comment]
Which part of the documentation is not clear? There are both tutorials and reference documentation related to TreeBehavior.

**Comment by salines** [comment]
For example

```
class ArticlesTable extends Table
{
    public function initialize(array $config)
    {
        $this->addBehavior('Translate', ['fields' => ['title', 'body']]);
    }
}

class Article extends Entity
{
    use TranslateTrait;
}
// Where put this code????
$articles = TableRegistry::get('Articles');
$article = new Article([
    'title' => 'My First Article',
    'body' => 'This is the content',
    'footnote' => 'Some afterwords'
]);

$articles->save($article);
```

Another example, echos in code,

```
use Cake\ORM\Behavior\Translate\TranslateTrait;
use Cake\ORM\Entity;

class Article extends Entity
{
    use TranslateTrait;
}
```
*Now you can find all translations for a single entity:*

```
$article = $articles->find('translations')->first();
echo $article->translation('spa')->title; // 'Un Artículo'

echo $article->translation('eng')->title; // 'An Article';
```

Where echos data in Table / Entity?

How can we use this behavior from the controller?

**Comment by markstory** [comment]
Ok. Based on those code samples, I'm guessing that you're referring to [the translate docs](http://book.cakephp.org/3.0/en/orm/behaviors/translate.html). I can add some additional context to the code samples there.

As for how you can use the behavior from a controller. Once you've loaded the appropriate table object you can use any behavior method:

```php
// In a controller
$this->loadModel('Categories');
$category = $this->Categories->find('translations')->first();
```

**Comment by markstory** [comment]
Pull request up now.
