### ISSUE TITLE
2.x Replace $this->Session->setFlash() in Blog Tutorial

### ISSUE THREAD

**Issue by vanquang9387** [cakephp/docs#3293]
Since 2.7, FlashHelper has replaced the flash() method on SessionHelper.
But $this->Session->setFlash() is still used in Blog Tutorial and introduces error in default layout because of using $this->Flash->render()
http://book.cakephp.org/2.0/en/tutorials-and-examples/blog/part-two.html#adding-posts

Someone please update Blog Tutorial

**Comment by markstory** [comment]
Pull request up now. If there are any places I missed please let me know :smile:

**Comment by vanquang9387** [comment]
:+1:
