### ISSUE TITLE
Bookmarks Tutorial Part 2, inconsistancy.

### ISSUE THREAD

**Issue by devcorrelator** [cakephp/docs#3319]
I'm going through the Bookmarks tutorial, and may have found an inconsistency.

On this page: http://book.cakephp.org/3.0/en/tutorials-and-examples/bookmarks/part-two.html
It mentions that the BookmarksController needs the following in its `isAuthorized()` method:

    // The add and index actions are always allowed.
    if (in_array($action, ['index', 'add', 'tags'])) {
        return true;
    }

Specifically, it mentions the `index` action.
Later down the page it mentions that the `index` action needs the following code:

    $this->paginate = [
        'conditions' => [
            'Bookmarks.user_id' => $this->Auth->user('id'),
        ]
    ];

If `index` is allow without  a login, and a user visits `index` without logging in, how does `Auth` know the User's id?

**Comment by dereuromark** [comment]
That would simply mean that if you are not logged in you would only see Bookmarks, that have no user_id (null), and those might be public ones.
As soon as you add them logged in, your user_id will be stored and then you will only see your own.

While it might be a little bit strange for the tutorial, it is not wrong per se then IMO.

**Comment by devcorrelator** [comment]
Oh, ok.
Well that wasn't clear to me.

As I'm looking through the code, the `BookmarksController` doesn't have a `beforeFilter();` that allows access to `index` without a login. It only contains the `isAuthorized();`
Therefore, the user has to be logged in. And any logged in user can see /bookmarks/index.

It just wasn't immediately clear to me, and I've been using CakePHP since 1.x. 
Maybe make that clarified for newer users?

**Comment by markstory** [comment]
All actions require authentication when auth component is active. The isAuthorized() method decides _if_ a logged in user can complete the current action.
