### ISSUE TITLE
Searching in the book yields zero results unless exact match

### ISSUE THREAD

**Issue by ankr** [cakephp/docs#3325]
When searching the book it seems like it only yields results for exact matches.
My example is the search term "shell";

"shell": 0 results
"shells": 0 results
"Shell": 0 results
"Shells": yay!

I also tried searching for "authentication" where both "authentication" and "Authentication" correctly gives results.

cc @lorenzo

**Comment by ravage84** [comment]
@ankr just for clarification, do you mean the docs for 3.x, 2.x or both?

**Comment by ankr** [comment]
@ravage84 Appears to be only 3.x

**Comment by markstory** [comment]
![screen shot 2015-09-28 at 11 16 48 am](https://cloud.githubusercontent.com/assets/24086/10139755/721f6fee-65d2-11e5-83da-1d5172605a6c.png)

Are you sure?

**Comment by HavokInspiration** [comment]
@markstory I also have the problem (tested on Chrome / Firefox / Safari on MacOSX). The console shows an error : ``Uncaught TypeError: item.contents.join is not a function`` from [this line](https://github.com/cakephp/docs/blob/3.0/themes/cakephp/static/app.js#L126)

**Comment by markstory** [comment]
@HavokInspiration Ah, I can fix the JS error. I remember seeing it in the 2.x version of the docs.

**Comment by markstory** [comment]
JS error fixed with #3328

**Comment by ankr** [comment]
Ah didn't bother to check JS console, just assumed it was an analyzer issue - thanks @HavokInspiration @markstory
