### ISSUE TITLE
RFC: Demonstrate use of Cache in Blog Tutorial

### ISSUE THREAD

**Issue by jeffblack360** [cakephp/docs#3378]
So I had this thought for an enhancement to the documenation when I worked my way through the Blog Tutorial.

I exercised the Cache feature in conjunction with the Categories table and was thinking that there might be an opportunity to showcase it's use to new developers?

Maybe it's better to consider it an advanced feature, but I thought it was worth asking the question.

**Comment by josegonzalez** [comment]
Note: we can both do query caching as well as usage of the `Cache` class here.

**Comment by jeffblack360** [comment]
Indeed. I used the Cache class originally then swapped it out for the query caching feature -- just for fun. Maybe a good chance to demonstrate both techniques.

**Comment by HavokInspiration** [comment]
Having something explaining both feature, the pros and cons, and when to use which would indeed be nice.

**Comment by markstory** [comment]
Sounds like a good idea to me.

**Comment by HavokInspiration** [comment]
@jeffblack360 Do you want to give it a try ?

**Comment by jeffblack360** [comment]
@HavokInspiration Sure! I thought I'd try to recycle what I did from my Blog tutorial.

**Comment by jeffblack360** [comment]
I just wanted to provide an update that I've started working on this item.

**Comment by ionas** [comment]
Would mark it "ProTip!" ;) somehow :+1: Any progress?

**Comment by ravage84** [comment]
How about extracting the whole thing into a separate, dedicated Cache tutorial which starts on top of the blog tutorial?
This way we blow up the existing tutorial but still levage the existing work.

**Comment by ionas** [comment]
:+1: @ravage84

**Comment by jeffblack360** [comment]
Sorry folks I got distracted with some other things.
@ravage84 Sorry to be dense, but can you expand a bit on your vision for a "dedicated Cache tutorial" and "This way we blow up the existing tutorial"?

**Comment by ravage84** [comment]
With dedicated I mean a separate article/section/page in the book. Solely about all things getting started with caching.
So instead of amending one of the current tutorial articles/sections/pages with some more information about caching, I would like to see a new tutorial about it.

http://book.cakephp.org/3.0/en/tutorials-and-examples.html

Currently we have 
 - Bookmarker Tutorial
 - Bookmarker Tutorial Part 2
 - Blog Tutorial
 - Blog Tutorial - Part 2
 - Blog Tutorial - Part 3
 - Blog Tutorial - Authentication and Authorization

And now I would add a new one called "Blog Tutorial - Caching", for example.

**Comment by jeffblack360** [comment]
Thanks @ravage84! That's a great idea to bolt it on like the "Authentication and Authorization" section.

**Comment by jeffblack360** [comment]
What is the best way for me to generate the documentation locally to make sure it renders properly as I build this out?  Thanks!

**Comment by antograssiot** [comment]
@jeffblack360 you can either use docker or install sphinx localy. Please have a look to the [Readme](https://github.com/cakephp/docs/blob/master/README.md)

**Comment by jeffblack360** [comment]
@antograssiot Thanks for the link Anto. :+1:  
I'm embarrassed that I didn't think to check there!
