### ISSUE TITLE
Basic authentication in cakephp 3

### ISSUE THREAD

**Issue by raymak23** [cakephp/docs#3397]
I am new to cakephp framework and as per the tutorials form authentication make sense, but with basic auth, the document doesn't have good way to implement basic auth. Here is the link http://stackoverflow.com/questions/33130758/cakephp-3-http-basic-authentication-login-issue?noredirect=1#comment54076134_33130758 to my issue with basic auth, I'm not sure what else I'm missing since doc online doesn't any other example to clarify basic auth.

**Comment by markstory** [comment]
Yes it looks like the docs are incorrect around basic authentication keys. The api_key database column should also be hashed. I'll get that updated.

**Comment by markstory** [comment]
@raymak23 Could you check out #3398 and see if that is clearer/more correct?

**Comment by raymak23** [comment]
Hi @markstory - I am able to generate hash keys in api_key column. Thank you very much. Another thing I notice is that this code below has some error. The below code has comma in wrong place after closing bracket of 'Basic'. It should be after *** 'api_key']
```
$this->Auth->config('authenticate', [
    'Basic' => [
        'fields' => ['username' => 'username', 'password' => 'api_key']
        'userModel' => 'Users'
    ],
]);
```

It should be like this:
```
$this->Auth->config('authenticate', [
    'Basic' => [
        'fields' => ['username' => 'username', 'password' => 'api_key'],
        'userModel' => 'Users'
    ]
]);
```

One more question I have:

So when I send basic auth credentials in headers, will Cakephp automatically take credentials and return true or false Boolean? Do i need to add getUser() method in controller as well?

**Comment by raymak23** [comment]
I think I just my question for the last one. I was able to use basic authentication and didnt have to add any validation or anything. Thank you so much. Please make sure the document gets update with above information :+1:
