### ISSUE TITLE
http://cakefest.org/ misses recent book and API links

### ISSUE THREAD

**Issue by ionas** [cakephp/docs#3415]
http://cakefest.org/
vs
http://book.cakephp.org/3.0/en/index.html
<img width="683" alt="screen shot 2015-10-19 at 17 02 38" src="https://cloud.githubusercontent.com/assets/106845/10581479/3e30056a-7683-11e5-9146-69c00e9c30b7.png">
<img width="715" alt="screen shot 2015-10-19 at 17 02 46" src="https://cloud.githubusercontent.com/assets/106845/10581482/3f8bd984-7683-11e5-8f0f-ee7d99b93ed5.png">

**Comment by josegonzalez** [comment]
I think @jameswatts is probably best suited for the task (or maybe someone at CakeDC).

**Comment by saeideng** [comment]
better choice use http://api.cakephp.org address for all api address
however http://book.cakephp.org address for all book address

**Comment by jameswatts** [comment]
@steinkel ping

**Comment by steinkel** [comment]
Menu was updated in http://cakefest.org, now we have Book and API links pointing to the latest versions.

**Comment by josegonzalez** [comment]
<3
