### ISSUE TITLE
RFC: Why is the title 'Console & Shells'?

### ISSUE THREAD

**Issue by davidyell** [cakephp/docs#3427]
Referring to this page, http://book.cakephp.org/3.0/en/console-and-shells.html

Why is the title of the page and in the left hand sidebar 'Console & Shells' when all the sub-pages are referring to shells? With Cake 3 there isn't even a `Console` folder, so holding onto this seems misleading to me.

I also, when looking for the page, scan the sidebar for 'Shells', as that's what I'm building. 

I would suggest changing it to 'Shells & Tasks` to better label it's content as a manual page about creating shells and shell tasks.

**Comment by ravage84** [comment]
People might be looking for "console", because they want to create a "console command".

Didn't like the "Console & Shells" title either, but I know some people are more used to the term shell, even though I think shell is a VERY broad term.

How about "Console Shells & Tasks"?

**Comment by dereuromark** [comment]
Sounds like a good compromise :)

**Comment by cake17** [comment]
:+1: for "Console Shells & Tasks"

**Comment by davidyell** [comment]
My main sticking point is looking for an S instead of a C.

I don't even know what `console` means in this context, as to me the actual command line is either 'bash' or 'terminal'

**Comment by ravage84** [comment]
Opened up two PRs, for 2.0 and 3.0:
2.0 https://github.com/cakephp/docs/pull/3431
3.0 https://github.com/cakephp/docs/pull/3432

**Comment by markstory** [comment]
Closing as pull requests are up now.

**Comment by davidyell** [comment]
I'm disappointed this didn't get more discussion. I do not feel that my points have been addressed in any way.

**Comment by markstory** [comment]
@davidyell I'm happy to merge future pull requests as well.

**Comment by HavokInspiration** [comment]
What about "Shells and Console tools" ?
