### ISSUE TITLE
Extending Bake - Tests file generation

### ISSUE THREAD

**Issue by HavokInspiration** [cakephp/docs#3435]
While creating a custom bake task for a custom type of class [following the docs](http://book.cakephp.org/3.0/en/bake/development.html#creating-new-bake-command-options), I got errors because my class type was not recognized by bake when it was baking the tests file for my custom class : 

```
Notice Error: Undefined index: mode in [/home/yves/PhpStormProjects/cakephpapp-3.1.2/vendor/cakephp/bake/src/Shell/Task/TestTask.php, line 321]
```

and

```
Exception: Invalid object type. in [/home/yves/PhpStormProjects/cakephpapp-3.1.2/vendor/cakephp/bake/src/Shell/Task/TestTask.php, line 353]
2015-10-23 21:07:54 Error: [Cake\Core\Exception\Exception] Invalid object type.
```

I ended up adding them manually by overloading ``MyTask::bakeTest()`` :

```php
    public function bakeTest($className)
    {
        if (!isset($this->Test->classSuffixes[$this->name()])) {
            $this->Test->classSuffixes[$this->name()] = 'Suffix';
        }

        $name = ucfirst($this->name());
        if (!isset($this->Test->classTypes[$name])) {
            $this->Test->classTypes[$name] = 'Sub\Namespace';
        }

        return parent::bakeTest($className);
    }
```

I have two questions :
- is there a better alternative ? 
    - If yes, it should be added to the docs because, as it is, the example in the doc will trigger the same error.
    - If no, I will add my example in the doc

- should we implement in Bake a better "out of the box" solution to prevent the problem if possible ?

**Comment by markstory** [comment]
I don't know how we would be able to provide good defaults for the namespace mapping. It might be best to have the baseclass method be a no-op, if the required keys are not defined in the Test Task, and document code like you have above as a way to enable custom test case generation.

**Comment by HavokInspiration** [comment]
So if I understand correctly, make ``bakeTest`` method do nothing if the object we are baking is not recognized by BakeTest ?

**Comment by markstory** [comment]
@HavokInspiration I think so. That would avoid the notice errors, and problems around not knowing the class suffix/namespace to use.

**Comment by HavokInspiration** [comment]
Ok, I'll start working on something.

**Comment by HavokInspiration** [comment]
Pull requests up.
