### ISSUE TITLE
How to remove unique email validation? 

### ISSUE THREAD

**Issue by raymak23** [cakephp/docs#3437]
Hello,

I was looking through cakephp 3 book for email validation. I am able to validate the email. However, I would like to store that email address to database after validation passes.

For example, I have a ticketing system where same person can create ticket for multiple time with same email address. How can I validate, but not check for unique values in database? Every time I try to add a valid email that was used before, I get value already in use.

**Comment by markstory** [comment]
Email validation and unique validation are totally separate rules. Just delete the unique rules you/bake has applied to the relevant email columns.

Closing as this is more of a question and not a defect with the documentation.
