### ISSUE TITLE
Asset.timestamp error

### ISSUE THREAD

**Issue by stw3** [cakephp/docs#3441]
Documentation says:
Asset.timestamp
        **(bool) true - Appends the timestamp when debug is false**

But in app.php it says:
        **Set to true to apply timestamps when debug is true.**

Actually timestamps are only appended if debug is true (v 3.1.3)

**Comment by bcrowe** [comment]
Closing as https://github.com/cakephp/docs/pull/3442 has been opened.

**Comment by bcrowe** [comment]
Good catch. Thanks!
