### ISSUE TITLE
Use route API prefix with RESTful routes in CakePHP

### ISSUE THREAD

**Issue by fccpt** [cakephp/docs#3444]
Please provide cakephp version 2 docs with some examples to setup a RESTful route with api version.

Credits to:
http://stackoverflow.com/questions/20601162/use-route-prefix-with-restful-routes-in-cakephp

```
Router::connect('/:api/:apiVersion/:controller/:action/*',
    array(),
    array(
        'api' => 'api',
        'apiVersion' => '1.0|1.1|'
    )
);
```

With prefix routing

```
Router::connect('/:prefix/:apiVersion/:controller/:action/*',
    array(),
    array(
        'prefix' => 'api',
        'apiVersion' => '1.0|1.1|'
    )
);
```

**Comment by mdemblani** [comment]
This link might help : 
https://github.com/mdemblani/CakePhp-Rest-Route-with-api-prefix/blob/master/README.md
