### ISSUE TITLE
Search results points to not found pages

### ISSUE THREAD

**Issue by HavokInspiration** [cakephp/docs#3450]
In the 3.X version of the book, if you type "Completion", 2 out of the 4 first search results point to 404 pages.

**Comment by markstory** [comment]
I can get that fixed.

**Comment by HavokInspiration** [comment]
I haven't had the time to check it out myself, but out of curiosity, where can that be done ?
So I can fix it next time.

**Comment by markstory** [comment]
Sadly one has to ssh into the webserver to fix this. I think I will finally build a jenkins job to do it now though.

**Comment by markstory** [comment]
I've manually rebuilt the indexes. #3461 will let us rebuild easier in the future via jenkins jobs.
