### ISSUE TITLE
Bookmarker Tutorial, Part 1

### ISSUE THREAD

**Issue by rask004** [cakephp/docs#3494]
Bookmarker tutorial used: http://book.cakephp.org/3.0/_downloads/en/CakePHPCookbook.pdf, pages 11-17.

After updating config/routes.php as specified on page 16, Cake Server states that routes '/' and '/pages' are missing.

After adding the code on pages 16 and 17, restarting the Server and navigating to /bookmarks/tagged/, The Error "Impossible to generate condition with empty list of values for field (Tags.title), Cake\Database\Exception" occurs.

My Database has one user, one bookmark and one Tag. The bookmark is linked to the user, and the tag is linked to the bookmark (no orphaned data). 

I am wondering, if a '$this->set('bookmarks/tagged', ...);' is required under the index() method? Otherwise if something is missing from config/routes.php?

**Comment by markstory** [comment]
> After updating config/routes.php as specified on page 16, Cake Server states that routes '/' and '/pages' are missing.

The `/` and `/pages` routes are not part of the tutorial, and haven't been included. If you want to keep them, then re-add those routes at the bottom of your routes file.

The error you're having with `/bookmarks/tagged` is a newly added error. I can update the tutorial to reflect the new error.

**Comment by rask004** [comment]
The default routes.php content for a new cakePHP install has the `/` and `/pages`, so a learner may be confused by this. Perhaps update the sample code at the top of page 16 to reflect the current default?

And yes, updating to reflect the new error would be helpful.

For my information, what was expected to appear at `/bookmarks/tagged`, if everything was working fine?

**Comment by markstory** [comment]
> For my information, what was expected to appear at /bookmarks/tagged, if everything was working fine?

An empty page. By adding a tag to the the URL you should see the bookmarks with the requested tag.

Fixes for these issues have been done in #3497.
