### ISSUE TITLE
CakePHP 3: Configure::dump($key, $config = 'default', $keys =[])

### ISSUE THREAD

**Issue by salines** [cakephp/docs#3537]
[Here is](http://book.cakephp.org/3.0/en/development/configuration.html#Cake\Core\Configure::dump) incorrectly shown how to use the dump method

    Configure::dump('my_config.php', 'default');
    Configure::dump('error.php', 'default', ['Error', 'Exception']);

instead of

    Configure::dump('my_config', 'default');
    Configure::dump('error', 'default', ['Error', 'Exception']);

**Comment by dereuromark** [comment]
You are correct. Do you want to make a PR to fix this?

**Comment by salines** [comment]
Done.

**Comment by dereuromark** [comment]
Closing as PR is now open.
