### ISSUE TITLE
Ambiguous directory app/tmp in the install documentation

### ISSUE THREAD

**Issue by pmclee** [cakephp/docs#3546]
In the install documentation (http://book.cakephp.org/2.0/en/installation.html), under the section heading **Permissions**, the documentation refers to a directory named `app/tmp`. This directory does not exist in the cakephp source that I just cloned, nor is it a directory that I recognize in my limited linux administration experience.

The permission settings instructions appear to be important. I wish I knew where that directory was.

**Comment by sitedyno** [comment]
The cloned repository will be on the master branch which is currently the 3.1.x version. If you do `git checkout 2.7.7` then the instructions for the 2.0 book should make more sense.

**Comment by ravage84** [comment]
@pmclee thanks for letting us know. Se my promoted change of the relevant doc section in #3547
