### ISSUE TITLE
Different description and code examples of core-libraries/registry-objects

### ISSUE THREAD

**Issue by gr-ishiguro** [cakephp/docs#3552]
Hello.

I found a mistake in the description and code examples of core-libraries/registry-objects.
In the example, load the ACL component, but the code has been written with the Toolbar properties.
Which is correct?

about line 17 (en/core-libraries/registry-objects.rst) ::

    $this->loadComponent('Acl.Acl');
    $this->addHelper('Flash')

    This will result in the ``Toolbar`` property and ``Flash`` helper being loaded.

Yoroshiku !

**Comment by markstory** [comment]
Thank you. Fixed in 626df2da48bd46975a21e2c9c7fbd6f44c2d2e84
