### ISSUE TITLE
Making actions public indicates that Auth->allow('*') should work when it doesn't in 2.7

### ISSUE THREAD

**Issue by AshleyPinner** [cakephp/docs#3570]
Under the [Cake 2 documentation for Authentication, making actions public](http://book.cakephp.org/2.0/en/core-libraries/components/authentication.html#making-actions-public) says that the following should work the same:

```PHP
// Allow all actions. CakePHP 2.0
$this->Auth->allow('*');

// Allow all actions. CakePHP 2.1
$this->Auth->allow();
```

There is no indication that `$this->Auth->allow('*');` has been deprecated, but I've resolved an issue in our codebase today (after migrating from 1.3!) where `$this->Auth->allow('*');` didn't work, but `$this->Auth->allow();` did.

The documentation needs to possibly have that be a bit clearer.

**Comment by davidyell** [comment]
Perhaps the update could be just to change the versioning to be clearer?

`CakePHP 2.0 and below` and `CakePHP 2.1 and onwards`

**Comment by AshleyPinner** [comment]
The indication that `$this->Auth->allow('*')` had been deprecated is hidden away in the [2.1 migration guide](http://book.cakephp.org/2.0/en/appendices/2-1-migration-guide.html#authcomponent).

I agree with @davidyell here, it should be explicit in saying that `allow('*')` only works for 2.0, and you should be using `allow()` instead.
