### ISSUE TITLE
Better examples of testing Tables and Behaviors

### ISSUE THREAD

**Issue by davidyell** [cakephp/docs#3588]
**Preface**
I am not a PHPUnit ninja.

**Frustration**
I believe there can be some improvements made in the book to help people test behaviour and table classes. [The current page is a bit light, and doesn't even cover behaviors](http://book.cakephp.org/3.0/en/development/testing.html#testing-table-classes).

The problem that I often encounter and still haven't managed to solve is that a behavior needs a table, which needs a connection which needs a schema.

Even making use of `getMockForModel()`, which should be `getMockForTable()`, it still relies on a Connection. So if you want to make a mock table to pass to your behaviors constructor you're hobbled because you need to mock all the things the Table class needs.

**Solution**
Ideally I'd like someone more versed in PHPUnit and CakePHP to improve the book to better explain how to avoid all the mockception needed to get a mock table class, without a database connection.

I usually get about this far, then get frustrated and give up.

``` php
    public function testIsContained($contains, $containedTable, $expected)
    {
        // Mockception
        $table = $this->getMockForModel('Packages');

        $schema = $this->getMockBuilder('\Cake\Database\Schema\Table')
            ->setConstructorArgs([$table, ['id' => ['type' => 'integer']]])
            ->setMethods(['typeMap'])
            ->getMock();

        $schema->expects($this->any())
            ->method('typeMap')
            ->willReturn(['id' => 'integer']);

        $table->schema($schema);

        $connection = $this->getMockBuilder('\Cake\Database\Connection')
            ->setConstructorArgs([['driver' => 'MySQL']])
            ->getMock();
        // End mockception

        $behaviour = new ApiVerboseBehavior($table);

        $query = new Query($connection, $table);
        $query->contain($contains);

        $result = $behaviour->isContained($containedTable, $query);

        $this->assertEquals($expected, $result);
    }
```

**Comment by davidyell** [comment]
I've only managed to side step this by removing all the mocks, and duplicating some of the core testing techniques.

Query - https://github.com/cakephp/cakephp/blob/master/tests/TestCase/ORM/QueryTest.php#L54
Behavior - https://github.com/cakephp/cakephp/blob/master/tests/TestCase/ORM/Behavior/TimestampBehaviorTest.php#L53

So I am I right in thinking that the ORM layer cannot be mocked? Because it sure seems that way to me.

**Comment by markstory** [comment]
> So I am I right in thinking that the ORM layer cannot be mocked? Because it sure seems that way to me.

No it can, its sometimes not worth the effort though.

**Comment by ravage84** [comment]
We certainly should have one testing example for each and every part of the framework, if we really want to ecourage users to do proper testing.

Haven't looked into testing 3.x myself yet, but the need for many mocks could hint at a design problem or at least to a need for a helper method to ease the work and reduce redudant mocking.

I tend to the latter.

**Comment by markstory** [comment]
> a need for a helper method to ease the work and reduce redudant mocking.

getMockForModel() exists. But it might not do all the things we need just yet.

**Comment by dereuromark** [comment]
Are you able to provide a pull request with your suggested changes?
