### ISSUE TITLE
Coding Standards and PSRs

### ISSUE THREAD

**Issue by cesarkohl** [cakephp/docs#3651]
Hello,

I've been studying PSRs and, at the same time, the amazing CakePHP documentation.

As I see several functionalities in CakePHP being up to the newest technologies I would like to improve it's documentation relating the PSRs and CakePHP's Coding Standards.

Do you think this is a good idea? I'm looking forward to your feedback in order to do it or to just give up the idea.

Best,
Cesar

**Comment by markstory** [comment]
@cesarkohl The examples in the 3.0 book should follow PSR2. The 2.x book follow a different set of standards (documented in the book). If code examples are incorrectly formatted any corrections would be greatly appreciated.

Closing as this was a question, and I'm assuming corrections will come as follow up pull requests.

**Comment by cesarkohl** [comment]
Interesting. I will be analysing the code examples. Thanks for the fast reply.
