### ISSUE TITLE
3.x ORM Info about contain() should declare outer query PKs to be required.

### ISSUE THREAD

**Issue by ionas** [cakephp/docs#3665]
Documentation about `->contain()` should explain that the PK the associations in contain reference must selected by the parent `Query` else contain will fail to pull in association data silently.
Ref: http://book.cakephp.org/3.0/en/orm/query-builder.html#loading-associations

**Comment by inoas** [comment]
This is actually resolved. https://book.cakephp.org/3.0/en/orm/query-builder.html#passing-conditions-to-contain
