### ISSUE TITLE
RFC Optional View Classes per Resource

### ISSUE THREAD

**Issue by ionas** [cakephp/docs#3669]
> > jhli/ionas: For 4.x? we could move to `PostsView` etc also via bake?
> > Mark Story: Do you mean view classes per resource? I feel that is a lot of complexity to force on new developers and simple applications.

What I'd like to purpose is to communicate that the view layer can actually be used to do stuff.
Setting up helpers. Transforming data for specific views, etc. Setting up HTML/XML/JSON builders and whatnot. After differentiating templates and views in 3.0. 

Ideas:
- `cake bake view articles`, `cake bake all articles --with-views` would create those views whereas `cake bake all` would not. The bake behavior can then for 4.0 be changed to `cake bake all articles` auto-generating those views whereas `cake bake all articles --no-views` would omit those.
- For 'articles' the view class file would be `ArticlesView.php`
- The controller will look for its matching View automatically. If none is found the controller will implicate that just `AppView` is being used, e.g. fully BC and convenient. This will keep things easy.

Ref: https://github.com/cakephp/docs/pull/3668#issuecomment-172020538

**Comment by josegonzalez** [comment]
Can you show a use-case where this might be useful? Also sounds like something we can just implement now in bake...

**Comment by ionas** [comment]
@josegonzalez Yes. COULD.

Reason
- Communicating clearly that there are views to be worked with, getting the view layer out of its de-facto niche, completing the MVC pattern in de-facto practise.

Use cases
- Setting Layout
- Configuring Helpers
- View specific data transformation (view specific, else there are DataTypes and formatResults)
- Creating and Using builders that don't use template files.
- There is probably more...

This is just an idea, thus this RFC. Pro *and* Cons are welcome.
