### ISSUE TITLE
3.0, SQL Injection enhancement

### ISSUE THREAD

**Issue by davidyell** [cakephp/docs#3690]
Ref: http://book.cakephp.org/3.0/en/orm/query-builder.html#sql-injection-prevention

This page lists what not to do, but doesn't link to, or inform the user about the proper course of action. To me it should be structured in a 'What not to do' and something further on 'How to do it right', perhaps a single example with a link to the correct section in the Query Builder documentation?

**Comment by ionas** [comment]
:+1: It should teach about how to use quotes and how to use custom prepared statements.
It also misses - I think - info on left hand full strings.
```php
            ->order([
                'union_table_order' => 'ASC',
                'levenshtein(' . $this->connection()->quote($street) . ', LOWER(street)) ASC',
                'LOWER(street) ASC',
            ])
```
Is an example of using a custom function in orderBy that needs escaping.
The escaping done here though does not use prepared statements (which probably? is better).
An example of quote() can be extracted from above. I am atm however not sure how to convert that to use PDO binding (probably http://api.cakephp.org/3.1/class-Cake.Database.Query.html#_bind)

**Comment by ravage84** [comment]
1. What not to do
1.b WHY

2. What to do
2.b How to do it in CakePHP specifically

If we can reuse external ressources, I would prefer that.

**Comment by ravage84** [comment]
@davidyell have you found relevant resources on the matter we could link to?

**Comment by davidyell** [comment]
Sorry @ravage84 I'd totally forgotten about this ticket. I'll take a look and submit a pull request for it.
