### ISSUE TITLE
find('list'), keyField/valueField, nomenclature fields vs property, missing virtual property/field example

### ISSUE THREAD

**Issue by ionas** [cakephp/docs#3701]
This issue touches cake core and/or the book.
* In Cake Core: `keyField` and `valueField` should be renamed `keyProperty` and `valueProperty` or this chapter should be renamed to `Creating Virtual Fields` http://book.cakephp.org/3.0/en/orm/entities.html#creating-virtual-properties.
* This chapter should explain that you can also utilize virtual fields/properties (and group by them?) http://book.cakephp.org/3.0/en/orm/retrieving-data-and-resultsets.html#finding-key-value-pairs

This is to make utilizing `find('list')` more transparent to newcomers as the nomenclature about properties and fields is ambiguous and unclear as well as the docs for keyField and keyValue working towards virtual properties missing.

**Comment by ionas** [comment]
Ref: https://github.com/cakephp/cakephp/issues/8097#issuecomment-174376918

**Comment by markstory** [comment]
> In Cake Core: keyField and valueField should be renamed keyProperty and valueProperty or this chapter should be renamed to

I don't think we can rename option properties without continuing to support the current ones. I think updating the nomenclature in the documentation around virtual fields is simpler and removes one term :smile:

**Comment by markstory** [comment]
Pull request up now.
