### ISSUE TITLE
3.0, Short description of collection methods

### ISSUE THREAD

**Issue by davidyell** [cakephp/docs#3709]
Ref: http://book.cakephp.org/3.0/en/core-libraries/collections.html#list-of-methods

With such a myriad of collection methods, I can see the value of having a list of methods. However when I approach this page I often have a goal in mind to achieve. The goal in my head might not map directly to a collection method.

I think it would be beneficial to have a short description of what the method does next to it's entry in the list of methods section. This will help users find the right collection method much quicker I think.

**Comment by markstory** [comment]
The long TOC is now a table. I think that should help address this.

**Comment by davidyell** [comment]
Thanks for taking a look @markstory, but I don't agree that the change will bring any benefit. I do see your point though, but it means clicking each method to read the description and then going back each time.

The method names are not descriptive enough to give a user an idea of their functionality in my opinion. I would prefer some description which helps map a user's code objective to the correct method. This is especially pertinent in that some of these methods overlap, in that they can be used to achieve the same thing in different ways.

Some examples, would be the difference between `every` and `each`, and the difference between `map` and `reduce`.

It could be down to my lack of understanding of the Collection class, however I think any change which gets users to the best place for their goal quicker would be great. I'd be interested in your thoughts on this.

**Comment by lorenzo** [comment]
It is quite difficult to shortly describe the functions without showing examples. I do think clicking on the method names to discover what they do is better than bloating that section with cryptic descriptions

**Comment by davidyell** [comment]
Fair enough @lorenzo, if the methods cannot be summarised in a sentence then I guess it's the best approach.

**Comment by HavokInspiration** [comment]
What about adding a "Back to top" button after each methods description ? Maybe that can improve the "reading flow".
