### ISSUE TITLE
[fr] Conventions around FK column names

### ISSUE THREAD

**Issue by HavokInspiration** [cakephp/docs#3710]
An issue I read on a help forum made me research a link to give to the user about conventions regarding FK column names which lead me to this page : http://book.cakephp.org/3.0/fr/intro/conventions.html#conventions-pour-les-models-et-les-bases-de-donnees

The examples given give the hint that the conventions can work out in French, which I thought was not possible and that conventions had to be followed in English (in some basic cases it can work).

Am I correct to think that this part of the doc (specifically this sentence : ``Pour une table avec un nom de plusieurs mots comme “type_categories”, la clé étrangère sera type_categorie_id.``) is wrong and it should be noted that conventions only works in English to avoid confusions about cases working in non irregular plural in English ? For instance, ``categorie_id`` is a wrong FK name for a FK reference to a ``categories.id`` column... but given in the doc.

ping @antograssiot @cake17

**Comment by cake17** [comment]
@HavokInspiration true, it only works for english words, we should correct the docs with `type_category_id` and add a note to explain this

**Comment by HavokInspiration** [comment]
I'll try to take of that during lunch (unless someone is faster :smile:)

**Comment by cake17** [comment]
:smile:

**Comment by HavokInspiration** [comment]
PR opened
