### ISSUE TITLE
Mention a link to 2.x changes from 3.x migration guide.

### ISSUE THREAD

**Issue by dereuromark** [cakephp/docs#3719]
http://book.cakephp.org/3.0/en/appendices/3-x-migration-guide.html
only tells about 2.x=>3.x.

Coming from 1.x some people wonder what "else" changed.
I thinnk we should add a link to the http://book.cakephp.org/2.0/en/appendices.html where the rest of the changes are.

Especially since the migration notes of 2.x are hidden in Appendix and not too visible from the main navi.

**Comment by davidyell** [comment]
:+1:
