### ISSUE TITLE
SecurityComponent::requireAuth() documentation

### ISSUE THREAD

**Issue by ypnos-web** [cakephp/docs#3726]
The documentation (CakePHP 3.2) seems to be wrong:

Under "Restrict Actions to SSL":

> SecurityComponent::requireAuth()
> Sets the actions that require a valid Security Component generated token. Takes any number of arguments. Can be called with no arguments to force all actions to require a valid authentication.

1. Why is this under "Restrict Actions to SSL"
2. The last sentence is wrong. The method requires an argument!
3. What is the interaction with this methods and other methods described to define when form tampering protection is enabled and when it is not?

In the API the method is described as follows:

> Sets the actions that require whitelisted form submissions.
> 
> Adding actions with this method will enforce the restrictions set in SecurityComponent::$allowedControllers and SecurityComponent::$allowedActions.

I really have no idea what that means. Are my forms not tampering-protected if I don't use `requireAuth()`? As I understood the rest of the docs, they would be protected by default.

It seems the methods documentation needs to be updated to 3.X reality.

**Comment by markstory** [comment]
I would recommend you _don't_ use this method at all. Its a train wreck which is one of the reason it is not documented and won't be documented.

**Comment by markstory** [comment]
Actually, I'll deprecate this method/feature right now.

**Comment by markstory** [comment]
Closing as this feature is deprecated and I'd rather not document things that will disappear.
