### ISSUE TITLE
Broken Links CakePHP 2.0 Docs

### ISSUE THREAD

**Issue by ravage84** [cakephp/docs#3735]
After seeing https://github.com/cakephp/cakephp/pull/8205/ I was wondering if there were other broken links.
So I set out to find out.
I used the [LinkChecker](https://wummel.github.io/linkchecker/) tool available on many Linux distros
By executing the following command:
``LANG=C linkchecker --no-warnings --no-status --ignore-url=localhost --ignore-url=example.com --ignore-url=exemple.com http://book.cakephp.org/2.0/ | tee linkcheck_book.cakephp.org_2.0.txt``

I got this [report](https://gist.github.com/ravage84/eba2ec60090dedea1904) with 23 errors found.

**Comment by ravage84** [comment]
An analysis for 3.0 can be found in #3736

**Comment by markstory** [comment]
Closing as I think I got most of the important issues here.
