### ISSUE TITLE
Broken Links CakePHP 3.0 Docs

### ISSUE THREAD

**Issue by ravage84** [cakephp/docs#3736]
After seeing https://github.com/cakephp/cakephp/pull/8205/ I was wondering if there were other broken links.
So I set out to find out.
I used the [LinkChecker](https://wummel.github.io/linkchecker/) tool available on many Linux distros
By executing the following command:
``LANG=C linkchecker --no-warnings --no-status --ignore-url=localhost --ignore-url=example.com --ignore-url=exemple.com http://book.cakephp.org/3.0/ | tee linkcheck_book.cakephp.org_3.0.txt``

I got this [report](https://gist.github.com/ravage84/ca37b301c58d1406e137) with 11 errors found.

**Comment by ravage84** [comment]
An analysis for 2.0 can be found in #3735

**Comment by cake17** [comment]
Close this because of #4122
