### ISSUE TITLE
Section about customizing bake templates not precise enough

### ISSUE THREAD

**Issue by srad** [cakephp/docs#3762]
I tried to figure out how to customize the bake templates as described in http://book.cakephp.org/3.0/en/bake/development.html#customizing-the-bake-templates

But it doesn't work, which means that the default templates are still used and _not_ my modified templates.

I copied the full subtree ```vendor/cakephp/bake/src/Template/Bake/<from here>/**``` to ``` /src/Template/Bake/<to here>``` and changed some views. I guess the directory structure has to be diffenrent?

**Comment by markstory** [comment]
I wasn't able to reproduce the issue you had. Following the docs worked fine for me.

```
# Copy the controller template
mkdir -p src/Template/Bake/Controller
cp vendor/cakephp/bake/src/Template/Bake/Controller/controller.ctp src/Template/Bake/Controller/
```

I edited the controller.ctp in my app and added 'CHANGES' to the doc block, and then ran

```
bin/cake bake controller tags
```

The generated controller contained my edits.
