### ISSUE TITLE
Creating category

### ISSUE THREAD

**Issue by rfrancois** [cakephp/docs#3773]
Hi,

I did this part of the tutorial : http://book.cakephp.org/3.0/en/tutorials-and-examples/blog/part-three.html

I had a trouble that I solved.
When I launch : 
bin/cake bake migration CreateCategories parent_id:integer lft:integer[10] rght:integer[10] name:string[100] description:string created modified
it creates all the fields as it should, but trouble is that parent_id can't be null.
So when you finish the tutorial and you try to add a category, an sql error tells you that parent_id can't be null.
To solve this issue, I went to phpmyadmin and I checked that parent_id can be null.

I guess there is a way more convenient than going to phpmyadmin ? For instance, notice in command line that parent_id can be null ?
It would be interesting to write it in the doc.

**Comment by markstory** [comment]
You would have to update the migration before running it. The book mentions this

>Now that the migration files are created, you can edit them before creating your tables. We need to change the 'null' => false for the parent_id field with 'null' => true because a top-level category has a null parent_id.
