### ISSUE TITLE
Follow the docs, but FixtureManager not finding plugin Fixtures

### ISSUE THREAD

**Issue by CodeBlastr** [cakephp/docs#3778]
I don't know exactly where the issue is in the docs, somewhere on this page probably : http://book.cakephp.org/3.0/en/development/testing.html#fixtures

I follow all the docs, I install plugins with composer, I use namespaces and paths from other plugins as examples, I create a testsuite and I run `vendor/bin/phpunit`.  Then I get the message `Referenced fixture class "[Privileges]\Test\Fixture\[AcosFixture]" not found `.  I spend another 4 hours digging into the cake core trying to figure out where it's getting the path and/or trying to load this fixture with zero luck.  

The comments on FixtureManager::_loadFixtures() has comments that say, "Looks for fixture files and instantiates the classes accordingly", but I don't see anything in that function which actually instantiates a class (it merely checks if the class already exists). 

My fixture is located at 
`/opt/bitnami/apps/[domain name]/htdocs/vendor/codeblastr/privileges/tests/Fixture/AcosFixture.php'

My TestCase has this parameter
`public $fixtures = ['plugin.privileges.acos'];`

I check the value of Configure::read('plugins.Privileges'); and it equals (which is correct)
`/opt/bitnami/apps/[domain name]/htdocs/vendor/codeblastr/privileges/`

These docs are messed up somewhere, because running the testsuite from the app folder is not finding fixtures from plugins that were installed with composer, and there is zero explanation about how to specify the path, there is zero help on the IRC channel, nothing on stackoverflow and/or google or anywhere else with help for trying to figure this out.

**Comment by markstory** [comment]
What does your plugin's composer.json have in it? Are the fixture namespaces include in 'autoload' or 'autoload-dev'? A working example [can be found in debug kit](https://github.com/cakephp/debug_kit/blob/master/composer.json#L33-L38).
