### ISSUE TITLE
Missing documentation for retrieving data through an association of an association.

### ISSUE THREAD

**Issue by thisispaulcyr** [cakephp/docs#3799]
# Scenario:

(PostalCode = ZipCode for the American users)

- Neighbourhoods belong to many PostalCodes
- A Neighbourhood belongs a City
- Many PostalCodes belong to many Cities

The appropriate CakePHP table associations and DB tables have been set.

# Problem:

In the NeighbourhoodsPostalCodes controller, I am unable to access the associated City data through standard finders.

In CakePHP pre-3.0, I understand that there were a couple of ways of accessing the data, and that those ways have been removed from 3.0. However, in the current Cookbook, I cannot find any straightforward method of accessing the City data from within the NeighbourhoodsPostalCodes controller, aside from writing joins outside the ORM.

Googling for the answer was quite difficult (as most answers were for pre-3.0), but after some time I stumbled across the answer here: http://stackoverflow.com/a/30428204

While the Associations page in Cookbook does contain an example using the AssociatedTable1.TableAssoicatedWithTable1 syntax, it is not actually specific to the example being discussed.

# Recommendation:

Perhaps this "association chaining" method was explained elsewhere in Cookbook. If it is, then I recommend referencing it from the Associations page and elsewhere as appropriate. If it is not elsewhere in Cookbook, I strongly recommend it be added ASAP, as I would assume this would be heavily used.

Thanks!

**Comment by markstory** [comment]
Are [these the docs you're looking for](http://book.cakephp.org/3.0/en/orm/retrieving-data-and-resultsets.html#eager-loading-associations)

**Comment by thisispaulcyr** [comment]
Yep, that's it. Thanks.

Could a link to that section be added to http://book.cakephp.org/3.0/en/orm/associations.html ? From the questions I found on Stackoverflow, there seems to be a few vectors that people looking for that info are taking, so cross-referencing would be helpful in directing to the right section.

**Comment by markstory** [comment]
Cross link added.
