### ISSUE TITLE
Difficult to find the download link in cakephp homepage: http://cakephp.org/

### ISSUE THREAD

**Issue by daveozoalor** [cakephp/docs#3800]
The download link there, points to the installation section documentation for 3.2 .

It should lead to the github page for downloads.

**Comment by ionas** [comment]
http://cakephp.org/ => http://book.cakephp.org/3.0/en/installation.html => always up to date (at least should be) links, ATM 3.2 - the only reason to change this would be to make it easier to maintain, which would not be more helpful to newbies.

It points to the installation documentation because the recommended way to install is via composer.

Under section **News and Releases** there are links to release notes / bakery which again lead to the github releases page: **Download a packaged release on github.** ... maybe that last thing could be BOLD on the bakery... if that's easy to be done.

**Comment by dereuromark** [comment]
I agree, the downloads are not the preferred way of doing this.
The docs are always up to date with how things are done.

**Comment by daveozoalor** [comment]
I make cakephp tutorials, I would like to know why composer was chosen and what advantage it offers rather than just having to download the latest release from github.

**Comment by ionas** [comment]
:+1: for making cakephp tutorials @daveozoalor
Personally I went from zip files (okay) to git clone + git submodules (horrible) to composer (fantastic).

Composer is similar to `bundle` for ruby, `npm` for node etc. It is very easy to discover packages, register them and have a nice meta file (composer.json) which describes semver compatible versions of components of your application.

After installing composer (which is NOT hard, at least not to be run as `php composer.phar`) it is a breeze for any newbie. It also (tries) to setup correct privileges which helps with issues, forgetting (pros) or not knowing (newbies) about them.

**Comment by markstory** [comment]
> I would like to know why composer was chosen and what advantage it offers rather than just having to download the latest release from github.

Composer was chosen as it sets people up for success later. Yes it is more complicated to get started, but it also makes future upgrades easier, and lets users take advantage of the package ecosystem available from packagist. With that said we also [package up tarballs](https://github.com/cakephp/cakephp/releases/tag/3.2.4) in the release pages.

Would having the main site link to https://github.com/cakephp/cakephp/releases/latest be more helpful in your opinion?

**Comment by jhli** [comment]
A link to that page in the install dics sounds good, however it should warn that even if you pull just the app you will miss vendor libs an permissions (right?) - overall IMHO composer is EASIER to use especially for complete *nix newbies.

**Comment by markstory** [comment]
The packaed zip file on the release page includes vendor dependencies. It might also have the permissions set. I can't remember if permissions go into zip files.

**Comment by jhli** [comment]
If its tar gz and p flag is set http://stackoverflow.com/questions/20338215/why-doesnt-tar-preserve-file-permissions/20338301#20338301

It is possible for zip, too http://stackoverflow.com/questions/13633488/can-i-store-unix-permissions-in-a-zip-file-built-with-apache-ant/13633772#13633772

Depends on how the files are created, though. Can't check on my mobile.

**Comment by cake17** [comment]
I think we should promote the composer installation. In the installation docs, there is already a paragraph that contains a link in [Create a CakePHP project section](http://book.cakephp.org/3.0/en/installation.html#create-a-cakephp-project). Is it enough ?

**Comment by ravage84** [comment]
> It won't hurt and won't take five minutes to do.

This is a wrong assumption.
A proper video always takes a multiple to produce than the time the video runs.

Also such video can get outdated and outdated stuff is even worse.

**Comment by daveozoalor** [comment]
If it gets outdated, a recent one will be made and used to replace the
outdated one.
Lets say a 5 minutes installation video takes one 2 hours to prepare and
will get outdated in 6 months.
2 hours is still too little a sacrifice than to loose so many newbies that
would have aborted mission within those 6 months.

Even if its not official by Cake, their should be a link to 'some'
installation videos on youtube.

Infact, I'm now angry. It seems I should just start CakeCast.

**Comment by ravage84** [comment]
@daveozoalor CakePHP, like many other open source projects, live from (most often) voluntary and unpaid contributions from people like you and me.

I agree, tutorial videos about CakePHP, especially about getting started parts, would be great.
But somebody needs to to them.

And yes, 2 hours aren't much, but still somebody has to do it.
Once outdated, somebody has to do it, _again_.

Also those videos might be nice, but they would play only a tiny part in the big ecosystem around CakePHP.

So if you want to help us with anything, then you are very welcome!

I'm not good at creating videos but if you are, then it would be great if you could create one or potentially more videos about CakePHP.

**Comment by kz** [comment]
I disagree that there should be a link to the downloads page on GitHub. Composer has become a standard with mature PHP frameworks (another great example is Laravel: https://laravel.com/docs/5.2#installing-laravel). The documentation even teaches users how to set up Composer. Tutorial videos would be useful for complete beginners to PHP, but they already exist (especially on YouTube) and embedding a video for something so trivial/targeted towards beginners would add unnecessary clutter to documentation.

**Comment by daveozoalor** [comment]
No matter how you wish to explain it, Tutorial videos are very important
for cake php.
Basically what is needed is just one setup video.
The whole setup process appears easy to you because you've been through it
before, for a complete beginner, its just a maze.
I like the new cake homepage Design, link to 3rd party youtube tutorials
should be included in some prominent place on the page.
I like that they included links to cake events. But that's nothing to
someone that wants to install cake the right way, and right away.

**Comment by kz** [comment]
I agree that tutorial videos are very important for CakePHP. However, I disagree that they should be contained within documentation. I'd be happy to see Cakecasts become a thing, however, I respect the amount of time CakePHP's developers have put into CakePHP. As a result, we would need the Jeffrey Way of the Laravel world (who runs Laracasts) to create one for CakePHP. Alternatively, you could build a website where people can contribute tutorial videos - there's an idea.

In fact, the best example of how to approach the issue of helping complete beginners is Laravel. If you go to https://laravel.com/, you can see a Laracasts link in the navigation bar. It's up to the community to bring one to CakePHP.

For a complete beginner, there are of course barriers to entry one must overcome. However, documentation would be the wrong place to put tutorial videos for complete beginners. CakePHP documentation is for people to learn CakePHP, not how Composer works.

Anyway, we are deviating from the original issue, which is to place a direct link to the GitHub downloads page. Doing so would be unconventional and encouraging bad practice. It would be a good idea to close this issue in favour of one discussing the possibility of videos in documentation as we've gone quite off-track from the original issue.

**Comment by daveozoalor** [comment]
You are right, cakephp official website just needs to link beginners people
to third party tutorial sites. It never has to be in the documentation,
just on the homepage or some documentation drop down menu.

**Comment by kz** [comment]
@daveozoalor Do you mind closing this issue and making a new one detailing a request for a video tutorial site? I'm not sure whether this would be the best repository to create the issue under, but this repository is somewhat related to the request.

**Comment by ravage84** [comment]
@daveozoalor if you have any further suggestions for/about the main CakePHP website, please open an issue or even better a pull request on the [cakephp/cakephp.org repo](https://github.com/cakephp/cakephp.org).

**Comment by ravage84** [comment]
Closing. If anybody is willing to contribute further documentation or even a video, it will be welcome.
