### ISSUE TITLE
Folder structure for cake 3.2.4 and 3.2.3 incomplete

### ISSUE THREAD

**Issue by daveozoalor** [cakephp/docs#3801]
The Folder structure for cake 3.2.4 and 3.2.3 are incomplete incomplete  and there is no explanation for that in the docs:
I didnt test others
https://github.com/cakephp/cakephp/tags

**Comment by dereuromark** [comment]
What do you mean with incomplete?
Please specify.

**Comment by daveozoalor** [comment]
See the folder structure of cake 3.2.4 https://www.dropbox.com/s/f145wvu4qtf9bja/cakephp.png?dl=0

as compared to what is found in the documentation:
Several folders are missing - bin, logs etc
bookmarker/
/bin
/config
/logs
/plugins
/src
/tests
/tmp
/vendor
/webroot
.editorconfig
.gitignore
.htaccess
.travis.yml
composer.json
index.php
phpunit.xml.dist
README.md

**Comment by dereuromark** [comment]
Did you run composer install as documented?
Most of those will be auto generated in the setup process - or if needed.

**Comment by daveozoalor** [comment]
I just downloaded the zipped cake file and unzipped it. I like to work with cake that way out-of-the-box instead of having to download composer, configure environment path etc.

it works for me on cake 3.1.x
Its the 3.2.x versions that have that issue

**Comment by dereuromark** [comment]
What is wrong with composer as approach? It sets it up way faster than any of your downloads ever can:

    composer create-project --prefer-dist cakephp/app yourapp

as documented.
Nothing else required.

**Comment by markstory** [comment]
You have downloaded the _framework_ not the _app skeleton_. You should be downloading a zipball from cakephp/app if you are going to go down the zipball path, or get a zipball from the releases (not tags).
