### ISSUE TITLE
Warning text should be in white not black on cake default page

### ISSUE THREAD

**Issue by daveozoalor** [cakephp/docs#3802]
After installing cake, before making any set up, the page that shows up warns that
"Please be aware that this page will not be shown if you turn off debug mode unless you disable the NotFoundException in src/Template/Pages/home.ctp."

That warning is on a red background, but then the text is in black making it difficult to read. The text should be in white or a lighter color.

**Comment by dereuromark** [comment]
This is not a ticket for this repo, as it is part of the https://github.com/cakephp/app package.
But it sure makes sense to improve that.
A PR would be very welcome.

**Comment by markstory** [comment]
Closing as a pull request is up now.
