### ISSUE TITLE
Cake default auth system should come inbuilt

### ISSUE THREAD

**Issue by daveozoalor** [cakephp/docs#3803]
In laravel there is an inbuilt auth system. 
In the command line i can simply type 'migration:auth' and the entire user authentication will be built for me - user registration, user login, user forgot password etc.

It should come inbuilt with cake since its a very vital part of all websites. Nearly all websites require authentication system. And that's usually the first part that every developer battles with. 

The default cake auth, should be inbuilt. User can choose to install it via command line, or build their own.

**Comment by lorenzo** [comment]
There are many great plugins available for this, did you try https://github.com/cakedc/users ?

The reason cake does not implement any in the core is that more often than not the small details of a users system can add up to the point where most of it needs to be replaced. That's why we prefer to rely in plugins instead

**Comment by dereuromark** [comment]
Also see https://github.com/FriendsOfCake/awesome-cakephp#authentication-and-authorization

**Comment by daveozoalor** [comment]
I understand it, but a lot of time will be saved for a developer and most  new learners if the default minimal auth can come inbuilt

**Comment by dereuromark** [comment]
@daveozoalor What is a minimal auth? A logged in vs not logged in? A single group acl? Or multi user/group acl? There are tons of different project specifications playing into this. Most apps don't need any auth.
Having this as a very quick plugin solution sounds like the best approach in the long run.
Opt-in quick and easy, if you need to.

**Comment by ionas** [comment]
While I do agree that Laravel does some thing rights, like laracasts.com and the look and feel of its homepage and while I like conventions I am with @lorenzo and @dereuromark on this one. For me the mixing of Authentication and Authorization in Auth Component is already annoying *to me*. I don't want those parts to be integrated even more tightly and opinionated.

Maybe on the home.ctp of a fresh cake installation we can link to the awesomelist (if that is not the case yet), and the friendsofcake and cakedc repository collections on github.

I do agree that virtually all require authentication btw. Some require HTTP AUTH, some HTTP DIGEST, some LDAP, some HTTP/COOKIE, some two-factor auth, some store in DBs some into files, other into cookies - etc.

**Comment by daveozoalor** [comment]
That will be great too. Authentication is too important to leave a new user struggling with it. A link to good auth choices will be great on cake default homepage after install

**Comment by jhli** [comment]
Well for most stuff especually if you can go wurh the conventions Auth Component will do just fine.

**Comment by lorenzo** [comment]
I think adding links to good plugins in the docs and home page is a great idea

**Comment by ravage84** [comment]
@lorenzo I totally agree. We should help people leveraging the good ecosystem of CakePHP plugins.
Linking them in the docs is a good way to do so.
