### ISSUE TITLE
The blogging tutorial should contain how to create a logout button 

### ISSUE THREAD

**Issue by daveozoalor** [cakephp/docs#3808]
Rather than just asking the user to visit a specific url, the tutorial should end with how to include a logout button

**Comment by ionas** [comment]
A PR for that is welcome.
`<?= $this->Html->link('Sign Out', ['controller' => 'users', 'action' => 'logout'] ?>`

**Comment by daveozoalor** [comment]
Ok, great, will do that.

**Comment by dereuromark** [comment]
ping

**Comment by daveozoalor** [comment]
Hello Dereuromark
