### ISSUE TITLE
How do i check if a user is logged in in a .ctp file?

### ISSUE THREAD

**Issue by daveozoalor** [cakephp/docs#3809]
i couldnt find it in the docs.

please link me to it if its there, if not, what is the recommended way to do that?

In cake 2.x $this->Session->Auth() was available both in the controller and in the view.

**Comment by ionas** [comment]
In Controller `$this->set('authUser', $this->Auth->user());` or anywhere `AuthComponent::user()`

**Comment by ionas** [comment]
It is actually mentioned here briefly http://book.cakephp.org/3.0/en/controllers/components/authentication.html#AuthComponent::user at least the latter.
For the first - if that's best practice (no idea), it should be in the docs.

**Comment by daveozoalor** [comment]
You assume that i already know where to put the code you just showed me.


This is what i did
In appController.php


beforeRender(){

$this->set('authUser', $this->Auth->user());

}


then in User/view.ctp

debug(authUser); //gave me null

**Comment by ionas** [comment]
This is not a help forum.
Last note, I just checked and this works: 
```php
        $this->set('authUser', $this->Auth->user()); // in beforefilter
// in my layout template    
<?= var_dump($authUser) ?>
```
null if not logged in, else user info.
