### ISSUE TITLE
Suggested adjustment to cakephp.org homepage

### ISSUE THREAD

**Issue by daveozoalor** [cakephp/docs#3812]
If you visit cakephp.org on a PC right now, the most important links can be found when the user clicks on 'menu' at the top right corner.

Its surprising that all those links are hidden behind just a button. Initial user reaction on a page is to hit the scroll button and start scrolling down vertically. To find more information, they have to actually scroll up and search for a menu or something.

Since all the links are important, i suggest the menu be dropped permanently. Or that section of the site redesigned in such a way that all those links are seen first. 
![cake_site](https://cloud.githubusercontent.com/assets/1010556/13658822/ec43f730-e67a-11e5-9dd9-0f6e38500a66.png)

**Comment by markstory** [comment]
All good ideas. I think there might be a new design coming up in the next few months. I'm not sure those links will be 'first' though as they are more resources once you are 'bought in' to the idea of the framework. I do agree that they could be more prominently featured though.

**Comment by thinkingmedia** [comment]
I never even noticed the menu button.

**Comment by andtxr** [comment]
Already done? :bowtie:

**Comment by markstory** [comment]
@andtxr Yes, the new footer links duplicate the content hidden in the previous menu system.
