### ISSUE TITLE
Where is the Passing Conditions to Contain inside branch 3.0?

### ISSUE THREAD

**Issue by simkimsia** [cakephp/docs#3818]
On the actual docs website, I can find this section 

http://book.cakephp.org/3.0/en/orm/query-builder.html#passing-conditions-to-contain

In the github branch, I cannot find it.

https://github.com/cakephp/docs/blob/3.0/en/orm/query-builder.rst#loading-associations

<img width="935" alt="screen shot 2016-03-12 at 8 10 36 pm" src="https://cloud.githubusercontent.com/assets/245021/13722874/973b9110-e88e-11e5-9a47-f1c2d8c379c8.png">

**Comment by antograssiot** [comment]
It's there https://github.com/cakephp/docs/blob/3.0/en/orm/retrieving-data-and-resultsets.rst#passing-conditions-to-contain

**Comment by simkimsia** [comment]
Thanks. That's confusing. How is it that the passing conditions to contain end up there?

**Comment by antograssiot** [comment]
@simkimsia there are `include` tags used by sphinx to avoid repetition of blocks

**Comment by simkimsia** [comment]
Note to self:

open the file in raw form to see the include tags.

Thanks @antograssiot
