### ISSUE TITLE
2.x Shell::_useLogger() is not documented

### ISSUE THREAD

**Issue by ravage84** [cakephp/docs#3824]
[Shell::_useLogger()](http://api.cakephp.org/2.8/class-Shell.html#__useLogger) is not documented, though quite handy.

I think we should add it to http://book.cakephp.org/2.0/en/console-and-shells.html.
At least as under http://book.cakephp.org/2.0/en/console-and-shells.html#shell-api.

**Comment by markstory** [comment]
Its a protected method. We generally don't document them because they are not part of the documented, public API.

**Comment by ravage84** [comment]
I totally understand that.
But today I needed to  disable logging stream output to stdout and stderr and if I wasn't so familiar with the Framwork and it's documenation infrastructure, I probably woulldn't have found it.

**Comment by markstory** [comment]
We've never really documented the protected methods in the book. That is one of the many reasons the API docs exist.
