### ISSUE TITLE
RFC Provide HTTPS access through Let's Encrypt

### ISSUE THREAD

**Issue by ravage84** [cakephp/docs#3825]
Since the advent of [Let's Encrypt](https://letsencrypt.org/), it got really pain- and cost-free to setup HTTPS.
I think we should make the docs accessible through HTTPS by utilizing a certificate from Let's Encrypt.

**Comment by josegonzalez** [comment]
We're actually in the middle of working on the server provisioning setup, so this is something I have on my list.

**Comment by markstory** [comment]
I'm not against having https on the docs, I don't really understand what the value is to the community?

**Comment by jorisvaesen** [comment]
Thanks to Lets's Encrypt is super easy and should be done because [Google is about to start favoring HTTPS sites in search results](http://thenextweb.com/google/2015/12/17/unsecured-websites-are-about-to-get-hammered-in-googles-search-ranking/)

**Comment by tenkoma** [comment]
Since the change to https has been completed, is this issue also completed? 🔒 
The certificate is not "Let's encrypt" but COMODO 😄

**Comment by ravage84** [comment]
Yup!

**Comment by josegonzalez** [comment]
We used a wildcard certificate.
