### ISSUE TITLE
composer can't create new projects anymore

### ISSUE THREAD

**Issue by gugleboot** [cakephp/docs#3851]
Hi 
don't know where to report this

from : http://book.cakephp.org/3.0/en/installation.html

following composer command stopped working
php composer.phar create-project  --prefer-dist cakephp/app demo

result

[InvalidArgumentException]
  Could not find package cakephp/app with stability stable.

kind regards

**Comment by josegonzalez** [comment]
Works here. Maybe your composer.phar is out of date? Please call `php composer.phar self-update` to ensure you have the latest version of composer.

**Comment by gugleboot** [comment]
Thanks for the update 

i am following installation guide step by step each time I download fresh composer.phar

i have tested it on 3 distinct servers and result is always the same 

[InvalidArgumentException]
Could not find package cakephp/app with stability stable.

I was able to install it on my local machine using phpstorm -> create new composer project .

is php version important during this step ? i know that composer shows php requirements during installation process that can be suppressed and it will continue to download files.

first server config:
cli php (v 5.3)
shared hosting domain (php7) when accessed from the browser

i have found workaround : download zip from github cakephp/app and then composer update
but i would like to know what is wrong with this

kind regards

**Comment by josegonzalez** [comment]
Ah, that might be it. CakePHP 3 requires a minimum of 5.4+, and the most recent stable requires 5.5+. You should upgrade your cli version to use the same version as you use in the browser.
