### ISSUE TITLE
What does $query->first() return if there are no records found?

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/docs#3854]
Can I make a pull request to clarify what the return value for `first()` will be for empty results?

http://book.cakephp.org/3.0/en/orm/retrieving-data-and-resultsets.html#getting-the-first-result

Does not say what the result for none will be.

**Comment by markstory** [comment]
Sure.

**Comment by thinkingmedia** [comment]
@markstory what branch do I update for 3? There are a couple of branches for 3.x

**Comment by markstory** [comment]
`3.0` is the branch that gets auto-deployed. The `3.3` branch will be merged into `3.0` with the release of 3.3.
