### ISSUE TITLE
Use of second person on the Internationalization & Localization page.

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/docs#3857]
I noticed that there is heavy usage of the second person (`you` and `your`) on the Internationalization & Localization page.

http://book.cakephp.org/3.0/en/core-libraries/internationalization-and-localization.html

This does not appear to be consistent with the other parts of the documentation.

While it is sometimes good to use the second person when you are providing instructions. For example; "You add X to Y and you will get Z". I think the majority of the documentation is written in the passive voice. For example; "Adding X to Y will give Z".

**Comment by ravage84** [comment]
@thinkingmedia interested in putting up a fix for this?

**Comment by saeideng** [comment]
I think we can close this , a PR has been merged
