### ISSUE TITLE
Authorization Issues in Part 2 of bookmarker tutorial

### ISSUE THREAD

**Issue by Gammrar** [cakephp/docs#3875]
If you follow the part 2 of the tutorial the logout doesn't seem to work - after visiting a new page, there's a message saying you weren't authorized, as I believe the isAuthorized function returns false for everything that isn't the login page and the logout page doesn't get authorized through later actions in the tutorial like the users/add page is.  

In addition, it looks like some other pages, such as the List Users page, are never added to be accessed by any users in the tutorial.  Adding some sort of notice that portions of the site available in part 1 won't be accessible when you're finished with part 2 would be helpful for newbies who think they've screwed something up along the way.

**Comment by markstory** [comment]
Pull request up now.
