### ISSUE TITLE
3.x Time, DateTime, FrozenTime, FrozenDateTime

### ISSUE THREAD

**Issue by ionas** [cakephp/docs#3879]
http://book.cakephp.org/3.0/en/core-libraries/time.html#setting-the-default-locale-and-format-string

I was wondering why this did not work within `beforeFilter()`:
```php
        \Cake\I18n\Time::$defaultLocale = 'de-DE';
```
It is due to the split. Thus the docs are really inaccurate and not too helpful.
This is what you want to do ***currently***:
```php
use Cake\I18n\Time;

        // ...

        Time::$defaultLocale = 'de-DE';
        Date::$defaultLocale = 'de-DE';
        FrozenTime::$defaultLocale = 'de-DE';
        FrozenDate::$defaultLocale = 'de-DE';
```

Either the docs have to be fixed (I can do that, just say so) or the code needs to be fixed.

There should be a way to set all those 4 at once. I still purpose `Configure::write()`, or setup something like a static DateTimeConfig class.

What's your call?

At the moment doing this `Time::$defaultLocale = 'de-DE';` won't change backed output on for instance index actions.

**Comment by markstory** [comment]
You should only need to set the properties for the relevant classes. For example if you are not using the immutable objects, you don't need to set them up.

I don't like the idea of using `Configure` as it adds more hidden dependencies/coupling. I can update the documentation so it mentions the other classes.

**Comment by ionas** [comment]
@markstory well what I'd like to see is one way to set the defaults for all 4 time classes, one to set the defaults for the 2 frozen vs non frozen and then the way implemented in PR #8588 (for each one separately). However the only solutions that came to my mind is subclassing (no multiple inheritance) and globals/Configure.

Maybe one/multiple setter config methods in the trait that make it easy to specify all vs frozen/unfrozen vs specific? If you agree I can think about a PR after finishing the tests on #8588.

**Comment by markstory** [comment]
What about something like `I18n::setDefaultLocale()` and `I18n::defaultOutputTimezone()`?

**Comment by ionas** [comment]
@markstory there is already a combined magic getter setter `I18n::defaultLocale() {}`
I have created `I18n::defaultOutputTimezone()` that mimicks those default setters in `I18n`.

**Comment by ionas** [comment]
Thanks for updating to a getter/setter and the corresponding docs.

For locales I think its justified to have one `i18n::setDefaultLocale()` call available (however, after digging into the issue, for a proposed `::setDefaultOutputTimezone()` this is not the case, as it does only work on datetimes/times and not on dates).
