### ISSUE TITLE
Comparing two fields in where clause

### ISSUE THREAD

**Issue by RaXaR** [cakephp/docs#3895]
Hi there :)

I'm using CakePHP: 3.1.13.
I have a model with Model.field1 and Model.field2. I'm trying to add a where() clause that compares two fields, something like:
```
...
->where(['Model.field1 !=' => 'Model.field2'])
...
```
I checked [QueryBuilder](http://book.cakephp.org/3.0/en/orm/query-builder.html) and [Retrieving Data & Results](http://book.cakephp.org/3.0/en/orm/retrieving-data-and-resultsets.html)
But couldn't seem to get info on how to get it to work. Is it possible to do?

Thanks

**Comment by markstory** [comment]
You can do this with a string SQL snippet.  `where(['Model.field1 != Model.field2'])`.  Depending on your database and configuration you may need to quote the column identifiers.

I'll add a section to the docs on how to do this.

**Comment by RaXaR** [comment]
Aha, that did the trick.
Thanks!

**Comment by markstory** [comment]
Pull request up now #3899
