### ISSUE TITLE
Remove hiddenField when creating array checkbox with form helper

### ISSUE THREAD

**Issue by doshu** [cakephp/docs#3910]
creating checkboxes with the name in the array form like 
```
<input` type="checkbox" name="selected[]" value="1" />
```

created with $this->Form->input('selected.', ['type' => 'checkbox']) should not create the hiddenField because createing an hidden field with the name selected[] will duplicate all the checkboxes with no sense

**Comment by markstory** [comment]
You should use the [hiddenField](http://book.cakephp.org/3.0/en/views/helpers/form.html#options-for-select-checkbox-and-radio-inputs) option.

**Comment by doshu** [comment]
yes i know that i can suppress it using hiddenField, but i think it should be good if cake handle it automatically

**Comment by markstory** [comment]
@doshu I disagree. I prefer functions where I can understand the output based on reading the parameters. Having to parse/understand effectively magic strings makes code harder to read, review and understand. It also introduces hidden conventions which are interpreted as 'magic' by those unfamiliar with them.

**Comment by doshu** [comment]
the hiddenField params must be always exists but the default value in this case should be false

**Comment by markstory** [comment]
The issue I have is that you're asking for the default value of the hiddenField option to become linked to a trailing `.` in the field name. That implicit dependency/relationship is what I would prefer to avoid.
