### ISSUE TITLE
Documentation: Blog Tutorial

### ISSUE THREAD

**Issue by Factorsmith** [cakephp/docs#3924]
Nice Tutorial, however the example name is unfortunate.  Some great confusion is caused by the fact that the example is a "Posts" controller since it is unclear when 'post' refers to a submit request.

**Comment by jhli** [comment]
Agreed. Would you set up a PR to change any 'Post' nomenclature to 'Article'?

**Comment by Factorsmith** [comment]
Umm,  sure would if I knew how.  -hate to see this lost due to my ignorance.
By "PR", do you mean project request, or pull request, where I have re-written the Blog -really do not have time for that.  :(

**Comment by markstory** [comment]
@Factorsmith He means a 'pull request'. The book pages all include an 'Edit this page' link that will open the page you're looking at in github's editor. If you don't have the time/interest in doing that someone else will eventually get around to it.

**Comment by Factorsmith** [comment]
I'll put it on my list -and for the 3.0 doc also -but no promises

**Comment by cake17** [comment]
The docs now refer to Articles and not Posts anymore at least for 3.x. Maybe we can close this ?
