### ISSUE TITLE
Session Config.language  after Upgrading to 3.2.8

### ISSUE THREAD

**Issue by dividedbynothing** [cakephp/docs#3938]
Hello,
I've recently upgraded my App from Cake version 3.1.1 to version 3.2.8.

Before the upgrade, in 3.1.1, I set the default local in my bootstrap file:
`ini_set('intl.default_locale', 'en_US');`

With that, $session->read('Config.language'); resulted in 'en'.  This setting was also visible in the debug kit under Session config.

However after upgrading, that Session Config Language show only "null".

Has something changed, or is there any fix for this?

Thanks in advance,
DBN

**Comment by markstory** [comment]
> Has something changed, or is there any fix for this?

Nothing has intentionally changed. CakePHP never reads or writes to `Config.language` in the session.

**Comment by dividedbynothing** [comment]
Hi Mark... thank you.  And yes, I realized this... Config.language is not written in the session unless explicitly called to do so.

I figured out my problem however:
In 3.1.1, this code:
`echo  $this->Html->link(__('English'), ['controller' => 'Users', 'action' => 'setlang','?' => ['en']], ['class' => 'myclass']);` would output `<a href="/myapp/users/setlang/en" class="myclass">`.
After upgrading 3.2.8, the same code outputs `<a href="/myapp/users/setlang?0=en" class="myclass">` which fails in my controller method.

I fixed it in 3.2.8 with the URL builder using this code instead:
`                $langurl = $this->Url->build([
                "controller" => "Users",
                    "action" => "setlang",
                    "id","en"
]);
                echo "<a href=\"".$langurl."\" class=\"myclass\">English</a>";`

This give the same output as my 3.1.1 version.

Anyway thanks.. and sorry about my initial misunderstanding on Config.language.
Thanks,
DBN
