### ISSUE TITLE
Error in doc for Session Configuration

### ISSUE THREAD

**Issue by Aerue** [cakephp/docs#3945]
http://book.cakephp.org/3.0/en/development/sessions.html#built-in-session-handlers-configuration

The doc say : 

`'timeout' => 4320 // 3 days`

While the core code say :

- timeout: The time in minutes the session should be valid for.

The doc should say :

`'timeout' => 72 // 3 days`

**Comment by markstory** [comment]
The timeout option is in 'minutes'. 72 minutes is not 3 days, `4320 / 60 / 24 = 3` though.
