### ISSUE TITLE
Docs don't mention compatiblity to APCu

### ISSUE THREAD

**Issue by ravage84** [cakephp/docs#3946]
While doing some research on caching with CakePHP, I came across this statement:

> APCEngine cache is now compatible with APCu.

http://bakery.cakephp.org/2014/07/21/CakePHP-2-5-3-and-1-3-20-released.html

While this is nice and good to know, I wasn't able to find the same statement in the 2.x (3.x) cookbook nor in the API docs.

https://www.google.ch/?gws_rd=ssl#q=site:api.cakephp.org+%22apcu%22
https://www.google.ch/?gws_rd=ssl#q=site:book.cakephp.org+%22apcu%22

Not sure if this is actually true or if this feature is requested often, but if it's in CakePHP, it should be documented at a proper place.

**Comment by ravage84** [comment]
Probably related: https://github.com/cakephp/cakephp/issues/3749

**Comment by markstory** [comment]
Both 2.x and 3.x docs updated.
