### ISSUE TITLE
3.x - Patching associated data not working as described

### ISSUE THREAD

**Issue by ndm2** [cakephp/docs#3952]
Currently, when patching associated data, the original data must be present in the entity, respectively, for `hasMany` and `belongsToMany` associations, there must be at least one entry in the association property, which doesn't necessarily have to be the data to patch, there just needs to exist _something_ in order for the marshaller to skip the following condition:

**https://github.com/cakephp/cakephp/blob/3.2.8/src/ORM/Marshaller.php#L653-L655**

After that point, the marshaller is able to load non-existent original records by possible primary keys present in the data, and patch them.

The corresponding cookbook section **[Saving Data > Patching HasMany and BelongsToMany](http://book.cakephp.org/3.0/en/orm/saving-data.html#patching-hasmany-and-belongstomany)** doesn't reflect that (there might be further non-working examples, I haven't searched everything), ie it doesn't load associated data for the entity to patch.

Now I'm not 100% sure which behavior to expect, ie should one _have_ to load associated data _in any case_ in order to be able patch it, ie the docs are incorrect as the examples are missing proper contains, or is there maybe a bug in marshaller, ie the marshaller should be able to load entities by possible primary keys in the data even when the association property on the entity doesn't exist/is empty?

Another issue related to this, is that the docs say

> For belongsTo and hasOne associations, new entities will be constructed if no previous entity is found for the target property.

which seems to be only half of the truth, as the same happens for `hasMany` and `belongsToMany` associations, when no previous data is available (ie the association property is empty or doesn't exist), new entities will be created. Again I'm not really sure about what behavior to expect.

**Comment by markstory** [comment]
I'll update the examples so that they do the include the required 'contain' keys. The marshaller should not be inferring when data should be loaded, and automatically loading it.

**Comment by markstory** [comment]
I think this is addressed with #4022
