### ISSUE TITLE
CakePHP3 - Custom page error 404 not working

### ISSUE THREAD

**Issue by ldcuong** [cakephp/docs#3968]
I doing tutorial follow http://book.cakephp.org/3.0/en/development/errors.html#exception-renderer but it is not working and display blank page.

In config/bootstrap.php

    use App\Error\AppError;
    $errorHandler = new AppError();
    $errorHandler->register();
In src/Error/AppError.php

    <?php
    namespace App\Error;
    
    use Cake\Error\BaseErrorHandler;
    
    class AppError extends BaseErrorHandler
    {
        public function _displayError($error, $debug)
        {
            return 'There has been an error!';
        }
        public function _displayException($exception)
        {
            return 'There has been an exception!';
        }
    
        public function handleFatalError($code, $description, $file, $line)
        {
            return 'A fatal error has happened';
        }
    }
I create my_error.ctp in src/Template/Layout/my_error.ctp. And in my src/Template/Error/error404.ctp I change layout to my_error.ctp.

    $this->layout = 'my_error';

Finally, In my controller

    use Cake\Network\Exception\NotFoundException;
    $staff = $this->Staff->find()->where(['Staff.StaffId = '=> $id, 'Staff.PartnerId = ' =>$this->partnerId])->first();
    if (empty($staff)) {
        throw new NotFoundException(__('Staff not found'));
    }

---------------------------------

**Comment by markstory** [comment]
I'll double check, but last time I looked the docs were right.

**Comment by ldcuong** [comment]
@markstory 
Thank you for reply, can you explain more?
If the docs right so I wrong, but I don't know where is wrong. Can you point it?

**Comment by markstory** [comment]
@ldcuong I can't point it out right now. I'll have to try and reproduce the issue and get back to you later on.

**Comment by ldcuong** [comment]
@markstory 
Thank you, If you need more information please tell me.

**Comment by ldcuong** [comment]
@markstory 
I'm sorry, I found my mistake. :( 
Because in bootstrap.php I copy below code at the end of file. Therefore Cake cannot understand it. Please close this issue. Thank you for support.
```
use App\Error\AppError;
$errorHandler = new AppError();
$errorHandler->register();
```

**Comment by kuldeepdhoni** [comment]
use App\Error\AppError;
$errorHandler = new AppError();
$errorHandler->register();

how solve this issue??

**Comment by saeideng** [comment]
@kuldeepdhoni 
there are 2 error handler 
https://github.com/cakephp/app/blob/910634f18b279dbe320f479ec015f7e49c1aa24e/config/bootstrap.php#L113-L118

replace your error handler with one of them 
cli or for browser 

docs : https://book.cakephp.org/3.0/en/development/errors.html#creating-your-own-error-handler

**Comment by kuldeepdhoni** [comment]
may i know , only need to change the code in bootstrap.php ?? or any other file??

$isCli = PHP_SAPI === 'cli';
if ($isCli) {
    (new ConsoleErrorHandler(Configure::read('Error')))->register();
} else {
    (new ErrorHandler(Configure::read('Error')))->register();
}
