### ISSUE TITLE
Validation: Example somehow incorrect

### ISSUE THREAD

**Issue by nrother** [cakephp/docs#3971]
The [page about validation](http://book.cakephp.org/3.0/en/core-libraries/validation.html#conditional-validation) has this example:

```php
$validator->requirePresence('full_name', function ($context) {
    return $context['data']['action'] === 'subscribe';
});
```

This will trigger a warning as the FormHelper will call the function with `$context['data'] === []`. Also the fact that the FormHelper will call this function should be documented there.

**Comment by markstory** [comment]
Where does FormHelper call `isPresenceRequired()`? I can only see calls to `isEmptyAllowed()` in the EntityContext class.

**Comment by nrother** [comment]
You're right, it was actually a callback in `notEmpty` causing said problems. Looks good now in the docs.
