### ISSUE TITLE
FormHelper - date and dateTime fields 'default' value

### ISSUE THREAD

**Issue by nemmons** [cakephp/docs#3974]
Hello, I believe the documentation [here](http://book.cakephp.org/3.0/en/views/helpers/form.html#common-options) is incorrect. It says "Date and datetime fields’ default values can be set by using the ‘selected’ key.". As far as i can tell this is incorrect and one needs to use the 'default' key for default values on date and datetime fields as well.

**Comment by nemmons** [comment]
Actually, after trying out some more code, I think it may even be the case that even the 'default' key doesn't work on date and datetime fields. I don't think it's possible to set a default at all here.

**Comment by markstory** [comment]
> Date and datetime fields’ default values can be set by using the ‘selected’ key.

This statement is accurate based on the test cases for FormHelper.

**Comment by nemmons** [comment]
Thank you for taking the time to look at my issue. I'm sorry but I've read through the [Test Cases for FormHelper](https://github.com/cakephp/cakephp/blob/master/tests/TestCase/View/Helper/FormHelperTest.php) and I'm unable to find any test cases that verify the statement in the documentation. There doesn't seem to be a single test case here where 'selected' is used as a key for an options array. 

If i'm missing one, I'd really appreciate it if someone could point it out so that I can better understand how to have a default value for a date select input. Thanks again.

**Comment by markstory** [comment]
You're right. I got confused between 2.x and 3.x. I'll get the docs updated.

**Comment by markstory** [comment]
Pull request up now. Thanks for being persistent :smile:
