### ISSUE TITLE
Links to older versions of cookbook in subdomain websites of cakephp.org

### ISSUE THREAD

**Issue by markstory** [cakephp/docs#3979]
_From @MrSnoop on March 27, 2016 22:16_

This is a (multiple allowed):
- [x] bug

@  http://certification.cakephp.org/ &  http://my.cakephp.org/login : links in top navigation refer to old versions of cookbook ;)

_Copied from original issue: cakephp/cakephp#8553_

**Comment by markstory** [comment]
The sites haven't been updated in a while. We'll have to figure that out soon :smile:

**Comment by tenkoma** [comment]
I thought that this problem, now it has been fixed. 😄 

http://my.cakephp.org/login has been renewed,
Nothing linked to the old document from http://certification.cakephp.org/ top navigation.

**Comment by ravage84** [comment]
Agree with @tenkoma
