### ISSUE TITLE
Adding Query::epilog() to documentation

### ISSUE THREAD

**Issue by chinpei215** [cakephp/docs#3981]
Not only MySQL, but also Postgres and Oracle seem to support FOR UPDATE clause. It would be worth to document it.

[Postgres]
http://www.postgresql.org/docs/current/static/sql-select.html#SQL-FOR-UPDATE-SHARE

[Oracle]
http://docs.oracle.com/database/121/SQLRF/statements_10002.htm#SQLRF55370

**Comment by markstory** [comment]
Pull request up now.
