### ISSUE TITLE
Showcase the model "action" idea

### ISSUE THREAD

**Issue by ravage84** [cakephp/docs#3989]
During the first day of the CakeFest 2016 advanced workshop @lorenzo showed the audience his idea of invokable actions for storing business logic outside of the models.
Someone asked for slides of how it was done, but I think this would be a good fit to be showcased in the 3.x documentation.
As @lorenzo mentioned, people get in doubt when they hit the boundaries of the convention ruleset of the framework.
Showing an example of one possible approach could help those people.

**Comment by ravage84** [comment]
@lorenzo you said your model actions weren't formalized as opposed to the query builder for example. Would it make sense to formalize them and add them to the built-in tools of the framework?

**Comment by ravage84** [comment]
@markstory you showed two ways in your advanced workshop yesterday: actions and services. I think it would be interesting to show case this for a broader audience. If not in the CookBook, then may be in your blog?

**Comment by markstory** [comment]
I could put together a blog post on services.
