### ISSUE TITLE
Tip Divs Overflow and Sit On Top of the Sub Section Listing

### ISSUE THREAD

**Issue by justinyost** [cakephp/docs#4000]
Example in the Testing Page
<img width="1047" alt="screen shot 2016-05-28 at 3 21 54 pm" src="https://cloud.githubusercontent.com/assets/85320/15627553/1c3dff70-24e8-11e6-8cf7-1db8737d661c.png">

**Comment by dakota** [comment]
![image](https://cloud.githubusercontent.com/assets/83255/15627573/599d1018-24e8-11e6-970c-1d92abbd2c5c.png)

**Comment by markstory** [comment]
I'll have this fixed after my talk.

**Comment by markstory** [comment]
Mostly fixed now as you can see the content. Getting the backgrounds to respect the floats is going to be fun..

**Comment by markstory** [comment]
Closing as this is fixed enough for now. Until CSS floats get less awful, I don't think I can get the background colorus to behave properly underneath the 'Page Contents'
