### ISSUE TITLE
Anchors are hidden behind the nav-bar.

### ISSUE THREAD

**Issue by ndm2** [cakephp/docs#4010]
When visiting an anchor, like [this for example](http://book.cakephp.org/3.0/en/core-libraries/collections.html#Cake\\Collection\\Collection::append), the targeted element is being hidden by the nav-bar, which can be a little confusing (same problem in the API docs).

Having the nav-bar expand when scrolling upwards adds some additional annoyance in this case, as the target is going to be hidden even more.

![hidden-anchor](https://cloud.githubusercontent.com/assets/5031606/15634209/98304026-25be-11e6-942e-33f1fb88c531.png)

![hidden-anchor-transparency](https://cloud.githubusercontent.com/assets/5031606/15634213/9ce48e10-25be-11e6-9853-eaceaf6bf516.png)

**Comment by markstory** [comment]
Fixing this is going to be tricky. In order to get the sticky header it needs to be fixed/absolute position which interacts poorly with anchor behavior in browsers.

**Comment by ndm2** [comment]
Yeah, I know... I'm usually using JS, or hidden, offset anchors to work around this without having to adjust the content layout.

**Comment by ADmad** [comment]
This CSS trick might be the solution https://www.itsupportguides.com/tech-tips-tricks/how-to-offset-anchor-tag-link-using-css/

**Comment by markstory** [comment]
Nice find @ADmad that works really well in Firefox. I'll test it some more in other browsers, and if it works push up a fix.

**Comment by markstory** [comment]
Fixed on the 2.x and 3.x docs.
