### ISSUE TITLE
Concatenate and minify css and js

### ISSUE THREAD

**Issue by cake17** [cakephp/docs#4017]
Maybe we could minify and concatenate the css and js to decrease the number of HTTP requests to the server

**Comment by ionas** [comment]
* [Google Pagespeed Insights](https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fbook.cakephp.org%2F3.0%2Fen%2F)
* [W3 Validator](https://validator.w3.org/nu/?doc=http%3A%2F%2Fbook.cakephp.org%2F3.0%2Fen%2Findex.html)

**Comment by markstory** [comment]
@cake17 Yes. Its on my list of things to do. It requires some more `Makefile` work but its doable.

**Comment by markstory** [comment]
Closing as this is done on 2.x and 3.x docs.
