### ISSUE TITLE
Search not working for versions != 3.X

### ISSUE THREAD

**Issue by elboletaire** [cakephp/docs#4018]
First off, nice update! The book now looks much better. Congrats guys :)

I've found an issue though, the search does not work for any other versions than 3.X. The results provided are from version 3.X and thus returns a 404  in the majority of cases.

**Comment by markstory** [comment]
I think I know why. Because of git issues, I copied assets from 3.x branch into all the other branches. I'll get this fixed.

**Comment by markstory** [comment]
This should be all good now. I dropped and rebuilt the indexes for each of the old versions so they shouldn't contain any bogus results now.

**Comment by elboletaire** [comment]
Nice :+1: !!
