### ISSUE TITLE
Website: Release notes from GitHub should appear on CakePHP.org prominently!

### ISSUE THREAD

**Issue by ionas** [cakephp/docs#4026]
### Problem
@ypnos-web on IRC was wondering where the release change logs on cakephp.org are gone!

### Suggestion
https://github.com/cakephp/cakephp/releases/tag/3.2.10 et al.
via
https://developer.github.com/v3/repos/releases
on
https://releases.cakephp.org (or similar)

### Bug
http://cakephp.org/changelogs/3.2.10 is even broken which is being linked from https://github.com/cakephp/cakephp/releases/tag/3.2.10

**Comment by ravage84** [comment]
https://releases.cakephp.org  sounds good to me.
It could be a simple redirect to https://github.com/cakephp/cakephp/releases or if we want to promote releases of sub projects, we could show their releases there, too.

**Comment by ionas** [comment]
👍 For sub-projects. Some more visibility to migrations, bake, etc. would not hurt.
The [Github API](https://developer.github.com/v3/repos/releases) is probably straight forward enough to automate things on cakephp.org.

**Comment by josegonzalez** [comment]
@phpnut lets talk about this via PM, since we had some SEO concerns around this that were raised previously.

@ionas thanks for bringing it up.

**Comment by phpnut** [comment]
I should be  on slack some today and back to normal schedule tomorrow afternoon in the states

**Comment by markstory** [comment]
The website was previously reading the bakery RSS feed. Which is [still around](http://bakery.cakephp.org/rss.html).

**Comment by ravage84** [comment]
All the GitHub repos provide RSS feeds, too.

**Comment by phpnut** [comment]
fixed
http://cakephp.org/changelogs/
http://cakephp.org/changelogs/3.2.10

**Comment by ypnos** [comment]
I suggest you also link to this in the Documentation menu.

**Comment by ionas** [comment]
Thanks!. 👍 for having it linked somewhere
