### ISSUE TITLE
Cookbook documentation extension

### ISSUE THREAD

**Issue by dnns19** [cakephp/docs#4051]
Today I posted a question on stackoverflow. An answer was given with the suggestion to open a question on the Github page. So here it is. 

**Missing doc**
I was looking for specifying a composite key in the tables. I couldn't find this in the documentation. 
The url to the stackoverflow post: [http://stackoverflow.com/questions/37658120/cakephp-3-linking-two-tables-with-two-composite-foreign-key-relation](http://stackoverflow.com/questions/37658120/cakephp-3-linking-two-tables-with-two-composite-foreign-key-relation).

**Comment by andtxr** [comment]
Closing the issue because there is already a PR for it. Thanks @dnns19!
