### ISSUE TITLE
Back to contents button

### ISSUE THREAD

**Issue by cake17** [cakephp/docs#4061]
Maybe we could place and fix the "Back to contents" button under the fixed pencil "Edit button". With only an arrow-up icon.

For now, the button "Back to contents" disappears under the navbar when sliding up.

**Comment by ravage84** [comment]
2.x, 3.x or both?

**Comment by cake17** [comment]
@ravage84 both versions

**Comment by markstory** [comment]
I can reposition the link when the header is showing as well.

**Comment by cake17** [comment]
@markstory Would be better in my opinion under the pencil, but the reposition would be ok

**Comment by markstory** [comment]
Under the pencil means it could easily overlap with the content the person is trying to read. If it was on the right side, it would need to be much smaller/just an icon.

![screen shot 2016-06-07 at 12 48 15 pm](https://cloud.githubusercontent.com/assets/24086/15866790/2c2305fc-2cae-11e6-987a-3ba370f86552.png)

**Comment by cake17** [comment]
Maybe with an arrow up like this http://fontawesome.io/icon/arrow-circle-up/

**Comment by markstory** [comment]
That might work.

**Comment by cake17** [comment]
PR #4104 open
