### ISSUE TITLE
Testing actions that require authentication - stateless authentication

### ISSUE THREAD

**Issue by markvdlaan93** [cakephp/docs#4078]
The documents suggest how to mock actions that [requires authentication](http://book.cakephp.org/3.0/en/development/testing.html#testing-actions-that-require-authentication). However, it is often the case that someone uses stateless authentication (e.g. when building an api) and therefore can't inject the session array. I would suggest to add an extra common use case which explains how to perform the task with stateless authentication. This did the job for me: 

`public function controllerSpy($event)
 {
    parent::controllerSpy($event);
    if (isset($this->_controller)) {
        $this->_controller->Auth->setUser([]);
    }
}`

**Comment by markstory** [comment]
Couldn't you also simulate the API credentials with fixture data? For example have users with known API tokens, and use those tokens to do requests?

**Comment by jeremyharris** [comment]
Perhaps explaining how to pass environment info to the request would be helpful, this is similar to what I do when testing APIs that use basic auth and a single api key:

```php
$this->configRequest([
    'environment' => [
        'PHP_AUTH_USER' => $apiKey
    ]
]);
```

My concern is that any sort of documentation would be application-specific, unless we better documented `configRequest` and how to use it to set env vars or headers. (I usually end up reading it each time, as I forget headers prefix with HTTP automatically when the request is built.)

**Comment by markstory** [comment]
Providing better docs on how to set arbitrary headers including basic auth and Oauth2 headers might help.

**Comment by jeremyharris** [comment]
If you'd like, I'd be happy to put together a PR with a few examples :)

**Comment by markstory** [comment]
@jeremyharris That would be awesome!
