### ISSUE TITLE
Missing example for using the key "url" with IDs in the FormHelper

### ISSUE THREAD

**Issue by doonot** [cakephp/docs#4085]
Using key `action` is deprecated, use `url` directly instead. 

If this is done in an edit form where an ID has to be passed, it is not possible to achieve the same result by just changing the key from action to url.

There should be an example that shows how to use the "url" key with IDs.

http://book.cakephp.org/2.0/en/core-libraries/helpers/form.html#options-for-create

Best Regards,
Patrick

**Comment by dereuromark** [comment]
It is in there, inside "Options for create()"
It just lists both action and url key, since both still work.

**Comment by doonot** [comment]
Working with IDs is not documented. When I only change "action" to "url" the ID is not transferred to the controller.

**Comment by dereuromark** [comment]
Ah, I see. That is right. In general it is always good practice to manually set up some id if you need it by the way.

**Comment by ravage84** [comment]
I see the problem. People who are used to the old ``'action'`` way, are expecting the new ``'url'`` to work the same way.
So I agree, there should be an example to show them that they need to set and use an ID  manually.
