### ISSUE TITLE
Is it right for docs? if mod App.base, AuthComponent will not work properly

### ISSUE THREAD

**Issue by junichirojp** [cakephp/docs#4088]
Hi, i can't find the result. is it true?

if we don't set App.base on false, the AuthComponent will not work properly.
https://github.com/cakephp/docs/blob/3.0/en/development/configuration.rst#general-configuration

**Comment by chinpei215** [comment]
> ensure your string starts with a / and does NOT end with a /. E.g., /basedir is a valid App.base.

Did you read this sentence? It says "Ensure ~. Otherwise ~." Or are you asking this question after understanding it?

Aside from that, Any chance you could join japanese slack channel? You could ask it in Japanese before opening an issue.

**Comment by junichirojp** [comment]
Sorry make isue.
I have to check again.

**Comment by junichirojp** [comment]
I can understand your explain.
thank you!
