### ISSUE TITLE
PDF Book missing contents links

### ISSUE THREAD

**Issue by raul338** [cakephp/docs#4100]
In the contents page of the pdf book, There are missing links in the Database Access & ORM section, currently it looks like this
```
12 Database Access & ORM ............. 341
    Quick Example .................... 341
    More Information ................. 343
13 Authentication .................... 495
```
Or is it intended that there are almost 50 pages under "More information"?

**Comment by markstory** [comment]
We don't have much control over the fine details of the PDF. Sphinx handles all of those details in a fairly opaque way.

I'm going to close as I don't think we'll be able to make much progress on this.
