### ISSUE TITLE
2.x Document lack of Foreign Key Constraint Support in Schema

### ISSUE THREAD

**Issue by ravage84** [cakephp/docs#4102]
Came across [this](https://github.com/CakeDC/migrations/issues/230) issue and wanted to explain them that CakePHP 2.x does not support foreign key constraints in schema generation by providing an official Cookbook link.

To my surprise I haven't found any official statement about this in the Cook book.

This should be fixed.

I guess that could prevent [such issue](https://github.com/cakephp/cakephp/issues/8136#issuecomment-177286591)s, too

**Comment by cake17** [comment]
PR #4114 is now up
