### ISSUE TITLE
Can't find any documentation on how to upgrade CakePHP generally

### ISSUE THREAD

**Issue by PoeticIntensity** [cakephp/docs#4105]
Migration guides for specific versions are a great help, but it would be awesome if there was a page that describe best practices on how to upgrade between cake versions generally.  Both from git / svn / non-versioned code / etc...

savant told me to open this issue in IRC.  If the page already exists, it's on him. :)

**Comment by ravage84** [comment]
@PoeticIntensity could you broadly outline what content you would expect from such a guide?

Some bullet point list would be a good start.

*sarcasmOn*
Do you expect this guide to tell you to do a backup of your stuff before?
*sarcasmOff*

**Comment by dereuromark** [comment]
There are tons of blog post and resources around it. Not sure that and a lot of other things are suited for cakephp docs, as they usually go out of scope of the actual documentation and would create a "bible" of pages that will be harder to read through.
Google for the keywords and you will find the "That's how I did it" kind of articles.

**Comment by josegonzalez** [comment]
I'm 👍 on getting some documentation on upgrading between minor versions. The CakePHP core team knows how to upgrade their apps - seems simple enough - but we can definitely provide a good workflow for more junior developers.

For instance, I've seen people ask if they should just start with a fresh `app` repo and move their `src` dir over, etc. Providing guidance here would be great to get rid of any ambiguities.

> Aside: I normally find what I need on google and wasn't able to find an upgrade guide for Cake3 versions.

Here is what I normally do (and can probably be made into a small section on the migration page):

```
git checkout -b cakephp-VERSION
composer require cakephp/cakephp:VERSION
# resolve any composer issues
# read the migration guide, remove deprecated code
# use new features where necessary
# add any changes that seem to apply
# look at cakephp/app repo, see if anything yummy in the defaults is now there and copy it over as necessary
phpunit
# resolve test issues
git add . && git commit -m "Upgrade to cakephp VERSION"
git checkout master
git merge cakephp-VERSION
```

**Comment by markstory** [comment]
I think including a short section on how to upgrade between patch and minor versions is probably useful.

**Comment by ravage84** [comment]
I think CakeFest is a good time to re-discuss this. Conference attendees might be interested to participate as some might need to upgrade yet.

**Comment by markstory** [comment]
I've added upgrade notes to the 3.5 migration guide. Would it make sense to have minor or patch version upgrade instructions in the installation docs?

**Comment by jeremyharris** [comment]
Does `require` update dependencies the same way `update --update-with-dependencies` does? In some cases depending on requirements, I've seen an `update` command fail without explicitly telling it to update the deps, such as bake, migrations, etc.

**Comment by markstory** [comment]
The way I have it now composer won't update dependencies. We should probably tell people to use `--update-with-dependencies` as well.
