### ISSUE TITLE
Link to the Composer installation page

### ISSUE THREAD

**Issue by cake17** [cakephp/docs#4106]
As mentionned on the [download page of Composer](https://getcomposer.org/download/), we should probably add a link to the [composer installation instructions](https://getcomposer.org/download/).
Something like in the [symfony docs](http://symfony.com/doc/current/cookbook/composer.html):

```
Install Composer on Linux and Mac OS X
1. Run the installer as described in the official Composer documentation;
2. Execute the following command to move the composer.phar to a directory that is in your path:
    $ sudo mv composer.phar /usr/local/bin/composer

Install Composer on Windows
Download the installer from getcomposer.org, execute it and follow the instructions.
```

**Comment by ravage84** [comment]
A link to composer's docs is fine. We do not need to copy & paste their documentation.

Link could be added to:
2.x http://book.cakephp.org/2.0/en/installation/advanced-installation.html#installing-cakephp-with-composer
3.x http://book.cakephp.org/3.0/en/installation.html#installing-cakephp

**Comment by markstory** [comment]
:+1: to giving new folks more information on how to get started.

**Comment by cake17** [comment]
PR  #4113 up now
