### ISSUE TITLE
3.x validation docs should give a hint on how to validate "isTrue" and "isFalse"

### ISSUE THREAD

**Issue by ionas** [cakephp/docs#4147]
* http://book.cakephp.org/3.0/en/core-libraries/validation.html#core-validation-rules (none)
* http://api.cakephp.org/3.2/source-class-Cake.Validation.Validation.html#505 (none)
* http://api.cakephp.org/3.2/source-class-Cake.Validation.Validation.html#834 (none)

### Alternative
Change `public static function boolean($check)` to `public static function boolean($check, $validBooleanValueList = null)` which then inside sets given `$booleanList`.

**Comment by markstory** [comment]
`isTrue` and `isFalse` are not existing validators, are you hoping to have the documentation explain how to build them?

**Comment by htstudios** [comment]
Yes, it stems from a question on IRC. I'll add a reference from Validator::boolean()'s docblock to inList().

**Comment by inoas** [comment]
@markstory This is now basically resolved. I am not entirely happy but I think adding a passage to the written docs (cookbook) is not the way to go as it generally only points to the validation class. I will open a new issue targeting 4.x docs for a better way.

**Comment by ionas** [comment]
Closed as PR #4317 is up.
