### ISSUE TITLE
Layout: API anchor links are hidden by static/fixed menu

### ISSUE THREAD

**Issue by ionas** [cakephp/docs#4148]
http://api.cakephp.org/3.2/source-class-Cake.Validation.Validation.html#505 for instance is partially hidden at the top.

**Comment by andtxr** [comment]
If I click in the link, I can view the link as the first line of the content area using Chrome but if I force the page refresh, the anchor link stays hidden by the expanded top menu.

**Comment by ionas** [comment]
Safari is kind of okay. Firefox is not.

**Comment by andtxr** [comment]
Opera has the same behavior described previously.

**Comment by markstory** [comment]
The layout looks fine for me on Firefox (OSX) on both initial page load and forced refresh.

**Comment by markstory** [comment]
This issue was moved to cakephp/cakephp-api-docs#51
