### ISSUE TITLE
3.x beforeMarshal misses use statement

### ISSUE THREAD

**Issue by ionas** [cakephp/docs#4211]
http://book.cakephp.org/3.0/en/orm/saving-data.html#before-marshal

Which results in questions like this:
http://stackoverflow.com/questions/29012513/warning-incorrect-argument-passed-to-function/29013088

**Comment by markstory** [comment]
Is it `ArrayObject` that is causing the issues? We can just remove that typehint.

**Comment by ionas** [comment]
I did add use something\EntityInterface and use ArrayObject to solve the issue and kept the signature. Isn't that recommended?

*If it is, I can do the docs change, and you don't need to worry about that @markstory*

**Comment by markstory** [comment]
> I did add use something\EntityInterface and use ArrayObject to solve the issue and kept the signature. Isn't that recommended?

That is one option. The typehints are optional as none of the event hook methods are implemented in the base classes.

**Comment by markstory** [comment]
I added use statements in those examples.
