### ISSUE TITLE
::first and ::last method with custom url

### ISSUE THREAD

**Issue by eniacom** [cakephp/docs#4212]
I have override paginator functions but I noticed that "first" and "last" do not work as expected.
Abstract: I override default link generator method to create link with language prefix like this: mydomain.com/:language/:controller/:action/:params and all method work as expected.

If I invoke Paginator::first function with tow args (i.e. Paginator::first( '<<', [ 'url' => [ 'language' => 'en_US' ]]) ) does not work propertly.

Paginator::first method generate retuned value with:

```
$this->templater()->format('first', [
                'url' => $this->generateUrl(['page' => 1], $options['model']),
                'text' => $first
            ]);
My Solution and fix for cake core (insedie Paginator::first and ::last method) was:
$url = array_merge($options['url'], ['page' => 1]);
$this->templater()->format('first', [
                'url' => $this->generateUrl($url, $options['model']),
                'text' => $first
            ]);
```

I extend paginatorhelper class:

```
class MyPaginatorHelper extends PaginatorHelper
{
public function first($title = '', array $options = []) {
		$options['url']['language'] = $this->_getLanguage();
		return parent::first( $title, $options );
}
}
```

What do you think about?
It is good solution or not?
I should override enteire method?

**Comment by markstory** [comment]
This is not a help forum. The ticket tracker is reserved for possible bugs and feature enhancements to the CakePHP framework. If you are looking for help on how to implement a feature or to better understand how to use the framework correctly, please visit one of the following:
 
* [The CakePHP Manual](http://book.cakephp.org)
* [The CakePHP online API](http://api.cakephp.org)
* [CakePHP Official Forum](http://discourse.cakephp.org)
* [Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
* [Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than happy to help answer your questions.
 
Thanks!
