### ISSUE TITLE
UrlHelper named parameters

### ISSUE THREAD

**Issue by arilia** [cakephp/docs#4229]
http://book.cakephp.org/3.0/en/views/helpers/url.html#generating-urls

the second example says that you can create named parameters using UrlHelper.

I believed named parameters were removed in cake3, in fact if it try the example I get `/posts/view/?foo=bar` and not `/posts/view/foo:bar` (using cakephp 3.2.13)

I guess it is a documentation error and not a bug

**Comment by markstory** [comment]
Yes, named parameters were removed. I'll get the docs updated.

**Comment by arilia** [comment]
IMO it would be a good idea also to explain the difference (if any) to use

     "foo" => "bar"

rather than

    "?" => ["foo" => "bar"]

thanks

**Comment by markstory** [comment]
Pull request up now.

**Comment by manoj81290** [comment]
Hi,

I want create URL like bellow:
admin/users/account_id:1234

how can I create url like this.?
