### ISSUE TITLE
2.x/2.8.x Docs: phpredis requirements unclear

### ISSUE THREAD

**Issue by sgradix** [cakephp/docs#4273]
Nor Migration guide, nor docs nor composer.json mention the requirement of phpredis 2.2.3+. 

Since 2.8.0, the use of RedisEngine requires phpredis 2.2.3 

[https://github.com/cakephp/cakephp/blob/2.8.0/lib/Cake/Cache/Engine/RedisEngine.php#L117](url)

Redis->isConnected() was added in 2.2.3, so CakePhp 2.8.0+ using RedisEngine and phpredis 2.2.2 will break.

PhpRedis 2.2.2 is a very old version (2012) and infact cannot be found on PECL, but it can still be found between Github releases [https://github.com/phpredis/phpredis/releases/tag/2.2.2](url) and installed manually, and can still be found installed on some servers (happened to me :( )

It could be an improvements in the docs to clarify it, since previous versions of CakePhp actually work with 2.2.2.

**Comment by markstory** [comment]
I'll update the API docs to mention the requirement on 2.2.3
