### ISSUE TITLE
link to other sections/api when using "See"

### ISSUE THREAD

**Issue by danielzzz** [cakephp/docs#4299]
I am reading: http://book.cakephp.org/3.0/en/core-libraries/email.html
In the section Configuration Profiles for example there are lines like this one:
_'from': Email or array of sender. See Email::from()_

**Expected Behavior**
I would like all instances of "See XXX" to link to the actual source or other section of the docs

**Actual Behavior**
No link :(

thanks

**Comment by markstory** [comment]
You can add links the links you'd like to see. If you need help with sphinx syntax let me know.
