### ISSUE TITLE
RFC: Convention on references

### ISSUE THREAD

**Issue by inoas** [cakephp/docs#4315]
I am not yet sold on the idea but I wanted to throw it to the room:
What about having a convention that any header in the docs must be prepended by a reference - in future.

The reference should be {dashed path to document}-{slug or shortened slug of the chapter title, basically any unique identifier per document/page}. That way collisions are unlikely, and it is also easy to know about where a reference points to. Once a header changes, the reference would however stay. 

### Benefits
- Once you remove/merge whole chapters, references will be destroyed and you will know that linking broke.
- It is easy to reference any existing chapter simply through one single file edit on GH (easy to contribute)

I'd only suggest to do this forward going, e.g. any existing references would stay like they are and any chapters without references could be but would not need to be patched having a reference anchor

Docs: http://www.sphinx-doc.org/en/stable/markup/inline.html#cross-referencing-arbitrary-locations

**Comment by markstory** [comment]
What problems would having the references ahead of time solve? I see it adding more process/complexity to contributing but am not sure if it solves a problem you have run into.

**Comment by inoas** [comment]
I'll give it some more time but in general if the core's consensus is that there is little or no benefit, then it is not worth the additional work (in future)

**Comment by inoas** [comment]
As for the question itself:

* You have the references setup, you just go to the docs, click on github, see the reference, go to the file you want to edit and - well - reference the reference. No double file editing.

* The added convention makes sure that global reference name somehow make sense just by looking at them alone - so that you can always "from" the reference, backtrack to its target/anchor/source.

**Comment by inoas** [comment]
In case someone else likes this convention, just continue the discussion and I will open it up again.
