### ISSUE TITLE
Paginator query parameters are not documented.

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/docs#4318]
I noticed that the docs don't actually list the query parameters that are used by pagination in the request. Except, for the section about multiple pagination.

I'll open a PR for this, unless someone can point me to where this is documented.

I'll be adding descriptions for the query parameters `page`, `limit`, `sort` and `direction`.

Did I miss any?

**Comment by saeideng** [comment]
http://book.cakephp.org/3.0/en/views/helpers/paginator.html#configuring-pagination-options

**Comment by thinkingmedia** [comment]
@saeideng thank you! What we need is a link added to the places I went looking for those parameters.

**Comment by josegonzalez** [comment]
@thinkingmedia probably worth duplicating those in the pagination page.

**Comment by thinkingmedia** [comment]
@josegonzalez I thought there were more than that, but I couldn't remember them.

**Comment by markstory** [comment]
@thinkingmedia Could you add links to where you were expecting to find them?

**Comment by thinkingmedia** [comment]
@markstory sure, I'll do that tomorrow.
