### ISSUE TITLE
Saving complex types example doesn't work

### ISSUE THREAD

**Issue by mo86** [cakephp/docs#4320]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3
* Platform and Target XAMPP

### What you did
Read the section about saving complex types (http://book.cakephp.org/3.0/en/orm/saving-data.html#saving-complex-types) and tried the example code:

```
// In config/bootstrap.php
use Cake\Database\Type;
Type::map('json', 'App\Database\Type\JsonType');
```

First the namespace "**Cake\Database\Type**" is already defined in **config/bootstrap.php** by default and second `Type::map('json', 'App\Database\Type\JsonType');` results in "Class 'App\Database\Type\JsonType' not found". 
Just `Type::map('json');` works fine ;)

### Actual Behavior
Example code doesn't work.

**Comment by markstory** [comment]
The docs are correct. You have to create the `JsonType` as described in [this page](http://book.cakephp.org/3.0/en/orm/database-basics.html#adding-custom-database-types) which is linked to in the sentence above the code snippet.

**Comment by mo86** [comment]
Hmmmm still don't agree. 
First the referenced section in your post is about ADDING custom types. But the JSON type is already included in the standard cake installation. So the example is not about ADDING a new type, it is OVERWRITING an existing one.

Second is that the text "This functionality is achieved by using the custom types system. See the Adding Custom Types section to find out how to build custom column Types:" doesn't say that the following example is only for your own custom post types. Escpecially because they explain how to use the json type which is included in the core already. It's a little bit confusing.

And still the  namespace "Cake\Database\Type" is already defined in config/bootstrap.php by default.

**Comment by saeideng** [comment]
> First the referenced section in your post is about ADDING custom types. But the JSON type is already included in the standard cake installation. 

json type implemented in cake 3.3.x but docs is not up to date :)

**Comment by markstory** [comment]
@mo86 Which custom type would you like to see implemented then?

>And still the namespace "Cake\Database\Type" is already defined in config/bootstrap.php by default.

We try not to assume that people have left all the `use` statements in place. When we've not included them we get issues about classes not existing and the docs being 'incomplete'.

**Comment by mo86** [comment]
@saeideng okay I didn't know that. But a good reason to keep them up to date ;)
@markstory You wrote that the docs are correct and that the user has to create that json type first. Which is not true since the json type is now included by default. But that wasn't my point. What I meant is that the section about "Adding custom types" should be about CREATING a NEW custom post type (not JSON anymore).
The section about "Saving Complex Types" should be about how to use an existing "core" custom type and not about how to save a user created type. 

My solution proposal: We change the "Adding custom types" example to another type which is not included in core and in the "Saving Complex Types" we just explain how to use for example how to use the json type. Because in this case `Type::map('json');` is enough. I hope u all understand what I mean :)

**Comment by markstory** [comment]
> But that wasn't my point. What I meant is that the section about "Adding custom types" should be about CREATING a NEW custom post type (not JSON anymore).

Ok but what should that _new_ type be. I left the JSON type there as it is a simple example that fits in the documentation nicely, and people can easily understand.

**Comment by mo86** [comment]
Okay than let's just keep the "Adding custom types" example as it is :)
But than please change the example code in "Saving Complex Types" from `Type::map('json', 'App\Database\Type\JsonType');` to `Type::map('json');` because it's not about a new created one. Is that okay? Still got the feeling that we talk about different things ;D

**Comment by markstory** [comment]
@mo86 Sounds like you have changes in mind. Could you open a pull request with the changes you think should be done?

**Comment by ndm2** [comment]
@mo86 `Type::map('json');` doesn't do anything other than returning the possibly mapped classname for the `json` type!

**Comment by saeideng** [comment]
i think we can use 
```
//table class
use Cake\Database\Type;
class UsersTable extends Table
{
    public function initialize(array $config = [])
    {
        Type::map('json', 'App\Database\Type\JsonType');
```
instead of adding `Type::map('json', 'App\Database\Type\JsonType')` into `config/bootstrap.php`

**Comment by mo86** [comment]
Sorry for the chaos. I will try to explain it again.
My problem with the current [Saving Complex Types section](http://book.cakephp.org/3.0/en/orm/saving-data.html#saving-complex-types)  is that the example doesn't work if the user didn't add the JsonType from this [example ](http://book.cakephp.org/3.0/en/orm/database-basics.html#adding-custom-database-types) first. 
Just try it out. You will get the follwing error: Uncaught Error: **Class 'App\Database\Type\JsonType' not found in ...**. Which is obvious.
So in my opinion the example for Saving Complex Types should just use a Complex Type which is already included in core. For example JSON. But than we have to change `  Type::map('json', 'App\Database\Type\JsonType');` to `Type::map('json');`

I hope u all get what I am trying to explain :)

**Comment by ndm2** [comment]
@mo86 You don't have to touch `Type` at all if you're using built-in types, as mentioned, `Type::map('json')` doesn't do anything, it will simply act as a getter in that case, ie if you'd wanted to show the usage of internal types, then the `Type::map()` call should be removed alltogether.

**Comment by mo86** [comment]
Okay then I would like to remove the whole top section. At least th line `Type::map('json', 'App\Database\Type\JsonType');` if we want to keep the Namespace...
