### ISSUE TITLE
Use .gitattributes to fix language stats on github

### ISSUE THREAD

**Issue by inoas** [cakephp/docs#4328]
Currently this repo shows 44% JavaScript despite that it is mostly Sphinx Doc code aka reStructuredText.

Could this be fixed via https://github.com/github/linguist#overrides ?

**Comment by markstory** [comment]
I've never paid much attention to that, but it looks like [linguist knows about rst](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L4381-L4393). I suspect linguist is excluding our docs as that's a thing it does.

**Comment by inoas** [comment]
Yes it does. I went into correspondence and they consider reStructured text prosa (but simple html not). Not much we can/should do about it within this repo. I will discuss a bit with the github folks, because I think it de-evaluates community driven docs.
