### ISSUE TITLE
Exception: Shell class for "Schema" could not be found

### ISSUE THREAD

**Issue by imdad** [cakephp/docs#4338]
Hi,
Ref : https://github.com/cakephp/docs/blob/master/en/core-libraries/components/access-control-lists.rst
When I try to create ACL database trough the command given in documentation I get an error.

$ cake schema create DbAcl

Exception: Shell class for "Schema" could not be found. in [_<path to project folder>_/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php, line 305]

Thank You
SK Imdad

**Comment by dereuromark** [comment]
You should run it from root dir as `bin/cake ...` as documented. That might find the shells.
Just run `bin/cake` to confirm they are listed.

**Comment by markstory** [comment]
@dereuromark `master` branch is still the 2.x docs. The `3.x` branch is the default branch.
