### ISSUE TITLE
toDateTimeString not mentioned in the book

### ISSUE THREAD

**Issue by jimgwhit** [cakephp/docs#4340]
I was trying to figure out how to format a datetime in cakephp, and dug around in the code and found FormattingTrait. But he docs show this:
```
Formatting Strings

Chronos provides a number of methods for displaying our outputting datetime objects:

// Uses the format controlled by setToStringFormat()
echo $date;

// Different standard formats
echo $time->toAtomString();      // 1975-12-25T14:15:16-05:00
echo $time->toCookieString();    // Thursday, 25-Dec-1975 14:15:16 EST
echo $time->toIso8601String();   // 1975-12-25T14:15:16-05:00
echo $time->toRfc822String();    // Thu, 25 Dec 75 14:15:16 -0500
echo $time->toRfc850String();    // Thursday, 25-Dec-75 14:15:16 EST
echo $time->toRfc1036String();   // Thu, 25 Dec 75 14:15:16 -0500
echo $time->toRfc1123String();   // Thu, 25 Dec 1975 14:15:16 -0500
echo $time->toRfc2822String();   // Thu, 25 Dec 1975 14:15:16 -0500
echo $time->toRfc3339String();   // 1975-12-25T14:15:16-05:00
echo $time->toRssString();       // Thu, 25 Dec 1975 14:15:16 -0500
echo $time->toW3cString();       // 1975-12-25T14:15:16-05:00

// Get the quarter
echo $time->toQuarter();         // 4;
```
But toDateTimeString() I cannot find anywhere in the docs.  If there is it is well hidden.  It would be nice if all methods were in the docs.  If I hadn't used laravel prior which uses traits, I would have never found this, so how would someone brand new to cakephp.  Searched api as well could not find it. But why api when the others are listed right in the docs as above.

Side note I used like this:
```
echo "<td style=\"width:40px;\">" . $row->lastedit->toDateTimeString() . "</td>";
```
It seems to work fine with no needed "use" statement.

**Comment by markstory** [comment]
Why would you need a `use` statement after you have an instance of the object?

The API docs for CakePHP don't show that specific method as it is defined in [chronos](http://api.cakephp.org/chronos/1.0/class-Cake.Chronos.MutableDateTime.html#_toDateString). I'll add the missing method into the book with its friends.

**Comment by markstory** [comment]
Pull request up now.
