### ISSUE TITLE
Provide proper documentation for controllerSpy

### ISSUE THREAD

**Issue by rdac2012** [cakephp/docs#4361]
Hi!

I would like to ask if someone will provide various examples on how to utilize controllerSpy in integrationtest controller. 

Thank you very much.

**Comment by ravage84** [comment]
Refers to https://github.com/cakephp/cakephp/blob/3.3.5/src/TestSuite/IntegrationTestCase.php#L458

**Comment by markstory** [comment]
Its not really intended to be used as a public API method, which is one of the reasons its not documented with examples.
