### ISSUE TITLE
Little Cookbook improvement

### ISSUE THREAD

**Issue by bblaette** [cakephp/docs#4375]
http://book.cakephp.org/3.0/en/intro/conventions.html#model-and-database-conventions

How about replacing the example of 
  "People, BigPeople, and ReallyBigPeople" 
with something like 
  "Apples, ApplePies, People and WeThePeople", 
to clarify table name conventions ->
  "apples, apple_pies, people and we_the_people"?

Thank you

**Comment by markstory** [comment]
Thanks, the terms used in that page are pretty inconsistent. I'll fix that up so the narrative requires remembering fewer names.

**Comment by markstory** [comment]
Closing as a pull request is up that I think addresses the issues raised here.

**Comment by bblaette** [comment]
You guys are quick, respect! Thanks very much.
