### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by jamiel-sharief** [cakephp/docs#4378]
When trying to access the Email Component help, i get a 404 error.

http://book.cakephp.org/2.0/en/search.html?check_keywords=yes&area=default&q=email+component

Clicking on the first link takes me to
**http://book.cakephp.org/2.0/en/core-libraries/components/email.html** which gives the 404 error.

However Google shows **http://book.cakephp.org/2.0/en/core-utility-libraries/email.html** - The difference seems to be in CORE UTILITY or CORE LIBRARIES.

**Comment by markstory** [comment]
Sounds like a stale index error. I'll rebuild the search indexes.

**Comment by markstory** [comment]
Fixed :+1:
