### ISSUE TITLE
Importing Fixtures with a column of JsonType

### ISSUE THREAD

**Issue by arithran** [cakephp/docs#4433]
I've noticed a bug with Cake3 while importing a fixture that has a column of JsonType.

I've identified that the the toDatabase() function's first param $value is an array in this case, which the function doesn't account for and throws this exception.
vendor/cakephp/cakephp/src/Database/Type/StringType.php: line 57

It already accounts for is_string, is_object, is_scalar. Might just need an additional is_array check.

Cheers

**Comment by markstory** [comment]
How can someone reproduce the issue you're having?

**Comment by arithran** [comment]
Apologies for the late response. Here's how you can reproduce this issue.

1. Create a database field and make it  a Json Column type.
eg: $schema->columnType('preferences', 'json'); 
https://book.cakephp.org/3.0/en/orm/saving-data.html#saving-complex-types

2. Populate this table and Create a fixture based on this table.
3. Create a Unit Test and use this fixture.
4. Issue: It won't import this fixture.

I believe this is because when it tries to populate the test database it runs the toDatabase($value, Driver $driver) method, the $value param is n Array. It has checks for is_string, is_object, is_scalar but it may require an is_array check. @see https://api.cakephp.org/3.4/source-class-Cake.Database.Type.StringType.html#31-53

**Comment by markstory** [comment]
This sounds very similar to cakephp/cakephp#10396
