### ISSUE TITLE
Error: Database connection "Sqlserver" is missing, or could not be created.  In Tasks

### ISSUE THREAD

**Issue by tecnoydes** [cakephp/docs#4480]
I have a valid connection with SQL Server, and all controllers are working fine. But when I try to execute a command Task, I recive this error: **Error: Database connection "Sqlserver" is missing, or could not be created.** 
` 
        $this->loadModel('Client');
        $this->loadModel('User');

        // Repasar los clientes de SAGE que tengan informados datos de WS
        $clients = $this->Client->find('all', array(
            'conditions' => array(
                'Client.wsName <>' => '',
                'Client.wsPassword <>' => '',
                'Client.Email <>' => ''
            )
        ));
...
`
This project is in Cake 2.5.3, I also try upgrade to 2.9.2, but same error.

**Comment by ravage84** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!

**Comment by tecnoydes** [comment]
Sorry @ravage84 , I'm not looking for help. I'm trying to inform about an issue in ConnectionManager when working with models from a SQLServer connection.

I think this is a possible bug. Anyway, I try the forum.
Thanks.

**Comment by tecnoydes** [comment]
Sorry @ravage84 . Seems that the IT guy in the client desn't know the difference between php.ini for command CLI and php ini for Apache.
What a shame :_D
