### ISSUE TITLE
Flash Component & Helper - Escaping conflict

### ISSUE THREAD

**Issue by Holt59** [cakephp/docs#4483]
The [**Flash Component**](http://book.cakephp.org/3.0/en/controllers/components/flash.html) documentation says:

> By default, CakePHP escapes the content in flash messages for security reasons. If you are using any request or user data in your flash messages those are escaped and therefore safe to be printed. If you want to output HTML, you need to pass in an escape param and also adjust the templates to allow disabling escaping when such a param is passed.

While the [**Flash Helper**](http://book.cakephp.org/3.0/en/views/helpers/flash.html) documentation says:

> By default, CakePHP does not escape the HTML in flash messages. If you are using any request or user data in your flash messages, you should escape it with h when formatting your messages.

I know that the [default flash elements](https://github.com/cakephp/app/tree/master/src/Template/Element/Flash) do escape their content, but this is not managed by the Component or the Helper but rather inside the elements, meaning that if someone create a custom element without escaping, no "auto-escaping" is done. Also, I did not find any trace of escaping in the Flash Component, neither did I in the Flash Helper.

Maybe the documentation for the Flash Component is targeting the default flash elements, but this is not clear at all. Since this may raise some security "concerns", I think this is a relevant issue and that the the quote from the Flash component should be updated (maybe both quotes).

**Note:** I would have opened a pull-request myself if I were full aware of what was actually going on inside the flash component and helper, but since I do not, I'd rather rely on more reliable people!

**Comment by dereuromark** [comment]
The code and documentation was recently adjusted, but maybe the flash helper docs have been missed.
All elements escape by default, at least since recent CakePHP versions.
You can help fixing the documentation parts that are still wrong, that would be greatly appreciated.

**Comment by dereuromark** [comment]
Refs https://github.com/cakephp/app/pull/427
