### ISSUE TITLE
2.x alt. structure

### ISSUE THREAD

**Issue by josephzidell** [cakephp/docs#4512]
We're upgrading a legacy 1.x enterprise-size app to 2.x (I know, should do 3.x, but this is a first step). We're trying to go "vanilla" and not modify the core files. We're using `mod_rewrite` and also installed the framework with composer.

How to setup the constants to achieve below structure?

    www
        cake2 (base - will visit http://localhost/cake2)
            src
                Controller
                Model
                ...
                webroot
                    .htaccess
                    index.php (file with constants)
            Vendor
                cakephp
                    cakephp
                        ...
            .htaccess (sends requests to src/webroot/)

After playing with the constants in `webroot/index.php`, the framework loaded but got error

    Error: Cake2Controller could not be found.

**Comment by markstory** [comment]
If you're using composer to install cakephp, then you might want to look at the [composer installation](http://book.cakephp.org/2.0/en/installation/advanced-installation.html#installing-cakephp-with-composer) instructions.

**Comment by ravage84** [comment]
@josephzidell I can recommend you https://github.com/FriendsOfCake/app-template which I personally use in a customized form.

Please re-open this issue, if you feel the documentation lacks something about the topic or directly open a PR with some improvements.
