### ISSUE TITLE
Cookbook section on TestSuites for 3.x has leftover bits from 2.x

### ISSUE THREAD

**Issue by ADmad** [cakephp/docs#4519]
_From @tharlinsmith on December 7, 2016 22:20_

This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)
* [x] documentation issue

* CakePHP Version: 3.x Cookbook
* Platform and Target: 

### What you did
The 3.x section on creating test suites, http://book.cakephp.org/3.0/en/development/testing.html#creating-test-suites, refers to the CakeTestSuite class which is from 2.x.  The 3.x version is Cake\TestSuite\TestSuite.  It also uses an example of "TESTS" concatenated with "Case/Model", but that should be "TestCase/Model/Table" for the current platform.

_Copied from original issue: cakephp/cakephp#9852_

**Comment by ADmad** [comment]
_From @ravage84 on December 9, 2016 12:18_

Please [open an issue in the correct repository](https://github.com/cakephp/docs/issues).
This is about the framework itself. [cakephp/docs](https://github.com/cakephp/docs/) is about the Cookbook.

**Comment by cake17** [comment]
PR #4521 has been merged, this PR can be closed
