### ISSUE TITLE
CakePHP

### ISSUE THREAD

**Issue by GeorgeBush91** [cakephp/docs#4527]
I'm new user. How do i download the app CakePhp

**Comment by inoas** [comment]
Read: http://book.cakephp.org/3.0/en/index.html
Then: http://book.cakephp.org/3.0/en/installation.html
Then: http://book.cakephp.org/3.0/en/quickstart.html

e.g. via composer install, it is covered in the docs.

IMHO, you should use a linux/unix-style operation system for the server running cakephp.
For example:
https://github.com/FriendsOfCake/awesome-cakephp#development-environment
e.g. https://github.com/alt3/cakebox
and/or: https://puphpet.com/
and/or: https://www.youtube.com/watch?v=PmOMc4zfCSw

This is not a help channel, try stackoverflow, irc, slack, etc.

**Comment by markstory** [comment]
Closing as you've got some good links to start off with. If you get stuck please join the slack group and people should be able to help you further.

**Comment by GeorgeBush91** [comment]
Installed successfully. thanks for the help
