### ISSUE TITLE
Incorrect examples in development/errors.html

### ISSUE THREAD

**Issue by chinpei215** [cakephp/docs#4543]
1\.  http://book.cakephp.org/3.0/en/development/errors.html#creating-your-own-error-handler
[_displayError()](https://github.com/cakephp/cakephp/blob/855c4d114b0ac42169b1cb6237f9dcaefc5f4408/src/Error/BaseErrorHandler.php#L41) and [_displayException()](https://github.com/cakephp/cakephp/blob/855c4d114b0ac42169b1cb6237f9dcaefc5f4408/src/Error/BaseErrorHandler.php#L52) declared as `@return void`. Returning string doesn't make sense.

2\. http://book.cakephp.org/3.0/en/development/errors.html#changing-fatal-error-behavior
[handleFatalError()](https://github.com/cakephp/cakephp/blob/855c4d114b0ac42169b1cb6237f9dcaefc5f4408/src/Error/BaseErrorHandler.php#L205) is declared as `@return bool`. Returning string doesn't make sense.

**Comment by markstory** [comment]
Looks like the docs were not correctly updated from the 2.x days.

**Comment by chinpei215** [comment]
Half-soled in #4694.
