### ISSUE TITLE
Incorrect examples of MapReduce

### ISSUE THREAD

**Issue by chinpei215** [cakephp/docs#4545]
http://book.cakephp.org/3.0/en/orm/retrieving-data-and-resultsets.html#modifying-results-with-map-reduce

### 1. [Line 1089](https://github.com/cakephp/docs/blame/a528eeb6a80c038db05f434466475756b2bb311c/en/orm/retrieving-data-and-resultsets.rst#L1089)
Wrong argument order of `stripos()`. It should be `stripos($article['body'], 'cakephp')`.

### 2. [Line 1110](https://github.com/cakephp/docs/blame/a528eeb6a80c038db05f434466475756b2bb311c/en/orm/retrieving-data-and-resultsets.rst#L1110)
Wrong variable name. `$articlesByStatus` should be `$wordCount` or something.

### 3. [Line 1114](https://github.com/cakephp/docs/blame/a528eeb6a80c038db05f434466475756b2bb311c/en/orm/retrieving-data-and-resultsets.rst#L1114)
The `toArray()` should be called after the `mapReduce()`, because the document says:

> This could return a very large **array**

### 4. [Line 1134](https://github.com/cakephp/docs/blame/a528eeb6a80c038db05f434466475756b2bb311c/en/orm/retrieving-data-and-resultsets.rst#L1134)
I am guessing that `source_target_id` is a typo of `source_user_id`.

### 5. [Line 1149](https://github.com/cakephp/docs/blame/a528eeb6a80c038db05f434466475756b2bb311c/en/orm/retrieving-data-and-resultsets.rst#L1149)
Incorrect use of `emit()`. Unlike `emitIntermediate()`, `emit()` overwrites the previous item if it is called with the same key. Therefore, the example code never returns 2D array like [this](https://github.com/cakephp/docs/blame/a528eeb6a80c038db05f434466475756b2bb311c/en/orm/retrieving-data-and-resultsets.rst#L1163-L1167). The correct example will be like the following:

```php
$reducer = function ($friendsList, $user, $mr) {
    $fakeFriends = []; // Prepare an array

    $friends = array_count_values($friendsList);
    foreach ($friends as $friend => $count) {
        if ($count < 2) {
            $fakeFriends[] = $friend; // Push friend's ID to the array
        }
    }

    if ($fakeFriends) {
        $mr->emit($fakeFriends, $user); // Return the array if not empty
    }
}
```

### 6. The logic to find fake friends
Regarding to the example of finding fake friends, I think that not only the implementation, but also the logic is incorrect. As I mentioned above, If my thought is correct, the correct code of `$mapper` will be the following:
```php
$mapper = function ($rel, $key, $mr) {
    $mr->emitIntermediate($rel['source_user_id'], $rel['target_user_id']);
    $mr->emitIntermediate($rel['target_user_id'], $rel['source_user_id']);
};
```

If 1 follows 2, after the first call of `emitIntermediate()`, it will make an internal array like the following:
```php
[
    2 => [ 1 ],
]
```

After the second call, the internal array will be:
```php
[
    2 => [ 1 ],
    1 => [ 2 ],
]
```
And if 1 follows 3 and 4 too, the internal array will be:
```php
[
    2 => [ 1 ],
    1 => [ 2, 3, 4 ],
    3 => [ 1 ],
    4 => [ 1 ],
]
```

And if 3 follows 1 back, the internal array will be:
```php
[
    2 => [ 1 ],
    1 => [ 2, 3, 4, 3 ],
    3 => [ 1, 1 ],
    4 => [ 1 ],
]
```

If the above array is passed to the correct `$reducer`, it will make an array like the following:
```php
[
    1 => [ 2, 4 ],
    2 => [ 1 ],
    4 => [ 1 ],
]
```

The document says:

> The resulting array means, for example, that user with id 1 follows users 2 and 4, but those do not follow 1 back.

It is seemingly correct, but actually wrong. See `2 => [ 1 ]`. It apparently doesn't mean that **user with id 2 follows user 1, but user 1 doesn't follow 2 back**. Although the logic can find users who are not following each other, it cannot distinguish which user is following. The document says too much.

I have an idea to fix the logic:

```php
$mapper = function ($rel, $key, $mr) {
    // Prepend `-` to distinguish which user is following.
    $mr->emitIntermediate(-$rel['source_user_id'], $rel['target_user_id']); 
    $mr->emitIntermediate($rel['target_user_id'], $rel['source_user_id']);
};
```

```php
$reducer = function ($data, $user, $mr) {
    $fakeFriends = [];

    foreach ($data as $friend) {
        // If the negative ID is not found, the user with the ID is a fake friend.
        if ($friend > 0 && !in_array(-$friend, $data)) {
            $fakeFriends[] = $friend;
        }
    }

    if ($fakeFriends) {
        $mr->emit($fakeFriends, $user);
    }
};
```

What do you think?

**Comment by josegonzalez** [comment]
👍

**Comment by markstory** [comment]
All the suggested changes sound good to me.

**Comment by chinpei215** [comment]
Thank you for your comment and reaction. I'll send a pull request next year if no one does it earlier than me.

**Comment by chinpei215** [comment]
Pull request up now.
