### ISSUE TITLE
wrong sample

### ISSUE THREAD

**Issue by saeideng** [cakephp/docs#4552]
we could not use limit() in sub query in contain()
below sample in https://github.com/cakephp/docs/blob/3.0/en/orm/retrieving-data-and-resultsets.rst
```
$query = $articles->find()->contain([
    'FirstComment' => [
            'strategy' => 'select',
            'queryBuilder' => function ($q) {
                return $q->order(['FirstComment.created' =>'ASC'])->limit(1);
            }
    ]
]);
```
other Issue : https://github.com/cakephp/docs/issues/4057

**Comment by othercorey** [comment]
What should this be?

**Comment by ADmad** [comment]
In order to achieve the desired result one needs to use a subquery similar to this https://gist.github.com/ADmad/0a451d837f019edf3447.

**Comment by othercorey** [comment]
Using a `limit()` clause in the queryBuilder query seems to work.

**Comment by othercorey** [comment]
Moved discussion to PR.
