### ISSUE TITLE
ci.cakephp.org (docs CI) Build results can't be viewed (Required Auth)

### ISSUE THREAD

**Issue by tenkoma** [cakephp/docs#4555]
[Documentation](http://book.cakephp.org/3.0/en/contributing/documentation.html)

"Various builds" on this page is linked to http://ci.cakephp.org/, but authentication is required now. Is it better to replace the link destination with https://travis-ci.org/cakephp/docs ?

**Comment by josegonzalez** [comment]
We should just remove that bit, right @markstory ? Don't know if we need to have it exposed.

**Comment by markstory** [comment]
I'll remove that bit from the docs. I don't think there is much value in exposing our CI tooling.

**Comment by markstory** [comment]
Pull request up now.
