### ISSUE TITLE
"Allowing Empty Fields" chapter

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/docs#4583]
"Validation" page, chapter "Allowing Empty Fields", [here](https://book.cakephp.org/3.0/en/core-libraries/validation.html#allowing-empty-fields):

> create The field is required when validating a create operation.
> update The field is required when validating an update operation.

It seems to have been reported examples of the previous chapter ("Requiring Field Presence").

Then, the example is correct, but it can be confusing:

```
$validator->allowEmpty('published')
    ->notEmpty('title', 'A title is required')
    ->notEmpty('body', 'A body is required', 'create')
    ->allowEmpty('header_image', 'update');
```

"is required" suggests that the field is required. 

Just as well:

```
$validator->allowEmpty('published')
    ->notEmpty('title', 'The title can not be empty')
    ->notEmpty('body', 'The body can not be empty', 'create')
    ->allowEmpty('header_image', 'update');
```

**Comment by markstory** [comment]
Is the problem that the create/update modes use the 'is required' wording for `allowEmpty()`? I'm not entirely clear on what is confusing to you here.

**Comment by mirko-pagliai** [comment]
Yes. When compared with the previous chapter ("Requiring Field Presence"), you'll see that it is quite confusing.

`requirePresence()`:
> false The field’s presence is not required.
> create The field’s presence is required when validating a create operation.
> update The field’s presence is required when validating an update operation.

`notEmpty()`
> false The field is not allowed to be empty.
> create The field is required when validating a create operation.
> update The field is required when validating an update operation.

As you can see, the explanation for `false` is instead rather clear.
Why not use the same formula? Eg.:

`notEmpty()`
> false The field is not allowed to be empty.
> create The field is not allowed to be empty when validating a create operation.
> update The field is not allowed to be empty when validating an update operation.

The examples are even more confusing. Example for `requirePresence()`:
```
$validator->requirePresence([
    'author_id' => [
        'mode' => 'create',
        'message' => 'An author is required.',
    ],
    /// ...
]);
```
Example for `allowEmpty()`:
```
$validator
    ->notEmpty('title', 'A title is required');
```

**Comment by markstory** [comment]
OK. I'll find a better way to express the constraint that `notEmpty()` creates.
