### ISSUE TITLE
Contributing to 2.x should have an updated intro

### ISSUE THREAD

**Issue by JelmerD** [cakephp/docs#4629]
I just pulled in the 2.x of Cakephp in order to resolve an issue/try to recreate the bug in a test, and therefore I'm trying to run Cakephp with just php and phpunit, as described in https://book.cakephp.org/2.0/en/contributing/code.html#initial-setup.

But when installing cakephp on windows (as I don't want to setup a complete Vagrant box for this) I found that the docs are not complete/correct/easy to understand.

I suggest the following changes:

- Tell me which php extensions should be enabled at least, as I had to do a lot of trial and error;
- instead of saying which phpunit version I need, tell me that composer is required and instruct me to install the dependencies via composer. I could imagine this, but because the docs state I need a specific PHPUnit version, I installed it manually and then it still didn't work. This is partly because the PHPUnit docs are not very clear when you're not familiar with a manual installation on Windows.
- Tell me I need MySQL installed, this is also a minor thingy and it came up in my head, but because the docs didn't say... I didn't think it was a requirement. (Or Sqlite, just got that working, would be even better)

You could say: well, it's easy, don't need all those instructions. But I'm new to development on the Cake core, so it's not easy for me and it gave me a headache to just get started.

**Comment by josegonzalez** [comment]
Would you like to prepare a pull request with these changes?

**Comment by markstory** [comment]
I've put up a pull request to remove obviously wrong (to me) information. Any additional help is appreciated.

**Comment by JelmerD** [comment]
I will once I have the time for it. Thanks for the quickfix @markstory

**Comment by ravage84** [comment]
@JelmerD could you have a look, please?

**Comment by saeideng** [comment]
markstory's  PR merged about 2 years ago 
we can close now
