### ISSUE TITLE
Translations : follow recent modifications (direct commits)

### ISSUE THREAD

**Issue by HavokInspiration** [cakephp/docs#4632]
Follow these commits : 

# FR

### 3.0

Nothing

### 3.next

https://github.com/cakephp/docs/commit/94db8289a0d31d380d23d324c9a1c33665abbe53
https://github.com/cakephp/docs/commit/7acbcfdecd6165b93057790df68fee3c69000e01

### master (2.X)

Nothing

**Comment by HavokInspiration** [comment]
I'm going to keep this thread open. If any of you guys directly merge directly without a PR, would you mind adding the commits hashes so it's easier for docs translator to keep in sync ?

Thanks a lot !

**Comment by chinpei215** [comment]
Removed f393e6de98a8b34b1772bce97becda8fff23239a from JA.

**Comment by okinaka** [comment]
Removed JA.
