### ISSUE TITLE
Everything about contain in its own chapter

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/docs#4651]
This is a very simple request, but can we have a section in the manual just about using contain. Right now it's kind of difficult to find.

For example, I needed to look up sorting with a contain. 

https://book.cakephp.org/3.0/en/orm/retrieving-data-and-resultsets.html#sorting-contained-associations

Sorting for contained is filed under Eager Loading Associations. It doesn't appear to even have it's own heading.

Containable had it's own chapter in the Cake 2 book.

https://book.cakephp.org/2.0/en/core-libraries/behaviors/containable.html

I can remember easily finding this back in my 2.0 days.

**Comment by markstory** [comment]
One reason containable had its own chapter was that it was a standalone behaviour. In 3.x the contain key is one of a few different ways you can eager load relations. Would you also move the docs for other relation loading features into thia new chapter?

**Comment by thinkingmedia** [comment]
That's like documenting how use buttons under device drivers, because you need a mouse to click them.

I understand the logic, but contains is a complex beast. When I use it I'm not thinking about eager loading. I'm trying to remember what the name of that array key is to set the join type. It takes some searching and luck to find it.

**Comment by markstory** [comment]
Aren't join types defined in the association configuration though?

**Comment by inoas** [comment]
Interim: https://github.com/cakephp/docs/pull/4652
I think eager loading can also be done via matching() and leftJoinWith(), so I opted for that chapter header "via contain".

**Comment by thinkingmedia** [comment]
@inoas thanks.
@markstory for performance reasons I set all mine to SELECT, and then manually tune it when using contain. I have tables with 1+ million records so I have to be careful using joins as I quickly run out of memory on my MySQL box.
