### ISSUE TITLE
Docs Bug: In the method argument, comma and default value are swapped

### ISSUE THREAD

**Issue by tenkoma** [cakephp/docs#4670]
occurrence example: 

* [Creating Nested Lists](https://book.cakephp.org/3.0/en/views/helpers/html.html#Cake\View\Helper\HtmlHelper::nestedList)
* [Cake\View\Helper\FormHelper::inputs(array $fields =, \[\]$options =\[\])](https://book.cakephp.org/3.0/en/views/helpers/form.html#Cake\View\Helper\FormHelper::inputs)

Rendered Image:

<img width="764" alt="defect-image" src="https://cloud.githubusercontent.com/assets/16202/22625358/9115586e-ebd7-11e6-9c82-16d41802ca28.png">

Occurrence condition (My expectation):

* This is not typo in source. Source is collect
  * example: https://github.com/cakephp/docs/blame/3.0/en/views/helpers/html.rst#L575
* Occurs when the default value is an empty array with short array syntax
  * Case that has not occurred: [Cake\View\Helper\HtmlHelper::tableHeaders(array $names, array $trOptions = null, array $thOptions = null)](https://book.cakephp.org/3.0/en/views/helpers/html.html#Cake\View\Helper\HtmlHelper::tableHeaders)
* This is not caused by CSS

**Comment by markstory** [comment]
Looks like this might be an issue with [php sphinxdomain](https://github.com/markstory/sphinxcontrib-phpdomain). I can take a look.

**Comment by boarnasia** [comment]
I've made a pull request for this problem.
Please check, at your convenience.

https://github.com/markstory/sphinxcontrib-phpdomain/pull/4

**Comment by markstory** [comment]
Thanks @boarnasia. I'm going to close this issue as the upstream fix will solve our problems as well.
