### ISSUE TITLE
Wrong info in API 

### ISSUE THREAD

**Issue by ironbone** [cakephp/docs#4715]
In 
`https://api.cakephp.org/3.4/class-Cake.View.Helper.TimeHelper.html`
and also in the previous version in the description of a lot of functions there is: 
```
Returns

boolean 
True if datetime string is today
```
What is for example not true for:
`isPast()` 
or 
`isFuture()`

**Comment by ravage84** [comment]
Proposed fixes to the doc blocks in https://github.com/cakephp/cakephp/pull/10239
