### ISSUE TITLE
Regular DNS issues on cakephp.org

### ISSUE THREAD

**Issue by aaronstillwell** [cakephp/docs#4793]
Hi,

is anyone else facing regular issues accessing cakephp.org domains (including book.cakephp.org and api.cakephp.org)? In Chrome, the browser automatically redirects after being unable to connect, while Firefox simply fails. I'm therefore often forced into having to view the online docs through Chrome.

I've been seeing these issues over the last month and a half with no end in sight after having been brought into an existing CakePHP project.

**Comment by phpnut** [comment]
@aaronstillwell We are in the process of moving our DNS. We experienced an outage last week, before that I was not aware of any other DNS related problem.

**Comment by phpnut** [comment]
DNS has been migrated to a new server. Closing this ticket. Reopen a new ticket if you notice DNS failing again. Thanks

**Comment by aaronstillwell** [comment]
Cheers @phpnut - haven't seen any issues since.
