### ISSUE TITLE
After merging the pull request docs doesn't update

### ISSUE THREAD

**Issue by Leo240** [cakephp/docs#4827]
Earlier if pull request was merged, documentation on the site had updated in course of time. Now it doesn't  - is it normal?

**Comment by markstory** [comment]
I'll take a look. The last few jenkins jobs have failed.

**Comment by Leo240** [comment]
Ok.

**Comment by markstory** [comment]
Builds are fixed now. I'm going to update our jenkins jobs so we're notified of failures sooner.

**Comment by saeideng** [comment]
> Builds are fixed now.

@markstory  not fixed 
there are problem now

**Comment by markstory** [comment]
@saeideng Looks like our jenkins has run into some permissions issues that are preventing jobs from starting/

**Comment by markstory** [comment]
Fixed again.

**Comment by saeideng** [comment]
Not fixed again

https://github.com/cakephp/docs/pull/4839

**Comment by josegonzalez** [comment]
I just looked, seems as though we have some sort of encoding error in creating the english pdf.

**Comment by markstory** [comment]
I will get that fixed.

**Comment by markstory** [comment]
Fixed again. Our latex packages don't support persian characters, and the recent updates to the Time examples caused the builds to break.

**Comment by saeideng** [comment]
see again :laughing: 
https://book.cakephp.org/3.0/en/orm/query-builder.html
and
https://github.com/cakephp/docs/edit/3.0/en/orm/query-builder.rst
is not sync

**Comment by saeideng** [comment]
related to 
https://github.com/cakephp/docs/blame/3.0/en/orm/query-builder.rst#L1114-L1116
