### ISSUE TITLE
3.x migration guide 404 missing stylesheet

### ISSUE THREAD

**Issue by inoas** [cakephp/docs#4832]
Ref: https://book.cakephp.org/3.0/en/appendices/notexisting.html

**Comment by markstory** [comment]
Not sure how easy this is going to be to fix. Unfortunately sphinx doesn't make it very easy to get absolute paths for assets which makes having 404 pages work everywhere a bit hard. One option could be to change the URL rewrite to be a redirect but that isn't how 404 pages typically work.

**Comment by inoas** [comment]
If there is a dedicated 404 page in sphinx, maybe it can just have the stylesheet inlined, if sphinx can do that?! Or load it directly from https://book.cakephp.org (full URL)?

**Comment by markstory** [comment]
> If there is a dedicated 404 page in sphinx, maybe it can just have the stylesheet inlined

There isn't. sphinx just generates static HTML.

**Comment by othercorey** [comment]
Considering that 404 doesn't work properly at all at the moment, might as well redirect to the summary page of the select version for html requests.
