### ISSUE TITLE
Complete example of `afterFind()` (2.x)

### ISSUE THREAD

**Issue by josephzidell** [cakephp/docs#4844]
### What you did
Try to make a fully functional `afterFind()` callback, and spent way too much time.

### What happened
Results came back in varying formats, and the callback wasn't getting run on my data.

### What you expected to happen
Can you please write a 100% complete, fully functional example of `afterFind()` that takes every possible results format into account? Stackoverflow and the Google provide no full example. This would help me and countless others.

Thanks!

**Comment by natzar** [comment]
1 hour  and a half wasted ...

**Comment by saeideng** [comment]
you can define it beside other callbacks , `beforeFInd()`/ `beforeSave()`/ 'afterSave()` withing Model class 
Docs : https://book.cakephp.org/2.0/en/models/callback-methods.html#afterfind
