### ISSUE TITLE
Example code for a try/catch + transaction combination

### ISSUE THREAD

**Issue by mo86** [cakephp/docs#4867]
I would like to add an example code snippet to the documentation where we explain the best practise for a complex saving operation using a transaction and a try/catch block.

For example I want to do 2 inserts into different tables. But the second insert should only be done when the first insert was done without errors.

My approach:
```

try {
            $conn = ConnectionManager::get('default');
            //start transaction
            $conn->begin();

            $table1 = TableRegistry::get('Table1');
            $entity1 = $table1->newEntity();
            $entity1->bar = 'foo';

            //validate
            if ($entity1->errors()) {
                throw new \Exception(__('Error ....'));
            }
            if (!$table1->save($entity1)) {
                throw new \Exception(__('Error ....'));
            }

            $table2 = TableRegistry::get('Table2');
            $entitiy2 = $table2->newEntity();
            $entitiy2->foo = 'bar';

            //validate
            if ($entitiy2->errors()) {
                throw new \Exception(__('Error ....'));
            }
            if (!$table2->save($entitiy2)) {
                throw new \Exception(__('Error...'));
            }
            $conn->commit();
        } catch (\Exception $ex) {
            //error handling...
            $conn->rollback();
        }
    }`
```
What do you think about? Is there a better approach? I would like to hear your opinion :)

**Comment by markstory** [comment]
Why not use `$connection->transactional()`? It does pretty much exactly what you have in your code, but doesn't require a try/catch.

**Comment by mo86** [comment]
Thx I didnt know about that. But I still think it would be great to add a more complex saving example with two or more models/tables and the use of the last insert id as a foreign key for the following tables inside a transaction. 
Maybe we could add a "best practises" category to the documentation where we show how to solve common problems in the "cake way". I mean a collection of example code with a short summary. Just an idea.

**Comment by markstory** [comment]
I am not sure a best practices section would age well. I have seen them just collect all sorts of information that could fit into the documentation relevant to each sample.

Normally you shouldn't need to use last insert id. The ORM can automatically connect foreign key data together.

**Comment by saeideng** [comment]
>Thx I didnt know about that. But I still think it would be great to add a more complex saving example with two or more models/tables and the use of the last insert id as a foreign key for the following tables inside a transaction.

```php
            $result=$this->Users->connection()->transactional(function(){
                    if ($this->Users->save($user)) {
                                    // .....
                                    $profile->user_id = $user->id;
                                    if ($this->Users->Profiles->save($profile)) {
                                               //other logic
                                                return true;
                                    }
                    }
                    return false;
            });
            if($result){
                    $this->Flash->success(__('....'));
                        return $this->redirect(['action' => 'index']);
                } else {
                        $this->Flash->error(__('........'));
            }
```

**Comment by saeideng** [comment]
I think docs is clear enough
