### ISSUE TITLE
[cookbook] response->withFile() which isn't in 3.0

### ISSUE THREAD

**Issue by jarekgol** [cakephp/docs#4869]
Hi, there some functions in 3.4 cookbook that don't work in 3.0 and they aren't in 3.0 API
here is an example https://book.cakephp.org/3.0/en/controllers/request-response.html#Cake\Http\Response::withFile

I suggest add this chef's hat on green background and appropriate info.
Jarek

**Comment by markstory** [comment]
I'll add an example of sending a file in earlier versions.

**Comment by markstory** [comment]
Pull request up now.
