### ISSUE TITLE
3.4: What about $request->url?

### ISSUE THREAD

**Issue by 2ndGAB** [cakephp/docs#4881]
Is it now $request->getUrl()?

**Comment by dereuromark** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!

**Comment by dereuromark** [comment]
There is a getUri() method now and also submethods on that one.

**Comment by 2ndGAB** [comment]
I ask the question to potentially improve the doc as I didn't find it in the the migration guide.
And I didn't think to look for getUri instead of getUrl.

**Comment by dereuromark** [comment]
OK, let's try to add more migration info then.

**Comment by markstory** [comment]
The `url` property of the request is not currently deprecated. That might change in 3.5 though.
