### ISSUE TITLE
3.4: Response::header()

### ISSUE THREAD

**Issue by 2ndGAB** [cakephp/docs#4882]
This sentence looks strange for [Response](https://book.cakephp.org/3.0/en/appendices/3-4-migration-guide.html#request-response-deprecations):

> Response::header() is deprecated. Use getHeaderLine(), hasHeader() or Response::getHeader() instead.

Should be Response::setHeader() or withHeader() no?

**Comment by markstory** [comment]
Depends on whether you are using the read or write mode for `header()`.

**Comment by 2ndGAB** [comment]
I agree @markstory but the migration guide doesn't talk about `Response::withHeader()`.

**Comment by markstory** [comment]
@2ndGAB I'll get that fixed up.

**Comment by markstory** [comment]
Actually, we've not recommended any of the `withX` methods in the deprecation notes. The reasoning there is that using the `withX` methods requires changing more than just the method name.

Going to close this as the 'Adopting Immutable Responses` section has examples of how to update header() and change the code to work with immutable object patterns.
