### ISSUE TITLE
3.4: We have to modify Application.php?

### ISSUE THREAD

**Issue by 2ndGAB** [cakephp/docs#4886]
It seems we have to modify `Application.php` and `webroot/index.php` to use middleware instead of `DispatchFactory` , if I well understood, and maybe modify `bootstrap.php` to remove:

     /**
     * Connect middleware/dispatcher filters.
     */
    DispatcherFactory::add('Asset');
    DispatcherFactory::add('Routing');
    DispatcherFactory::add('ControllerFactory');

Right?
If yes, it should be added to the doc.

And also remove [this](https://book.cakephp.org/3.0/fr/core-libraries/internationalization-and-localization.html#selection-automatique-de-locale-basee-sur-les-donnees-de-requetes) if it's deprecated.

**Comment by markstory** [comment]
> It seems we have to modify Application.php and webroot/index.php to use middleware instead of DispatchFactory

Yes. The app skeleton has already been updated. Part of [the 3.3. migration notes was to replace webroot/index.php from the app template](https://book.cakephp.org/3.0/en/appendices/3-3-migration-guide.html#psr-7-middleware-support-added).

I don't write french well enough to update that translation, but I can update the english documentation.

**Comment by 2ndGAB** [comment]
Soory, I though it came with 3.4. I'm a bit in late

**Comment by wggwcn** [comment]
waiting for 3.4

**Comment by markstory** [comment]
Closing as the gaps in the documentation raised here have been addressed.
