### ISSUE TITLE
App.base config key is not documented for 2.x

### ISSUE THREAD

**Issue by liviascapin** [cakephp/docs#4895]
I found this config key while debugging and found out it wasn't documented anywhere in the 2.x docs.

This key is used in the dispatcher and router and also heavily used in various tests.

https://github.com/cakephp/cakephp/blob/2.9.7/lib/Cake/Routing/Dispatcher.php#L56
https://github.com/cakephp/cakephp/blob/2.9.7/lib/Cake/Routing/Router.php#L849

**Comment by liviascapin** [comment]
The ``base`` parameter of Router::url() might be related: https://api.cakephp.org/2.9/class-Router.html#_url

**Comment by markstory** [comment]
Any chance you'd be able to do a pull request to add the missing documentation?

**Comment by ravage84** [comment]
@markstory ``The base directory for the application``, taken from [Dispatcher.php](https://github.com/cakephp/cakephp/blob/2.9.7/lib/Cake/Routing/Dispatcher.php#L52).
But that still does not explain when to set it in the **configuration** or what pitfalls to look for.

At best, I'd like to have something like we have with ``fullBaseUrl`` in [core.php](https://github.com/cakephp/cakephp/blob/2.x/app/Config/core.php#L114-L121).

**Comment by ravage84** [comment]
Closinga s pull request #5024 is open.
