### ISSUE TITLE
Should App.fullBaseUrl in 2.x contain the base path, too?

### ISSUE THREAD

**Issue by liviascapin** [cakephp/docs#4896]
Should ``App.fullBaseUrl`` in 2.x contain the base path, too, if the application runs in a subdirectory? The documentation does not make it fully clear.

**Comment by markstory** [comment]
Yes.

**Comment by ravage84** [comment]
@liviascapin may be you can send a PR improving the existing docs?

**Comment by liviascapin** [comment]
@markstory I just found this: https://github.com/cakephp/cakephp/pull/1718 and the way I understand it (and the issue it references), setting ``App.fullBaseUrl`` with base path causes issues in web context (which I am experiencing right now) and we should set ``App.fullBaseUrl`` to just the host and set ``base`` to the subdirectory instead? Or did I get this wrong?

**Comment by markstory** [comment]
@liviascapin You're right. I've not used fullBaseUrl or base in years. But that pull request looks like it is still relevant.

**Comment by liviascapin** [comment]
Okay :) Thank you! I will send a PR with suggestions to improve the docs for ``App.fullBaseUrl`` and ``App.base`` (#4895) within the next few days.

**Comment by ravage84** [comment]
@ndm2 has provided a promising fix in cakephp/cakephp#10517
