### ISSUE TITLE
Table to TableSchema in Docs

### ISSUE THREAD

**Issue by Theaxiom** [cakephp/docs#4901]
Due to this change 5 months ago: https://github.com/cakephp/cakephp/commit/703260adac96694d1bc41f779c8535a16acb116c

There are some issues in the documentation, such as the following example in: https://book.cakephp.org/3.0/en/orm/saving-data.html#saving-complex-types

## Current
```
// In config/bootstrap.php
use Cake\Database\Type;
Type::map('json', 'App\Database\Type\JsonType');

// In src/Model/Table/UsersTable.php
use Cake\Database\Schema\Table as Schema;

class UsersTable extends Table
{

    protected function _initializeSchema(Schema $schema)
    {
        $schema->columnType('preferences', 'json');
        return $schema;
    }

}
```

## Expected
```
// In config/bootstrap.php
use Cake\Database\Type;
Type::map('json', 'App\Database\Type\JsonType');

// In src/Model/Table/UsersTable.php
use Cake\Database\Schema\TableShema as Schema;

class UsersTable extends Table
{

    protected function _initializeSchema(Schema $schema)
    {
        $schema->columnType('preferences', 'json');
        return $schema;
    }

}
```

**Comment by Theaxiom** [comment]
Tagging @dereuromark since he made the change.

**Comment by dereuromark** [comment]
Are you able to Provide a PR? Otherwise I can do it later.

**Comment by Theaxiom** [comment]
I can try, I believe there are many instances of that change necessary. I'll @mention you when I submit it.

**Comment by saeideng** [comment]
I think all `Table` classes converted to `TableShema` now
