### ISSUE TITLE
Request getParam only for Cake 3.4+

### ISSUE THREAD

**Issue by TheoRenouf** [cakephp/docs#4911]
Hi,
On the page https://book.cakephp.org/3.0/en/controllers/request-response.html#request-parameters we can see an example explaining how to get parameters of the request. But that example works only for Cake 3.4+. 

We should add an explication for Cake 3.x <3.4 users.

**Comment by ravage84** [comment]
https://api.cakephp.org/3.4/class-Cake.Http.ServerRequest.html#_param

**Comment by markstory** [comment]
Docs updated now.
