### ISSUE TITLE
Translate to Portuguese

### ISSUE THREAD

**Issue by FilipeVoges** [cakephp/docs#4957]
To translate all pages into Portuguese

**Comment by markstory** [comment]
Sounds like a great idea, but the documentation is quite large, and will only get translated by Portuguese speakers taking the time to translate the content.

I am closing this issue, as there is no 'fix' for this other than a dedicated and interested group of translators, which we currently don't have.

**Comment by ravage84** [comment]
@FilipeVoges may be get in touch with @andtxr. He is part of the @cakephp/docs-pt team, which tranlsates our docs into Portuguese.
