### ISSUE TITLE
Examples for "Creating Reusable Emails" use deprecated methods

### ISSUE THREAD

**Issue by JoshuaLuckers** [cakephp/docs#5005]
It might be a good idea to add examples using the 3.4.* methods.

**Comment by markstory** [comment]
We have been having other issues that when the docs use the new methods people on older versions get fatal errors. Tough spot to be in.

**Comment by ravage84** [comment]
Refers: https://book.cakephp.org/3.0/en/core-libraries/email.html#creating-reusable-emails

@JoshuaLuckers in the past, in such cases we added both versions, both with comments which can be used in what version range.
Unfortunately, with all the recent getter/setter splits including deprecations, it's easy to overlook some code examples in the docs.

I'm going to close this. But feel free to updat the docs in a PR. Thanks!
