### ISSUE TITLE
Global Translation Functions supporting Context are not documented

### ISSUE THREAD

**Issue by ravage84** [cakephp/docs#5006]
At [Global Constants and Functions](https://book.cakephp.org/2.0/en/core-libraries/global-constants-and-functions.html), the following functions aren't documented:

- ``__x($context, $singular, $args = null)``
- ``__xn($context, $singular, $plural, $count, $args = null)``
- ``__dx($domain, $context, $msg, $args = null)``
- ``__dxn($domain, $context, $singular, $plural, $count, $args = null)``
- ``__dxc($domain, $context, $msg, $category, $args = null)``
- ``__xc($context, $msg, $category, $args = null)``

**Comment by ravage84** [comment]
Related for 3.x: https://github.com/cakephp/docs/pull/2466

**Comment by ravage84** [comment]
@liviascapin would you give this a shot?

**Comment by markstory** [comment]
Closing as a pull request is up.
