### ISSUE TITLE
hasAndBelongsToMany  is not mentioned in Associations - Linking Tables Together¶

### ISSUE THREAD

**Issue by Josexato** [cakephp/docs#5038]
https://book.cakephp.org/3.0/en/orm/associations.html

This is not explicit regarding what happened with hasAndBelongsToMany (HABTM) that existed in 2.0

**Comment by markstory** [comment]
It is now called belongsToMany. Would it make sense to include that terminology change in the migration guide?

**Comment by inoas** [comment]
I think HABTM / Has and Belongs To Many is a term that will be generally looked for, not just a migration issue.

**Comment by markstory** [comment]
Closing as a pull request is open
