### ISSUE TITLE
intro/cakephp-foler-structure.rst is outdeted.

### ISSUE THREAD

**Issue by okinaka** [cakephp/docs#5054]
Refs: https://github.com/cakephp/docs/blob/0cebf9feba05299011e5fa40c734862f996d3d52/en/intro/cakephp-folder-structure.rst

- No longer "download and extract" in current installation.
- Console folder description is incorrect.
- There is no description of Shell folder.
- View folder description is also slightly different.

**Comment by markstory** [comment]
Closing as there is a pull request open now.
