### ISSUE TITLE
Query Builder Docs Section isn't available in Spanish

### ISSUE THREAD

**Issue by martinrios95** [cakephp/docs#5109]
Hi, I'm Martin from Argentina.

I want to learn CakePHP with Spanish docs. Yes, I speak and read English, but it would be better if the Query Builder was in Spanish.

I didn't want to make a pull request because I'm new on GitHub... so I'm posting this issue.

Best regards!

Martin

**Comment by saeideng** [comment]
Spanish docs is not update all over

**Comment by jeremyharris** [comment]
Are you interested in contributing @martinrios95? If so, I can try to help with any difficulties you are having.

The easiest way to get started is to click the "Improve this doc" button (the pencil icon) on the left hand side of the book: https://book.cakephp.org/3.0/es/orm/query-builder.html

The format we use can be tricky at first, but I assure you once you work on a page or two you'll get the hang of it! We're also here to help if you have formatting questions :)

**Comment by martinrios95** [comment]
I want to contribute on that section, yes. I saw that button... so I'm going to dive on the docs.

I wanted to learn CakePHP's Query Builder, but in Spanish the docs aren't ready yet, like @saeideng said.
And, thanks! If I've got questions, I'll be giving to you by posting a message to you @jeremyharris! :D

**Comment by jeremyharris** [comment]
@martinrios95 no problem, I look forward to your contributions! I'm also in the slack channel pretty regularly if you have quick questions - it will be much faster to answer them there :)

**Comment by dereuromark** [comment]
Closing this until a team has been found to continuously translate into this language.
You can then directly open PRs.
