### ISSUE TITLE
setExtensions is not there

### ISSUE THREAD

**Issue by midorikocak** [cakephp/docs#5173]
Page at https://book.cakephp.org/3.0/en/development/routing.html says if we wanted to allow REST access to a recipe controller, we’d do something like this:

`// In config/routes.php...

Router::scope('/', function ($routes) {
    $routes->setExtensions(['json']);
    $routes->resources('Recipes');
});`

But when we add that we get this error:

Call to undefined method Cake\Routing\RouteBuilder::setExtensions();

Instead of that adding Router::extensions(['json']); to routes.php, solves the problem.

Docs should be changed.

Thanks.

**Comment by markstory** [comment]
The docs reflect 3.5.0 rc which does have that method. I can add a backwards compatible method call in a comment like other examples.
