### ISSUE TITLE
Incorrect example

### ISSUE THREAD

**Issue by bigasbespip** [cakephp/docs#5187]
In https://book.cakephp.org/3.0/en/orm/query-builder.html#passing-conditions-to-contain
 there is 
Passing Conditions to Contain
When using contain() you are able to restrict the data returned by the associations and filter them by conditions:

// In a controller or table method.

$query = $articles->find()->contain('Comments', function ($q) {
   return $q
        ->select(['body', 'author_id'])
        ->where(['Comments.approved' => true]);
});

i beleive the query should read:

$query = $articles->find()->contain(['Comments' => function ($q) {
   return $q
        ->select(['body', 'author_id'])
        ->where(['Comments.approved' => true]);
}]);

**Comment by markstory** [comment]
The documented form was added in 3.5.0
