### ISSUE TITLE
beforeSave callback inconsistency

### ISSUE THREAD

**Issue by dereuromark** [cakephp/docs#5189]
https://book.cakephp.org/3.0/en/orm/behaviors.html

There is always just a

    public function beforeSave(Event $event, EntityInterface $entity)

signature, whereas in table docs:

    public function beforeSave(Event $event, EntityInterface $entity, ArrayObject $options)

Shoudnt behaviors also have the objects param?
Otherwise the IDEs complain about

> Declaration should be compatible with ...

because of the behavior mixins.

**Comment by markstory** [comment]
PHP doesn't give any runtime errors if your method gets extra arguments. But I can take care of updating the documentation for completeness sake.

**Comment by markstory** [comment]
Pull request up.
