### ISSUE TITLE
Explain what each form template is used for

### ISSUE THREAD

**Issue by davidyell** [cakephp/docs#5232]
Trying to figure out which template strings to modify is difficult and I find it frustrating. I wanted to see a nice list with an explanation of each one.

Which led me here, https://book.cakephp.org/3.0/en/views/helpers/form.html#list-of-templates

Which then linked me to here, https://api.cakephp.org/3.5/class-Cake.View.Helper.FormHelper.html#%24_defaultConfig

This is in no way helpful, in my opinion. I've just spent a good 20 minutes trying to figure out how to add a data attribute to an input, and have failed. Mostly due to `label` not being used for radio buttons but instead `nestingLabel` being used. Why? I have no idea. 

I've ended up having to add my data attribute to the wrapping label, as I couldn't add it to the input, due to the `{{text}}` not being available for some reason.

I found this experience frustrating, so I wanted to report an issue in the hope that someone who knows more about the string templating could improve the documentation here.

**Comment by markstory** [comment]
I can add more context to the template usage.

**Comment by davidyell** [comment]
That would be great, thanks Mark

**Comment by saeideng** [comment]
you should challenge with this list and find proper case, like me :smiley:

**Comment by saeideng** [comment]
and if I remember some of docs in this block of cookbook is invalid (related to this list)

**Comment by ADmad** [comment]
Closing as related PR has been merged.
