### ISSUE TITLE
Improvement Suggestion (Email Transport) - Gmail configuration support

### ISSUE THREAD

**Issue by obinoob** [cakephp/docs#5233]
Perhaps you might want to add https://support.google.com/a/answer/176600?hl=en to the 
"You will need to have access for less secure apps enabled in your Google account for this to work: Allowing less secure apps to access your account." paragraph.

At: https://book.cakephp.org/3.0/en/core-libraries/email.html#configuring-transports

**Comment by markstory** [comment]
This will be addressed via #5234
