### ISSUE TITLE
Styles don't work with `make`

### ISSUE THREAD

**Issue by davidyell** [cakephp/docs#5271]
For those of us who don't use Docker, building the html with `make` seems to create HTML which looks for `<link rel="stylesheet" href="../_static/css/app.css" type="text/css" />` but does not create this file.

Which means that the docs are without any css. I have tried making a symlink in the folder to various css files, but none seem to comprise of all the styles required to view the documentation as it appears on the live site.

**Comment by markstory** [comment]
What make target are you using to build the docs? `make html-en` should be building the assets https://github.com/cakephp/docs/blob/21ae928122ea0dcca19e12bac516dcbfd4ee8173/Makefile#L45-L46

**Comment by davidyell** [comment]
When I try and run that I get an error.

```bash
david@UKWM157 ~/Sites/CakePHP-Docs $ make html-en
make: Circular en/Makefile <- en/Makefile dependency dropped.
cp -n en/Makefile es/Makefile
make: *** [es/Makefile] Error 1
david@UKWM157 ~/Sites/CakePHP-Docs $ david@UKWM157 ~/Sites/CakePHP-Docs $ make html-en
```

**Comment by markstory** [comment]
Oh. make is losing the plot there.

```bash
rm */Makefile
git checkout en/Makefile
```
will fix that problem.

**Comment by saeideng** [comment]
@markstory 
assets for all lang is same?
`build/html/.../_static/css/app.css `
