### ISSUE TITLE
Request for make Korean docs

### ISSUE THREAD

**Issue by jeayoon** [cakephp/docs#5282]
Hi markstory, my name is JaeYoon and I am a developer currently using your cakePHP3 framework. It has been an effective and useful tool so far and I wanted to extend this to others. I am from South Korea and due to your excellent documentation and instructions provided, I was able to set up and use this framework for my company.

I was wondering, could you possibly create a cakePHP3 documentation page that can be written in Korean? By combining my experiences of developing cakePHP3 and translating English to Korean, I was hoping I could commit and contribute to this project by starting a Korean documentation so that other Korean developers could take part and use this framework. I would be grateful if you could create a Korean Documentation page within your cakePHP3 github and allow me access to edit it. Let me know what works for you! Thank you.

**Comment by ravage84** [comment]
Hi @jeayoon 

We are glad you enjoy CakePHP and that you want to contribute.
We welcome any contribution to the docs including translations into new languages.

Unfortunately we had to learn that often such translation efforts slowly wind down after the initial phase.
This leads to mostly unmaintained, half translated documentation which helps nobody.
Often times, there is much more translation to be done than a single person can actually do by him-/herself.

Do you think you can find one or two other people who would be able to help you in your translation effort?

**Comment by jeayoon** [comment]
Hi @ravage84 ,
Thank you for the quick reply! As for what you have said, I can totally understand where you're coming from and how it could cause problems or some sort of degradation of your quality if there are unfinished documentation. As you may know, there is a substantial amount of documentation content that needs to be translated and so I have came up with an offer. Prior to any sort of publishing or creation of an actual CakePHP Korean Documentation page, I have already been creating the documentation on my own as I progressed using CakePHP. How about I finish up and finalize say 50% of the entire documentation (translated), in which then I can show you the content. Once you review it (I understand it'll be a bit hard to review it since it will be in Korean), I hope I could gain your trust that I will take responsibility for the latter half of the documentation such that we can start/create a page for the korean translated documentation and have the initial half posted. There really is no reason as to why I would abandon this documentation after finishing the first half but if you would recommend another idea please feel free to let me know and we can further discuss what's the best course of action to take. Again, the initial 50% will have the main integral parts of setting up and getting started with the framework but just won't contain all the specifics and each use case details.

Let me know how that sounds! 

Thanks

**Comment by ravage84** [comment]
@jeayoon , I don't think it is necessary that you translate 50 % of the docs up front.
I really encourage you to find at least a second person who speaks your language and thus can help you.

Also it makes sense to have such a person simply because nobody of the current docs team (at least to my knowledge) could verify what you translate, at least not with a translator 😼

**Comment by ravage84** [comment]
By the way, it's much more fun to work in a team on such a project...

**Comment by ravage84** [comment]
I've posted a [request for helpers](https://www.facebook.com/groups/cake.community/permalink/1649756825056328/) in our [CakePHP Facebook group](https://www.facebook.com/groups/cake.community/).

**Comment by jeayoon** [comment]
Hi @ravage84 ,
That makes sense. After thinking through things, it really does seem like the best choice is to find another person that I could work with. I'll also take a look for other people that I can work with and thank you so much for your help to reach out to the community for potential people! Let me know if you can find a person interested in working. I'll let you know if I can find someone as well!

Thank you!

**Comment by dereuromark** [comment]
Closing for now then - until a team has been found to take this on.

**Comment by jeayoon** [comment]
Hi @ravage84 , 
I was able to acquire 2 more people to collaborate and form a group to create the Korean Documentation. Is it possible for us to gain the permission to start on this project together?

**Comment by ravage84** [comment]
@jeayoon great. Sure, please go on. 👍
