### ISSUE TITLE
Conventions for Entities

### ISSUE THREAD

**Issue by gildonei** [cakephp/docs#5299]
Are there a convention for Entity names?

**Comment by dereuromark** [comment]
What do you mean? Can you please be a bit more specific what part is missing on top of the https://book.cakephp.org/3.0/en/intro/conventions.html guide?

**Comment by gildonei** [comment]
First I would like to apologize for post a question on Issues

My doubt is about paragraph **File and Class Name Conventions** and **Model and Database Conventions**.

I know that Entity creation is optional unless you have some specific rules to apply. In this case, how should I name an Entity with HABTM relationship ? Use the same rules applied for Table objects?

EX: UserEntity -> _UserPreferencesEntity_ <- PreferenceEntity

**Comment by gildonei** [comment]
Also I would like to know what the core team recomends for table specilizations (isOne).

Should it be considered as a **hasOne** relationship and use _tablename_ _id as it's primary key.

**Comment by dereuromark** [comment]
primary keys always are "id", no exceptions here for the conventional approach.
You have the same rules applying here as for hasMany usually (and you can easily switch to this if it becomes necessary).

**Comment by gildonei** [comment]
OK, doubt solved about PK names.

Resting only about Entity names. Should it be Singular, Singular + Plural,  Singular + Singular, other?

**Comment by markstory** [comment]
@gildonei Entity names should be the singular inflection of the table name. When singularizing CakePHP only singularizes the end noun. So `users_preferences` would become `UsersPreference`.

I can update the conventions docs to make that clearer.

**Comment by inoas** [comment]
Could this be addressed in 4.x to become configurable?

I would very much love to see plural everywhere being an option for just about everything (foreign keys, table classes, entities, just not flash messages/bake)

Making it configurable we can either move to plural only in 5.x to have easier and less error prone conventions (1 person vs n people? 1 people vs n people (nations)) etc?

**Comment by markstory** [comment]
> Could this be addressed in 4.x to become configurable?

It already is. You can use the `setEntityClass()` method on table classes to define any entity class you want. I don't think we need additional layers of configuration.

> I would very much love to see plural everywhere being an option for just about everything (foreign keys, table classes, entities, just not flash messages/bake)

The methods exist to do all of this already as well.

**Comment by gildonei** [comment]
Ty @markstory and @dereuromark - doubts solved

**Comment by inoas** [comment]
@markstory what about plural foreign keys then? Just use `setForeignKey()` and `setEntityClass()` and be done with it?

**Comment by ssimo3lsuhsc** [comment]
This issue needs to be reopened. As of 2:35 PM Central Time on April 30, 2019, the page at https://book.cakephp.org/3.0/en/intro/conventions.html, section "Database Conventions," does NOT contain the following sentence:

The field name of a primary key should always be `id`, even if it is related to a foreign key in another table.

The truth is, I'm not trustworthy enough to make that change, and I want to know that it is really true before I or anybody else makes the change.

**Comment by dereuromark** [comment]
I would say yes: That convention is useful to add as this is the default in all cases, including initial migrations for bake.

**Comment by gildonei** [comment]
> This issue needs to be reopened. As of 2:35 PM Central Time on April 30, 2019, the page at https://book.cakephp.org/3.0/en/intro/conventions.html, section "Database Conventions," does NOT contain the following sentence:
> 
> The field name of a primary key should always be `id`, even if it is related to a foreign key in another table.
> 
> The truth is, I'm not trustworthy enough to make that change, and I want to know that it is really true before I or anybody else makes the change.

Does it include the primary key on specialized tables where the primary key is a foreign key from a **isOne** relation?

**Comment by othercorey** [comment]
Usually pivot tables have primary keys in the form of `table_id` not `id`.  I'm not sure the phrase is clear.

>even if it is related to a foreign key in another table

If you are saying that for tables Users and Profiles that the primary key in Profiles should be `id` even though there is a foreign key in Users called `profile_id` then that makes sense.

**Comment by dereuromark** [comment]
> Does it include the primary key on specialized tables where the primary key is a foreign key from a isOne relation?

Yes, by convention for all relations, no matter what.
As such this is helpful to add, you can always choose to strive from conventions.

**Comment by gildonei** [comment]
> Usually pivot tables have primary keys in the form of `table_id` not `id`. I'm not sure the phrase is clear.
> 
> > even if it is related to a foreign key in another table
> 
> If you are saying that for tables Users and Profiles that the primary key in Profiles should be `id` even though there is a foreign key in Users called `profile_id` then that makes sense.

As an example of specialized tables I am referring could be:

* customers
      id -> Primary, Auto increment, Not Null
      name
* people
      id -> Foreign Key from customers, Not Null (this will not be auto increment, must have the same Id as customers)
      driver_license_number
* companies
       id -> Foreign Key from customers, Not Null (this will not be auto increment, must have the same Id as customers)
       foundation_date

In the sample above, we have Primary Keys at same time it also is a Foreign Key. So what is the right convention for this sample.

In my opinion, Cake should consider **isOne** relations as Primary Key, so developers should use PK name as **id**

**Comment by inoas** [comment]
In my opinion a lot of trouble could be saved by going two fold:
A) respect foreign key constraints where they exist otherwise fall back to only plural
B) only use plural for table names, foreign keys, table class names, entity class names, only use the inflector for cake bake to render single entities, flash messages etc
 
I know that that's against how ancient rails and cake since version 1 did it, but the non-ui inflection is a big pain and imposes. What I suggest would remove inflection from non-ui stuff. You could still use singular foreign key ids if you specified your foreign keys as real ones (InnoDB, Postgres etc)

**Comment by gildonei** [comment]
> In my opinion a lot of trouble could be saved by going two fold:
A) respect foreign key constraints where they exist otherwise fall back to id + only plural
B) only use plural for table names, foreign keys, table class names, entity class names, only use the inflector for cake bake to render single entities, flash messages etc

I completely agree with item B

About item A, i think ORM must support same kind of relations that databases supports, isOne, hasOne, hasMany, etc. In Cake since version 1, in docs I only saw about hasOne, hasMany and Habtm, never was spoked about isOne and this relationship type is very commom.

Just like OOP supports inherance, all major databases also supports table inherance, said that, an Id from an inherited table is always the same Id as its parent table (usualy an auto increment field) and it is a Primary key. So, following the conventions I think it should be named as ID only.

**Comment by inoas** [comment]
My 2 cents: Maybe I am wrong but isOne/isA can be mapped as hasOne/BelongsTo - databases that do isOne also have foreign keys only on one side and primary keys on the other (and not bidirectional as isOne/isA would assume)
