### ISSUE TITLE
The 'Adding Password Hashing' section should be moved into the 'Authentication' chapter.

### ISSUE THREAD

**Issue by chinpei215** [cakephp/docs#5312]
While I am creating an example CMS application by reading the tutorial, now I think the 'Adding Password Hashing' section in 'Tags and Users' chapter should be moved into the 'Authentication' chapter. Though we suddenly start explaining the password hashing, I think it would be better to focus on how to deal with many-to-many (BelongsToMany) association in the chapter. So the chapter name would be 'Tags'. The three bake commands on the top of the page also should be moved into the 'Authentication' chapter. It would be nice if we have the `comments` table to explain simpler associations such as BelongsTo and HasMany,  before BelongsToMany. 

Also, it would be better to not declare the `users` table and the foreign keys until the 'Authentication' chapter. Then we could remove the following temporary code:
https://github.com/cakephp/docs/blame/1aa219e9cca9b3a284702664cc8bc087ff0cc043/en/tutorials-and-examples/cms/articles-controller.rst#L269-L270
https://github.com/cakephp/docs/blame/1aa219e9cca9b3a284702664cc8bc087ff0cc043/en/tutorials-and-examples/cms/articles-controller.rst#L327-L331
We could start explain how to change the table definition by using the Migrations plugin, in the next section.

To be clear, my suggestions are:
1. Move the 'Adding Password Hashing' section into 'Authentication'.
2. Add a new chapter for BelongsTo and HasMany.
3. Add a new chapter or new section for Migrations (and not declare 'users' table until this).

**Comment by markstory** [comment]
I am not sure using migrations is right for a first run tutorial. Could adding comments/using migrations be a follow up chapter to the existing content?

I agree that the user table and authentication steps could all be one chapter that is done after the basic articles & tags content is complete.

**Comment by chinpei215** [comment]
I see. On second thought, I also think learning Migrations plugin is not suitable for the first tutorial. And adding comments might not be a good tutorial either, as it would require more complex templates to display comments. But it would be nice if beginners could learn BelongsTo/hasMany earlier than BelongsToMany. For now, beginners wouldn't understand how to save such common associations even after finished the CMS tutorial.

**Comment by markstory** [comment]
I chose to show BelongsToMany early as it allows us to showcase `matching()` which is a fairly distinctive feature of the Cake ORM. Also attaching articles to users shows saving a belongsTo association.

**Comment by chinpei215** [comment]
I guess you are talking about `innerJoinWith()/leftJoinWith()` that using `setMatching()/getMatching()` internally. Reading the Bookmarker tutorial and CMS tutorial, I understand the intention that we want to show new features, such as ORM and Collection. But I feel the examples seem too complex to me. For example, [the first example of the custom finder](https://book.cakephp.org/3.0/en/tutorials-and-examples/cms/tags-and-users.html#creating-the-finder-method). It would be nice if it is simpler:
```php
public function findPublished(Query $query, array $options)
{
    return $query->where(['Articles.published' => true]);
}
```
Then we can start explaining how custom finders are called. However, for now, there are no explanation about that in the tutorial.

But I see. Writing tutorials is not an easy task. When I have time, I try to write it in Japanese for Japanese users. If I could write nice tutorial, I would show you it.

**Comment by chinpei215** [comment]
So, for now, I suggest to move the 'Adding Password Hashing' section into 'Authentication'. I withdraw other suggestions.
