### ISSUE TITLE
"Requesting Elements from the App" does not work

### ISSUE THREAD

**Issue by ravage84** [cakephp/docs#5337]
The feature "Requesting Elements from the App" documented at: https://book.cakephp.org/3.0/en/views.html#requesting-elements-from-the-app does not work, because the theme/plugin search paths are always the first two.

The tests say so too:
https://github.com/cakephp/cakephp/blob/3.5.4/tests/TestCase/View/ViewTest.php#L516-L521

````
$themePath . 'src' . DS . 'Template' . DS . 'Plugin' . DS . 'TestPlugin' . DS,
$themePath . 'src' . DS . 'Template' . DS,
TEST_APP . 'TestApp' . DS . 'Template' . DS . 'Plugin' . DS . 'TestPlugin' . DS,
$pluginPath . 'src' . DS . 'Template' . DS,
TEST_APP . 'TestApp' . DS . 'Template' . DS,
CAKE . 'Template' . DS,
````

Could be related:
https://github.com/cakephp/cakephp/issues/4064
https://github.com/cakephp/cakephp/pull/11198
https://github.com/cakephp/cakephp/pull/11210

There is another, related feature that does not work, which I will document next.

**Comment by markstory** [comment]
Using plugin => false used to work :cry:

**Comment by othercorey** [comment]
Should we remove the example?
