### ISSUE TITLE
"Overriding Plugin Templates from Inside Your Application" does not work

### ISSUE THREAD

**Issue by ravage84** [cakephp/docs#5338]
The feature "Overriding Plugin Templates from Inside Your Application" documented at: https://book.cakephp.org/3.0/en/plugins.html#overriding-plugin-templates-from-inside-your-application does not work, because the theme/plugin search paths are always the first two.

The tests say so too:
https://github.com/cakephp/cakephp/blob/3.5.4/tests/TestCase/View/ViewTest.php#L516-L521

````
$themePath . 'src' . DS . 'Template' . DS . 'Plugin' . DS . 'TestPlugin' . DS,
$themePath . 'src' . DS . 'Template' . DS,
TEST_APP . 'TestApp' . DS . 'Template' . DS . 'Plugin' . DS . 'TestPlugin' . DS,
$pluginPath . 'src' . DS . 'Template' . DS,
TEST_APP . 'TestApp' . DS . 'Template' . DS,
CAKE . 'Template' . DS,
````

Could be related:
https://github.com/cakephp/cakephp/issues/4064
https://github.com/cakephp/cakephp/pull/11198
https://github.com/cakephp/cakephp/pull/11210

There is another, related feature that does not work, which I already documented in #5337.

**Comment by markstory** [comment]
Theme paths are always before the app/plugin paths. In your path snippet, the application overrides are the 3rd path checked (after the active theme). The docs are still correct, your scenario also has a theme which the application cannot override.

**Comment by ravage84** [comment]
I see.. So  I guess the documentation doesn't make it clear enough what the distinction between a "normal" plugin and a theme is and what the implications are.

**Comment by ivanamat** [comment]
Hi all,

When iinstall [AclManager plugin](https://github.com/ivanamat/cakephp3-aclmanager) vía Composer it doesn't work as described in the manual. To override virews must override without vendor, then it works.

The version of CakePHP is 3.5. Is the documentation really good or is there something I have not understood?

Regards!

**Comment by markstory** [comment]
The documentation should be how the code is working. @ivanamat could you open an issue in cakephp/cakephp for this?

**Comment by ivanamat** [comment]
Hi @markstory, The issue has been created.

Regards!

**Comment by markstory** [comment]
Thanks!

**Comment by othercorey** [comment]
Is this ok now?
