### ISSUE TITLE
Wrong SQL in CMS Tutorial

### ISSUE THREAD

**Issue by onz123** [cakephp/docs#5347]
When creating the Database (https://book.cakephp.org/3.0/en/tutorials-and-examples/cms/database.html), I think the foreign key for the articles_tags table should be articles_key instead of bookmark_key.

```
CREATE TABLE articles_tags (
    article_id INT NOT NULL,
    tag_id INT NOT NULL,
    PRIMARY KEY (article_id, tag_id),
    FOREIGN KEY tag_key(tag_id) REFERENCES tags(id),
    FOREIGN KEY bookmark_key(article_id) REFERENCES articles(id)
);
```

**Comment by ravage84** [comment]
True, I'm fixing it.
