### ISSUE TITLE
Wrong code snippet in CakePHP 2.x CookBook

### ISSUE THREAD

**Issue by bossvpm** [cakephp/docs#5356]
Hi,
I've found a wrong line code in CakePHP 2.x CookBook (https://book.cakephp.org/2.0/en/models/saving-your-data.html).
![cookbook_page](https://user-images.githubusercontent.com/9128194/32439886-c76094da-c316-11e7-8dbb-a325506e1eeb.jpg)
Here is the example of saving multiple data to the database. Here in the red marked portion, model name only is referred without $this pointer.

The following is my code according to the wrong documentation.
![code](https://user-images.githubusercontent.com/9128194/32440054-830a755c-c317-11e7-9e0d-7c2ac7bf11c3.PNG)
Here 'PentestScope' my model name and I'm getting the following error.

![error_message](https://user-images.githubusercontent.com/9128194/32443367-c35b00d8-c324-11e7-9be0-56984a84cf23.PNG)

It was working fine when I changed the line to 
$this->Model->saveMany($data);
So, I guess the documentation should be in this format.

**Comment by ravage84** [comment]
The code example in the book assumes you have initiated ``$Model`` beforehand.

**Comment by faizzaidi** [comment]
You could have followed the same pattern in all examples instead of having different kind of assumptions in different cases. This kind of errors may confuse beginners.

**Comment by bossvpm** [comment]
Please maintain same pattern code throughout the CookBook.
