### ISSUE TITLE
Error in Subqueries documentation

### ISSUE THREAD

**Issue by ArmenGabrielyan16** [cakephp/docs#5401]
**Issue Description**

There is a mistake in [Subqueries](https://book.cakephp.org/3.0/en/orm/query-builder.html#subqueries) documentation. In the example, the subquery `$matchingComment` returns more than 1 row and is used in `where` condition like this `['id' => $matchingComment]`. The code returns SQLSTATE[21000]: Cardinality violation error.
However, if we change the condition to `['id IN' => $matchingComment]`, the code will work perfectly.

![screenshot from 2017-11-23 19-22-09](https://user-images.githubusercontent.com/25867263/33179648-a3950fc0-d083-11e7-8847-3dab67a8bad1.png)

---

**Do you want to address this issue?**

I would like to work on this issue.

**Comment by markstory** [comment]
Closing as a pull request is open.
