### ISSUE TITLE
Add Contributing Guidelines

### ISSUE THREAD

**Issue by ArmenGabrielyan16** [cakephp/docs#5411]
**Issue Description**

I would like to add CONTRIBUTING file. There is **Contributing** section in README, but there is no separate CONTRIBUTING. Do we need to extend the project's Contributing Guidelines or just to link to current Contributing?

---

**Do you want to address this issue?**
Yes

**Comment by markstory** [comment]
I would just link to what we already have. Duplicating the information us not great.

**Comment by ArmenGabrielyan16** [comment]
Thanks. I will do it.
