### ISSUE TITLE
Add Coding Standards

### ISSUE THREAD

**Issue by ArmenGabrielyan16** [cakephp/docs#5433]
**Issue Description**

I think we should choose or define coding standards. This will make code style consistent throughout the project. I suggest PSR1/PSR2 standards.

---

**Do you want to address this issue?**

YES.

**Comment by dereuromark** [comment]
You must be confusing sth, CakePHP (incl the code samples) is using already all PSRs.
See https://github.com/cakephp/cakephp-codesniffer for details. This is documented in the docs.

**Comment by markstory** [comment]
@ArmenGabrielyan16 I think correcting code samples to use PSR2 where they aren't already doing so is a great idea. We try to make the samples follow the cakephp coding standards (which extends psr2), but mistakes invariably get made as it is hard to automate checking the code samples.

**Comment by ArmenGabrielyan16** [comment]
@dereuromark @markstory  I noticed that some code examples in the docs do not use PSRs. I think we can correct code samples to use PSRs and when new PRs are submitted correct coding style as well if necessary.

**Comment by dereuromark** [comment]
Yes, you can open PRs here then. Thank you.
We can then close this ticket.
