### ISSUE TITLE
Mysql Driver with ssl

### ISSUE THREAD

**Issue by Yetispapa** [cakephp/docs#5501]
I faced an issue where I can't establish a secure connection to a remote mySQL database. It seems like when I add the following line in **Cake\Database\Driver\Mysql**:

        if (!empty($config['ssl_key']) && !empty($config['ssl_cert'])) {
            $config['flags'][PDO::MYSQL_ATTR_SSL_KEY] = $config['ssl_key'];
            $config['flags'][PDO::MYSQL_ATTR_SSL_CERT] = $config['ssl_cert'];
            **$config['flags'][PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT] = false;**
        }

It seems to work. I also created a stackoverflow [question](https://stackoverflow.com/questions/47995069/cakephp-3-mysql-connection-over-ssl) related to this.

Is there another solution to achieve a secure connection without modifiying cakes code?

**Comment by markstory** [comment]
> Is there another solution to achieve a secure connection without modifiying cakes code?

No. I don't think turning off SSL verification is something that would be merged into CakePHP.
