### ISSUE TITLE
Should we change instructions for notes formatting?

### ISSUE THREAD

**Issue by Leo240** [cakephp/docs#5524]
In the Contributing's Documentation guide there is an instruction of how to make notes. In the example of formatting of the note there is a blank line between the ``.. note::`` tag and the text of the note. But I saw multiple times that not always blank link precedes the text of the note, and this not leads to errors in compiling of documentation. The question is - should we change that instruction?

**Comment by markstory** [comment]
Having the new lines makes the notes easier to read, but its not required by sphinx.

**Comment by Leo240** [comment]
I got it.
