### ISSUE TITLE
Exception Handling not clear

### ISSUE THREAD

**Issue by VinGarcia** [cakephp/docs#5539]
**Problems understanding CakePHP 3.x Error Handling**

While trying to implement a custom `error404.ctp` view I did not know how to proceed and the docs were not sufficient to help me. I found afterwards in [stackoverflow.com](https://book.cakephp.org/3.0/en/development/errors.html) that I am not the only one finding it difficult. The mentioned user of StackOverflow needed to read CakePHP source to solve his problem.

Things that I think could be improved:

1. When to use a custom ErrorHandler instead of a ErrorController, what each of them actually do?
2. How to choose an specific view to render from either an ErrorController, custom ErrorHandler or custom ExceptionRenderer.
3. How can I make the error code available for the view? [EDIT: I meant the status code, e.g. 404]

For me it would have been enough if the docs explained how to send the error code to the any of the default views, i.e. `error400.ctp` and `error500.ctp`. What I tried:

        throw new HttpException("TESTE", 404);
        throw new NotFoundException("TESTE");
        return $this->response->statusCode(404);

All 3 showed view `error500.ctp` instead of `error400.ctp` and I did not understand if this was expected or not.

---

Since I am still learning I am not qualified to solve this issue :(

Thanks for your work, I would also be happy if you could point me to an example of how to show a 404 error message when the `NotFoundException` was thrown.

**Comment by markstory** [comment]
Thank you for the feedback on the documentation. I will work on improving it and add an section on when each template is used.

**Comment by VinGarcia** [comment]
That's great, thank you =]

**Comment by markstory** [comment]
@VinGarcia could you look at #5543 and see if I've addressed the gaps you had with the current version of the docs?

**Comment by VinGarcia** [comment]
Thank you I just read it. It is much better. I missed an example with an `ErrorController`. I suspect that the reason you didn't put it was because it should appear by default in new Cake projects, however, I don't have it in mine. (it might be because I am not the first programmer to work in this project).

Some observations:
1. I think there is a typo in this sentence: "You can also implement methods to add additional for CakePHP errors::"
2. "Each framework layer exception will render specific view templates in debug mode.", maybe would be better like this: "Some bugs are related to the use of the Framework, while in debug mode these bugs will use specific CakePHP views.", if I understood this correctly.
3. The paragraph below made me wonder if the example was correct of if it was missing the `render` and `__constructor` definitions:
   
   > Your custom renderer should expect an exception in its constructor, and
   > implement a ``render`` method. Failing to do so will cause additional
   > errors.
   
   Would it be enough to just extend the `Cake\Error\ExceptionRenderer` as in the example?
   I mean, does the superclass implement these functions?

I write these in the hope it helps, the text is already much better.

**Comment by VinGarcia** [comment]
I also had 2 doubts that maybe are not related to the docs:

1. When I throw NotFoundException("message") the error page renders with an error 500 instead of a 404, is this the expected behavior? After reading the new version of the docs it seemed that it would be expected to render with `$code == '404'`.

2. When modifying the error layout the docs suggest creating a new layout file in `Layout/my_error.ctp`, is there a reason for not editing the original layout file `Layout/error.ctp`?

**Comment by markstory** [comment]
> When I throw NotFoundException("message") cake renders error500.ctp with a $code == 500 instead of a 404, is this the expected behavior?

No this is not how it was working for me with a fresh application skeleton. Perhaps there is an error during error page creation that is resulting in a 500 being rendered.

> When modifying the error layout the docs suggest creating a new layout file in Layout/my_error.ctp, is there a reason for not editing the original layout file Layout/error.ctp?

I included that example to cover the situation where people wanted to use one layout for the app & errors.

**Comment by VinGarcia** [comment]
Uhmm that is good to know, in a fresh application is it expected to exist an `ErrorController.php`? This would explain why it is behaving differently for me.

Thanks for the changes

**Comment by markstory** [comment]
>  in a fresh application is it expected to exist an ErrorController.php

Yes, applications should contain their own ErrorController classes. It makes editing the file much easier :smile:

**Comment by markstory** [comment]
Thank you for reviewing the new changes. I'm going to close this for now. If you find the docs lacking in other areas please open an issue as you had great feedback on this chapter.

**Comment by VinGarcia** [comment]
Thank you, I will.
