### ISSUE TITLE
Possibly wrong terminology in views.rst

### ISSUE THREAD

**Issue by Leo240** [cakephp/docs#5545]
In the main file of View documentation - /en/views.rst, there is the next lines:

> - **views**: Templates are the part of the page that is unique to the action
  being run. They form the meat of your application's response.

I think that instead of bolded "views" word should be "templates" word, because it describes the templates folders's contents and also there is exists the ``views`` folder that describes the program logic of representation

**Comment by markstory** [comment]
You're right! This is probably leftover from when we used 'views' to mean templates and view classes, which was confusing and lead to the adoption of templates.

**Comment by Leo240** [comment]
@markstory Ok) should I do corrections by myself?

**Comment by markstory** [comment]
That would be greatly appreciated @Leo240

**Comment by Leo240** [comment]
@markstory  Pull request is ready)

**Comment by markstory** [comment]
Thanks @Leo240 :clap:
