### ISSUE TITLE
Cache configuration is not fully explained

### ISSUE THREAD

**Issue by VinGarcia** [cakephp/docs#5555]
The Caching - 3.x documentation is good and well explained, however, there is a topic that could be improved about the [configuration options](https://book.cakephp.org/3.0/en/core-libraries/caching.html#configuring-cache-class).

For instance the examples below extracted from the Caching page:

```php
// ...
'Cache' => [
    'short' => [
        'className' => 'File',
        'duration' => '+1 hours',
        'path' => CACHE,
        'prefix' => 'cake_short_'
    ],
    // Using a fully namespaced name.
    'long' => [
        'className' => 'Cake\Cache\Engine\FileEngine',
        'duration' => '+1 week',
        'probability' => 100,
        'path' => CACHE . 'long' . DS,
    ]
]
// ...
```

and
 
```php
Cache::config('redis', [
    'className' => 'Redis',
    'duration' => '+1 hours',
    'prefix' => 'cake_redis_',
    'host' => '127.0.0.1',
    'port' => 6379,
    'fallback' => 'default',
]);
```

When reading the examples above I got 4 unanswered questions:
1. When should I use `path` or `host` + `port`, is there a doc explaining the set of configuration options for each cache engine?
2. What exactly `duration` means (I guess that it is for how long until the entry expires, but it is not written anywhere)
3. When to use `prefix` and why? (I guess it's for avoiding collisions with other apps, but this configuration is also not mentioned)
4. What is `probability` and when should I use it?

---

I think I am not the best person to address this issue since I have just learned how to use the cache feature.

Thanks for the good work =], I hope this report helps to improve the docs a little bit more.

**Comment by markstory** [comment]
Thanks for pointing out unclear sections of the documentation. I'll get those gaps addressed :smile:

**Comment by markstory** [comment]
I think I've incorporated your feedback in #5557, let me know if I've missed something.

**Comment by VinGarcia** [comment]
Yes it does solve the issue, thank you =]

**Comment by markstory** [comment]
@VinGarcia Thank you again for the great feedback on the documentation :+1:
