### ISSUE TITLE
4th level titles in docs

### ISSUE THREAD

**Issue by Leo240** [cakephp/docs#5562]
When I translated the Authentication guide. I've found that 4th level titles are poorly formatted - they looks almost like simple text in english (latin) text and not recognizable in cyrillic text. The question is can we make the formatting of these titles better?.

**Comment by markstory** [comment]
Are you referring to these titles? https://book.cakephp.org/3.0/en/controllers/components/authentication.html#creating-api-keys-for-basic-authentication

**Comment by Leo240** [comment]
@markstory Yes, you're right

**Comment by Leo240** [comment]
@markstory Maybe we can try to make this titles bold or cursive or some combination of that?

**Comment by markstory** [comment]
I was thinking of making them the same visual size as h3. We don't use 4th level titles often.
