### ISSUE TITLE
Cell constructor options

### ISSUE THREAD

**Issue by LubosRemplik** [cakephp/docs#5572]
**Issue Description**

When I bake cell, there is `$_validCellOptions` property, however there is no documentation at https://book.cakephp.org/3.0/en/views/cells.html which says how to work with cell class constructor so I am not sure what this property/options are there for

```
    /**
     * List of valid options that can be passed into this
     * cell's constructor.
     *
     * @var array
     */
    protected $_validCellOptions = [];
```

---

**Do you want to address this issue?**

If someone explains me what are these cell options I can update doc and send pull request

**Comment by LubosRemplik** [comment]
https://api.cakephp.org/3.5/class-Cake.View.Cell.html#___construct I can see celloptions in the costructor and when I take a look into code

https://api.cakephp.org/3.5/source-class-Cake.View.Cell.html#133-163

There are 3 options, `action`, `args`, `cache`, but this is not documented, am I right?

**Comment by markstory** [comment]
Cell options are intended to be an extension point for custom options. You are right that the documentation is lacking on them. I will get that fixed up.

**Comment by markstory** [comment]
Pull request up now.

**Comment by LubosRemplik** [comment]
Thank you! Makes sense
