### ISSUE TITLE
Cell ViewBundler setTemplate

### ISSUE THREAD

**Issue by LubosRemplik** [cakephp/docs#5573]
**Issue Description**

https://book.cakephp.org/3.0/en/views/cells.html#rendering-alternate-templates  
this part od docs says we are setting template for the cell by `$this->template = 'messages'`, should we say it is better to use `$this->ViewBundler()->setTemplate('messages')`

---

**Do you want to address this issue?**

I am OK to update doc once confirmed

**Comment by saeideng** [comment]
I think `Cell` dont support `$this->ViewBundler()->setTemplate()` yet

**Comment by LubosRemplik** [comment]
I had tried, and it worked. So I think Cell do support the ViewBuilder

**Comment by saeideng** [comment]
you are right 
`$this->viewBuilder()->setTemplate()` works 
thanks

**Comment by markstory** [comment]
A pull request to update the docs would be great!

**Comment by saeideng** [comment]
Pull request up now.
