### ISSUE TITLE
Mocking Models in Controller Tetss

### ISSUE THREAD

**Issue by ravage84** [cakephp/docs#5577]
Chris Harties asked on Twitter:

> any good examples on testing controllers where I need to mock models that are called by the action? Existing CakePHP docs don’t seem to cover it

https://twitter.com/grmpyprogrammer/status/956952005922250752

We should cover this at https://book.cakephp.org/3.0/en/development/testing.html#controller-integration-testing

**Comment by markstory** [comment]
We will likely need a new section as Integration tests don't make it easy to replace components with mocks as they are intended to test your controllers in an integrated scenario.

**Comment by ravage84** [comment]
Still valid

**Comment by ndm2** [comment]
Github bot is above the law.

**Comment by saeideng** [comment]
>Still valid

you can remove `stale` label add `pinned` and open issue if it closed
