### ISSUE TITLE
Router parse string URL

### ISSUE THREAD

**Issue by LubosRemplik** [cakephp/docs#5595]
**Issue Description**

I used to use `Router::parse('/some/url')` to get array URL from string URL, but this is deprecated. See  https://api.cakephp.org/3.5/class-Cake.Routing.Router.html#_parse 

> 3.4.0 Use Router::parseRequest() instead.

I am not sure how to parse string URL by Router::parseRequest(); I guess we need to make request from URL first and then parse request, but I think it is good idea to document this?

---

**Do you want to address this issue?**

If someone explains me how to parse string URL I can make PR

**Comment by markstory** [comment]
Where would you expect to find this information? We don't currently have book docs for parse() or parseRequest () as they are not commonly used in application code. Perhaps this is an example that should be in the API docs?

**Comment by LubosRemplik** [comment]
Possibly new section after this https://book.cakephp.org/3.0/en/development/routing.html#generating-urls *Parsing URLs*?

But you are right, not commonly used so API docs update with example should be OK.

**Comment by nedvajz** [comment]
If somebody has trouble to realize how to like me   
  
```
$request = new \Cake\Http\ServerRequest('/some/url');  
Router::parseRequest($request);  
```

**Comment by jimbo2150** [comment]
@dereuromark pointed out in Slack that RouteCollection has a compatible parse method `Router::getRouteCollection()->parse($url)` and is what was called by the `Router::parse()` method in 3.x.

**Comment by markstory** [comment]
@jimbo2150 Thanks for providing that. I think that API is good enough based on how often parsing string URLS is done.
