### ISSUE TITLE
TL - Tagalog / Filipino Translations

### ISSUE THREAD

**Issue by severinolorillajr** [cakephp/docs#5596]
**Issue Description**

Missing Tagalog translations.

---

**Do you want to address this issue?**

I'd like to actively contribute to this project, please.
I have gone over the guidelines and was mentioned to get hold of you here, so you can build the necessary skeleton files. If need further information from me, you can contact me anytime.

**Comment by markstory** [comment]
Do you have a few other people interested in working on the Tagalog translation? Getting the book translated and maintaining it can be a big job for a single person. We usually recommend at least 2 or 3 people work together on it.

**Comment by severinolorillajr** [comment]
That should not be a problem i have an entire team of 10 people here.
We can just proofread and evaluate each of our work to ensure good quality of translation. We just need a copy of en to our local code:tl. And then we can start right away.
What's the merging process by the way? How often can this be done?
Thanks.

**Comment by severinolorillajr** [comment]
Hi @markstory,
I have made a PR https://github.com/cakephp/docs/pull/5600 for the initial files for TL that needs to be translated.
Once this is merged, can we start with the translation?
Thanks.

**Comment by markstory** [comment]
>  What's the merging process by the way? How often can this be done?

I follow up with GitHub notifications every day. For translations I usually merge once the builds pass as that indicates that the documentation will build HTML/PDFs

**Comment by vinzruzell** [comment]
HI sir. I want to join also for the filipino translation. Thank you.

**Comment by severinolorillajr** [comment]
@vinzruzell , This is project is not open yet.
But we have a few projects lined up.
Come and join us at https://discord.gg/7C9JCa
But of course you have to comply with our process in order to contribute to the projects that we have pooled. Thanks.

**Comment by othercorey** [comment]
Closing as translation files are setup. Just submit PR to update.
