### ISSUE TITLE
Can't access 1.3 manual from version select menu

### ISSUE THREAD

**Issue by tenkoma** [cakephp/docs#5632]
## Issue Description

If select 1.3 from the version selection, the manual can not be displayed.

## Reproduction procedure

1. Access to https://book.cakephp.org/3.0/en/index.html
2. Select "1.3 book" from version selection in the upper right. Then, access to https://book-13.cakephp.org/1.3/en/ and "Service Unavailable" is displayed.

## Additional Information

- There is no problem switching to 1.1, 1.2 and 2.x.
- As a temporary workaround, you can access "/" at the end of the URL like https://book.cakephp.org/1.3/en/ .

---

## Do you want to address this issue?

To be able to switch from menu to 1.3 book.

**Comment by markstory** [comment]
I will get this fixed up.

**Comment by markstory** [comment]
Should be fixed now.
