### ISSUE TITLE
How to Set Cross Origin Request Headers (CORS) for CsrfProtectionMiddleware ?

### ISSUE THREAD

**Issue by Avemaar** [cakephp/docs#5750]
**Issue Description**

Its not clearly in the documentation how CORS headers should be defined.
The description here
https://book.cakephp.org/3.0/en/controllers/request-response.html#setting-cross-origin-request-headers-cors

Does not cover in which file(Appcontroller?),in which function must be added the lines in the link.
I know this is not a tutorial forum, but i trust in i will get answer since the amount of articles about using CORS in CakePHP is very limited.

Thank you for your help

---

**Do you want to address this issue?**

**Comment by markstory** [comment]
> Does not cover in which file(Appcontroller?),in which function must be added the lines in the link.

You can set CORS headers in any controller that needs them. If you'd like to have CORS headers across your application you could use AppController, or a Middleware layer.
