### ISSUE TITLE
Order of chapters in ebook pdf format

### ISSUE THREAD

**Issue by emartinez06** [cakephp/docs#5758]
**Issue Description**
Order of chapters on the pdf version feels wrong. Installation instructions for CakePHP should be the first or second chapter so a reader that is not familiar with it can follow the necessary steps to get into it. I think that a better order on chapters can help on the process of reading the whole book as it guides the lector to the correct section it is looking for in an organized way.

![order-on-ebook-cakephp](https://user-images.githubusercontent.com/794046/40741216-f53153ce-6418-11e8-8d21-386bb3016637.jpg)

---

**Do you want to address this issue?**

I could help on my spare time on organizing the chapters or sections as needed.

**Comment by markstory** [comment]
Help on reorganizing the epub-contents would be greatly appreciated.

**Comment by emartinez06** [comment]
Which branch do I need to use for make those changes? I already forked the project. Default it seems to be 3.0

**Comment by markstory** [comment]
Yes `3.0` is the correct branch if you want to update the docs for 3.x
