### ISSUE TITLE
UUID convention misleading

### ISSUE THREAD

**Issue by dsofeir** [cakephp/docs#5823]
**Issue Description**
In [Database Conventions](https://github.com/cakephp/docs/blob/3.0/en/intro/conventions.rst#database-conventions) towards the bottom of the section there is the following passage:

> In addition to using an auto-incrementing integer as primary keys, you can also use UUID columns. CakePHP will create UUID values automatically using (`Cake\Utility\Text::uuid()`) whenever you save new records using the Table::save() method.

From this I got the impression that if there was a field called `UUID` in the database or Model this would be automatically populated with a UUID on save, however after reviewing the code this is not what happens and I had to extend the save function to get this behavior.

So I am arguing this piece of documentation is misleading.

I can propose alternate language if everyone agrees?

**Comment by lorenzo** [comment]
sure, I’m all for making it more clear

**Comment by othercorey** [comment]
As a new user, I'd argue that this is clearly only talking about primary keys on insert.  It would be confusing to see columns named "UUID" auto-generated in this section.  I would be less confused to see it in a table Behavior's section.

**Comment by dsofeir** [comment]
@othercorey Thank you, I had forgotten about this ticket. I'm not entirely sure I understand your point.

I think the the following sentence suggests that CakePHP will do something with UUIDs __automatically__ when you use the `Table::save()` function.

> CakePHP will create UUID values automatically using (Cake\Utility\Text::uuid()) whenever you save new records using the Table::save() method. 

I've looked at the source and the function `Cake\Utility\Text::uuid()` is not called anywhere in the execution path of the `Table::save()` function.

So all I am suggesting is the passage:
> In addition to using an auto-incrementing integer as primary keys, you can also use UUID columns. CakePHP will create UUID values automatically using (Cake\Utility\Text::uuid()) whenever you save new records using the Table::save() method.

Be changed to:
> In addition to using an auto-incrementing integer as primary keys, you can also use `Cake\Utility\Text::uuid()` to populate UUID columns when the `Table::save()` function is called.To do this add a UUID field to your model and then override `Table::save()` in the associated Table declaration in `src/Model/Table/ExampleTable.php`. When overriding `Table::save()` use the `Cake\Utility\Text::uuid()` to generate and set a UUID.

Or maybe the whole paragraph should be removed? I just think the current reference to UUIDs is misleading.

**Comment by othercorey** [comment]
The UUID is generated for the primary key only when saving a new Entity using `Table::save()`.  This happens in `Table::_insert()`.
```php
// Table::_insert
$id = (array)$this->_newId($primary) + $keys;

// UuidType::newId:
public function newId()
{
    return Text::uuid();
}
```

**Comment by dsofeir** [comment]
Interesting, so that didn't work when I was working on it. However that was months ago. Maybe this is a bug rather than an unimplemented feature? 

In any case I agree, the intent is there so the documentation is correct.
