### ISSUE TITLE
Links for adding admin and user in  Simple Acl controlled Application is not working.

### ISSUE THREAD

**Issue by shakil3** [cakephp/docs#5836]
**

**Issue Description**
In the documentation of 2x series it is written that "add some groups and users using the baked forms by browsing to http://example.com/groups/add
and http://example.com/users/add". But when i click to that link  nothing found to add user and admin.

---
![image](https://user-images.githubusercontent.com/22347062/44942142-fc24bd80-adcc-11e8-83d1-de64aff64b7d.png)

**Do you want to address this issue?**
yes

**Comment by markstory** [comment]
You have to replace `example.com` with your actual host name.

**Comment by shakil3** [comment]
Thanks @markstory for your instant support. Will you help me little bit more by providing information that how would i get my actual host name......

**Comment by shakil3** [comment]
i took my host name from cmd using ipconfig /all
Windows IP Configuration

   Host Name . . . . . . . . . . . . : DESKTOP-4IA6IPO
   Primary Dns Suffix  . . . . . . . :
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No

and browse to those site.
http://desktop-4ia6ipo/groups/add
http://desktop-4ia6ipo/users/add

but still nothing found.

**Comment by shakil3** [comment]
I replaced example.com with host name found by ipconfig / all in cmd. But
still it is not working.

**Comment by saeideng** [comment]
if its on your server `http://example.com/groups/add` works ( after replace with your domain )
if its on your local `http://localhost/yourproject/groups/add` works ( in most cases  )
you have to install apache + php and follow how to run php projects in local 
these links are true 

--------
join to Slack  if you need more help 

--------
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:
 
[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
