### ISSUE TITLE
Incorrect licence accidentally added to docs

### ISSUE THREAD

**Issue by Megslalk** [cakephp/docs#5846]
MIT licence was added to the docs accidently/incorrectly via https://github.com/cakephp/docs/pull/5399

Correct licence needs to be added asap - https://creativecommons.org/licenses/by-nc-sa/4.0/

**Comment by markstory** [comment]
* 3.0 docs were updated in 7bec32bc57bd6a231ec44fadaf8d58822c40c5b2
* 4.0 docs were updated in c099d092ed989bc0ab9c3f5afa1544e12577a05d
