### ISSUE TITLE
Sending a String as File

### ISSUE THREAD

**Issue by arilia** [cakephp/docs#5847]
**Issue Description**

[Here](https://book.cakephp.org/3.0/en/controllers/request-response.html#sending-a-string-as-file) the manual suggest to use the deprecated `body()` method so I get deprecation warning If I use the suggested code

**Comment by ravage84** [comment]
@arilia thanks for pointing this out.

You are right, the docs are outdated in case of this example.

See the API docs:
https://api.cakephp.org/3.6/class-Cake.Http.Response.html#_body

Would be able to send us a pull request with the necessary changes to fix this example?
See the following example, which contains the old and  new way:

https://book.cakephp.org/3.0/en/controllers/request-response.html#setting-cookies

**Comment by arilia** [comment]
I'm not very good at this.

Anyway I created a PR, see https://github.com/cakephp/docs/pull/5850

**Comment by ravage84** [comment]
Don't worry. We all started small. :smirk_cat: 
Closing as PR is open.
