### ISSUE TITLE
Add deprecation to Csrf component, favor to Csrf Middleware

### ISSUE THREAD

**Issue by Aerue** [cakephp/docs#5865]
**Issue Description**

Documentation never warning about the conflict between  Csrf component and Csrf Middleware.

Maybe the doc should be updated to warning about this conflict like said in the install skeleton documentation...

https://github.com/cakephp/cakephp/issues/12453
https://github.com/cakephp/docs/commit/adcb9005876bbb04157bfa90875357536a7c4fc0

**Comment by ravage84** [comment]
Well the documentation states that the component is deprecated here:

https://book.cakephp.org/3.0/en/controllers/components/csrf.html

> Deprecated since version 3.5.0: You should use Cross Site Request Forgery (CSRF) Middleware instead of CsrfComponent.

Where and how would you improve thta?

**Comment by Aerue** [comment]
Having both Csrf component and Csrf middleware on the doc is a little bit confusing, maybe remove the deprecated one from the 3.x doc and only display on 3.0 <=> 3.4 ?

**Comment by ravage84** [comment]
@Aerue in the past sometimes we removed such documentation but that led to confusion for people still using the deprecated parts of the framework. Not everybody can rip out and replace code that use deprecated parts of a framework.

Unfortunately, we have no documentation for 3.0 - 3.4, separately. Maintaining them would be way too much work.

Do you see another way to improve?

**Comment by Aerue** [comment]
The major issue here, it's i checked the doc, but didn't see the deprecation warning, i go directly on the github issue to find the deprecated message on the skeleton, so maybe we can impove the visibility of deprecated warning ?

**Comment by saeideng** [comment]
>visibility of deprecated warning ? 

it shows if you use both Csrf component/middleware together 
this is a soft deprecation
I think we can close the issue
