### ISSUE TITLE
[3.x/4.x][RFC] Step-by-Step Guide for Integrating FriendsOfCake/bootstrap-ui

### ISSUE THREAD

**Issue by ravage84** [cakephp/docs#5867]
Refering my comment in https://github.com/cakephp/app/issues/635#issuecomment-426587452

> Instead of adding and fully integrating FriendsOfCake/bootstrap-ui into the app sleketon, we could also add a prominent step-by-step manual for that in our Cookbook. This way we do not need to adopt the plugin as core plugin but still can push its use and provide a clear path for people wanting a Bootstrap UI.

What do you guys feel about adding a step-by-step guide for integrating ``FriendsOfCake/bootstrap-ui`` into the app template to the documentation for 3.x or 4.x?

This could lead to a tighter inclusion of our plugin ecosystem.

**Comment by markstory** [comment]
> What do you guys feel about adding a step-by-step guide for integrating FriendsOfCake/bootstrap-ui into the app template to the documentation for 3.x or 4.x?

I could see providing a link out to the plugin docs, but maintaining plugin docs inside the core docs could get complicated as we may fall out of sync with the code.

**Comment by ravage84** [comment]
Issue is still valid
