### ISSUE TITLE
RFC: Remove minor version from URL of 4.0 docs

### ISSUE THREAD

**Issue by garas** [cakephp/docs#5891]
As minor versions (3.1, 3.2, ...) were released, version string in URL left `3.0`.

Readers might be misled that it is docs for older version.

As changing URL with each minor release is unfeasible, I suggest (starting with version 4) to change it to simply `4`, or to `4.x` as in version drop-down.

Another option would be to use `current` or `latest` like in Symfony, and change URL to simple `4` or last minor ex. `4.7` only when releasing new major version.

**Comment by markstory** [comment]
> As changing URL with each minor release is unfeasible,

Is it? We could have additional branches for each minor and add jenkins jobs to deploy each branch as well. It is more work but its not unfeasible.

> .. change it to simply 4, or to 4.x as in version drop-down.

:+1: to `4.x` if we stick with one edition of the docs for the entire major.

> Another option would be to use current or latest

We could do this today, it is a small amount of nginx changes. We already have https://api.cakephp.org/2.latest and https://api.cakephp.org/3.latest. Being consistent would be :+1:

**Comment by garas** [comment]
The _unfeasible_ is too strong term I used with my sometimes poor English dictionary. I meant it could be too much work to maintain (and translate) multiple minor versions, and to backport improvements.

If  `current`/`latest`, it should stay in URL, not redirect. Ex. `https://book.cakephp.org/latest/en/orm.html` should be URL for version 4, then 5 etc. As the advantage, it would be the same URL in my browser history even after mayor version changes and I will be able use browser autocomplete, and not book TOC or search. As disadvantage, there is no version in URL, also it might have some impact with SEO when renaming to archived URL.

**Comment by othercorey** [comment]
Just to offer another opinion, I think using either 4.x or just 4 makes the most sense.

If you have a minor version in the URL, people might try to change it to their version.  Currently, the 404 is a mess and will confuse them.  

You could use /latest/ but /4.latest/ still implies there is another version out there.

**Comment by ADmad** [comment]
My vote is for just `/4`.

**Comment by saeideng** [comment]
:+1:  to 4.x

just should done  before other release :)

**Comment by othercorey** [comment]
So...

Redirects:
`/2.0/` > `/2/`
`/3.0/` > `/3/`

Add:
`/4/`

Or...

Redirects:
`/2.0/` > `/2.x/`
`/3.0/` > `/3.x/`

Add:
`/4.x/`

For latest, there are several examples.  Here is an example from postgres that does use a `/current/` url. However, it does not redirect the URL to /12/ instead keeps the url as /current/.

Version 12 is very new and most people aren't using it, but it is 'current'.
https://www.postgresql.org/docs/current/datatype-datetime.html 

Has version links on the top
>Supported Versions: Current (12) / 11 / 10 / 9.6 / 9.5 / 9.4

**Comment by markstory** [comment]
I'm good with `/2/`, `/3/` etc. As long as we include redirects for the existing URLs.

**Comment by othercorey** [comment]
@markstory are you running different nginx instances for each book version?

**Comment by markstory** [comment]
@othercorey Yes. Each book instance runs in their own docker container, and then there is a top-level nginx that routes across the containers. I can take care of the top level nginx configuration as it isn't a public repository if someone gets the version containers updated.

**Comment by saeideng** [comment]
thank you
