### ISSUE TITLE
CsrfProtectionMiddleware documentation ambiguous

### ISSUE THREAD

**Issue by smarek** [cakephp/docs#5893]
Usage of CsrfProtectionMiddleware is ambiguous through the docs and examples

default app skeleton registers the middleware and uses it in routes
https://github.com/cakephp/app/blob/master/src/Application.php#L71
https://github.com/cakephp/app/blob/master/config/routes.php#L53

but the docs say, to add the middleware to the middlewareQueue on Application build
https://book.cakephp.org/3.0/en/controllers/middleware.html#cross-site-request-forgery-csrf-middleware

**Comment by smarek** [comment]
Looks like either one is OK, but using both at once, will cause the "CSRF token mismatch" error, even when using singleton for both $middlewareQueue->add and $routes->registerMiddleware

**Comment by markstory** [comment]
Yes you can do either approach, but they behave differently.  When applied in the application middleware hook, *all* actions in an application have CSRF checks applied. When applied through routing scopes specific route groups can be included/excluded.

Do you have a suggestion on how we could make both scenarios easier to understand? Should the docs only use scoped middleware in its examples?

**Comment by smarek** [comment]
@markstory thanks for clarification, I've made proposal PR for english version of docs in #5894

**Comment by markstory** [comment]
Closing this as the pull request is open now.
