### ISSUE TITLE
3.x findOrCreate() is not documented

### ISSUE THREAD

**Issue by ravage84** [cakephp/docs#5995]
The CakePHP 3.x ORM method [findOrCreate()](https://api.cakephp.org/3.7/class-Cake.ORM.Table.html#_findOrCreate) is nowhere documented in the book.

At best it should showcase an example with the callback.

Related [tests](https://github.com/cakephp/cakephp/blob/1d82fdd7fd1adceae640ee0f5e8e3f6d6cf3e95e/tests/TestCase/ORM/TableTest.php#L5651-L5840).

**Comment by dereuromark** [comment]
I just found the same issue when checking..

**Comment by dereuromark** [comment]
Also the callback option could need some examples or showcasing / use cases.

**Comment by challgren** [comment]
Could this maybe crosslinked in `Retrieving Data & Results Set`. I was looking for this and expected it in `Retrieving Data` instead of `Saving Data`

**Comment by ravage84** [comment]
@challgren I guess, it could. Please open a new Pull Request.
