### ISSUE TITLE
Failed to load PDF document.

### ISSUE THREAD

**Issue by edenramoneda** [cakephp/docs#6000]
I tried to open the pdf documentation for CakePHP but it returns error 
Failed to load PDF document.
![Untitled](https://user-images.githubusercontent.com/28981352/54974365-c6486000-4fce-11e9-9127-4612f10cd015.png)

**Comment by saeideng** [comment]
I test it with FF , also  I download it with a downloader , it works for me 
just with chrome I could not

**Comment by edenramoneda** [comment]
How can I download it?

**Comment by saeideng** [comment]
this problem should fix by cake itself but for now  you can download it with an App

>How can I download it?

just like other files 
 like uget/IDM/wget , ....

**Comment by saeideng** [comment]
I used uget but it taken more than 6 mins for 2Mb file

**Comment by edenramoneda** [comment]
It getting errors in IDM also I think I should try uget/wget

**Comment by saeideng** [comment]
until fixing this problem there is another way and it is making pdf in local 
https://github.com/cakephp/docs#building-the-pdf

**Comment by edenramoneda** [comment]
I downloaded it through my phone and it works. Thanks :-)

**Comment by edenramoneda** [comment]
It's so nice PDF! the contents is all the same as web documentation, I hope all frameworks have this we could just read documentation even offline. Good Job!Thank you again

**Comment by saeideng** [comment]
problem has been solved 
you can use chrome or any other application
