### ISSUE TITLE
Cakephp 4 Use session in a static method

### ISSUE THREAD

**Issue by jimgwhit** [cakephp/docs#6051]
I recently tried cakephp 4.  I had a need to get some session data in a static method.

See https://discourse.cakephp.org/t/solved-use-session-in-static-method-cakephp-4/6011

Got it resolved using:
```
Router::getRequest()->getSession()->read
```

However before I asked I could not find anything in the docs on how to use session in a static method.  Of course what the docs show did not work:
```
$this->getRequest()->getSession()->read //in static method
```
Can that be added to the docs, a short sentence showing how to use session in a static method..

Also, how would you come up with that, when there's nothing in the docs showing it, or didn't see it in the API.  Could you please explain how you'd know to use Router, pretending you were not a framework developer, and didn't know cakephp that well.

I searched the session chapter for "Router", no results.

I searched the router chapter for "session", no results.  Of course if you are one who writes and maintains the framework, you'd know this.

I ask this, because I am not new to this, I have used both cake and laravel for a while.  And plan to use cakephp for an upcoming project.

To me, this would make more sense:
```
Session::getRequest()->getSession()->read...
```

In laravel you can just:
```
$userrole = Session::get('thisrole');  // or whatever it is
```

**Comment by markstory** [comment]
We don't document reading session data from a static context as that isn't a scenario that our abstractions handle.

Instead of static access we try to encourage folks to pass the request or session object into their static functions. If that is not possible the `$_SESSION` super global works as it does in vanilla PHP.

> Can that be added to the docs, a short sentence showing how to use session in a static method.

We could. I am not sure why passing the session is a parameter would require explicit documentation though.

**Comment by jimgwhit** [comment]
@markstory

So in my helper if I put instance methods:
```
    public function chkRole($role = null)
    {
        $userrole = $this->getRequest()->getSession()->read('userrole');
        $checkrole = explode(',', $userrole);
        if (in_array($role, $checkrole)) {
            return true;
        }
        return false;
    }

```

But still want to call it statically, is there any thing wrong with this:
```
<?php

namespace App\Helpers;

use App\Helpers\ChkAuth;

class Auth
{
    public static function __callStatic($method, $params)
    {
        $instance = ChkAuth::class;
        $c = new $instance;
        return $c->$method(...array_values($params));
    }
}
```

Usage:
```
if (Auth::chkRole('admin') === true) {
//  more code.
```

That's how I use make "static" looking calls.

**Comment by markstory** [comment]
Couldn't the request/session be a parameter to `chkRole()`? That would remove the need to pull the request out of a global scope.

**Comment by jimgwhit** [comment]
@markstory of course that would work but would mean so much more code anywhere the usage was necessary.

Instead of a short and nice looking

```
if (Auth::chkRole('admin') === true) {
```

I would have to get the request every time I pass it, and cumbersome code all over the controller and model.

Too bad there's not facades in Cake PHP also.

Is there a short and nice-looking way to do as you suggested.

**Comment by dereuromark** [comment]
See how [TinyAuth](https://github.com/dereuromark/cakephp-tinyauth) provides a component and helper as convenience wrappers. No static calls necessary.
`$this->AuthUser->foo()` etc
You could do sth similar for your custom requests on the different levels.

**Comment by jimgwhit** [comment]
Another point is the documentation States at session is also available in helpers.

And many helpers use static methods.

Seems like you would have some sort of facade to easily use session in a helper kind of like laravel has facades.

That's the whole purpose of static looking calls, they are pretty.

Rather than having three four or five arrows.

A static looking call whether truly static or not it's nice looking short and sweet.

My call static method kind of duplicates that but not truly a facade.

And I usually don't like outside packages.

**Comment by jimgwhit** [comment]
Please see previous reply also.

I tried this:

Mad a class called SessionHelper:
```
<?php

namespace App\Helpers;

use Cake\Http\Session;

class SessionHelper
{
    public static function __callStatic($method, $params)
    {
        $instance = Session::class;
        $c = new $instance;
        return $c->$method(...array_values($params));
    }
}
```

In the class with static calls added use statement:
```
<?php

namespace App\Helpers;

use App\Controller\AppController;
use Cake\Core\Configure;
use App\Helpers\SessionHelper as session;

class ChkAuth extends AppController
{
// more
```

And just tested if it works:
```
    public static function chkLog($role)
    {
        $userrole = session::read('userrole');
        return $userrole;
```

That works.  Any way you can add a nicer helper to do this statically like above.

I would love to add a facade myself, but I never have worked with facades.

I would then have to add it into vendor via composer.  Right now my knowledge is limited to code outside of vendor, like the above.

**Comment by markstory** [comment]
Accessing the session through Router is because of some historical reasons. In earlier versions of Cakephp we offered a way to simulate sub-requests, and needed a way to keep track of the current 'request stack'. That place ended up being `Router` and `Router::getRequest()`. From the request you can get the session object.

Getting the current request from Router is not a method that will be going away soon.

**Comment by jimgwhit** [comment]
Weird how router offers a static method but session doesn't.  

Why is that I'm just so curious here.

**Comment by markstory** [comment]
Personally, I wouldn't use the __callStatic() approach. I find it adds indirection that I would need to re-read. I would also explore ways to structure code so that I don't have as many statics. I have been burned a few times in the past from many static functions and global mutable state though.
