### ISSUE TITLE
Adding schema.tablename format to Table::setTable() description

### ISSUE THREAD

**Issue by othercorey** [cakephp/docs#6059]
I found this issue where support for specifying a schema for a table was added in the form of 'schema.tablename'.

https://github.com/cakephp/cakephp/pull/4340

Since I'm working through the issues of using a legacy postgresql schema + table that requires double quotes, I initially assumed this needed to be specified in a postgres format of 'schema."table-name"'.

However, this isn't how the schema + table string is used internally and the quoting actually breaks the cake schema reflection.  For someone like me who is moving too fast to realize, a note that the schema is supported in 'schema.tablename' and that it should be the raw table/schema name would be helpful.

At the moment, the API documentation just says:

> Sets the database table name.

**Comment by othercorey** [comment]
I don't mind providing a patch, if this is information you want to publish.  Do you normally put implementation details like this in the api or book?

**Comment by markstory** [comment]
I think including it in the API makes sense for this as I don't think we introduce the schema.table form in the book.

**Comment by othercorey** [comment]
After looking at the code, I realized that insert might be broken for schema.table names.  I didn't need this functionality so I never tested it before.

If the table name requires quoting, then the insert will fail as it uses the raw name from Table::setTable().

However, you cannot currently quote the table name in the called to Table::setTable() because Collection::describe() doesn't handle it properly.

I can open an issue on the cakephp repository for this and might be able to provide a patch.

**Comment by markstory** [comment]
@othercorey Have you tried enabling `identifierQuoting`? it might help with the table name needing quotes.

**Comment by othercorey** [comment]
That did fix the issue on insert, thanks for reminding me.  We had disabled autoquoting because we have an awful mix of legacy tables using column names with spaces and have places were we manually quote to avoid issues.  I've been evaluating and mitigating all the issues of switching to cakephp from an internal orm while working to move way from these legacy tables.

**Comment by othercorey** [comment]
I'm going to close this as the API change will happen in cakephp repo.
