### ISSUE TITLE
Cannot build html docs with DockerHub image

### ISSUE THREAD

**Issue by othercorey** [cakephp/docs#6063]
The cakephpfr/docs DockerHub image recommended for building the html docs does not include cakephpsphinx in the requirements.txt file which causes the build to fail.

This issue is in both light and full cakephpfr/docs images.

> Status: Downloaded newer image for cakephpfr/docs:light
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ImportError: No module named cakephpsphinx

**Comment by markstory** [comment]
@othercorey Where is that image recommended? I don't think it has been maintained in a number of years, and building your own image from the Dockerfile in the repository should work better.

**Comment by othercorey** [comment]
Recommended might be the wrong word, but it comes first in the README.md file for building the docs.

**Comment by markstory** [comment]
Thanks. I'll get that updated.

**Comment by othercorey** [comment]
On a related note, you might consider moving to the debian:stretch base image.  The jessie packages were moved off to the archive server and unless you manually pull the latest jessie image, you get a really confusing error about missing package servers.

The ticket where they updated the issue begs users to migrate off jessie lol.

Unfortunately, docker doesn't auto-update the base image when building a dependent image.

**Comment by othercorey** [comment]
We can close this as the Dockerfile built image works.
