### ISSUE TITLE
Calling out importance of setting SQL function argument type

### ISSUE THREAD

**Issue by othercorey** [cakephp/docs#6077]
One of the difficult things about learning CakePHP ORM is walking through the query documentation.  While it covers almost everything at some point, sometimes it's difficult to pick out the magic words.  This is especially true of query-builder.rst which feels like one big sentence sometimes.

That specific page is so dense that I really only know what's in there from a search result or looking through the side menu.

https://book.cakephp.org/3.0/en/orm/query-builder.html#using-sql-functions

Would there be any objections to breaking this part up a little bit for users looking for specific answers?  The information about properly setting the argument type is important to avoid some confusing SQL errors such as SUM(text) overload does not exist.

I think the 'Using SQL Functions' section is fine up to the new version notes.  I'd like to make the information about argument types a separate section at least so it shows up in the side menu.

Then the information about dynamic func() building should be called out more than a footnote. 

>In addition to the above functions, the func() method can be used to create any generic SQL function such as year, date_format, convert, etc. 

This section starts off by telling you what functions it supports and then ends by saying don't forget to use the same function we just mentioned in a different way.  I think it could be re-worded better.

- Using SQL Functions
- Passing Arguments
- Custom Functions

**Comment by markstory** [comment]
Adding more headers sounds reasonable to me.
