### ISSUE TITLE
Instructions to retrieve socket file path

### ISSUE THREAD

**Issue by karmicdice** [cakephp/docs#6135]
**Issue Description**

Refers to [issue 351 at migrations](https://github.com/cakephp/migrations/issues/351)
---

**Do you want to address this issue?**

Yep.

**Comment by ravage84** [comment]
@karmicdice it wasn't necessary to create this issue. Referencing the original issue in the new PR is fine.

**Comment by karmicdice** [comment]
My bad. Will take care in future :)
