### ISSUE TITLE
Linking from the Book to the API docs

### ISSUE THREAD

**Issue by mehov** [cakephp/docs#6138]
I'm looking at [CookBook → Deleting Data → Bulk Deletes](https://book.cakephp.org/3.0/en/orm/deleting-data.html#bulk-deletes)

Right now it shows

    Cake\ORM\Table::deleteAll($conditions) ¶

without providing any further info on the `$conditions` format or requirements. Looking up the source myself has proved to always clarify the idea faster than asking on the internet, so normally I'd manually go to api.cakephp.org → specifically search for `deleteAll` → click on [class-Cake.ORM.Table.html#_deleteAll](https://api.cakephp.org/3.8/class-Cake.ORM.Table.html#_deleteAll) in autocomplete.

I may have been doing this wrong all this time, but unless I'm missing something, I believe the user experience here can be improved by cross-linking to corresponding API/source code directly. I think I've even seen it somewhere in your documentation already.

I realise I can contribute that exact link myself, but I guess you have the final code generated automatically anyway, plus there's a lot of links to put throughout the whole documentation, so doing this manually would use a lot more man hours compared to having this automated.

**Comment by ravage84** [comment]
I totally agree. This is about Developer Experience.
Over and over I ran into this, too.
My browser recommends me api.cakephp.org, when I start to type "api", so not much of a hassle for me, but it really could be improved.

If it only was for a static badge on the view port side (next to linking to the latest API docs of this release branch.

A quick mockup:

![grafik](https://user-images.githubusercontent.com/625761/60882714-b9cbd880-a248-11e9-961b-0f23f90fc847.png)

**Comment by othercorey** [comment]
I would not expect every code sample to have a link to the api documents.  It's just not feasible with the code formatter.

A static badge would be too hard for anyone to find.  I think just putting a link to the API docs on the nav bar would work.  It would have to link to latest point release of the major version.

Then a note on the Welcome page explaining that you'd start with the cookbook and look at the API docs for detailed notes on parameters and options.
