### ISSUE TITLE
Client adapter info

### ISSUE THREAD

**Issue by dereuromark** [cakephp/docs#6140]
https://book.cakephp.org/3.0/en/core-libraries/httpclient.html#

The Client is missing the info about default engine (curl), but also engine/adapter and how to switch in general.
Or maybe we just want to outline what is inside code doc block?
```
     * - adapter - The adapter class name or instance. Defaults to
     *   \Cake\Http\Client\Adapter\Curl if `curl` extension is loaded else
     *   \Cake\Http\Client\Adapter\Stream.
```
The curl part being available and otherwise fallback might be interesting.

**Comment by markstory** [comment]
Pull request open.
