### ISSUE TITLE
Add table of contents to Migrations page

### ISSUE THREAD

**Issue by Schlaefer** [cakephp/docs#6148]
The Migrations page [1] is very long, it would be nice if a TOC could be added for quick navigation.

[1] https://book.cakephp.org/migrations/2.x/en/

PS: The presentation of those non-core(?) modules is a little bit confusing. In this case I had to check thrice that I wasn't looking at CakePHP 2.x documentation.

**Comment by garas** [comment]
There is [contents page](https://book.cakephp.org/migrations/2.x/en/contents.html), but link is hard to discover.

I agree TOC should be in page itself too.

The same issue applies to other plugins.

**Comment by markstory** [comment]
Would you want to see an on page table of contents [similar to this](https://book.cakephp.org/3.0/en/development/configuration.html)?

**Comment by Schlaefer** [comment]
Yes - sorry if I wasn't clear on that - I meant the gray box on the right outlining the page [1]. It would make the page much more accessible for looking up a particular Migrations feature. I could swear it was there before.

[1] https://i.imgur.com/JDhjP0D.png

**Comment by markstory** [comment]
All the plugin mini-sites should have Page contents now.
