### ISSUE TITLE
Version switcher taking me to the index page, not the doc page I was on

### ISSUE THREAD

**Issue by mehov** [cakephp/docs#6153]
What I did:
----

1. [google.com/search?q=cake\orm\query](https://www.google.com/search?q=cake%5Corm%5Cquery)
2. click on [api.cakephp.org/3.2/class-Cake.ORM.Query.html](https://api.cakephp.org/3.2/class-Cake.ORM.Query.html), the first result on the SERP
3. manually edit *3.2* (the version in the URL) to *3.8* (the latest right now) in the page URL

What I want
----

Choosing a version in the switcher takes me to that exact documentation page for another version, if available. Currently it takes to the index page, e.g. [api.cakephp.org/3.8/](https://api.cakephp.org/3.8/)

**Comment by markstory** [comment]
I'm not sure how to get ApiGen to do this, but I agree it would be an improvement.

**Comment by othercorey** [comment]
This should be working now.

https://api.cakephp.org/
