### ISSUE TITLE
REST document page is incorrect in REST implementation

### ISSUE THREAD

**Issue by riddlemd** [cakephp/docs#6158]
https://book.cakephp.org/3.0/en/development/rest.html sample code uses a named parameter from a GET request to delete an entity. This is an incorrect implementation of REST.

---

The sample delete code should check if the request is of type DELETE or at the very least prevent deletes from happening from a GET request. GET requests are subject to prefetching and auto reloading (incases where the browser opens again after crashing or closing) which can cause unwanted behaviour such as accidental deletions.

**Comment by dereuromark** [comment]
The actions might be missing 

    ->request->allowMethod()

calls

**Comment by markstory** [comment]
> sample code uses a named parameter from a GET request to delete an entity. This is an incorrect implementation of REST.

Are you referring to the following

```php
public function delete($id)
 {
...
}
```

This doesn't read from a query string parameter, and instead reads from a path segment. The documentation also suggests using `RouterBuilder::resources()` to generate RESTful routes. This method only ensure that only `DELETE` method requests are forwarded to the delete method. Is there something I'm not understanding about the problem?

**Comment by riddlemd** [comment]
The issue with delete is that regardless of if parameterized, named, or query input is used to designated the id of a resource the request is still being done via GET. GET should never be used to perform an action that results in a state change or deletion of a resource. GET can be pre-cached by the browser (as in all the links on a page can be requested, without user performing the action) which would result in all resources on a given search page being deleted IF there is a delete link on the search page for each resource. GET requests can also be autoreloaded by browsers when they start up from a closed or crashed state resulting in resubmission of stale data over fresh data.

**Comment by markstory** [comment]
@riddlemd As an example doing a `GET /articles/123` will simply fetch the article, and this is fine to cache/prefetch as it is a read operation. One would need to do `DELETE /articles/123` in order to effect a change. With the routes generated by `RouteBuilder::resources()` a client cannot make a GET call to the `delete()` method.

I completely agree that using GET requests to effect deletes is a terrible idea, but that isn't how the RESTful routes that CakePHP generates work.

**Comment by riddlemd** [comment]
When using RouteBuilder::resources() you are correct -- but if they implement their own restful (or restlike) routing the example WILL accept a GET request, I just found it inconsistent with the other methods (add and edit) both check for POST/PUT.

**Comment by riddlemd** [comment]
It makes sense in context of the `RouteBuilder::resources()`, but if someone implements their own routing (for whatever reason) the example code will present issues -- just something to be mindful of as the `RouteBuilder::resources()` is only mentioned as a quick way, not a prefered way in the documentation.

A simple DELETE/POST/PUT check would alleviate a LOT of pain for some unweary soul down the road.

Also it's a bit weird that edit checks PUT/POST but add does not.

**Comment by markstory** [comment]
Pull request open now.
