### ISSUE TITLE
Label deprecated methods as such under Method Summary

### ISSUE THREAD

**Issue by mehov** [cakephp/docs#6160]
This is a screenshot of Method Summary on [this page](https://api.cakephp.org/3.8/class-Cake.Database.Schema.TableSchema.html). Both [`column()`](https://api.cakephp.org/3.8/class-Cake.Database.Schema.TableSchema.html#_column) and [`columnType()`](https://api.cakephp.org/3.8/class-Cake.Database.Schema.TableSchema.html#_columnType) methods are deprecated as of 3.5; the documentation is for 3.8.

Current look:
----
<img width="607" alt="Screenshot 2019-08-12 at 11 22 00" src="https://user-images.githubusercontent.com/7813306/62853076-ebc2d580-bcf3-11e9-8faf-61fb9a16312f.png">

Suggested look:
----
<img width="586" alt="Screenshot 2019-08-12 at 11 24 02" src="https://user-images.githubusercontent.com/7813306/62853078-ec5b6c00-bcf3-11e9-9b90-1a44588ce04b.png">

Reasoning:
----
I could tell something was off because I knew about the transition to explicit `set...`/`get...` method naming. I had to go down to the method details to confirm it indeed says: 

> **Deprecated** 3.5.0 Use setColumnType()/getColumnType() instead

Someone not knowing/thinking about the deprecation could've simply closed the page after confirming the method exists, without looking down to its details, and then learned about the deprecation later, potentially the hard way. 

Technically yes, that would still be their fault, but if the experience can be improved and made more fool-proof, then why not? :)

**Comment by markstory** [comment]
Fixed in cakephp/cakephp-api-docs#67e7790b6e79e8124ad7f3e6698940ea8e027ef3

**Comment by mehov** [comment]
Yep, seeing it already. Thank you! :)
