### ISSUE TITLE
Docker for Cakephp

### ISSUE THREAD

**Issue by sra122** [cakephp/docs#6170]
**Issue Description**

Docker setup for the Cakephp is not documented. 

---

**Do you want to address this issue?**

**Comment by markstory** [comment]
Are you looking for a base image for development or for production?

**Comment by sra122** [comment]
development

**Comment by markstory** [comment]
One reason we don't provide docker images for development is because folks need databases, caching and the combinations of those requirements become too complicated for us to reasonably manage.

**Comment by othercorey** [comment]
They'd need to publish a docker compose file along with the cakephp dev dockerfile at a minimum.

Running multiple main processes in a single container is wrong and would require much more work to write/maintain.

**Comment by MayMeow** [comment]
I using docker to run cakephp from to time to time :) Here is how my configs looks like. https://github.com/MayMeow/docker-for-cakephp Maybe it can help

**Comment by inoas** [comment]
Here is my take https://github.com/htstudios/cakephp-docker-compose-box
Features Nginx FPM CLI/Bash Redis Memcached Postgres MariaDB Mailhog
