### ISSUE TITLE
Problem Uploading the EPUB file to e-Readers.

### ISSUE THREAD

**Issue by assunluis80** [cakephp/docs#6176]
The EPUB version (CakePHP.epub) which can be downloaded from https://book.cakephp.org/3.0/en/index.html it's not working on Google Play Books, Bookari, eBoox, AIReader and several others e-Book readers. 

On the Google Play Books page for troubleshooting uploading: https://support.google.com/googleplay/answer/3097151, they suggest to validate the cause of the unavailability to upload, using the following validator: http://validator.idpf.org/, which throws a bunch of errors for the version 3.8 of CakePHP.epub.

**Comment by othercorey** [comment]
@markstory After updating to sphinx 1.8.5 and enabling HTML5 output (default in sphinx 2.x), I re-ran the validator.  Most of the errors are due to invalid ids generating from the php classes.

>ERROR | contents.xhtml | 244 | 113 | 'development/configuration.xhtml#namespace-Cake\Core' is not a valid URI.

```
<div class="section" id="namespace-Cake\Core">
```

```
Configure Class
===============

.. php:namespace:: Cake\Core

.. php:class:: Configure
```

**Comment by othercorey** [comment]
@markstory I took at look at the phpdomain code, but I'm not sure what generates this id string. There are multiple places that have the "'namespace-' + name" format.

**Comment by Marty** [comment]
I also just ran into this issue. The current version is still rejected by all common epub readers :(

**Comment by othercorey** [comment]
@Marty Can you give me an example of an epub reader that doesn't load? I tested a couple free e-readers and they were able to load it.

**Comment by Marty** [comment]
Google books for example. Also validator.idpf.org shows many errors.

**Comment by markstory** [comment]
I downloaded a file tonight and was able to open it in MacOS Books. There are quite a few validation errors in the output of validator.idpf.org. Some are coming from the sphinx base templates. We are working on an upgrade to sphinx, hopefully that helps solve some of these problems.
