### ISSUE TITLE
How to Test a Plugin utilizing a test_app is not documented

### ISSUE THREAD

**Issue by ravage84** [cakephp/docs#6177]
The current [plugin testing section](https://book.cakephp.org/3.0/en/development/testing.html#creating-tests-for-plugins) of the book, does not showcase how to test parts of a plugin that can only be tested thoroughly utilizing a [test app](https://github.com/cakephp/cakephp/tree/bbd4abe94c6c6c0b86af19b66beb750e32a69d9b/tests/test_app), such as the CakePHP built-in tests use.

Having such a documentation could help plugin developers in their quest to test their code.

**Comment by dereuromark** [comment]
Please include Routing part as well :) for such thing

**Comment by dereuromark** [comment]
The stale bot is not helpful here IMO. The docs wont get better if those valid issues just get closed.

**Comment by andretefras** [comment]
Hello guys. I will do it in the next week. As soon as I have something done I share with you to get inputs.
