### ISSUE TITLE
Could be a typo on /3.8/class-Cake.ORM.Query.html#_identifier

### ISSUE THREAD

**Issue by mehov** [cakephp/docs#6178]
https://api.cakephp.org/3.8/class-Cake.ORM.Query.html#_identifier

> Example
> $query->newExp()->lte('count', $query->identifier('total'));

Should this not be `$query->newExpr()`?

**Comment by mehov** [comment]
If needed, I can edit and commit

**Comment by lorenzo** [comment]
Yes, your suggestion is correct. Please send a correction :)
