### ISSUE TITLE
4.x File input example should be in sync with Zend Diactoros?

### ISSUE THREAD

**Issue by karmicdice** [cakephp/docs#6189]
As in : https://book.cakephp.org/4.0/en/views/helpers/form.html#creating-file-inputs

It shows: 

```
$this->request->data['submittedfile']

// would contain the following array:
[
    'name' => 'conference_schedule.pdf',
    'type' => 'application/pdf',
    'tmp_name' => 'C:/WINDOWS/TEMP/php1EE.tmp',
    'error' => 0, // On Windows this can be a string.
    'size' => 41737,
];
```

Rather it should be :

    $destination = <Path to upload> . $data['field']->getClientFilename()
    $data['field']->moveTo($destination)

Investigated the change based on Based on :

![Image of beta update](https://i.imgur.com/PVbObEg.png)

Please let me know if we should be using Zend Diactoros based functions directly? If so, I will write a proper doc and send a PR

**Comment by karmicdice** [comment]
Made it more instructured keep `$this->request->getData(field)` instead of the the usual `$data['field']`

**Comment by markstory** [comment]
Closing as there is a pull request open now.
