### ISSUE TITLE
The 4.0 Docs on PaginatorHelper->counter is wrong

### ISSUE THREAD

**Issue by hydraheim** [cakephp/docs#6194]
**Issue Description**

[The docs on PaginatorHelper's counter method](https://book.cakephp.org/4.0/en/views/helpers/paginator.html#creating-a-page-counter) (4.0, possibly also 3.0) is wrong. The docs state:

> The wording output by the counter() method can also be customized using special markers:

```
<?= $this->Paginator->counter([
    'format' => 'Page {{page}} of {{pages}}, showing {{current}} records out of
             {{count}} total, starting on record {{start}}, ending on {{end}}'
]) ?>
```

However, using an array as the first input raises an ArgumentCountException:

`Argument 1 passed to Cake\View\Helper\PaginatorHelper::counter() must be of the type string, array given.`

Simply removing the array and using a straight up string circumvents the issue. I.e:

```
$this->Paginator->counter('Page {{page}} of {{pages}}, showing {{current}} records out of
             {{count}} total, starting on record {{start}}, ending on {{end}}'
```
---

**Do you want to address this issue?**
Update the docs to correctly show usage of this helper's method.

**Comment by dereuromark** [comment]
This is only relevant to 4.x: https://github.com/cakephp/cakephp/compare/4.x#diff-9331fd78b8c7f46ba39642f792749d81R718

**Comment by markstory** [comment]
Thanks :+1:
