### ISSUE TITLE
Certificate expired for book.cakephp.org

### ISSUE THREAD

**Issue by othercorey** [cakephp/docs#6212]
It looks like the certificate expired October 05, 2019.

Start: (October 5, 2016, 12:00:00 AM GMT)
End: (October 5, 2019, 11:59:59 PM GMT)

**Comment by markstory** [comment]
Thanks for the issue. It is something we are working on resolving. Unfortunately only a few people have access to the web server configuration and they've been hardish to get a hold of.

**Comment by josegonzalez** [comment]
This has been resolved by provisoning an updated certificate. Thanks for the report.

**Comment by dereuromark** [comment]
See u again Sunday, September 26, 2021 :)
