### ISSUE TITLE
Dispatcher is deprecated. You should update your application to use the Http\Server

### ISSUE THREAD

**Issue by sitedyno** [cakephp/docs#6215]
**Issue Description**

As indicated [here](https://github.com/cakephp/cakephp/blob/3.next/src/Routing/Dispatcher.php#L28) Dispatcher is deprecated in 3.6

I can't find any mention of the Dispatcher [here](https://book.cakephp.org/3.0/en/appendices/3-6-migration-guide.html)

Is this deprecation actually addressed [here?](https://book.cakephp.org/3.0/en/appendices/3-3-migration-guide.html#psr-7-middleware-support-added)

---

**Do you want to address this issue?**
No.

**Comment by markstory** [comment]
Yes. The http/server code was added in 3.3, and the dispatcher was deprecated much later.

Are you looking for how to update your application?

**Comment by sitedyno** [comment]
> Are you looking for how to update your application?
Yes.

The end result is you have to used middleware in 4.0?

**Comment by markstory** [comment]
The migration guide for [3.3](https://book.cakephp.org/3.0/en/appendices/3-3-migration-guide.html#psr-7-middleware-support-added) included a section on updating with links to the [step-by-step process](https://book.cakephp.org/3.0/en/development/application.html#adding-http-stack).

I update the 3.6 migration guide with links to guide as well.
