### ISSUE TITLE
4.x - Search for Commands shows old and new url

### ISSUE THREAD

**Issue by othercorey** [cakephp/docs#6252]
The URL for Console Commands changed when the files were re-organized. 

It looks like the search cache still has the old reference and returns it along with the new reference.  The old reference takes you to a 404 page because it is now invalid.

![console](https://user-images.githubusercontent.com/24221186/68271431-14721700-0026-11ea-83f1-059778c1f97f.png)

**Comment by markstory** [comment]
I went into elasticsearch and removed the naughty document.
