### ISSUE TITLE
French epub version of the cookbook is not available

### ISSUE THREAD

**Issue by diden78** [cakephp/docs#6256]
Hello,

French epub version of the cookbook is not available.
The link is : https://book.cakephp.org/3/_downloads/fr/CakePHPCookbook.epub
But we get error 404

Thanks
BR

**Comment by garas** [comment]
File is available at https://book.cakephp.org/3/_downloads/fr/CakePHP.epub

Link is invalid.

**Comment by diden78** [comment]
Ok thanks,

I guess you will fix the link in the website !

BR
