### ISSUE TITLE
Migrations page points to URL that doesn't exist

### ISSUE THREAD

**Issue by othercorey** [cakephp/docs#6263]
**3.x**
https://book.cakephp.org/3/en/migrations.html

points to

https://book.cakephp.org/migrations/2//index.html

**4.x**
https://book.cakephp.org/4/en/migrations.html

points to

https://book.cakephp.org/migrations/3.x/en/

**Comment by markstory** [comment]
The links in the 3.x book are fixed. The 4.x book points to a version of the docs that was never published. I'll get that fixed up.

**Comment by markstory** [comment]
Migrations v3 docs are published now.
