### ISSUE TITLE
Link Plugin [ElasticSearch] loading to Welcome Nginx

### ISSUE THREAD

**Issue by p2sousa** [cakephp/docs#6269]
**Issue Description**

Clicking on the Elasticsearch Menu Item loads a default Nginx page.
I noticed that the url is missing the language indication.

Expected Link: [https://book.cakephp.org/elasticsearch/2/en/index.html](https://book.cakephp.org/elasticsearch/2/en/index.html)
Current Link: [https://book.cakephp.org/elasticsearch/2//index.html](https://book.cakephp.org/elasticsearch/2//index.html)

---

**Do you want to address this issue?**
Not in the moment.

**Comment by markstory** [comment]
Fixed now!
