### ISSUE TITLE
Missing callable function parameters

### ISSUE THREAD

**Issue by davidyell** [cakephp/docs#6307]
**Issue Description**

https://book.cakephp.org/3/en/core-libraries/validation.html#allowing-empty-fields

This page doesn't include any information, that I can find, about the callable 'when' function parameters, or an example.

---

**Do you want to address this issue?**

No.  I wouldn't know what to document.

**Comment by garas** [comment]
https://book.cakephp.org/3/en/core-libraries/validation.html#conditional-validation

**Comment by davidyell** [comment]
Perhaps a cross link can be added to the empty fields section to allow users to follow on through the docs?

**Comment by dereuromark** [comment]
It would be nice if the docs examples always contained all typehints :) That would make it clear, right?
