### ISSUE TITLE
4.x - Clarify in upgrade guide that rector commands should run before requiring cakephp 4.0

### ISSUE THREAD

**Issue by othercorey** [cakephp/docs#6313]
This should have the same notes before the commands as the upgrade readme.  Users probably won't see that require is at the bottom because it should happen last.

>The upgrade tool is intended to be run before you update your application's dependencies to 4.0. The rector based tasks will not run correctly if your application already has its dependencies updated to 4.x.

https://book.cakephp.org/4/en/appendices/4-0-upgrade-guide.html

**Comment by dereuromark** [comment]
I actually ran them afterwards and it also kind of worked for me. on some plugins.

**Comment by othercorey** [comment]
I'm not actually familiar with the issues you cause if running after.  But, considering it's important want to make sure we consistently call it out early.

**Comment by othercorey** [comment]
Example: https://github.com/cakephp/upgrade/issues/128#issuecomment-563010181

**Comment by niel** [comment]
@othercorey you misunderstood my reply. I updated my CakePHP and dependencies to latest *current* versions which is still CakePHP 3.8, as 4 is still only an RC. I've updated my reply to clarify that.

**Comment by othercorey** [comment]
> @othercorey you misunderstood my reply. I updated my CakePHP and dependencies to latest _current_ versions which is still CakePHP 3.8, as 4 is still only an RC. I've updated my reply to clarify that.

Thanks for the clarification.  We'll still try to improve the docs!

**Comment by othercorey** [comment]
Fixed in https://github.com/cakephp/docs/pull/6316.
