### ISSUE TITLE
Cakephp 3.x migrations is in 2.x cookbook

### ISSUE THREAD

**Issue by blieb** [cakephp/docs#6317]
Hi, I was checking the cakephp migrations command, but was unable to find it. However I did find it in the 2.x cookbook. But the commands are actually for 3.x. I think this needs to be moved to 3.x cookbook.

You can find it at:
https://book.cakephp.org/migrations/2/en/index.html#

---

**Do you want to address this issue?**
I'm not sure how to move items so I think someone else can do this.

**Comment by ADmad** [comment]
The `2` in the URL is version for the plugin, not CakePHP core.

There's no migrations plugin for CakePHP 2.x.

**Comment by dereuromark** [comment]
Maybe we could make this a bit more clear in the headline or first paragraph or sth.

**Comment by othercorey** [comment]
The header is:

`CakePHP 4.x Strawberry Cookbook` vs `CakePHP Migrations 3.x Cookbook`

Maybe it should be `CakePHP 3.x Migrations Plugin Cookbook`
