### ISSUE TITLE
4.0 Missing Chronos Docs (404)

### ISSUE THREAD

**Issue by jimbo2150** [cakephp/docs#6334]
**Issue Description**

The link to the Chronos docs in the CakePHP 4.0 cookbook is https://book.cakephp.org/chronos/2/ under the Plugins -> Chronos side navigation but that link returns a 404 (Not Found) error.

**Comment by markstory** [comment]
I can get this fixed.

**Comment by markstory** [comment]
Thank you for letting us know about this. It is fixed now.
