### ISSUE TITLE
cakephptheme and sphinx 2.2 causes <p> tags in lists

### ISSUE THREAD

**Issue by othercorey** [cakephp/docs#6359]
When upgrading to sphinx 2.2, the list items are all wrapped in paragraph tags which causes extra spacing.

![sphinx-22-list](https://user-images.githubusercontent.com/24221186/71388388-bd1c0c00-25bd-11ea-8e89-29c46c2fc935.png)

**Comment by markstory** [comment]
This is likely a change in docutils. We will have to update our CSS.

**Comment by othercorey** [comment]
Both versions are using docutils 0.15.2, so I'm not sure where the change happened.

**Comment by markstory** [comment]
Could be in sphinx then. Either way we'll need to update our CSS :smile:

**Comment by othercorey** [comment]
We need to make a change like this to the theme:
https://github.com/sphinx-doc/sphinx/pull/6114/files

Original issue with notes on docutils writer spacing:
https://github.com/sphinx-doc/sphinx/issues/6113

**Comment by markstory** [comment]
I think this is fixed. The CDN caching is making my changes hard to verify. I'll check back tomorrow.

**Comment by markstory** [comment]
Going to close this. The conventions page no longer has double margins in the lists and tables.
