### ISSUE TITLE
"Expected type 'array'. Found 'string'." in  /vendor/cake...src/View/Helper/FormHelper.php  

### ISSUE THREAD

**Issue by LuizMarin** [cakephp/docs#6365]
**Issue Description**

Intelephense reports error at this location

![image](https://user-images.githubusercontent.com/50879411/71419648-37e13780-264f-11ea-86f2-be124ee76df4.png)

---

**Comment by garas** [comment]
There is `is_array` check one line above, `$options` is defined as generic `array`, not `string[]` or something.

This is issue with Intelephense how it guesses variables types, not issue with CakePHP.

**Comment by LuizMarin** [comment]
thanks you
