### ISSUE TITLE
How to Test Mailer

### ISSUE THREAD

**Issue by swiffer** [cakephp/docs#6377]
**Issue Description**

The docs about testing mailers seem to be incomplete.

https://book.cakephp.org/4/en/core-libraries/email.html#testing-mailer

**Do you want to address this issue?**

Don't know how.

**Comment by markstory** [comment]
What extra information are you looking for? Would having an example test method showing some of the assertions help?

**Comment by swiffer** [comment]
The assertions are fine. But how to i set up a TestCase for a Mailer. When testing as part of a Controller action it's working but having a separate test case just for a mailer my tests currently fail because CakePHP does not find a route to the URL i want to build in the template. So basically: setting up a Mailer TestCase :)
