### ISSUE TITLE
cakephp 4.x some docs with authentication are for 3.x

### ISSUE THREAD

**Issue by andraskende** [cakephp/docs#6380]
cakephp 4.x some docs with authentication are for 3.x

Preface -> Tutorials & Examples -> CMS Tutorial - Authentication
https://book.cakephp.org/4/en/tutorials-and-examples/cms/authentication.html

searching for 'blog'
https://book.cakephp.org/4/en/tutorials-and-examples/blog-auth-example/auth.html

Thanks,
Andras

**Comment by markstory** [comment]
These tutorials aren't necessarily for 3.x they are using `AuthComponent` which while deprecated is still around in 4.x. Updating these tutorials to use the new plugins will take some time as the changes are significant.

**Comment by markstory** [comment]
Closing this as the CMS tutorial has been updated to use the new plugins. The other tutorials aren't less easy to find and might be removed in the future.
