### ISSUE TITLE
Migration docs don't document changed Table name inflection

### ISSUE THREAD

**Issue by BGehrels** [cakephp/docs#6408]
**Issue Description**
https://github.com/cakephp/cakephp/commit/4b6806379c45436a051a1fb65eea8be8c143f132#diff-2aa3ae5dc64d2182b7096ee758ba5e1a changed the inflection behaviour of `TableLocator`. This is a non backwards compatible chnge that is not documented in the migration docs

Why is it an issue? Because cake returns a default table class when no explicit one has been found. So you end up having a table class, but the return type of your Queries is `Cake\ORM\Entity` instead of your own entity class.

(In our case this got worse, because for some non-obvious reason, it returned our custom entity class locally (Windows) and in our Gitlab CI test pipeline), but returned `Cake\ORM\Entity` on our live environment (standard linux based hosting provider). May have something to do with the underlying case insensitive file systems, but caused a little bit of panic after deployment.

---

**Do you want to address this issue?**

I'm not quite sure what the "right" solution here is. Adding a note to the migration docs seems like the easiest way to go. On the other hand, if there is a Table in the Locator with an alias that only case insentitvely equals the search term, it's most likely that the develper made a mistake and cake should probably warn her about that.

**Comment by markstory** [comment]
Pull request open now.
