### ISSUE TITLE
User Guide - Quick Start Guide - Adding Simple Slug Generation

### ISSUE THREAD

**Issue by raisha99** [cakephp/docs#6411]
Hi there.  It is probably just me, but...following the quick start user guide, I am up to:

// src/Model/Table/ArticlesTable.php

The code provided is this:
```php
// src/Model/Table/ArticlesTable.php
namespace App\Model\Table;

use Cake\ORM\Table;

class ArticlesTable extends Table
{
    public function initialize(array $config): void
    {
        $this->addBehavior('Timestamp');
    }
}
```
The next step identified is adding the simple slug

When I change the articlesTable.php to match the example:
```php
// in src/Model/Table/ArticlesTable.php
namespace App\Model\Table;

use Cake\ORM\Table;
// the Text class
use Cake\Utility\Text;
```

// Add the following method.
```php
public function beforeSave($event, $entity, $options)
{
    if ($entity->isNew() && !$entity->slug) {
        $sluggedTitle = Text::slug($entity->title);
        // trim slug to maximum length defined in schema
        $entity->slug = substr($sluggedTitle, 0, 191);
    }
}
```
 I get an error at the public function line...

"syntax error, unexpected T_PUBLIC

Can someone help with this please :)
---

**Comment by markstory** [comment]
What does the current state of your ArticlesTable look like?

**Comment by dereuromark** [comment]
I would recommend looking into the plugins that ship slugging: https://github.com/FriendsOfCake/awesome-cakephp#seo

**Comment by garas** [comment]
Back on the original question:

`syntax error, unexpected T_PUBLIC` means you put `public function` in wrong location.

`public function beforeSave()` must be put inside `class ArticlesTable extends Table { }`, not outside.

**Comment by dereuromark** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
