### ISSUE TITLE
Invalid result in search for "Find"

### ISSUE THREAD

**Issue by Megslalk** [cakephp/docs#6466]
When typing "find" into the search of the book. First suggestion is 
":orphan: True Not Found ######### The page you're looking for cannot be found. Try using the search bar to find what you're looking for." This result is en/404.html 
Result should be excluded from search index.

**Comment by othercorey** [comment]
Closing this as the CakePHP 4 index builder excludes 404.rst now.  The new servers will have a clean cache built without the old 404 page in it.
