### ISSUE TITLE
4.0 Migration upgrade guide should mention "minimum-stability": "dev"

### ISSUE THREAD

**Issue by xhs345** [cakephp/docs#6473]
Just spend a few hours not being able to install some dependencies and it turns out I was missing the entry 

`"minimum-stability": "dev"` in composer.json

Though it would be helpful for others to add this as a note

**Comment by dereuromark** [comment]
As soon as Migrations is released as beta (last one missing along with Phinx), we only need beta, and once they all are stable, we can remove it completely.

**Comment by othercorey** [comment]
@dereuromark is this fixed now?

**Comment by dereuromark** [comment]
I would think so.
