### ISSUE TITLE
Sessions page not included in "sessions" search results

### ISSUE THREAD

**Issue by othercorey** [cakephp/docs#6580]
The sessions page should be included in search results for "sessions".

https://book.cakephp.org/4/en/development/sessions.html

**Comment by markstory** [comment]
Not sure what's going on here. The document is indexed and does show up if you search for `session.ini` I think there might be too many matches for 'session'.

**Comment by othercorey** [comment]
Is there any way to index just headers and prioritize them in the cache?

**Comment by markstory** [comment]
We do index the title separately, and the title was parsed correctly when we indexed the document. The search frontend also applies a [boost to the title](https://github.com/cakephp/search.cakephp.org/blob/master/src/Model/Index/SearchIndex.php#L49). I'm not sure why we're not getting hits. It is possible that the boost logic is broken.
