### ISSUE TITLE
Cake 3 docs missing description of how to change error handler class

### ISSUE THREAD

**Issue by burzum** [cakephp/docs#6587]
https://book.cakephp.org/3/en/development/errors.html#error-exception-configuration

I've tried class, className, handler, handlerClass as a key in the Error array in app.php but no success.

It's funny that the docs tell me:

> **Ceate & register your own error handler** This gives you complete control over how errors & exceptions are handled, logged and rendered.

But doesn't tell me how to replace the default handler.

**Comment by markstory** [comment]
This [section covers creating your own error handler](https://book.cakephp.org/3/en/development/errors.html#creating-your-own-error-handler).
