### ISSUE TITLE
German Translation Skeleton Folder

### ISSUE THREAD

**Issue by wiifree** [cakephp/docs#6590]
I read in the docs if a translation language does not exist one should start contact via github. can anyone create a skeleton folder for german translation for the cakephp 4 docs, please.

**Comment by othercorey** [comment]
@wiifree We are only interested in full translations. Are you going to be able to do that with a team?

**Comment by wiifree** [comment]
Ohh ok. No, I wanted to do it alone. I have seen that many translations have not been completed and I thought a few translations were better than none at all.

**Comment by othercorey** [comment]
We have problems with incomplete translations and out-dated english copied into those files.

We would like to have a simple intro page that can be translated better instead of random pages.

**Comment by wiifree** [comment]
that's bad but i understand it. so if i understand that right, no new translations are accepted on this way?

**Comment by dereuromark** [comment]
As a fellow German I would always recommend to contribute to the primary (English) docs, to make that one more accurate and complete.
That way everyone benefits from it and we don't run into incomplete/outdated issues.
