### ISSUE TITLE
4.0: App Class

### ISSUE THREAD

**Issue by mirko-pagliai** [cakephp/docs#6604]
The section [Locating Plugins](https://book.cakephp.org/4/en/core-libraries/app.html#locating-plugins) should be updated or extended.

The `App::path()` method is documented, as from the CakePHP's last release, while the `Plugin::path()` method is described and exemplified.

**Comment by dereuromark** [comment]
Turns out the whole Plugin class was missing
Fixed and Added at https://github.com/cakephp/docs/pull/6606
