### ISSUE TITLE
Broken link in the side menu of the Japanese version (authorization, authentication in plugin)

### ISSUE THREAD

**Issue by tomcat0090** [cakephp/docs#6666]
The link is broken, in the side menu of the Japanese version.
The English version is linked correctly.
I would like to fix it, but I don't know the correct link.

https://book.cakephp.org/3/ja/index.html

**Comment by garas** [comment]
There is only English docs for [authorization](https://github.com/cakephp/authorization/tree/master/docs) and [authentication](https://github.com/cakephp/authentication/tree/master/docs).

You can fix left menu at https://github.com/cakephp/docs/blob/3.x/ja/contents.rst
