### ISSUE TITLE
Add a lang attribute to improve indexing of the pages

### ISSUE THREAD

**Issue by steinkel** [cakephp/docs#6668]
**Issue Description**

Searching for book related contents in duck retrieves the same page for different languages 

https://www.w3.org/International/questions/qa-html-language-declarations

Adding the lang attribute would possibly help to filter the language and provide better results.

---

**Do you want to address this issue?**

Maybe

**Comment by ADmad** [comment]
Manual for CakePHP core already seems to have `lang` attribute with proper values for the `<html>` tag. It's the manuals for the plugins/standalone package which need to be fixed. They current all seem to have `<html xmlns="http://www.w3.org/1999/xhtml">`. The `xmlns` attribute should also be not present.

**Comment by markstory** [comment]
I added the lang attribute to the book and forgot to comment back here. I can update the plugin sites as well.

**Comment by markstory** [comment]
The base image for the plugin sites has been updated. As those sites are updated they will get the new lang attribute.
