### ISSUE TITLE
The Blog Tutorial - Authentication does not show how to install the "Authentication Plugin".

### ISSUE THREAD

**Issue by nosvazquez** [cakephp/docs#6670]
The Blog Tutorial - Authentication does not show how to install the "Authentication Plugin". It assumes that the user has the plugin.

I followed the tutorial and I got some errors, I wasted my time searching why those errors and I found that just was I did not have the "Authentication Plugin" installed...

This article show how to install and how to add the plugin to the boostrap method, please add the first section about the installation.

https://www.bookstack.cn/read/cakephp-4.x/3ff7cc29055186c8.md

Feedback me If I need to improve my english!

**Comment by markstory** [comment]
Which page in the book are you referring to? The blog tutorial is not longer the primary tutorial used in the 4.x docs, and I'm not familiar with what bookstack.cn is.

**Comment by nosvazquez** [comment]
https://book.cakephp.org/4/en/tutorials-and-examples/blog-auth-example/auth.html#adding-authentication, well, this page disappears in the left menu about tutorials and examples and I hadn't noticed because I was clicking next... next... buttons at the footer.

But that post needs to add the part that says how to add the plugin in src/Application.php inside boostrap() with $this->addPlugin('Authentication');
