### ISSUE TITLE
CMS Tutorial "Articles-Controller" in 4.x/en

### ISSUE THREAD

**Issue by holginaut** [cakephp/docs#6688]
Hello,

i just tried the Cake 4.x CMS Tutorial "Articles-Controller" (https://book.cakephp.org/4/en/tutorials-and-examples/cms/articles-controller.html) and it might be that there are some problems:

1. public function beforeSave [...] ends up in unexpected syntax error if function is public

2. public function validationDefault [...] also ends up in unexpected syntax error if function is public

3. I can view and edit and save the edited Article. But if i try to "add" a new Article and click on "Save Article" it ends up with:

SQLSTATE[HY000]: General error: 1364 Field 'slug' doesn't have a default value

(see screenshot)

![cake-articlescontroller-pdoexception](https://user-images.githubusercontent.com/11685841/86168656-d081d400-bb18-11ea-97d1-e06f30eab2c3.png)

I hope it helps a bit. I'm not clever enough to fix it, just started with Cake4 and i'm sorry, if this is my fault. :-)

**Comment by garas** [comment]
It is expected developer to have basic PHP knowledge.

`public/protected/private` before `function` suggests it is class method.

`public function beforeSave()` and `public function validationDefault()` should be put inside of `class ArticlesTable extends Table { }`.

After that, 3 will be OK too.

**Comment by holginaut** [comment]
Hey garas,

thank you, that was it.

On Page https://book.cakephp.org/4/en/tutorials-and-examples/cms/database.html they told how to create ArticlesTable.php and on the next Page https://book.cakephp.org/4/en/tutorials-and-examples/cms/articles-controller.html at "Adding Simple Slug Generation" i thought i had to change it to what there is and so i removed the part with "class ArticlesTable extends Table". My fault, sorry. I was a bit tired yesterday and haven't read properly. ;-)
