### ISSUE TITLE
Link 'chronos' in footer of 'Using CakePHP' directs to moved page.

### ISSUE THREAD

**Issue by drtrppr** [cakephp/docs#6707]
**Issue Description**
In the footer of https://book.cakephp.org/4/en/topics.html , the 'chronos' button gives https://book.cakephp.org/4/en/chronos.html .

But apart from the redirect, is it correct to direct to the chronos-page? https://book.cakephp.org/4/en/intro.html# seems more in place at this point? 

Or maybe the welcome-page has to link to the intro-page, and the topics-page is an overview at another point in the book?

 

---

**Do you want to address this issue?**

**Comment by markstory** [comment]
> But apart from the redirect, is it correct to direct to the chronos-page? https://book.cakephp.org/4/en/intro.html# seems more in place at this point?
>
> Or maybe the welcome-page has to link to the intro-page, and the topics-page is an overview at another point in the book?

I don't understand which page you're referring to with 'welcome-page' and 'intro-page' do you have links?

The footer link you've mentioned is automatically generated by our documentation tool. I don't think there is a way for us to omit that link without removing the page entirely which could break links elsewhere on the internet.

**Comment by drtrppr** [comment]
Welcome-page: https://book.cakephp.org/4/en/index.html 
Intro-page: https://book.cakephp.org/4/en/intro.html

It's not about omitting the link in footer, but referring to the right page. Right in the sense that it follows the reading flow.

Same on the intro-page, the 'back-button' is labelled with 'Phinx migrations' (BTW this one is moved too).  The generator links to the standalone packages pages for some reason? 

When reading the book on-line and you're not that familiar with CakePHP, there's a chance you get completely lost. 

Now I'am lost :) 

Seems using the 'back-button' brings you to a page which has been moved. Using the 'back-button' on that page also links to a moved page etc.

**Comment by othercorey** [comment]
I think they are saying if you start at the index (Welcome) page, then next link takes you to the topics page. From there it takes you to external packages like Chronos which is a strange direction.

The intro page takes you to the Phinx package.

**Comment by markstory** [comment]
Thank you for the extra info @drtrppr I understand what you're saying now. I'll try reordering the table of contents to get a better chapter ordering.

**Comment by drtrppr** [comment]
Sorry I wasn't clear. Think that's the result of writing the issue on the fly.  Started with the problem of links directing to moved pages, then started wondering about the chapter ordening. Better made two issues with some more afterthougt (the way we tell users to do so).

**Comment by othercorey** [comment]
The intro page back link looks better, but the welcome page still takes you to chronos and debug kit instead of something useful.

**Comment by markstory** [comment]
Pushed another commit to try and fix the welcome -> next page.

**Comment by othercorey** [comment]
Looks good to me.
