### ISSUE TITLE
CMS Tutorial error with "bake all tags" (pg 54 in v4 book)

### ISSUE THREAD

**Issue by adoniahei** [cakephp/docs#6715]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1.0
* Platform and Target: Linux Mint 20 VM, MariaDB, PHP 7.4

### What you did
I am going through the CMS Tutorial from the new book. On page 54, there is the command **bin/cake bake all tags** After that, it says: Once you have the scaffold code created, create a few sample tags by going to http://localhost:8765/tags/add.

### What happened
I got an error that there was no add() function.

After poking around a bit, I tried: **bin/cake bake template tags add** which solved that issue. At this time, my literacy is not enough to know what caused the error or why this command fixed it.

### What you expected to happen
The  form to add a tag displayed so I can start adding the initial tags as instructed in the tutorial.

I actually got the form, and could enter a new tag title, but the submit returned a "Missing or invalid CSRF cookie" error -- but that will be in another issue.

**Comment by markstory** [comment]
I wasn't able to reproduce this problem. Locally, `bake all tags` generated the following output for me:

```bash
Wrote `/home/mark/code/cms-tutorial/src/Model/Table/TagsTable.php`

Baking entity class for Tag...

Creating file /home/mark/code/cms-tutorial/src/Model/Entity/Tag.php
Wrote `/home/mark/code/cms-tutorial/src/Model/Entity/Tag.php`

Baking test fixture for Tags...

Creating file /home/mark/code/cms-tutorial/tests/Fixture/TagsFixture.php
Wrote `/home/mark/code/cms-tutorial/tests/Fixture/TagsFixture.php`
Bake is detecting possible fixtures...

Baking test case for App\Model\Table\TagsTable ...

Creating file /home/mark/code/cms-tutorial/tests/TestCase/Model/Table/TagsTableTest.php
Wrote `/home/mark/code/cms-tutorial/tests/TestCase/Model/Table/TagsTableTest.php`
Done
Baking controller class for Tags...

Creating file /home/mark/code/cms-tutorial/src/Controller/TagsController.php
Wrote `/home/mark/code/cms-tutorial/src/Controller/TagsController.php`
Bake is detecting possible fixtures...

Baking test case for App\Controller\TagsController ...

Creating file /home/mark/code/cms-tutorial/tests/TestCase/Controller/TagsControllerTest.php
Wrote `/home/mark/code/cms-tutorial/tests/TestCase/Controller/TagsControllerTest.php`
Done

Baking `index` view template file...

Creating file /home/mark/code/cms-tutorial/templates/Tags/index.php
Wrote `/home/mark/code/cms-tutorial/templates/Tags/index.php`

Baking `view` view template file...

Creating file /home/mark/code/cms-tutorial/templates/Tags/view.php
Wrote `/home/mark/code/cms-tutorial/templates/Tags/view.php`

Baking `add` view template file...

Creating file /home/mark/code/cms-tutorial/templates/Tags/add.php
Wrote `/home/mark/code/cms-tutorial/templates/Tags/add.php`

Baking `edit` view template file...

Creating file /home/mark/code/cms-tutorial/templates/Tags/edit.php
Wrote `/home/mark/code/cms-tutorial/templates/Tags/edit.php`
Template file `No bake template found for "Bake.Template/delete" skipping file generation.` could not be found.
Bake All complete.
```
And all the view files were created correctly.
