### ISSUE TITLE
CakePHP Conventions: Summarized Table probably incorrect

### ISSUE THREAD

**Issue by AlYourPal** [cakephp/docs#6716]
**Issue Description**

From what I read in the preceding paragraphs of the [CakePHP Conventions Page](https://book.cakephp.org/4/en/intro/conventions.html), the table in the [Summarized section](https://book.cakephp.org/4/en/intro/conventions.html#summarized) seems to be incorrect:

- The database table should be named article_categories instead of articles_categories. Accordingly the complete 3rd column seems to be incorrect (ArticleCategoriesController.php instead of ArticlesCategoriesController.php, ArticleCategory.php instead of ArticlesCategories.php, etc.)
- The entity should be named Article.php instead of Articles.php

Likewise, the join table in the '[Database Convention Summary](https://book.cakephp.org/4/en/intro/conventions.html#database-convention-summary)' table at the end of this chapter should be named article_tags instead of articles_tags.

---

**Do you want to address this issue?**

Still new to CakePHP and GitHub, so hopefully someone else will verify and fix this issue.

**Comment by dereuromark** [comment]
You are right about the entity (singular), but the convention for HABTM is still foos_bars (plural + plural) in alphabetical order.

**Comment by markstory** [comment]
Thanks! I've pushed a commit to correct the mistakes.

**Comment by AlYourPal** [comment]
Thx @markstory for the fix. I think I finally figured out what was puzzling me all the time: article_categories is not a join table where articles can have multiple categories and categories can belong to multiple articles (such as in the tutorial with articles_tags) but simply a table whose name consists of two words. Maybe another multiple word table such as presidential_candidates would be better in order to avoid this misconception in the docs?
