### ISSUE TITLE
Error: Class 'App\Model\Entity\DefaultPasswordHasher' not found

### ISSUE THREAD

**Issue by cristianemoyano** [cakephp/docs#6733]
**Issue Description**

CakePHP  4.x.

``
Error: Class 'App\Model\Entity\DefaultPasswordHasher' not found.
``
[Doc link](https://book.cakephp.org/4/en/tutorials-and-examples/cms/authentication.html#adding-password-hashing)

https://github.com/cakephp/docs/edit/4.x/en/tutorials-and-examples/cms/authentication.rst

<img width="1432" alt="Screen Shot 2020-08-01 at 16 20 57" src="https://user-images.githubusercontent.com/36732489/89108927-2812a880-d413-11ea-8e19-bc77b11e57d2.png">

---

Error fixed replacing: 

`use Cake\Auth\DefaultPasswordHasher;` by `use Cake\Auth\DefaultPasswordHasher;`

_src/Model/Entity/User.php_

<img width="1175" alt="Screen Shot 2020-08-01 at 16 21 21" src="https://user-images.githubusercontent.com/36732489/89108950-58f2dd80-d413-11ea-9a6c-7c7e518f5f8c.png">

**Comment by othercorey** [comment]
Can you create a PR to fix?

**Comment by cristianemoyano** [comment]
> Can you create a PR to fix?

Sure! I'll !

**Comment by othercorey** [comment]
From PR:

> It sounds more like you've possibly made a mistake and not included the authentication plugin (correctly)?

Yeah, that could be an option. But I just imported the `DefaultPasswordHasher` statement  like this:

_User.php_ 
```
<?php
declare(strict_types=1);

namespace App\Model\Entity;

use Authentication\PasswordHasher\DefaultPasswordHasher;
use Cake\ORM\Entity;

class User extends Entity
{
    // Code from bake.

    // Add this method
    protected function _setPassword(string $password) : ?string
    {
        if (strlen($password) > 0) {
            return (new DefaultPasswordHasher())->hash($password);
        }
    }
}
```

There are another line that should I include? Can you help me to understand what I'm doing wrong?

**Comment by othercorey** [comment]
From PR:

> You need to require the plugin via composer [as shown here](https://book.cakephp.org/4/en/tutorials-and-examples/cms/authentication.html#installing-authentication-plugin), have you successfully done that?
