### ISSUE TITLE
Errors in methods Bake Policy

### ISSUE THREAD

**Issue by luizcmarin** [cakephp/docs#6763]
BUG ?

CakePHP Version: 4.1.3, Bake 2.1.2

in [https://book.cakephp.org/4/en/tutorials-and-examples/cms/authorization.html#creating-our-first-policy](https://book.cakephp.org/4/en/tutorials-and-examples/cms/authorization.html#creating-our-first-policy)  the command   

     ` bin/cake bake policy --type table Articles`

  generates canCreate and canUpdate methods cause execution errors, should they be canAdd and canEdit?

**Comment by markstory** [comment]
The step right after running bake is to update the policy with new methods. Perhaps the tutorial should skip using bake to create the policy instead?

Why did you need a table policy? All the can() calls in the tutorial are against entities.
