### ISSUE TITLE
Awkward phrasing on conventions page

### ISSUE THREAD

**Issue by cautionbug** [cakephp/docs#6791]
**Issue Description**

On the Conventions page: https://github.com/cakephp/docs/blob/4.x/en/intro/conventions.rst#database-conventions

> Join tables, used in BelongsToMany relationships between models, should be named after the model tables they will join or the bake command won’t work, arranged in alphabetical order (`articles_tags` rather than `tags_articles`). If you need to add additional columns on the junction table you should create a separate entity/table class for that table.

Phrasing here is awkward. Instead of completing the rules of the convention, the consequence is injected in the middle. Also, mixing the term (join/junction) for this kind of table *might* be confusing without clarification they are synonymous.

i suggest:

>Join (or "junction") tables - used in BelongsToMany relationships between models - should be named for the tables they connect, pluralized, and sorted alphabetically: `articles_tags`, not `tags_articles` or `article_tags`. *The bake command will not work if this convention is not followed.* If the junction table holds any data other than the linking foreign keys, you should create a formal model/entity class for the table.

---

**Do you want to address this issue?**

i'm willing to correct the wording if someone wants to OK my suggestion or offer an alternative.

**Comment by markstory** [comment]
Your changes sounds better to me.

**Comment by dereuromark** [comment]
@cautionbug Do you want to make a PR here?

**Comment by cautionbug** [comment]
@dereuromark Yes, absolutely. i've been buried at work the last couple weeks. Hoping things will lighten up within the next week or so. i haven't forgotten - i'm excited to make my first submission. 😄

**Comment by cautionbug** [comment]
@dereuromark / @markstory i may need some guidance here. i'm running Windows, but i have the Docker instance running. i'm fairly new to Docker, though - mostly Vagrant before this.

However, when i attempt to [build the docs](https://github.com/cakephp/docs#build-the-image-locally) with my changes:
```
$ docker run -it --rm -v $(pwd):/data cakephp/docs make html
make: *** No rule to make target 'html'.  Stop.
```
Same message for all formats.

Please help the noob?

**Comment by markstory** [comment]
You don't need to build the docs. If you update the content, I can take care of making sure the build is correct.

**Comment by cautionbug** [comment]
Well, that certainly makes things easier. i'll have a PR today. Sorry for the delay.

**Comment by othercorey** [comment]
The -v maps a local directory to a directory in the container. However, on windows, $(pwd), might not be working for you so the directory could be empty.

**Comment by cautionbug** [comment]
When i used PowerShell, it threw an error. Switched to Git-bash which recognizes stuff like that, and it didn't "fail".

Anyway, i appreciate the assist.

**Comment by markstory** [comment]
I've cherry picked 639514a73f6b64e3c42c1f4304b805b015f6d212 into our repo. Thanks for the help on this.

**Comment by cautionbug** [comment]
Thanks @markstory - is there anything i should do different next time to make that a smoother process?

**Comment by markstory** [comment]
Nope, I'm dumb and didn't see the pull request before picking the commit into our repo.
