### ISSUE TITLE
orm/table-objects: Wrong namespace for TableLocator

### ISSUE THREAD

**Issue by levu42** [cakephp/docs#6854]
In [Using the TableLocator](https://book.cakephp.org/4/en/orm/table-objects.html#using-the-tablelocator) it mentions TableLocator to be in Cake\ORM\TableLocator but it's in Cake\ORM\Locator\TableLocator.

**Comment by dereuromark** [comment]
Hi @levu42 
You can also directly do a PR against https://github.com/cakephp/docs repo with the correction.
That would be awesome and we can process it faster then :)
