### ISSUE TITLE
Cake 4.x CMS Tutorial

### ISSUE THREAD

**Issue by biermannm** [cakephp/docs#6864]
**Issue Description**
When I tried to set up authentication following the CakePHP 4.x CMS tutorial, my apache2 server crashed reproducibly under Ubuntu 20, regardless if I ran php 7.2 or 7.4. In the end, I set display_errors = On in the "/etc/php/7.4/apache2/php.ini" (the one that is active on the web server - see phpinfo() on your server), and it became clear that the statement " ->add(new AuthenticationMiddleware($this));" is part of an object definition and must NOT have a trailing semicolon. 

The code snippet in the tutorial should be corrected as follows:

```
// src/Application.php
public function middleware(MiddlewareQueue $middlewareQueue): MiddlewareQueue
{
    $middlewareQueue
        // ... other middleware added before
        ->add(new RoutingMiddleware($this))
        // add Authentication after RoutingMiddleware
        ->add(new AuthenticationMiddleware($this))
       // ... no trailing semicolon here!

    return $middlewareQueue;
}

```

---

**Do you want to address this issue?**

**Comment by dereuromark** [comment]
This is expected to be known by a dev, based on the position or how the queue is built.

You can also do

    $middlewareQueue->add();
    $middlewareQueue->add();
    $middlewareQueue->add();

etc.

**Comment by biermannm** [comment]
I see your point. From a user's point of view, I would however claim that a tutorial should be "simple, stupid". I have been developing under CakePHP since v. 1.3 (see my publication on [PubMed](https://pubmed.ncbi.nlm.nih.gov/24507951/)), and have since migrated to 3.x. The point of my trying out the tutorial was to see if 4.1 was worth the effort. The answer is "Yes". Now that I know the final answer, I read the tutorial line by line with the aim of understanding all relevant details. I think that the tutorial would be more user friendly if it worked out of the box.
