### ISSUE TITLE
Quick Start Guide PR in french version

### ISSUE THREAD

**Issue by hhindustry** [cakephp/docs#6873]
**Issue Description**

The issue is in the Adding Articles part of the Quick Start Guide:

- In [English version](https://book.cakephp.org/4/en/quickstart.html) (it's working):
// src/Controller/ArticlesController.php
`    public function initialize(): void`
// src/Model/Table/ArticlesTable.php
`    public function initialize(array $config): void`
// src/Model/Table/ArticlesTable.php
`    public function validationDefault(Validator $validator): Validator`

- In [French version](https://book.cakephp.org/4/fr/quickstart.html) => fatal error because of the function declaration :
// src/Controller/ArticlesController.php
`    public function initialize()`
// src/Model/Table/ArticlesTable.php
`    public function initialize(array $config)`
// src/Model/Table/ArticlesTable.php
`    public function validationDefault(Validator $validator)`

---

**Do you want to address this issue?**

I can work on this issue if it's a real problem

**Comment by markstory** [comment]
I don't think the french translations have an active maintainer right now. We'd love any help you are able to provide :smile:

**Comment by hhindustry** [comment]
I can help you with the french version if you want. But I don't know how to modify the French Quick Start Guide.

**Comment by markstory** [comment]
Each page in the book has an 'edit' link in the site that takes you to the matching file in GitHub. You can either edit in GitHub or create a fork and edit locally on your machine.

**Comment by hhindustry** [comment]
Great, I found the way to do it. Thank you ! 👍
