### ISSUE TITLE
Missing documentation for testing the HTTP API calls

### ISSUE THREAD

**Issue by ishan-biztech** [cakephp/docs#6892]
**Issue Description**

Currently we are missing documentation on how to test HTTP/Curl API calls in CakePHP. It's not clear like what is an best practice to test these http request.

1. Is there any helper methods or anything that helps developers test this in CakePHP way? 
2. Is there any other way around that experienced developers are doing to test their HTTP request?

In above both cases we should add some content(along with some pseudo code) to let developers know what is the recommended way of doing this.

---

**Do you want to address this issue?**

I might but I don't actually know what is the best practice to test HTTP calls in CakePHP yet! Also I can't find much of a content on this topic.

**Comment by markstory** [comment]
Are you looking for how to test the outbound API calls your application is making, or are you wanting to test requests being made to your application?

**Comment by ishan-biztech** [comment]
Outbound API calls like making calls to Stripe or Xero API, etc. Currently it's not documented like how to do this(or what is the recommended way I should say). 

For example if you look at Laravel docs, they have [dedicated section](https://laravel.com/docs/8.x/http-client#testing) on how to mock HTTP requests made by Laravel's `Illuminate\Support\Facades\Http` client.

**Comment by markstory** [comment]
Ok. We don't currently have a high level API for faking outbound requests. I've used [php-vcr](https://github.com/php-vcr/php-vcr) for stubbing network requests in the past. I wrote a [blog post](http://mark-story.com/posts/view/integration-testing-with-php-vcr) about how to get it setup with a CakePHP application.

We might want to add a simpler to use wrapper/API for this in CakePHP itself though.

**Comment by ishan-biztech** [comment]
Hi @markstory, are you able to assign any milestone or something to this feature? To prevent from being closed?

**Comment by theafolayan** [comment]
Is someone intending to work on this yet? 
Looking to take this up soon.

**Comment by markstory** [comment]
@theafolayan I don't think there has been any movement on this. I have been preoccupied with fixtures and haven't gotten to this yet. If you have time an issue with the proposed API you are considering would be a great place to start.

**Comment by rochamarcelo** [comment]
What is the status here? Maybe we could add some basic examples in the doc of how to mock using mock builder. The changes would be in the page https://book.cakephp.org/4/en/development/testing.html

**Comment by markstory** [comment]
This can be closed now. The new features will be part of 4.3 and the docs are in the 4.next branch of this repo.
