### ISSUE TITLE
Loading paginator not clear  

### ISSUE THREAD

**Issue by ironbone** [cakephp/docs#6901]
**Issue Description**

Here 
https://book.cakephp.org/4/en/controllers/components/pagination.html#basic-usage
is described that in order to use Pagination we need to
`$this->loadComponent('Paginator');`

Then  in all the examples is used
`$this->paginate($this->Articles);`

But the `paginate()` function of the Controller class loads the Paginator.

Loading Paginator manualy is only needed when using the PaginatorComponent directly.

**Comment by dereuromark** [comment]
Yes, but it also doesn't hurt to load it manually.
So I guess this is fine as it is for now.

**Comment by ADmad** [comment]
As mentioned above showing explicit loading of `PaginatorComponent` doesn't hurt and actually helps understand that it's the component that handles the pagination.
