### ISSUE TITLE
Making sure I set the correct App.paths.locales and App.paths.templates paths

### ISSUE THREAD

**Issue by mehov** [cakephp/docs#6958]
[github.com/cakephp/docs/blame/4.x/en/appendices/4-0-upgrade-guide.rst#L62](https://github.com/cakephp/docs/blame/4.x/en/appendices/4-0-upgrade-guide.rst#L62):

> Once you’ve renamed your template and locale files, make sure you update App.paths.locales and App.paths.templates paths (in /config/app.php) to be correct.

By looking at [cakephp/app](https://github.com/cakephp/app), I can confirm the latter needs to be `ROOT . DS . 'templates' . DS`, but what about `locales`? Should it be going elsewhere?

I'm willing to edit the document once I confirm the right paths.

**Comment by garas** [comment]
See [config/app.php](https://github.com/cakephp/app/blob/master/config/app.php#L64-L68) of app skeleton.
