### ISSUE TITLE
Cake 4 Time Docs

### ISSUE THREAD

**Issue by yosus** [cakephp/docs#7035]
**Issue Description**
Cake 4 [Time docs](https://book.cakephp.org/4/en/core-libraries/time.html#manipulation) shows immutable `FrozenTime` being changed/manipulated

```
$now = FrozenTime::now();
$now->year(2013)
    ->month(10)
    ->day(31);
```

![cake4](https://user-images.githubusercontent.com/5551430/121024685-09b9ce00-c7d7-11eb-8905-2e25942ea7e8.png)

---

**Do you want to address this issue?**
Before I create a PR for this, I notice that cake 3 [time docs](https://book.cakephp.org/3/en/core-libraries/time.html) uses `Time` instead of `FrozenTime` in other parts of the document. May I know the reason why ?

**Comment by othercorey** [comment]
In cakephp 4, the datetime db types use FrozenTime by default.

https://github.com/cakephp/cakephp/blob/439fb6143fbe809e64ea58ae218d6ceee1b126a2/src/Database/Type/DateTimeType.php#L124

**Comment by yosus** [comment]
ok. Let me create a PR for this.

**Comment by yosus** [comment]
[Closed](https://github.com/cakephp/docs/pull/7038)
