### ISSUE TITLE
Overwriting configuration keys in environment specific default config files

### ISSUE THREAD

**Issue by TerryKern** [cakephp/docs#7050]
Lets assume we have the CakePHP standard configuration files "config/app_local.php" & "config/app.php" as outlined in: https://book.cakephp.org/3/en/development/configuration.html

In our app_local.php we have a config key as follows:

```` php
$config['App'] = [     
    'features' => [     
        'feature1' => false,     
        'feature2' => false,    
        'feature3' => false,    
    ],     
];
```` 
Now we want to overwrite one of these features in our non environment specific config file app.php.
In order to do this we can either access the key like so:
```` php
$config['App.features.feature2'] = true;
```` 
or like so:

```` php
$config['App']['features']['feature2'] = true;
```` 
Both of these options result in:

```` php
$config['App'] = [     
    'features' => [     
        'feature1' => false,     
        'feature2' => true,    
        'feature3' => false,    
    ],     
];
```` 
Now to the real reason for this issue.

Mixing the config key access methods (dot notation & array-key) results in some weird/undocumented behaviour.
For example:

We try to set "feature2" to true using a mixture of dot notation and array-keys:

```` php
$config['App.features']['feature2'] = true;
```` 
This works **only** for "feature2" resulting in:
```` php
$config['App'] = [     
    'features' => [     
        'feature2' => true,    
    ],     
];
```` 
As we can see both "feature1" & "feature3" have been unset.

This was the source of some confusion for my team and I, as we could not find any reference to this behaviour within the docs.

The goal of  this issue is to bring attention to this behaviour and to hopefully result in it being mentioned at an appropriate place in the docs.

**Comment by dereuromark** [comment]
The "dot notation" cannot work on pure and simple array access.
If you want this to work, you would need a high level wrapper of setting config that normalizes it then into nested form, using Hash class for example.

So I am not sure why this is confusing, or how the docs could be clear on that one.
This is just a basic PHP issue or limitation.

//EDIT
Are you saying it actually did transform `$config['App.features']['feature2'] = true` into the example below?
I didnt know it would internally do this magic :)

In that case it seems to just set and replace the whole key, as would a PHP array access on the parent here.
Why did you not use `$config['App.features.feature2'] = true` then?
