### ISSUE TITLE
Switching from 3.x to 4.x doesn't remember current open doc

### ISSUE THREAD

**Issue by LordSimal** [cakephp/docs#7067]
**Issue Description**

When exploring the Cookbook and switching between versions the webpage doesn't remember where the use has been before.

Example:
Go to https://book.cakephp.org/3/en/orm/table-objects.html
Click on the `Version 4.x Book` at the top right
You get redirected to https://book.cakephp.org/4/en/index.html but it should be https://book.cakephp.org/4/en/orm/table-objects.html

---

**Do you want to address this issue?**

I would like to help but I have absolutely no idea who the book is built with this repo. I am currently in the process of trying to understand that via the README.

**Comment by markstory** [comment]
That link is generated in the book's theme which is in [a different repository](/cakephp/sphinxtheme). That package is installed during the build of the docs.

**Comment by othercorey** [comment]
This wouldn't work when the url changes.

**Comment by markstory** [comment]
It wouldn't but it would work more often than never.

**Comment by LordSimal** [comment]
Sure, I can understand that it wouldn't work everywhere but maybe you can check if it works and then insert it instead of the default index link.

Otherwise you would need to have some sort of matching between the different versions (and also languages if we want to continue that train) to know which URL needs to be set on which page.

**Comment by markstory** [comment]
Checking that it works is tricky as each version of the docs are built independently without context of what exists in the other branches. An inventory file could be built early in the build process. These options are potentially feasible with a custom sphinx extension.

**Comment by othercorey** [comment]
Sorry but I think this is out of scope for the docs project with the tool we're using. If you have a solution you want to discuss, please open a PR.
