### ISSUE TITLE
Authentication/Authorization middleware position not 100% clear

### ISSUE THREAD

**Issue by LordSimal** [cakephp/docs#7083]
**Issue Description**

We just had a lengthy debug session in the Slack support channel where some community member had a problem with middleware positions.

In that session @ndm2 mentioned, that the BodyParserMiddleware needs to be present before the Authorization Middleware (and basically any other Middleware which proccesses request data)

Therefore should this be stated in the doc and/or have better code examples (like based on the current state of the cakephp/app middleware queue) or are there better approaches?

---

**Do you want to address this issue?**

If its clear what the best practice is I am glad to create a PR

**Comment by LordSimal** [comment]
Because according to https://book.cakephp.org/4/en/tutorials-and-examples/cms/authentication.html the authentication only needs to be placed after RoutingMiddleware and according to https://book.cakephp.org/4/en/tutorials-and-examples/cms/authorization.html the authorization needs to be added after authentication.

**Comment by markstory** [comment]
Where would you expect to find this more complete example? We could include a more complete example in the tutorial or the authentication docs or both.

**Comment by LordSimal** [comment]
Since I don't have that much experience with middlewares I am just going to describe the in my opinion "perfect world" example:

In this "perfect world" any middleware could define dependencies of other middlewares being either before or after the current middleware and if any violation is being detected either a notice, exception or some notification would inform the user of that issue.
This would of course only be applicable to known, cakephp/cakephp or cakephp/some-plugin middlewares and not user generated but there are so "many" middlewares now that positioning those correctly in the queue can be a bit confusing.

Othewise I would prefer some best practice examples (based on the current cakephp/app src/Application.php middleware function) in at least the authentication and the authorization doc with those used middlewares.

So like for Authentication
----
        $middlewareQueue
            // Catch any exceptions in the lower layers,
            // and make an error page/response
            ->add(new ErrorHandlerMiddleware(Configure::read('Error')))

            // Handle plugin/theme assets like CakePHP normally does.
            ->add(new AssetMiddleware([
                'cacheTime' => Configure::read('Asset.cacheTime'),
            ]))

            // Add routing middleware.
            // If you have a large number of routes connected, turning on routes
            // caching in production could improve performance. For that when
            // creating the middleware instance specify the cache config name by
            // using it's second constructor argument:
            // `new RoutingMiddleware($this, '_cake_routes_')`
            ->add(new RoutingMiddleware($this))

            // Parse various types of encoded request bodies so that they are
            // available as array through $request->getData()
            // https://book.cakephp.org/4/en/controllers/middleware.html#body-parser-middleware
            ->add(new BodyParserMiddleware())

            // Cross Site Request Forgery (CSRF) Protection Middleware
            // https://book.cakephp.org/4/en/controllers/middleware.html#cross-site-request-forgery-csrf-middleware
            ->add(new CsrfProtectionMiddleware([
                'httponly' => true,
            ]))

             // add Authentication after RoutingMiddleware
             ->add(new AuthenticationMiddleware($this));
         
         return $middlewareQueue;
----

and for Authorization
----
        $middlewareQueue
            // Catch any exceptions in the lower layers,
            // and make an error page/response
            ->add(new ErrorHandlerMiddleware(Configure::read('Error')))

            // Handle plugin/theme assets like CakePHP normally does.
            ->add(new AssetMiddleware([
                'cacheTime' => Configure::read('Asset.cacheTime'),
            ]))

            // Add routing middleware.
            // If you have a large number of routes connected, turning on routes
            // caching in production could improve performance. For that when
            // creating the middleware instance specify the cache config name by
            // using it's second constructor argument:
            // `new RoutingMiddleware($this, '_cake_routes_')`
            ->add(new RoutingMiddleware($this))

            // Parse various types of encoded request bodies so that they are
            // available as array through $request->getData()
            // https://book.cakephp.org/4/en/controllers/middleware.html#body-parser-middleware
            ->add(new BodyParserMiddleware())

            // Cross Site Request Forgery (CSRF) Protection Middleware
            // https://book.cakephp.org/4/en/controllers/middleware.html#cross-site-request-forgery-csrf-middleware
            ->add(new CsrfProtectionMiddleware([
                'httponly' => true,
            ]))

             // add Authentication after RoutingMiddleware
             ->add(new AuthenticationMiddleware($this))

             // add Authorization after Authentication 
             ->add(new AuthorizationMiddleware($this));
         
         return $middlewareQueue;
----

If that is even correct

**Comment by markstory** [comment]
> In this "perfect world" any middleware could define dependencies of other middlewares being either before or after the current middleware and if any violation is being detected either a notice, exception or some notification would inform the user of that issue.

Having dependencies is tricky as middleware instances aren't aware of the queue and don't have a way to look at it either. Middleware also lack 'names' so dependencies would need specific classname references which reduces flexibility in middleware.

> Othewise I would prefer some best practice examples (based on the current cakephp/app src/Application.php middleware function) in at least the authentication and the authorization doc with those used middlewares.

I can get the documentation examples updated.

**Comment by LordSimal** [comment]
Thanks for the clarifications. This will definitely prevent many headaches 😄
