### ISSUE TITLE
sphinx php parameter rendering hard to read

### ISSUE THREAD

**Issue by othercorey** [cakephp/docs#7096]
https://book.cakephp.org/4/en/core-libraries/logging.html#namespace-Cake\Log

The formatting is inconsistent and the font size is very large.

![image](https://user-images.githubusercontent.com/24221186/130576310-c6077d2d-e97b-4da3-a34f-1227bb2e1f12.png)

**Comment by othercorey** [comment]
@markstory did something change in the sphinx plugin?

**Comment by markstory** [comment]
Not any time recently, but I agree the formatting isn't great.

**Comment by vinodkmwt** [comment]
Can I be of any help?

**Comment by othercorey** [comment]
> Can I be of any help?

I think this is a css issue with `dd` elements.

**Comment by gludie** [comment]
(Looks like) this issue belongs to [cakephpsphinx](https://github.com/cakephp/sphinxtheme) package 
(default.css -> field-list) ... will propose a pull request for the theme (may be only a workaround)

preview:

![image](https://user-images.githubusercontent.com/583438/219906242-97407b88-92ee-4758-baf4-2d76460928b3.png)

following workaround applied to cakephpsphinx/themes/cakephp/static/css/default.css:

```
/* -- fix test -- */
.field-list,
.field-list strong {
  font-family: "Roboto Mono", "Consolas", "Monaco", monospace;
  color: #003d4c;
  font-weight: normal;
  font-size: 12px;
}
/* -- fix test end -- */
```

**Comment by markstory** [comment]
> (Looks like) this issue belongs to [cakephpsphinx](https://github.com/cakephp/sphinxtheme) package

@gludie You're right that this issue belongs there now. The preview of your changes looks good to me. A pull request would be greatly appreciated.

**Comment by gludie** [comment]
I guess, we can close the issue, hence PR was accepted and done in cakephp/sphinxtheme

**Comment by othercorey** [comment]
Thanks!
