### ISSUE TITLE
update tuned link

### ISSUE THREAD

**Issue by Arhell** [cakephp/docs#7102]
**Issue Description**
https://book.cakephp.org/4/en/development/testing.html#fixture-factories

Once your factories are **tuned**
From master to main

**Comment by markstory** [comment]
That tuned link seems to be working for me, what is the problem?

**Comment by othercorey** [comment]
> That tuned link seems to be working for me, what is the problem?

github is redirecting to the new branch name.

**Comment by Arhell** [comment]
You're right, but I think it's better when everything leads to the correct link.
Plus there will be no reminder that the branch has been changed in the  ui of the github
