### ISSUE TITLE
RESTful Routing needs to mention the ability to use a `prefix` for a Resource

### ISSUE THREAD

**Issue by mehov** [cakephp/docs#7151]
The documentaton at [routing.html#restful-routing](https://book.cakephp.org/4/en/development/routing.html#restful-routing) ([github source file](https://github.com/cakephp/docs/blob/c546fbfd47f4a0cfe9f48831829afe326197609d/en/development/routing.rst#restful-routing)) needs to mention the `prefix` option available for a resource introduced by cakephp/cakephp/pull/8493 in a response to cakephp/cakephp#8063

**Comment by markstory** [comment]
Docs were updated in 3d6515c92e176ef151500ad7cacc2f4b18660b34 (3.x) and 6c136b317f44d76af247f2dcc0dc572aca36ad52 (4.x)
