### ISSUE TITLE
app_local.php isn't mentioned/explained  to set debug=false

### ISSUE THREAD

**Issue by drtrppr** [cakephp/docs#7159]
https://book.cakephp.org/4/en/deployment.html#adjust-config-app-php

Doc tells to turn debug to false in config/app.php.

However, debug=false by default after fresh install.

Doc doesn't mention app_local.php in which debug=true by default, and which overrides the app.php.

Since I don't have the knowledge why work with app.php and app_local.php, would be nice to read (or given a link to) to why, benefits etc. of the app_local.php. As a noob in this matter, just think why not use just app.php.

**Comment by dereuromark** [comment]
I agree that this page should clarify better the need for the local file and how to use it (e.g. only set debug mode or passwords in that one).
Right now a lot of newbies trip over this.

**Comment by markstory** [comment]
The usage of `app_local` is optional which is why it doesn't show up consistently in the documentation. We could switch the docs over to it though as it is also the default for new applications, and plays nicely with many deployment setups.
