### ISSUE TITLE
Middleware and CSRF Protection Middleware have same menu entry

### ISSUE THREAD

**Issue by othercorey** [cakephp/docs#7221]
Both of these points to https://book.cakephp.org/4/en/controllers/middleware.html.

![image](https://user-images.githubusercontent.com/24221186/139499064-46909c3b-a790-4cdb-9c52-7005a925ba37.png)

**Comment by othercorey** [comment]
@markstory Should CSRF point to something else?

**Comment by markstory** [comment]
Based on the content we have I think it has to show up in the TOC twice. We could write another small page in the `Security` section for CSRF and move the content out of the middleware doc though.

**Comment by othercorey** [comment]
It doesn't open a specific subsection.
