### ISSUE TITLE
Request & Response Objects: `request` → `getRequest()`?

### ISSUE THREAD

**Issue by mehov** [cakephp/docs#7239]
Please see [*Request & Response Objects* → *Request Parameters*](https://book.cakephp.org/3/en/controllers/request-response.html#request-parameters):

### What happened

The first code example says:
```
$controllerName = $this->request->getParam('controller');

// Prior to 3.4.0
$controllerName = $this->request->param('controller');
```

### What I expected to happen
Consistently encouraging the (relatively) new getX/setX method naming convention.

```
$controllerName = $this->getRequest()->getParam('controller');

// Prior to 3.4.0
$controllerName = $this->request->param('controller');
```

**Comment by ADmad** [comment]
There no need to use the getter method for accessing protected properties.
