### ISSUE TITLE
broken link v2

### ISSUE THREAD

**Issue by Arhell** [cakephp/docs#7252]
**Issue Description**

https://book.cakephp.org/2/en/core-libraries/caching.html
**XcacheEngine**

cc @markstory

**Comment by markstory** [comment]
Yeah that project is no longer maintained, and they have no actual site anymore. We could link to https://en.wikipedia.org/wiki/List_of_PHP_accelerators#XCache instead?

**Comment by Arhell** [comment]
> Yeah that project is no longer maintained, and they have no actual site anymore. We could link to https://en.wikipedia.org/wiki/List_of_PHP_accelerators#XCache instead?

Thank you! https://github.com/cakephp/docs/pull/7255
