### ISSUE TITLE
 Number format helper displays NULL as 0

### ISSUE THREAD

**Issue by drtrppr** [cakephp/docs#7292]
**Issue Description**

Would have helped me if there was a warning that the null results in a zero, didn't expect that, can't find that in the text [Number](https://book.cakephp.org/4/en/core-libraries/number.html#formatting-numbers), see [discourse-topic](https://discourse.cakephp.org/t/database-nullable-integer-field-has-value-null-cakephp-displaying-0/10082l).

---

**Do you want to address this issue?**

**Comment by ADmad** [comment]
This isn't a documentation issue. A method meant to format numbers returning a number is nothing out of the ordinary and doesn't need a warning.

We can discuss this on the issue you have opened on the bake repo instead.

**Comment by drtrppr** [comment]
'Warning' wasn't maybe the correct word, it's indeed nothing out of the ordinary considering number_format(null) returns  "0" #8961 .

But a sentence like:

> Note that If $value is NULL, output will be a '0' 

or something like that, would have helped me, and maybe some other non-programmers users of cakephp.

All the number-methods will output zero I guess? If there could be a note, it should be in the intro?

(Think it's not for the bake repo because the number-helper is not exclusively used within 'bake'. How to get from the '0' to e.g. a blank when $value=NULL when using 'bake' belongs there?)
