### ISSUE TITLE
Missing echo

### ISSUE THREAD

**Issue by HumanG33k** [cakephp/docs#7313]
There is missing echo : 
https://book.cakephp.org/4/en/views.html#using-blocks-for-script-and-css-files

```bash 
<?php
// In your view file
$this->Html->script('carousel', ['block' => true]);
$this->Html->css('carousel', ['block' => true]);
?>
```
should be 

```bash 
<?php
// In your view file
echo $this->Html->script('carousel', ['block' => true]);
echo $this->Html->css('carousel', ['block' => true]);
?>
```

**Comment by garas** [comment]
Documentation is correct.

With `['block' => true]`, these methods append the tag to `script` or `css` block buffer.

Then you print block contents somewhere else with  `echo $this->fetch('script')` or `echo $this->fetch('css')`.

https://book.cakephp.org/4/en/views.html#displaying-blocks

**Comment by LordSimal** [comment]
As garas already said there is a difference between directly outputting a script/link tag or appending them into the `script` or `css` block provided by CakePHP.
Maybe we should explain the whole `block` concept a bit more

**Comment by saeideng** [comment]
I just found this #7316 that had unneeded echo

> Maybe we should explain the whole block concept a bit more


I think document is clear enough, but feel free to open a PR 
closing since document is correct
