### ISSUE TITLE
4.next book is missing css/theme

### ISSUE THREAD

**Issue by othercorey** [cakephp/docs#7376]
https://book.cakephp.org/4.next/en/index.html

This seems to be rendering without formatting.

**Comment by othercorey** [comment]
@markstory

**Comment by ndm2** [comment]
A `4.x` > `4.next` > `5.x` merge is needed to inherit the theme/make related changes.

**Comment by othercorey** [comment]
Can you do that merge in case something needs to be resolved?

**Comment by ndm2** [comment]
I've opened PRs for it just in case, didn't wanted to commit it directly as I've never did any forward merges here before.

**Comment by othercorey** [comment]
Looks correct after merge.
