### ISSUE TITLE
Options for Route Prefixes not well documented

### ISSUE THREAD

**Issue by cnizzardini** [cakephp/docs#7529]
**Issue Description**

The acceptable types for `prefix` in https://book.cakephp.org/4/en/development/routing.html don't seem to be well-documented. I am expecting `?string` but a user reports that `false` is an acceptable type as well. I was not able to determine anything from the comments either: https://github.com/cakephp/cakephp/blob/4.x/src/Routing/RouteBuilder.php#L345

https://github.com/cnizzardini/cakephp-swagger-bake/issues/475

**Do you want to address this issue?**

Maybe...

**Comment by markstory** [comment]
> I am expecting ?string but a user reports that false is an acceptable type as well. I was not able to determine anything from the comments either: https://github.com/cakephp/cakephp/blob/4.x/src/Routing/RouteBuilder.php#L345

Historically we've supported `string|false`. The `false` type is used to 'escape' prefix mode and go to a prefix-less route.

**Comment by dereuromark** [comment]
There is an example on that page linked above:
```php
// Go into a prefixed route.
echo $this->Html->link(
    'Manage articles',
    ['prefix' => 'Manager/Admin', 'controller' => 'Articles', 'action' => 'add']
);

// Leave a prefix
echo $this->Html->link(
    'View Post',
    ['prefix' => false, 'controller' => 'Articles', 'action' => 'view', 5]
);
```
