### ISSUE TITLE
AuthenticationMiddleware recommended position

### ISSUE THREAD

**Issue by martonmiklos** [cakephp/docs#7547]
**Issue Description**

I have spend quite a long time troubleshooting a ground up new application (started from skeleton) with JWT token authentication request while I realized that it was caused by the following:

```
            ->add(new RoutingMiddleware($this))
            ->add(new AuthenticationMiddleware($this))
            ->add(new BodyParserMiddleware())
```

The token request contained the authentication data in the body, which did not get to the Authentication component.
After I changed the order of the middlewares to the following it worked:
```
            ->add(new RoutingMiddleware($this))
            ->add(new BodyParserMiddleware())
            ->add(new AuthenticationMiddleware($this))
```

I started to wonder why the heck did I made this mistake and it lead me to the following sentence in the docs:
```
        // ... other middleware added before
        ->add(new RoutingMiddleware($this))
        // add Authentication after RoutingMiddleware
        ->add(new AuthenticationMiddleware($this));
```
---

**Do you want to address this issue?**

This is how the cakephp skeleton looks like today:
https://github.com/cakephp/app/blob/4.x/src/Application.php#L87

My recommendation would be changing the proposed position of the AuthenticationMiddleware int the docs to the following:
```
        // ... other middleware added before
        ->add(new RoutingMiddleware($this))
        ->add(new BodyParserMiddleware())
        // add Authentication after RoutingMiddleware and BodyParserMiddleware
        ->add(new AuthenticationMiddleware($this));
```

If no objections present, I am happy to send a PR.

**Comment by LordSimal** [comment]
Well at least in the authentication specific documentation we state clearly to put the middleware after routing and body parser (see red banner). See https://book.cakephp.org/authentication/2/en/index.html#getting-started

But its definitely not 100% clear from the doc in the [CMS tutorial](https://book.cakephp.org/4/en/tutorials-and-examples/cms/authentication.html#adding-login)

If you would like to provide a PR we are definitely happy about that 😄
