### ISSUE TITLE
5.x: Type::build() removal missing

### ISSUE THREAD

**Issue by dereuromark** [cakephp/docs#7561]
Seems to  be missing from migration/upgrade guides

bootstrap
```php
Type::build('time');
Type::build('date');
Type::build('datetime');
Type::build('timestamp');
```

as well as e.g.
```php
Type::map('array', ArrayType::class);
```
inside Model/Behavior code

**Comment by markstory** [comment]
~~This method is also missing a deprecation in 4.next. I can take care of both changes.~~

The methods are still present in [TypeFactory::build](https://github.com/cakephp/cakephp/blob/5.x/src/Database/TypeFactory.php#L72). We are missing a runtime deprecation in 4.next though.

**Comment by dereuromark** [comment]
And docs in migration etc, I was looking for build() and Type:: etc, and didnt find anything.
Same for Type::buildAll() which is now TypeFactory::buildAll()


Also _initializeSchema() removal doesnt seem to be covered in upgrade or migration guide

**Comment by markstory** [comment]
Looks like these methods were deprecated in cakephp/cakephp@598bc5ed038 and we forgot to update the docs and add runtime deprecations for them.

**Comment by markstory** [comment]
Closing as runtime deprecations have been added to 4.5
