### ISSUE TITLE
"Using Validation as Application Rules" does not work with IsUnique rule

### ISSUE THREAD

**Issue by notpron** [cakephp/docs#7573]
**Issue Description**

```
CREATE TABLE `my_table` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `unique_field` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_field` (`unique_field`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

A table with a unique constraint on a field, will be baked with something like the following validation rule:
```
    public function validationDefault(Validator $validator)
    {
        ...
        $validator->naturalNumber('unique_field')
            ->requirePresence('unique_field', 'create')
            ->notEmptyString('unique_field')
            ->add('unique_field', 'unique', [
                'rule' => 'validateUnique',
                'provider' => 'table',
            ]);
```

If we use the `buildRules` from [the documentation](https://book.cakephp.org/4/en/orm/validation.html#using-validation-as-application-rules), it will look like this:
```
public function buildRules(RulesChecker $rules): RulesChecker
{
    // Add validation rules
    $rules->add(function($entity) {
        $data = $entity->extract($this->getSchema()->columns(), true);
        $validator = $this->getValidator('default');
        $errors = $validator->validate($data, $entity->isNew());
        $entity->setErrors($errors);

        return empty($errors);
    });
```

When we have an entity that was *already persisted before*, mark the `unique_field` dirty and try to save the entity, the validation will fail.
```
$entity = $this->MyTable->get(1);
$entity->setDirty('unique_field');
$this->MyTable->saveOrFail($entity);
// boom
```

The reason this fails is because of the way the IsUnique rule works. For it to be able to generate the correct `exists` query, it needs to know if the entity is new, and if it is not, it needs to know the primary key of the entity. What it tries to generate is a query like this:
```
SELECT 1 AS `existing` FROM `my_table` `MyTable` WHERE (`MyTable`.`unique_field` = 1 AND NOT (`MyTable`.`id` = 1)) LIMIT 1
```

What happens in the rule added in `buildRules`, is that it only extracts the dirty fields from the entity, thus missing the primary key of the entity that is being validated. The same problem would be happening in `Marshaller::merge` if it didn't [append the primary key](https://github.com/cakephp/cakephp/blob/4.x/src/ORM/Marshaller.php#L554) to the data being passed to the validator.

---

**Do you want to address this issue?**

My initial thought is changing the documentation. If we follow the Marshaller, the primary key is added to the data passed to the validator. This could be something like this:
```
        $rules->add(function (EntityInterface $entity): bool {
            $data = $entity->extract($this->getSchema()->columns(), true);
            if (!$entity->isNew() && !empty($data)) {
                $data += $entity->extract((array)$this->getPrimaryKey());
            }
            $validator = $this->getValidator('default');
            $errors = $validator->validate($data, $entity->isNew());
            $entity->setErrors($errors);

            return empty($errors);
        });
```

But I'm hesitant to add this, for it will always validate the primary key on updates. I'm very curious what you think.

**Comment by ADmad** [comment]
All you need is

```php
    public function buildRules(RulesChecker $rules): RulesChecker
    {
        return $rules->add($rules->isUnique(['unique_field']);
    }
```

**Comment by notpron** [comment]
Thanks for the quick response. That's possible and I've already added that before creating this ticket, but it seems to me an issue that baked code will create problems when combined with the solution from the documentation. This is why I was trying to come up with a more solid way for reusing the validators as rules.

What I don't like about moving it to the buildRules, is that the rule won't go off on a `Table::patchEntity`. So then you might end up with forms that fail because of validator rules, they are corrected by the user, then it fails again on the save of the `unique_field`. It also requires me to go through all the baked entities and move stuff around, which I'm trying to avoid.

**Comment by dereuromark** [comment]
I always use validationDefault for that matter (validation on patching).
For me that works with unique, I dont use buildRules tbh. Only database constraints on the low level again.
You could use buildRules as additional safety net in between, but feels a bit overkill to me then.

**Comment by ADmad** [comment]
> But I'm hesitant to add this, for it will always validate the primary key on updates.

@notpron I don't think that would be an issue. As you pointed out the marshaller does the same thing.

**Comment by notpron** [comment]
@dereuromark There's data that I patch, mostly stuff coming in through forms so that's what I have the validationDefault setup for. But I also have a lot of backend processes that will update entities using the `$entity->field = 'new value';` syntax. Those won't be validated unless there are buildRules (right?). This is the reason we're using both.

**Comment by dereuromark** [comment]
You could patch them as well ;) then they reuse the same logic.
Otherwise u indeed need both.

**Comment by notpron** [comment]
No thanks! That sounds like a pain in the ass to change and also a little bit, just a very little bit, gross. I am a big fan of the direct assignments on fields in the entities.

**Comment by ADmad** [comment]
@notpron You can make a pull request with the change your suggested in the initial comment.

**Comment by dereuromark** [comment]
> I am a big fan of the direct assignments on fields in the entities

You shouldnt be a fan of sth specific without a (technical) reason
In this case, by doing that you are saying it doesnt need any form of "validation", you trust it to be fully OK when assigning.
If that is not what you mean, it might need refactoring to a more appropriate form of data assignment.

**Comment by notpron** [comment]
Sorry, I didn't mean to offend, I was saying it in a 'tongue-in-cheek' kind of way. I thought you were joking when you mentioned patching everywhere. It may have come across as snarky...

I'm not sure this is the right place to get into the discussion of what is "better", but here's my take on it. I think there are a lot of good reasons to use the assignments instead of patching everywhere. Patching requires an array for one, so there's a good chance you'll end up with a lot of magic string keys that can cause unexpected bugs because there are no checks on typos. Using the properties directly as much as possible, all static analysis tools will understand what you're doing, all IDE's understand what you're doing. Using the direct assignments also allows you to pass the entity around and update it where it makes sense to update, rather than collecting data in some uncontrolled structure like an array and then patching it. I think it really helps keeping our code clean and easy to maintain.

I don't think using the assignments means it doesn't need validation. Using the validator in the buildRules resolves that. It postpones the validation until the `save(OrFail)`.

**Comment by notpron** [comment]
> @notpron You can make a pull request with the change your suggested in the initial comment.

Done 👍
