### ISSUE TITLE
Query doc split or not.

### ISSUE THREAD

**Issue by rochamarcelo** [cakephp/docs#7582]
**Issue Description**

The top of the page https://book.cakephp.org/5/en/orm/query-builder.html says the doc is for class `Cake\ORM\Query` but now we have multiple classes(SelectQuery, UpdateQuery, DeleteQuery, InsertQuery), should we split this page? 

---

**Do you want to address this issue?**

I was going to updated a few things on that page but I want to know  this before.

**Comment by dereuromark** [comment]
You might want to look what part of https://github.com/cakephp/docs/pull/7506 needs to be redone

**Comment by rochamarcelo** [comment]
Okay, the pull request has done most of the things. The page was not split but I'm okay with that. 

Some part of the code is using SelectQuery::group but this method is depreated. This change can be done after the pull request to avoid more conflicts.

Thanks.

**Comment by dereuromark** [comment]
You can also just make a new PR with all useful changes.
