### ISSUE TITLE
CMS Tutorial:Authentication - Hint on checking the config for session.cookie_secure ? 

### ISSUE THREAD

**Issue by gludie** [cakephp/docs#7591]
**Issue Description**
CMS Authentication tutorial may not work for application served from non-SSL protocols. As recommended in the Session doc section (https://book.cakephp.org/4/en/development/sessions.html), it should be recommended to check the setting of session.cookie_secure in local config if authentication is not working. 

CakePHP’s defaults session.cookie_secure to true, when your application is on an SSL protocol. If your application serves from both SSL and non-SSL protocols, then you might have problems with sessions being lost. If you need access to the session on both SSL and non-SSL domains you will want to disable this.

`
Configure::write('Session', [
   'defaults' => 'php',
   'ini' => [
   'session.cookie_secure' => false
   ]
]);
`

If your application serves from a non-SSL protocol, set the session.cookie_secure to false in your config `config/app.php` or `config/app_local.php`. (See also Session Configuration at https://book.cakephp.org/4/en/development/sessions.html)

---

**Do you want to address this issue?**

Proposal to add to the cms authentication doc section at the end: 

Important: If your application serves from a non-SSL protocol, set the session.cookie_secure to false in your config `config/app.php` or `config/app_local.php`. (See also Session Configuration at https://book.cakephp.org/4/en/development/sessions.html)

**Comment by markstory** [comment]
Seems like a good improvement to make. Did you want to contribute a pull request to fix up the docs?

**Comment by gludie** [comment]
Sure, will do so

**Comment by gludie** [comment]
done
