### ISSUE TITLE
\Cake\Database\Connection::connect() not mentioned in 5.0 migration guide

### ISSUE THREAD

**Issue by cnizzardini** [cakephp/docs#7638]
**Issue Description**

Getting this during an upgrade to 5.0 when running test suite:

```
Error: Call to undefined method Cake\Database\Connection::connect()
```

This doesn't appear in the migration guide, but seems like this is the preferred method now: 

```php
ConnectionManager::get($name)->getDriver()->connect();
```

---

**Do you want to address this issue?**

No

**Comment by markstory** [comment]
We might be able to fix this with rector. In either case I'll get the migration guide updated.

**Comment by cnizzardini** [comment]
If its not yet added, a deprecation notice in 4.5 as well.
