### ISSUE TITLE
Some links in footer are broken

### ISSUE THREAD

**Issue by Tatsurou-Yajima** [cakephp/docs#7677]
**Issue Description**

I have found some broken links.

The target elements are the `Star` and the `Fork` buttons on the footer.

https://book.cakephp.org/4/en/index.html

These are the elements in the red box in the image below.

<img width="1245" alt="image" src="https://github.com/cakephp/docs/assets/44424270/c9f7ea4a-0e6b-4188-960e-8e9de7439069">

It works the same in all versions, not just 4.x.

The behavior is as follows.

![Aug-16-2023 10-39-22](https://github.com/cakephp/docs/assets/44424270/008fc853-35e3-4139-8192-bba07c1125a0)

404 error.

---

**Do you want to address this issue?**

No.

I actually tried to address it. 

However, since you seem to be using iframes, I decided it would be difficult for me to do so.

**Comment by markstory** [comment]
Thanks for bringing this up. I've been meaning to remove these buttons, and this issue gave me a nudge :smile:

These broken buttons came from our sphinx theme. I've removed the buttons from that project and as documentation sites rebuild they will be updated to not have the broken buttons anymore.

**Comment by Tatsurou-Yajima** [comment]
Thanks for fixing the problem😉
