### ISSUE TITLE
OpenSearch Feature Broken for most CakePHP Versions

### ISSUE THREAD

**Issue by ravage84** [cakephp/docs#7717]
The [OpenSearch](https://en.wikipedia.org/wiki/OpenSearch) feature for most CakePHP versions is broken. Either the downlaod link for the necessary XML file is brokien or the search URL isn't valid.

## 1.1 - Download broken
https://book.cakephp.org/1.1/en/index.html
Could not be downloaded: https://book.cakephp.org/1.1/en/_static/opensearch.xml

## 1.2 - Download broken
https://book.cakephp.org/1.2/en/index.html
Could not be downloaded: https://book.cakephp.org/1.2/en/_static/opensearch.xml

## 1.3 - Download broken
https://book.cakephp.org/1.3/en/index.html
Could not be downloaded: https://book.cakephp.org/1.3/en/_static/opensearch.xml

## 2.0 - Download broken
https://book.cakephp.org/2/en/index.html
Could not be downloaded: https://book.cakephp.org/2/en/_static/opensearch.xml

## 3.0 - Works
https://book.cakephp.org/3/en/index.html
Search could be added https://book.cakephp.org/3/en/_static/opensearch.xml
Search works: https://book.cakephp.org/3/en/search.html?check_keywords=yes&area=default&q=i18n

## 4.0 - Search URL broken
https://book.cakephp.org/4/en/index.html
Search could be added https://book.cakephp.org/4/en/_static/opensearch.xml
But Search doesn't work: https://book.cakephp.org/4/C.UTF-8/search.html?q=i18n

## 5.0 - Search URL broken
https://book.cakephp.org/5/en/index.html
Search could be added https://book.cakephp.org/5/en/_static/opensearch.xml
But Search doesn't work: https://book.cakephp.org/5.x/C.UTF-8/search.html?q=i18n

## Some related code links

OpenSearch config for docs:
https://github.com/cakephp/docs/blob/325b0819e5b51dc0d13c61dbb8ccfd0fbc80821a/config/conf.py#L58

Original pull request adding the OpenSearch feature:
https://github.com/cakephp/docs/pull/399

OpenSearch related code in docs theme:
https://github.com/search?q=repo%3Acakephp%2Fdocs-theme%20opensearch&type=code

**Comment by othercorey** [comment]
The 4.x and 5.0 branches were upgraded to latest sphinx some weeks ago. The default locale was causing problem in the github actions build and that URL looks related.
