### ISSUE TITLE
Clarify `recursive()` usage for CTE

### ISSUE THREAD

**Issue by mehov** [cakephp/docs#7775]
I'm on Cake 5

Neither https://book.cakephp.org/5/en/orm/query-builder.html#common-table-expressions, nor https://book.cakephp.org/4/en/orm/query-builder.html#common-table-expressions has no mention of `RECURSIVE`

The pull request cakephp/cakephp#14525 where code was added has `setRecursive()`, however it no longer works, resulting in

> Call to undefined method Cake\Database\Expression\CommonTableExpression::setRecursive()

Searching API docs, I found https://api.cakephp.org/5.0/class-Cake.Database.Expression.CommonTableExpression.html#recursive() which worked

So for those coming from search, the working recursive CTE example is

```
    // Attach the new query to the table expression
    return $cte
        ->name('orders_per_customer')
        ->recursive()
        ->query($q);
```

Please address this in the docs so that it's easier to find.

P.S. curious why the contributors went against the `set`/`get` naming

**Comment by othercorey** [comment]
Would you be able to submit a PR to include the notes you need?
