### ISSUE TITLE
Remove "blog" tutorial from 5.x docs, enhance the CMS tutorial

### ISSUE THREAD

**Issue by jtheuerkauf** [cakephp/docs#7786]
**Issue Description**

At the end of the "**cms**" tutorial, the bottom of the page shows the next "step" link is the "**blog**" tutorial. That tutorial is hidden from the TOC, but still gets linked in the build. Perhaps it's a problem with the RST builder, but the tutorial should probably be removed anyway: "**cms**" appears to replace and improve it.

![image](https://github.com/cakephp/docs/assets/105436210/3b7e9d93-eab2-460c-8293-a536a288ac88)
![image](https://github.com/cakephp/docs/assets/105436210/ca9d7133-15de-437e-a8ad-dfe607cb95e4)

Once you're in the blog tutorial, the TOC doesn't know where you are:
![image](https://github.com/cakephp/docs/assets/105436210/bf69fef5-d8a8-4d68-95ea-439585c56bfb)

I also thought it might be useful to add notes at the end of each page showing how the various structures can be built with `bin/cake`.
![image](https://github.com/cakephp/docs/assets/105436210/e1969b75-a22f-4319-8eca-4e826eeafff2)

---

**Do you want to address this issue?**

I've already worked on the changes proposed and can open a PR if there's interest. Unfortunately I can only do the English docs.

**Comment by ADmad** [comment]
A PR for English only is welcome.

**Comment by jtheuerkauf** [comment]
@ADmad Which branch should this be cut from and target: `5.x` or `5.next`?

**Comment by ADmad** [comment]
5.x
