### ISSUE TITLE
French documentation still include the RequestHandler in cakephp 5

### ISSUE THREAD

**Issue by ronaldcarucci** [cakephp/docs#7929]
Hi everybody,

I'm creating this issue because I was in the case and my problem is solved thanks to @markstory via email.

I'm from belgium and my google search result give me the French documentation of **CakePHP 5**.

On this [page](https://book.cakephp.org/5/fr/development/rest.html) we can see the use of `RequestHandlerComponent`. But that component is removed since the release of **CakePHP 5**.

For my job I wrote in **CakePHP 4** a controller containing the generic logical of REST and another controllers can extend it to have automatically the **CRUD** thanks to that logical.

For a personal project I wanted to do this in **CakePHP 5** but it's didn't work because the documentation is erroned.

After contacting @markstory via email, he advised me to refer to the English documentation with is always up to date, and I will be able to finish my project thanks to that.

It's possible to update the French documentation to avoid another French developers (experimented or not) meet the same problem than me ?

Thank you

**Comment by ADmad** [comment]
> It's possible to update the French documentation to avoid another French developers (experimented or not) meet the same problem than me ?

We rely on community contributions to maintain the non English docs. So it would be best if the French speakers submit fixes for issues they find instead of expecting someone else to do it.

**Comment by ronaldcarucci** [comment]
I'd tkink there are community contributors who usually update the documentation for the non English docs.

For that we can "just" edit the rst files into a separate branch for submit the changes to apply ?

**Comment by dereuromark** [comment]
As a side note for those upgrading to Cake5:
If you want to quickly get things up and running first before further refactoring, the RequestHandler component lives on in the Shim plugin:
https://github.com/dereuromark/cakephp-shim/blob/master/docs/Component/RequestHandler.md
With this usually it is a 1:1 replacement and things work again for a while if needed.

**Comment by ADmad** [comment]
> For that we can "just" edit the rst files into a separate branch for submit the changes to apply ?

Yes

**Comment by ronaldcarucci** [comment]
Okey.

If I have some time to spend to this I can try myself and submit it. Unless someone has already done it before me

**Comment by ronaldcarucci** [comment]
I cannot create a new branch for submit merge request :
 ![Image](https://github.com/user-attachments/assets/a042163f-528f-4e6e-8213-ba5377362991)

**Comment by LordSimal** [comment]
You need to fork the repo and create a pull requeust based on your fork. You can't directly commit to this repo.

**Comment by ronaldcarucci** [comment]
> You need to fork the repo and create a pull requeust based on your fork. You can't directly commit to this repo.

Okay, I didn't know before. This is my first contribution for a GitHub project. Thanks @LordSimal !

**Comment by ronaldcarucci** [comment]
I've create a fork. I have to update the 5.x branch or I must create a separate one ?

**Comment by ronaldcarucci** [comment]
> I've create a fork. I have to update the 5.x branch or I must create a separate one ?

It's Okay, I found !

**Comment by ronaldcarucci** [comment]
The fork is merged and the documentation is up to date right now.
Can I close this issue myself or someone else have to do this later ?

**Comment by ronaldcarucci** [comment]
And before I forget, I want to thank you guys for helping me contribute to this project

**Comment by markstory** [comment]
> Can I close this issue myself or someone else have to do this later ?

We can take care of closing issues. If you'd like to have the issue automatically close when the pull request is merged you can put `Fixes #7929` in the pull request description/commit messages, and upon merge github will close the issue automatically.
