### ISSUE TITLE
Lighthouseapp ticket #99: No datatype mapping information 

### ISSUE THREAD

**Issue by ravage84** [cakephp/docs#885]
https://cakephp.lighthouseapp.com/projects/43067/tickets/99-no-datatype-mapping-information

The ticket there contains a few comments.

---

For the 1.3 book, it is very useful knowing this information:
http://book.cakephp.org/1.3/en/The-Manual/Developing-with-CakePHP/Models.html#creating-database-tables

To know what database datatypes will work [best] in Cake.

However there is no such information for the 2.x book now that cake is using PDO.

**Comment by ravage84** [comment]
@dereuromark wrote about this back in 2012:

http://www.dereuromark.de/2012/05/01/schema-reference-for-table-less-models/

This will help to fill the documentation gap.

**Comment by markstory** [comment]
Pull request up now.
