### ISSUE TITLE
Character-Replacements in PDF-Version

### ISSUE THREAD

**Issue by Suven** [cakephp/docs#921]
Hi,

at least in the 2.0-PDF-Version of the cookbook ' are replaced with ´

Examples can be found at http://book.cakephp.org/2.0/_downloads/en/CakePHPCookbook.pdf

For example on page 11:
    `<td><?php echo $post[’Post’][’id’]; ?></td>`

I don't know if this problem still exists in 3.0 or if it is more LATEX-related but at least for  PHP-beginners this may cause confusion.

BR
Sven

**Comment by cake17** [comment]
I can't find anymore those ``’`` in the pdfs docs. Something happened to fix that ?

**Comment by markstory** [comment]
@cake17 I don't think we did any work intentionally to fix the situation.

**Comment by cake17** [comment]
this is magic ! :smile:
Can someone confirm everything is ok (or that I drank too much :beer: ? )

**Comment by HavokInspiration** [comment]
I can still some.
On the link @Suven posted, for instance, page 251 :

> To save also associated data with $options[’deep’] = true (since 2.1), the two above examples would look like:

**Comment by cake17** [comment]
It seems that this issue has been fixed in newest version of sphinx.

I'll make a new PR to update sphinx version to 1.4.5.

**Comment by cake17** [comment]
With update to 1.4.5, I built the pdf and it seems that quotes are now fine, see the screenshot for `$options[’deep’] = true`

![quote-pdf](https://cloud.githubusercontent.com/assets/1652972/16989629/3e150cac-4e95-11e6-9462-9d1a5e65c8ef.png)

**Comment by markstory** [comment]
@cake17 Awesome, we should be able to upgrade soon thanks to the work you've done :+1:
